### DISCUSSION TITLE
Run CI conditionally based on `[ci]`, `[ci_mac]`, etc. magic strings presence in commit message

### DISCUSSION THREAD

**Discussion by MartyIX** [actions/runner#1010] [Q&A]
Hi,

I have this simple working YAML definition which allows me to start CI for all OSs when `[CI]` string is in the commit message of the last commit of a git branch:

```yaml
name: .NET Core
on: [push, pull_request]

jobs:
  build:
    # If you want to do a CI check for your commit, include `[ci]` (or `[CI]`) anywhere in the git commit message.
    if: "contains(github.event.head_commit.message, '[ci]')" # Second parameter is not case sensitive.
    strategy:
      matrix:
        operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]

    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
```

I would love to add `[ci_mac]` and `[ci_win]` magic strings so that only the specified OS is used in the CI run.

I thought that something like this `if: "matrix.os == 'macos-latest' && contains(github.event.head_commit.message, '[ci_mac]')"` would help me but keep hitting the wall. It seems this is actually hard-ish problem.

Thank you!

(https://github.com/actions/runner/issues/982)
