### DISCUSSION TITLE
How to remove docker.sock mount option when using container?

### DISCUSSION THREAD

**Discussion by retzero** [actions/runner#1335] [Q&A]
I'm looking for a way to remove the `docker.sock` mount option.
Is there any way to change it?

```diff
/usr/bin/docker create --name 071a40a5144a4b699ad0ff7d347bfc61_ubuntu1804_66c1b8 --label cf4eaa
  --workdir /__w/actions-playground/actions-playground
  --network github_network_538b2c9d584a455eadadd159b63aa24f
  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true
-  -v "/var/run/docker.sock":"/var/run/docker.sock"
  -v "/home/github/actions-runner/_work":"/__w"
  -v "/home/github/actions-runner/externals":"/__e":ro
  -v "/home/github/actions-runner/_work/_temp":"/__w/_temp"
  -v "/home/github/actions-runner/_work/_actions":"/__w/_actions"
  -v "/home/github/actions-runner/_work/_tool":"/__w/_tool"
  -v "/home/github/actions-runner/_work/_temp/_github_home":"/github/home"
  -v "/home/github/actions-runner/_work/_temp/_github_workflow":"/github/workflow"
  --entrypoint "tail" ubuntu:18.04 "-f" "/dev/null"
```

**Comment by kanga333** [comment]
Hi, I have a hacky solution. You can remove `docker.sock` by using `privileged` option and `umount` command like this.

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: something
      options: --init --privileged
    steps:
      - name: umount
        run: |
          umount /var/run/docker.sock
```
