### DISCUSSION TITLE
Service container - Use `localhost` along with container job?

### DISCUSSION THREAD

**Discussion by retzero** [actions/runner#1777] [Q&A]
Do you have any idea how to use `localhost` (rather than it's service name) along with container job?

[This doc](https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers#running-jobs-directly-on-the-runner-machine) says...
> You can access service containers from the Docker host using `localhost` and the Docker host port number.

Example workflow;

```yaml
jobs:
  build:
    container:
      image: python:3.8.10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.12
        options: --network-alias localhost
        env:
          POSTGRES_USER: testuser
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - name: Connecting POSTGRES (postgres)
        run: until nc -z postgres 5432; do echo "connecting postgres..."; sleep 1; done
      - name: Connecting POSTGRES (localhost)
        run: until nc -z localhost 5432; do echo "connecting postgres..."; sleep 1; done # Stuck here....
```
