### DISCUSSION TITLE
Specify docker image that exists only locally as a container option?

### DISCUSSION THREAD

**Discussion by retzero** [actions/runner#1850] [Q&A]
Dear team.

How to use locally saved docker image?

```yaml
jobs:
  build:
    runs-on: self-hosted
    container:
      image: my.local.docker-image-name:tag-name # ???
    steps:
      <...>
```

Thanks.
