### DISCUSSION TITLE
Option to choose the runner from caller workflow

### DISCUSSION THREAD

**Discussion by deepaksinghkhetwal** [actions/runner#1896] [Q&A]
Hello,

I am working on reusable workflows. I have self-hosted runners at two places say test and prod. The runs-on parameter is added in the called workflow. I want to call the same workflow in multiple repos and choose different runners in test and prod by giving runs-on parameters in caller workflows. Is that already possible or any other workaround.

Called workflow example

jobs:
example_job:
name: Pass input and secrets to my-action
runs-on: [self-hosted, test]
steps:
- uses: ./.github/workflows/my-action
with:
username: ${{ inputs.username }}
token: ${{ secrets.token }}

Caller Workflow Example
jobs:
call-workflow-in-another-repo:
uses: octo-org/another-repo/.github/workflows/workflow.yml@v1

**Comment by henrygriffiths** [comment]
Hi @deepaksinghkhetwal,

You should be able to add `with: runner: "[\"self-hosted\", \"linux\", \"prod\"]"` to the calling workflow, and `runs-on: ${{ inputs.runner }}` to the called workflow to pass through runs-on data.

**Reply by shanmugamrak** [reply]
Hi 

I have same scenario like this, I have two workflow in different repository one is caller workflow and another one is called workflow. I want to use self-hosted runner to run my called workflow. I am getting error whenever I tried to called workflow from caller workflow 

Error: workflows cannot be queued onto self-hosted runners across organisations/enterprises. Failed to queue this job. Labels: 'self-hosted'.

Caller workflow:

name: caller-ci

on:
 workflow_dispatch:
  
jobs:
  caller-ci:
    uses: myuser/myrepo/.github/workflows/abc.yml@main
    
    secrets:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         

called workflow:

name: calledworkflow

on:
  workflow_call:
   secrets:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        required: true 
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

**Reply by ReenigneArcher** [reply]
This worked for me, but I had to use `fromJson` in the called workflow.

e.g.:

```yml
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "[ubuntu-latest]"

jobs:
  lint:
    name: Common Lint
    runs-on: ${{ (inputs && inputs.runner && fromJson(inputs.runner)) || 'ubuntu-latest' }}
```

**Comment by tamish-max** [comment]
Yes, but the called workflow has to expose it explicitly; the caller cannot override `runs-on` implicitly.

In the reusable workflow:

```yaml
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ${{ fromJSON(inputs.runner) }}
```

And in the caller:

```yaml
jobs:
  call:
    uses: octo-org/another-repo/.github/workflows/workflow.yml@v1
    with:
      runner: '["self-hosted","linux","prod"]'
```

If you only need one label, pass a plain string and use `runs-on: ${{ inputs.runner }}`. For multiple labels, `fromJSON()` is usually the reliable route.
