### DISCUSSION TITLE
GITHUB_OUTPUT in Azure cli step

### DISCUSSION THREAD

**Discussion by alefred** [actions/runner#2222] [General]
I'm trying to use $GITHUB_OUTPUT instead of set-output in a azure cli step, however it's not possible with the next error:

```
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
"/subscriptions/***/resourceGroups/rg-gatekeeper-ci-01"

/_temp/AZ_CLI_GITHUB_ACTION_[16](https://github.com/alefred/wizzportkey/actions/runs/3308475561/jobs/5460883993#step:4:17)66556969175.sh: line 4: /home/runner/work/_temp/_runner_file_commands/set_output_4a7175e2-c7ff-4bca-8d6f-0b451c9551f3: No such file or directory
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1666556968994_CONTAINER

(node:1681) UnhandledPromiseRejectionWarning: Error: az cli script failed.
    at /home/runner/work/_actions/Azure/cli/v1/dist/index.js:1:23964
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/cli/v1/dist/index.js:1:[20](https://github.com/alefred/wizzportkey/actions/runs/3308475561/jobs/5460883993#step:4:21)436)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

How to reproduce the error, this is my github action:

```
name: reproduce-issue

on:
  workflow_dispatch

jobs:
  get-info:
    name: get-info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    #Login to Azure
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    #start VM    
    - name: Get RDP connection 
      id: rdp-info
      uses: Azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          ippub=$(az group show --name rg-gatekeeper-ci-01 --query id)

          echo "$ippub"
          echo "rdpip=$ippub" >> $GITHUB_OUTPUT
    outputs:
      biginfo: ${{ steps.rdp-info.outputs.rdpip }}

```

Even I tried to use  without variable to the ouput and It doesn't work:
`echo "rdpip=demo" >> $GITHUB_OUTPUT
`

Thanks for the advises.
[rawlog.txt](https://github.com/actions/runner/files/9847476/rawlog.txt)
