### DISCUSSION TITLE
How can I make a job with `needs` to require dependents to succeed also when skipped?

### DISCUSSION THREAD

**Discussion by pmalek** [actions/runner#2419] [Q&A]
Let's say I have several testing jobs that I run in separate jobs. Out of those I run integration tests in a matrix to speed things up. Now, these integration tests might change in time so I don't want to set the required checks for each one of them. Hence I create a job `tests-passed` and I require all previous jobs via `needs`. Something like:

```
  test-passed:
    runs-on: ubuntu-latest
    needs:
      - "unit-tests"
      - "integration-tests"
      - "conformance-tests"
    if: always()
    steps:
    - name: Set workflow outcome based on unit-tests
      if: needs.unit-tests.result == 'failure' || needs.unit-tests.result == 'cancelled'
      run: ${{ false }}
    - name: Set workflow outcome based on integration-tests
      if: needs.integration-tests.result == 'failure' || needs.integration-tests.result == 'cancelled'
      run: ${{ false }}
    - name: Set workflow outcome based on conformance-tests
      if: needs.conformance-tests.result == 'failure' || needs.conformance-tests.result == 'cancelled'
      run: ${{ false }}
```

This is a workaround for the fact that [ref](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview)

> Note: A job that is skipped will report its status as "Success". It will not prevent a pull request from merging, even if it is a required check.

Can I achieve this differently, ideally in a way that doesn't require scheduling a runner just to set the status?
