### DISCUSSION TITLE
Define inputs both for workflow_dispatch and workflow_call

### DISCUSSION THREAD

**Discussion by Makperson** [actions/runner#2558] [Q&A]
Hi!

I'm defining most of my workflows as reusable i.e

`Workflow 1` - Build docker image
`Workflow 2` - Reuse `workflow 1 `and push image to registry
`Workflow 3` (From different repo) - Reuse` workflow 2` and deploy image into dev environment

Thanks to this solution, i can trigger` workflow 1` each time PR is opened so I have built run for checks, but I can also run it manually, the same applies for `workflow 2`.

The problem is, that I want to pass some inputs to `workflow 2` from `workflow 3` (i.e branch to build), but I also want to run `workflow 2` manually. My main question is - do I need to define all the inputs twice, if I want them to be present in case the workflow is dispatched or called? (I know that by default, all caller workflow inputs will be passed, but this is not clear solution and I want to have it clearly indicated that I'm passing those variables. 

Is it the only way to achieve that?

```
on:
  workflow_dispatch:
    inputs:
        backend_branch:
        required: true
        type: string
        description: Backend tag
        default: main

  workflow_call:
      inputs:
          backend_branch:
          required: true
          type: string
          description: Backend tag
          default: main
```
 
 
Or this could be somehow assigned both to `workflow_dispatch` and `workflow_call` without adding extra lines of code?
