### DISCUSSION TITLE
Docker build FROM ghcr.io/actions/actions-runner:latest - enable-AzPSSession: true fails

### DISCUSSION THREAD

**Discussion by anwarnk** [actions/runner#2699] [General]
Hi, we created a docker image using the following:

#Dockerfile
```

FROM ghcr.io/actions/actions-runner:latest

RUN sudo apt-get update \
    && sudo apt install curl unzip -y \
    && sudo apt-get install -y wget apt-transport-https software-properties-common

RUN sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

RUN sudo apt-get install -y Node.js

RUN sudo wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" \
    && sudo dpkg -i packages-microsoft-prod.deb \
    && sudo rm packages-microsoft-prod.deb \
    && sudo apt-get update \
    && sudo apt-get install -y powershell

RUN pwsh -Command Install-Module Az -Force

USER runner

```
When we create an action with something like this:

#redacted
```
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
             azPSVersion: "latest"
```
It continues to try and logon but never succeeds, so we have to cancel it. If we use FROM summerwind/actions-runner:latest instead of FROM ghcr.io/actions/actions-runner:latest when building our docker image, it works successfully.
