### DISCUSSION TITLE
On Release published self hosted does not trigger but in GitHub Hosted runner it works.

### DISCUSSION THREAD

**Discussion by ccfiel** [actions/runner#2873] [Q&A]
I have this sample GitHub workflow. In GitHub Hosted runner, this will trigger, but in self-hosted runner, this will not triggered. Any idea why?

```
name: Release Drafter
on: 
  release:
    types: [published]
jobs:
  update_release_draft:
    runs-on: [ self-hosted, macOS ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
```
