### DISCUSSION TITLE
Using kaniko to build and push image in gha-runner-scale-set in Kubernetes mode

### DISCUSSION THREAD

**Discussion by Rollson** [actions/runner#3105] [Q&A]
Hi, i was going through the `containermode: Kubernetes` configuration for the gha-runner-scale-set. And i wanted to implement building and pushing image using Kaniko to a registry (for e.g, Azure Container Registry). Can anyone help out on how to set this up. could not find something in the documentation. My initial idea was to set up the workflow as shown below. However i had issues when deploying the workflow. 
Like this error, `Run '/home/runner/k8s/index.js'
  shell: /home/runner/externals/node16/bin/node {0}
env: can't execute '/__e/node16/bin/node': No such file or directory` in the `checkout action` and also the `initialize container` step showing this error `Run '/home/runner/k8s/index.js'
cat: can't open '/etc/*release*': No such file or directory.` Is this even the right way to do it? Thank you for your thoughts or suggestion 

```
name: Build and Deploy

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

env:
  ACR_URL: "myacr.azurecr.io"
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  kaniko-build:
    runs-on: arc-runner-set 
    container:
      image: gcr.io/kaniko-project/executor:debug 
    permissions:
      contents: read 

    outputs:
      commit_sha_short: ${{ steps.commit_sha.outputs.sha_short }}
    steps:

      - uses: actions/checkout@v4.1.1

      - name: short commit sha
        id: commit_sha
        run: echo "sha_short=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

      - name: print commit sha
        run: echo ${{ steps.commit_sha.outputs.sha_short }}

      - name: Build and Push Image with kaniko
        run: |
          echo "{\"credHelpers\":{\"${{ env.ACR_URL }}\":\"acr-env\"}}" > /kaniko/.docker/config.json

          kaniko/executor --dockerfile="./app/Dockerfile" \
            --destination="${{ env.ACR_URL }}/nginx:${{ steps.commit_sha.outputs.sha_short }}" ${{ env.KANIKO_CACHE_ARGS }} \
            --push-retry 3 
        env: 
          AZURE_CLIENT_ID: ${{ secrets.ACR_SPN_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.ACR_SPN_PASSWORD }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
```
