### DISCUSSION TITLE
What am I doing wrong with this conditional step?

### DISCUSSION THREAD

**Discussion by tking16** [actions/runner#3217] [Q&A] [answered]
I'm creating an action for a Selenium grid instance, it's only supposed to exit if $READY comes back false, $READY is true and  we're still getting a failed job!

```yaml
      - name: Get Selenium Grid status variables
        run: |
          echo "READY=$(cURL 'http://localhost:4444/status' | jq '.value.ready')" >> $GITHUB_ENV
          NODE_COUNT=$(cURL 'http://localhost:4444/status' | jq '.value.nodes' | jq 'length')

      - name: (DEBUG) Print variables
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
          STEP_CONTEXT: ${{ toJson(steps) }}
        run: |
          echo "$READY" # true
          echo "${{env.READY}}" # true
          cURL http://localhost:4444/status

      - name: Confirm Grid is up
        if: ${{ env.READY }} == true
        run: echo "Selenium Grid is Ready"
      - name: Exit if Grid is down
        if: ${{ env.READY }} != true
        run: echo "Selenium Grid wasn't ready, ending action" && exit 1
```
<img width="632" alt="Screenshot 2024-03-22 at 17 40 47" src="https://github.com/actions/runner/assets/13576824/4064590e-28ea-419f-95f5-8ef5088a068e">

Any help is appreciated
