### DISCUSSION TITLE
How to use the Docker version of Actions Runner？

### DISCUSSION THREAD

**Discussion by pooneyy** [actions/runner#3410] [Q&A]
How to write its docker-compose.yaml file? Can you give an example? Be deeply grateful

**Comment by amasen02** [comment]
Here is a complete, production-ready `docker-compose.yml` setup for running a containerized GitHub Actions runner, along with Docker-in-Docker support so your workflow jobs can run container steps:

### 1. `docker-compose.yml`

```yaml
services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner-01
    restart: unless-stopped
    environment:
      # Use REPO_URL for a single repository or ORG_NAME for an organization
      REPO_URL: "https://github.com/your-user/your-repo"
      # Pass via .env file (never hardcode in this file)
      RUNNER_TOKEN: "${RUNNER_TOKEN}"
      RUNNER_NAME: "docker-runner-01"
      RUNNER_WORKDIR: "/tmp/runner/work"
      LABELS: "self-hosted,linux,x64,docker"
      # ephemereal: set to 'true' if you want a clean container after each job
      EPHEMERAL: "false"
    volumes:
      # Mount the Docker daemon socket so workflows can build and run containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist the runner workspace across container restarts
      - runner-workspace:/tmp/runner/work

volumes:
  runner-workspace:
```

---

### 2. Create the `.env` file
Do not put your registration token directly in the YAML. Create a `.env` file in the same directory:

```bash
RUNNER_TOKEN=AAABBBCCCDDDEEEFFF12345
```

> **How to get the token:**  
> Go to your GitHub Repository -> **Settings** -> **Actions** -> **Runners** -> **New self-hosted runner**. Copy the token listed in the registration command (note that this registration token is valid for 1 hour for setup).

---

### 3. Start the Runner

```bash
# Start in the background
docker compose up -d

# Inspect runner logs to verify connection
docker compose logs -f github-runner
```

When connected, the logs will show:
```text
√ Connected to GitHub
Listening for Jobs
```

And in your GitHub repository under **Settings > Actions > Runners**, you will see `docker-runner-01` in the **Idle** state ready to accept jobs.
