### DISCUSSION TITLE
How to ask the runners to wait till the node get's provisioned

### DISCUSSION THREAD

**Discussion by sjm-ho** [actions/runner#3419] [Q&A]
So I use karpenter instead of cluster autoscaler to provision nodes in my EKS cluster, and one of my runner config tries to provision a node which is resource heavy.

```
          env:
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
          resources:
            requests:
              memory: "64Gi"
              cpu: "16000m"
            limits:
              cpu: "16000m"
              memory: "64Gi"
```

The runner waits for a particular time and then exists. I want it to wait for longer until the big node gets provisioned. How can I achieve that?
