### DISCUSSION TITLE
macos 14.6.1 curl download github runner package has error: certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

### DISCUSSION THREAD

**Discussion by zoezhangmattr** [actions/runner#3436] [General]
try to use ansible playbook to download github runner release
failed .anyone has the same issue? any help is appreciated.
aws macos instance
os :14.6.1, 

this is the playbook config
```yaml
- name: Download github runner package
  ansible.builtin.get_url:
    url: https://github.com/actions/runner/releases/download/v2.318.0/actions-runner-osx-arm64-2.318.0.tar.gz
    dest: "/opt/actions-runner/actions-runner-osx-arm64-2.318.0.tar.gz"
    mode: "0755"
```

```
"msg": "Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>",
    "url": "https://github.com/actions/runner/releases/download/v2.318.0/actions-runner-osx-arm64-2.318.0.tar.gz"
```
