### DISCUSSION TITLE
Job skips even with IF condition is satisfied

### DISCUSSION THREAD

**Discussion by rsorelli-hedgepoint** [actions/runner#3601] [General]
Hello folks,

I need some help regarding the IF condition on GHA.
I have a job with a if condition that keeps skipping even with the condition evaluating as TRUE.
Here it is:

```
  provision-resources:
    if: |
      (needs.call-run-build.result == 'success' &&
      github.event_name != 'pull_request')
    needs: [call-run-build]
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
```

I have set another job to check the value of those variables and all trem returns correctly:

```
  test-provision-resources:
    if: ${{ always() }}
    needs: [call-run-build]
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:

      - name: echo conditions
        run: |
          echo "provision-resources-result=${{ needs.call-run-build.result }}"
          echo "github-event-name=${{ github.event_name }}"
```

The output:

```
provision-resources-result=success
github-event-name=push
```

Does anyone have a hint of how I can fix it ?
