### DISCUSSION TITLE
sudo: apt-get: command not found

### DISCUSSION THREAD

**Discussion by lyledouglass** [actions/runner#3640] [Q&A]
Hello, 
I'm working on implementing ARC runners in our K8s cluster and have them 'working' and scaling as expected. I'm using the latest runner image and running into an odd error on some action steps. For example, I'm using:
```
browser-actions/setup-chrome@v1
  with:
    install-dependencies: true
    chrome-version: latest
    install-chromedriver: false
    no-sudo: false
```
For the `install-dependencies` step, it runs `/usr/bin/sudo apt-get update` without issue, however when it then tries to run the following, I get the error `sudo: apt-get: command not found`

`/usr/bin/sudo apt-get install --yes --no-install-recommends libglib2.0-0 libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 xvfb fonts-liberation libu2f-udev xdg-utils`

The `no-sudo` option available just hits a permissions error. I'm hoping someone can shed some light as to why the runner image is behaving like this.
Thank you,
