### ISSUE TITLE
 GitHub Actions Not Respecting Trigger "On Create Tags"

### ISSUE THREAD

**Issue by yousefcodes** [actions/runner#1007]
**Describe the bug**
I have two github workflows, one that fires when pushing a branch to master. And another that fires only when a tag is created. However, I am itermittently seeing my tags workflow fire, even when I push a branch. This doesn't always happen, it only happens ocassionally and generally it follows the tag creation rule. However, this is our production github workflow, and we simply cannot have a branch push cause that action to fire. What gives?

Note, I had also created this issue here: 
https://github.com/actions/virtual-environments/issues/2898

**To Reproduce**
1. Create a github actions workflow that fires on:
```
on:
  create:
    tags:
      - v*
```
2. Push a branch up to the repo, don't create a tag. The workflow fires. This is itermittent and can't always be replicated. So I'm perplexed here. It happens often enough to be a problem.

**Expected behavior**
I would only expect this github action to fire when I create a tag named v1.0.0 or v1.0.1 or vAnything

## Runner Version and Platform
Version of your runner?
This is happening live on GitHub.com not a local runner

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
When a github action fires, the `on` part of the workflow.

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by yousefcodes** [comment]
Not getting much traction on this issue, and thought I'd ask again!

**Comment by ChristopherHX** [comment]
Hi,
If I understand the [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) correctly, it states that the branch and tag filter are only supported for push and pull_request events. Althought it isn't a yaml schema error, it seems to ignore branch and tag filter for all other events like create.

I made a simple workflow which only runs if you create a tag. All other create events are skipped.
At least it skips create branch events.
```yaml
# This is a basic workflow to help you get started with Actions

name: prod-sample

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world
```
I hope it helps :)

**Comment by yousefcodes** [comment]
This is wonderful, thank you! Worked as expected.

**Comment by monkut** [comment]
It appears that this may perform the same desired result?

```
name: prod-sample

# Controls when the action will run. 
on:
  push:
    tag:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world
```
