### ISSUE TITLE
GTIHUB_TOKEN permissions seem inconsistent with docs

### ISSUE THREAD

**Issue by mikegeoffrey** [actions/runner#1008]
**Describe the bug**
GITHUB_TOKEN permissions listed here https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token do not appear to be consistent with reality.
For example GITHUB_TOKEN has read/write on contents, which includes the GET of the repository public-key, as described here: https://docs.github.com/en/rest/reference/actions#get-a-repository-public-key.
However when I do a simple workflow which does a curl against this endpoint, I receive the "Resource not accessible by integration." error.
This is using a self-hosted runner.

**To Reproduce**
1. Use the workflow code below and run it.
2. See error

**Expected behavior**
In this example I expected GITHUB_TOKEN to be able to read the public-key from the repository the workflow is running from.

## Runner Version and Platform
2.277.1

OS of the machine running the runner? OSX/Windows/Linux/...
 CentOS 7.9

## What's not working?
```
name: Test token
on:
  workflow_dispatch:
jobs:
   get_token:
    name: "Get and set Github token"
    runs-on: [self-hosted,live]
    steps:
    - name: Get public-key
      run: |
        curl -X GET --url https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'Accept: application/vnd.github.v3+json'
      shell: bash
```

```
curl -X GET --url https://api.github.com/repos/myorg/myrepo/actions/secrets/public-key --header 'authorization: ***' --header 'Accept: application/vnd.github.v3+json'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   159  100   159    0     0    524      0 --:--:-- --:--:-- --:--:--   524
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/actions#get-a-repository-public-key"

```

## Job Log Output
```
curl -X GET --url https://api.github.com/repos/myorg/myrepo/actions/secrets/public-key --header 'authorization: ***' --header 'Accept: application/vnd.github.v3+json'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   159  100   159    0     0    524      0 --:--:-- --:--:-- --:--:--   524
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/actions#get-a-repository-public-key"

```
