### ISSUE TITLE
Global npm dependencies are not installed correcly in 'ubuntu-latest'

### ISSUE THREAD

**Issue by LuisEnMarroquin** [actions/runner#1017]
**Describe the bug**

Running `npm list --global --depth 0` in `ubuntu-latest` fails with exit code 1

**To Reproduce**

1. Create a new repo (I am using branch main)
2. Add file `.github/workflows/publish.yml`
3. Write the following to the file

```yml
name: Publish to NPM

on:
  push:
    branches:
    - main

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
    - run: npm list --global --depth 0
```

![image](https://user-images.githubusercontent.com/35376824/111823290-624d8f00-88aa-11eb-8d9a-eb0909ce071e.png)

**Expected behavior**

The command should just show the globally installed packages and return exit code 0

![image](https://user-images.githubusercontent.com/35376824/111823641-ce2ff780-88aa-11eb-91c1-563a0f8c47b9.png)

## Runner Version and Platform

Version of your runner? 2.277.1 (provided by GitHub, not self-hosted)
OS of the machine running the runner? ubuntu-latest

![image](https://user-images.githubusercontent.com/35376824/111825522-2bc54380-88ad-11eb-881e-e304c3870eaf.png)

## What's not working?

![image](https://user-images.githubusercontent.com/35376824/111823910-20711880-88ab-11eb-86e5-883e769bc8af.png)
