### ISSUE TITLE
Literal colon character (":") in expressions kills YAML parser

### ISSUE THREAD

**Issue by noslouch** [actions/runner#1019]
Not sure how to escape a colon inside a double-quoted string. GitHub's web editor shows me a red squiggle and an error tooltip that verifies the parser error.

![image](https://user-images.githubusercontent.com/2090382/112238923-f5285980-8c1b-11eb-8ce4-b5d06ce2a4b0.png)

There's a thread over in [ansible](https://github.com/ansible/ansible/issues/38133#issuecomment-377525340) about this issue, but the escaping methods described there (quoting, curly braces) don't work.

This isn't isolated to the web editor. When the runner makes an attempt, it errors out:
![image](https://user-images.githubusercontent.com/2090382/112239230-7ed82700-8c1c-11eb-9835-b82ee540a2f5.png)

**Comment by ChristopherHX** [comment]
You can use format to get this working, just use `format('autorelease{0} pending', ':')` instead. You have to avoid writing ": " in yaml.

A sample workflow
```yaml
on: push
jobs:
    Test2:
        if: ${{contains(github.event.commits[0].message, format('autorelease{0} pending', ':'))}}
        runs-on: ubuntu-latest
        steps:
        - run: echo ${{github.event.commits[0].message}}
```

**Comment by noslouch** [comment]
That's a great workaround, thank you. 

> You have to avoid writing ": " in yaml.

Literal colons work just fine in pure yaml as long as they're quoted.

The problem is in the GitHub action expression, which I think qualifies this as a valid bug.

**Comment by ChristopherHX** [comment]
This workflow is also working, I cannot say if it is a bug or not.
```yaml
on: pull_request
jobs:
    Test2:
        if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
        runs-on: ubuntu-latest
        steps:
        - run: echo Hello World
```
see https://github.com/ChristopherHX/Buildbot/actions/runs/695354752/workflow and https://github.com/ChristopherHX/Buildbot/pull/1

I'm not affiliated with microsoft or this project. I'm just interested in using github actions :)

**Comment by noslouch** [comment]
You've got quotes around your expression:

```yaml
if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
```

Maybe that helps the yaml parser? Hard to say if the expression is still evaluated without seeing the debug output.

**Comment by hross** [comment]
Putting single quotes inside of double quotes will indeed fix the parsing and that is the right answer. Thanks @ChristopherHX!

**Comment by polsm91** [comment]
I came across this issue when fixing the following action snippet:

```yaml
    - name: Update version
        run: sed myfile.yaml  -i -e "s+^version:.*$+version: \"${{ inputs.new_version }}\"+g"
        shell: bash
```
It seems a big constrain to ban the colon in workflows.  I have noticed that the parser breaks when the colon character has a trailing space, but works if you write another character. For instance "something:something" works while "something: something" does not. In the end I removed the blank space because the other workarounds feel overenginered.

**Comment by Torxed** [comment]
For whomever ends up here..
```yaml
 -run: |
     ...
```
Also appears to be working.
```yaml
on: push
jobs:
    Test2:
        if: |
            ${{ contains(github.event.pull_request.labels.*.name, "autorelease: pending") }}
        runs-on: ubuntu-latest
        steps:
        - run: echo ${{github.event.commits[0].message}}
```

Didn't see it mentioned in the previous messages, and this pops up for other colon related issues.
This reference helped: https://stackoverflow.com/a/33149072/929999

**Comment by kda33** [comment]
@Torxed  you're awesome

**Comment by ckingbailey** [comment]
@Torxed your workflow did not work for me:
```
Invalid workflow file: .github/workflows/test.yml#L7 
The workflow is not valid. .github/workflows/test.yml (Line: 7, Col: 13): Unexpected symbol: '"autorelease:'. Located at position 51 within expression: contains(github.event.pull_request.labels.*.name, "autorelease: pending")
```
I switched double quotes to single, and it validates ok, but the if condition does not work.

I tried a very similar test, switching it to run on pull_request, and it would seem that the pipe `|` causes the if condition to always evaluate true.
```
on:
  pull_request:
    branches:
      - main

jobs:
  autorelease_pending: # Runs on any pull request despite the if condition
    runs-on: ubuntu-22.04
    if: |
      ${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}
    steps:
      - run: |
          echo "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}" # prints false

  autorelease_pending2: # Correctly runs only on expected label
    runs-on: ubuntu-22.04
    if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
    steps:
      - run: |
          echo "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}" # prints false
```
I have tried this with various other expressions and gotten the same result.

**Comment by persep** [comment]
Is this related to giving me an error when I have a : in a step? like so

```
- name: Number of files in data
  run: echo "Number of files in data folder: $(ls data | wc -l)"
```
It works when I remove the :

**Comment by mateuszgazdziak** [comment]
> @Torxed your workflow did not work for me:
> 
> ```
> Invalid workflow file: .github/workflows/test.yml#L7 
> The workflow is not valid. .github/workflows/test.yml (Line: 7, Col: 13): Unexpected symbol: '"autorelease:'. Located at position 51 within expression: contains(github.event.pull_request.labels.*.name, "autorelease: pending")
> ```
> 
> I switched double quotes to single, and it validates ok, but the if condition does not work.
> 
> I tried a very similar test, switching it to run on pull_request, and it would seem that the pipe `|` causes the if condition to always evaluate true.
> 
> ```
> on:
>   pull_request:
>     branches:
>       - main
> 
> jobs:
>   autorelease_pending: # Runs on any pull request despite the if condition
>     runs-on: ubuntu-22.04
>     if: |
>       ${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}
>     steps:
>       - run: |
>           echo "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}" # prints false
> 
>   autorelease_pending2: # Correctly runs only on expected label
>     runs-on: ubuntu-22.04
>     if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
>     steps:
>       - run: |
>           echo "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}" # prints false
> ```
> 
> I have tried this with various other expressions and gotten the same result.

I had very same problem with release-please. Could not solve it. I ended up, modifying `label` in `release-please-config.json` to `nextRelease`.

**Comment by JohnTheCoolingFan** [comment]
This is still a bug, having a bunch of workarounds is not a solution.

I encountered this when I had to make a simple json request body for curl, it was hellish and turned out not looking great: https://github.com/JohnTheCoolingFan/PlutoniumEnergy/blob/0dbeb7d84c0faa63f774fb4d21f34ba1c7c8cd68/.github/workflows/cd.yml#L47

**Comment by jeremycarroll** [comment]
I found using `>-` rather than `|` works:
i.e.
```
jobs:
  job2:
    if: >-
        ${{ 1 == 0 }}
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo Hello world
```
does not run, whereas
```
jobs:
  job2:
    if: |
      ${{ 1 == 0 }}
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo Hello world
```
does

**Comment by misium** [comment]
This bug killed me for a good while this morning.

+1 to @polsm91 for suggestion to remove trailing spaces.

Since this has lingered for years now -- a simple user-intelligible error report (or just citing the column that breaks the parser) would've been a huge help here

**Comment by kubotty** [comment]
> I found using `>-` rather than `|` works: i.e.
> 
> ```
> jobs:
>   job2:
>     if: >-
>         ${{ 1 == 0 }}
>     runs-on: ubuntu-latest
>     steps:
>       - run: |
>          echo Hello world
> ```
> 
> does not run, whereas
> 
> ```
> jobs:
>   job2:
>     if: |
>       ${{ 1 == 0 }}
>     runs-on: ubuntu-latest
>     steps:
>       - run: |
>          echo Hello world
> ```
> 
> does

Additionally, this also works without `${{ }}`:

```
jobs:
  job2:
    if: |
      1 == 0
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo Hello world
```
does not run either.
