### ISSUE TITLE
Prepend path from steup-$tool installers broken in job containers

### ISSUE THREAD

**Issue by dakale** [actions/runner#103]
## What's not working?
Tools installed by setup-$tool actions that require a PATH update in the environment break in job containers

Containers typically bring their own toolsets so I havent seen anyone hit this yet, but it is broken

I introduced this bug via https://github.com/actions/runner/pull/23/files#diff-fd6512562302c29ee1adf6e88a5f1e11 

We had a nice chain-loader-ish setup via the node process where:
1. Node process exec'd in container would pick up PATH from container environment
2. Prepend tool paths that were tracked

Part of supporting more job container types (alpine!) and to simplify the job container concept I removed this dependency on node

Because the environment of the container cant be known until runtime so it must be started and some process must run in the container. Passing -e PATH={prependPath}:$PATH is $PATH relative to the host, and theres not really a way to set a modified path without completely writing over the container path

I am introducing some new patterns where we need to exec into the container to gather runtime information anyways (figure out distribution / libraries so we know which nodejs binary to use as the script runtime), so Im going to fix it there

In this example the modified path setup by setup-node doesnt make it to the run script
```yaml
on: push
jobs:
  myjob:
    container: alpine
    runs-on:
      pool: default
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: node --version
```
