### ISSUE TITLE
Cannot use inputs in non-composite actions

### ISSUE THREAD

**Issue by tarfeef102** [actions/runner#1035]
**Describe the bug**
No matter what I try, I cannot get inputs to work with non-composite actions. I'm allowed to define them, and trigger an action via API whilst providing inputs, but they cannot be referenced and don't show up as env vars later in the action (non-composite). I suspect the answer here is "you can't do that", however:
- I should be able to, why no? It'd be helpful
- [The docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) don't say that, and even if you disagree with the former point, you should support accurate docs.

**To Reproduce**
create an action looking roughly like this:
```
name: test_workflow

on:
  workflow_dispatch:
    inputs:
      varname:
        required: true
        description: 'a test varname'

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Print inputs
      - name: Print inputs
        run: echo ${{ inputs.varname }}
```
i also tried just using `INPUTS_VARNAME`, dumping `env`, etc. nothing worked. Either got `Unrecognized named-value: 'inputs'` as an error, the variable resolved to nothing, and when I dumped `env` there were no inputs present.

**Expected behavior**
Either inputs should work (ideal), or the docs should explicitly say "this only works with composite actions". 

## What's not working?
Either got `Unrecognized named-value: 'inputs'` as an error, the variable resolved to nothing, and when I dumped `env` there were no inputs present.

**Comment by hross** [comment]
The docs are a bit convoluted to interpret, but the issue you are having is you aren't using the github context ([documented here in the context section of the expression syntax guide](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts). Combining that with [the docs for the workflow dispatch event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events) you can rewrite:

```yaml
      # Print inputs
      - name: Print inputs
        run: echo ${{ inputs.varname }}
```

as the following to access inputs in your example yaml file:

```yaml
      # Print inputs
      - name: Print inputs
        run: echo ${{ github.event.inputs.varname }}
```

**Comment by tarfeef102** [comment]
Thanks. I don't suppose instead of just closing this out, we could recognize a collaborator on the project admits `the docs are a bit convoluted to interpret`, and fix that? I'd be happy to contribute to a rewrite if pointed at where to direct my ire :D

**Comment by Crisfole** [comment]
I know this is old, but this continues to be a footgun, and the *new* docs (https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) are **not** convoluted to interpret. They *explicitly* claim and use as an example that `${{ inputs.name }}` should work.

**Comment by bees4ever** [comment]
> I know this is old, but this continues to be a footgun, and the _new_ docs (https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) are **not** convoluted to interpret. They _explicitly_ claim and use as an example that `${{ inputs.name }}` should work.
> 
> > In the reusable workflow, reference the input or secret that you defined in the on key in the previous step.
> 
> with the demo code:
> 
> ```yaml
> ...
> jobs:
>   print-username:
>     runs-on: ubuntu-latest
> 
>     steps:
>       - name: Print the input name to STDOUT
>         run: echo The username is ${{ inputs.username }}
> ```

Yes for me the same I just copied over the example, which turn out to be not working....

**Comment by mykola-lysenko** [comment]
yeah, same for me, neither inputs or github.event.inputs.varname works

**Comment by melissachang** [comment]
I had the same problem (`Unrecognized named-value: 'inputs'`, [GHA run](https://github.com/DataBiosphere/tanagra/actions/runs/4559386553/jobs/8043285676)).

The problem wasn't `inputs.username`, it was `workflow_dispatch`.

This fails ([see here](https://rhysd.github.io/actionlint/#eJxVjrEOwjAMRPd8hQfWgsSYiW/gB1BIDQ1t42A7VFXVfye0UInt7mTfu+h6tHDGxGQMRWsABuL21tFwqYMkp775C73ruk8AEGLKKqsG4Bwj8s8Vj88cGGsLyhm3WMdUeKIc4t2YB12Xgn6silyfS5FUZQnspunL2K/lMM/LhSimjVtBFhQLzmugKAffoG8p6+l1NG+TfEPt)):

```
  workflow_dispatch:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
```

If I delete `workflow_dispatch`, it works ([see here](https://rhysd.github.io/actionlint/#eJw9jTEOwjAMRfecwgNrQWLMxBm4ACrBQGhrB9tpVVW9O6GFbv9/2e9R3aGHMyZh55i8AxhYmnvLwyXUbfsdACKlbLpmAMlEKP9WOr5zFLx5MMm4zTamglaTSA/nXnxdAN1Ylbg+F5BWRQq7afo59isc5nm5UMO0eSvIiuqhDhaZ9BCeGBrOduqP7gNS0zw/)):

```
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
```

If I add the input to `workflow_dispatch`, it works ([see here](https://rhysd.github.io/actionlint/#eJytj0EOwjAMBO95hQ9cCxLHnHgDH0AhGBraOsF2qKqqfye0UPEAbrsre1ZLrkMLR0wcjYlkDUAfubm2sT9dgiSnvn6HAIFSVlk0AGci5K8rHh85MF4sKGdcYx1SwYtyoNsv2ru2/RfW3ON5BnRDVeTyXEBSlT2wGcdPx3aBwzTNF6KY1t4KsqBYcF5DJNn5Gn0Tsx6ee/MCdHhXNA==)):

```
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: string
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
```

So it appears that `workflow_dispatch` and `workflow_call` inputs must be in sync. I suspect [this blog post](https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/) is related.

**Comment by Heachy** [comment]
> **Describe the bug** No matter what I try, I cannot get inputs to work with non-composite actions. I'm allowed to define them, and trigger an action via API whilst providing inputs, but they cannot be referenced and don't show up as env vars later in the action (non-composite). I suspect the answer here is "you can't do that", however:
> 
> * I should be able to, why no? It'd be helpful
> * [The docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) don't say that, and even if you disagree with the former point, you should support accurate docs.
> 
> **To Reproduce** create an action looking roughly like this:
> 
> ```
> name: test_workflow
> 
> on:
>   workflow_dispatch:
>     inputs:
>       varname:
>         required: true
>         description: 'a test varname'
> 
> jobs:
>   test:
>     name: test
>     runs-on: ubuntu-20.04
> 
>     steps:
>       # Checks-out repository under $GITHUB_WORKSPACE
>       - name: Checkout commit
>         uses: actions/checkout@v2
>         with:
>           fetch-depth: 1
> 
>       # Print inputs
>       - name: Print inputs
>         run: echo ${{ inputs.varname }}
> ```
> 
> i also tried just using `INPUTS_VARNAME`, dumping `env`, etc. nothing worked. Either got `Unrecognized named-value: 'inputs'` as an error, the variable resolved to nothing, and when I dumped `env` there were no inputs present.
> 
> **Expected behavior** Either inputs should work (ideal), or the docs should explicitly say "this only works with composite actions".
> 
> ## What's not working?
> Either got `Unrecognized named-value: 'inputs'` as an error, the variable resolved to nothing, and when I dumped `env` there were no inputs present.

So how did you solve this problem? I looked it up and it seems there is no accurate solution, but I still can't find it. QAQ

**Comment by zolex** [comment]
I have the same issue with a private/local action. In the following scenario, the inputs under the `args` are working fine, but the input in the `image` results in the error `Unrecognized named-value: 'inputs'`



```
name: 'Example'
description: 'Example'
inputs:
  image-tag:
    description: 'Version tag image to use.'
    default: 'latest'
  name:
    description: 'Service name'
    required: true
  stage:
    description: 'Stage to deploy'
    required: true
  target:
    description: 'Target to deploy'
    required: true
runs:
  using: 'docker'
  image: 'image-name:${{ inputs.image-tag }}'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.stage }}
    - ${{ inputs.target }}
```
