### ISSUE TITLE
[skip ci] skips non-CI workflows

### ISSUE THREAD

**Issue by couchand** [actions/runner#1049]
This is a follow-up to #774 and #976.

**Describe the bug**
Workflows that trigger on push are silently ignored if a commit contains the phrase "[ci skip]".  Not all `push`-triggered workflows are CI, notably pushes to tags are used to indicate releases.

**To Reproduce**
1. Create a release workflow, e.g.

```
on:                                                                    
  push:                                                                
    tags:                                                              
      - 'v[0-9]+.[0-9]+.[0-9]+'   
```

2. Tag a release on a commit with the message "[ci skip]" & push the tag.
3. Release workflow silently ignored.

**Expected behavior**
Pushes to tags should trigger workflows.

**Possible workarounds**
Trigger on the release event instead.  Not ideal, as this requires all tags to be tagged through the GitHub UI, rather than allowing the general git tag mechanism.
