### ISSUE TITLE
Github Action failed with out of memory error

### ISSUE THREAD

**Issue by mickd3** [actions/runner#1051]
I would like to deploy a project with Github Action.
I can't use SSH copy file because I can't add all IP addresses in white list on my server.

So I use a Linux self-hosted runner to try.

When I test my connexion with the server in the goal of testing a simple action, it works perfectly.

```
name: Hello World
on: [push]

jobs:
  one:
    name: Hello
    runs-on: self-hosted
    steps:
      - run: echo "hello world"
```

But when I want to  use some actions like checkout, it works with 'ubuntu-20.04' but not with a self hosted runner on my server.

```
name: Deployment to production

on:
  push:
    branches:
      - master
     
jobs:
  auto-pull:
    name: Build and deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
```

In Github Repo settings, my runner is green with 'Idle'

I do not see any errors in logs of the runner on the server.
I juste see 'Job Build and deploy completed with result: Failed' in the CLI just after the workflow start.
In Github, the workflow failed with 'Out of memory' error after a few time.

So I would like to find a solution to use Self-hosted runner or another method to solve the problem of the SSH access to deploy my project. 
Thanks in advance
