### ISSUE TITLE
Masked output can't be read by downsteam jobs.

### ISSUE THREAD

**Issue by DarqueWarrior** [actions/runner#1061]
**Describe the bug**
I have a workflow with two jobs. The first job deploys using bicep to Azure and retrieves sensitive information as an output of the deployment. I output that information and mask it.

```
Write-Output "::set-output name=aksName::$($deployment.properties.outputs.aksName.value)"
Write-Output "::set-output name=storageAccountKey::$($deployment.properties.outputs.storageAccountKey.value)"
Write-Output "::add-mask::$($deployment.properties.outputs.storageAccountKey.value)"
Write-Output "::set-output name=serviceBusEndpoint::$($deployment.properties.outputs.serviceBusEndpoint.value)"
Write-Output "::add-mask::$($deployment.properties.outputs.serviceBusEndpoint.value)"
Write-Output "::set-output name=storageAccountName::$($deployment.properties.outputs.storageAccountName.value)"
Write-Output "::set-output name=cognitiveServiceKey::$($deployment.properties.outputs.cognitiveServiceKey.value)"
Write-Output "::add-mask::$($deployment.properties.outputs.cognitiveServiceKey.value)"
Write-Output "::set-output name=cognitiveServiceEndpoint::$($deployment.properties.outputs.cognitiveServiceEndpoint.value)"
```

At the end of that job I define outputs. 

```
outputs:
      aksName: ${{ steps.azure-deployment.outputs.aksName }}
      storageAccountKey: ${{ steps.azure-deployment.outputs.storageAccountKey }}
      storageAccountName: ${{ steps.azure-deployment.outputs.storageAccountName }}
      serviceBusEndpoint: ${{ steps.azure-deployment.outputs.serviceBusEndpoint }}
      cognitiveServiceKey: ${{ steps.azure-deployment.outputs.cognitiveServiceKey }}
      cognitiveServiceEndpoint: ${{ steps.azure-deployment.outputs.cognitiveServiceEndpoint }}
```

In a downstream job I try to access the output .

```
helm upgrade --install demo3 ./chart `
            --set usingPowerShell=True `
            --set image.tag='${{ github.run_number }}' `
            --set twitter.consumerKey='${{ secrets.TWITTER_CONSUMERKEY }}' `
            --set twitter.accessToken='${{ secrets.TWITTER_ACCESSTOKEN }}' `
            --set twitter.accessSecret='${{ secrets.TWITTER_ACCESSSECRET }}' `
            --set twitter.consumerSecret='${{ secrets.TWITTER_CONSUMERSECRET }}' `
            --set tableStorage.key='${{ needs.deployInfrastructure.outputs.storageAccountKey }}' `
            --set tableStorage.name='${{ needs.deployInfrastructure.outputs.storageAccountName }}' `
            --set cognitiveService.token='${{ needs.deployInfrastructure.outputs.cognitiveServiceKey }}' `
            --set serviceBus.connectionString='${{ needs.deployInfrastructure.outputs.serviceBusEndpoint }}' `
            --set cognitiveService.endpoint='${{ needs.deployInfrastructure.outputs.cognitiveServiceEndpoint }}'
```

Only the unmasked values are able to be retrieved from the downstream jobs.  I need to mask in the first job because the values are used there as well. 

**To Reproduce**
1. Mask outputs in one job
2. Try and access in downstream job

**Expected behavior**
I expected to be able to read that data in the downstream job.

## Runner Version and Platform
Version of your runner?
`2.278.0`

OS of the machine running the runner? OSX/Windows/Linux/...
`ubuntu-20.04`

## What's not working?
Please include error messages and screenshots.
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.connection-string`

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
