### ISSUE TITLE
[Custom action] Cannot execute script using Bash in Windows

### ISSUE THREAD

**Issue by wzshiming** [actions/runner#1066]
**Describe the bug**
Cannot execute script using Bash in Windows, ${{ github.action_path }} cannot be used normally.
```
D:\a\_temp\9d1827c9-d470-46af-a45b-419b7fdd05fd.sh: line 1: D:a_actionswzshimingaction-testv1/test.sh: No such file or directory
```

**To Reproduce**

Workflow
```
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Self
      uses: wzshiming/action-test@v1
```

Custom action
```
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/test.sh
      shell: bash
```

**Expected behavior**
Run  `D:/a/_actions/wzshiming/action-test/v1/test.sh`

## Runner Version and Platform

Windows

## What's not working?

Backslash is escaped

Run `D:a_actionswzshimingaction-testv1/test.sh`

```
D:\a\_temp\9d1827c9-d470-46af-a45b-419b7fdd05fd.sh: line 1: D:a_actionswzshimingaction-testv1/test.sh: No such file or directory
```
