### ISSUE TITLE
Add support for `needs` based on `matrix`

### ISSUE THREAD

**Issue by nedrebo** [actions/runner#1121]
# Use case

I build my SW using a matrix, let's say:

```
matrix:
    os: [windows, linux]
    configuration: [Release, Debug]
    architecture: [amd64, arm64]
```

Then, when I want to test the SW I use another matrix:

```
matrix:
    os: [windows, linux]
    configuration: [Release, Debug]
    architecture: [amd64, arm64]
    tests: [foo, bar, baz, ....]
```

All the "tests" are big collections of tests that must be run in parallel (only limited by free runners) since they are time-consuming.

# Proposal

Testing must wait for the corresponding build to be done, but it does not need to wait for other builds to be done. Therefore, I would like to do the following in the test job, and I propose this as an extension:

```
needs: build-${{ matrix.os }}-${{ matrix.configuration }}-${{ matrix.architecture }}
```

Right now this is not supported. If I try this it results in an error. All I can do today is:

```
needs: build
```

This is way too coarse and puts unnecessary barriers in the pipeline that hits me twice. First, all testing must wait until all building is done. Then, once all building is done all tests are fired at once resulting in unnecessary queues.

Other job properties like `runs-on` and `steps` can depend on a matrix, so this seems like an oversight that should be fixed.

# Workaround

Right now I use our workflow generator to expands all matrices into a massive workflow with no matrices. This works ok, but it would be nice to avoid this step. That would make the generated workflow more readable since less duplication would be needed.

Unfortunately, this workaround is only possible for projects that generate their workflows.
