### ISSUE TITLE
Allow skipping a job based on whether there is permission to access certain secrets

### ISSUE THREAD

**Issue by ismay** [actions/runner#1138]
**Describe the enhancement**

Allow skipping a job based on whether there is permission to access a certain secret

**Code Snippet**

Currently, this is the most readable, concise way I've found of conditionally running jobs that need secrets:

```yml
jobs:
  secrets:
    runs-on: ubuntu-latest
    outputs:
      HAS_PERCY_TOKEN: ${{ steps.check.outputs.PERCY_TOKEN }}
      HAS_GITHUB_TOKEN: ${{ steps.check.outputs.GITHUB_TOKEN }}
    steps:
      - run: >
          echo "::set-output name=PERCY_TOKEN::${{ env.PERCY_TOKEN != '' }}";
          echo "::set-output name=GITHUB_TOKEN::${{ env.GITHUB_TOKEN != '' }}";
        id: check
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job1:
    needs: ["secrets"]
    if: >
      needs.secrets.outputs.HAS_PERCY_TOKEN == 'true' &&
      needs.secrets.outputs.HAS_GITHUB_TOKEN == 'true'
    runs-on: ubuntu-latest
    steps:
        # Steps here
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job2:
    needs: ["secrets"]
    if: >
      needs.secrets.outputs.HAS_GITHUB_TOKEN == 'true'
    runs-on: ubuntu-latest
    steps:
        # Steps here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

There are other ways of course, but my point is they all basically involve a _ton_ of boilerplate. It is a very common usecase to check for the existence of a secret before running a job, as your workflows could potentially also be started by dependabot, or someone without access to secrets. But currently it is just way to cumbersome to do so. Plus it is polluting my action logs with a lot of jobs that all check for secrets before a certain workflow runs (which is obscuring the info I _really_ want to see).

My feature request is to allow for a more concise way to conditionally run a job depending on whether it has access to one or more secrets. So basically the functionality from the code sample above, but ideally just in the if condition of the job that needs the secrets (or potentially configured in another manner, as long as it cuts down on the above boilerplate).

**Additional information**

I'm not the only one who really wants this, see these issues and questions that all deal with this topic:

- https://github.com/actions/runner/issues/520
- https://github.com/actions/runner/issues/953
- https://github.community/t/how-can-i-test-if-secrets-are-available-in-an-action/17911/10
- https://github.community/t/jobs-job-id-if-does-not-work-with-env-secrets/16928/8

For a real-world example, see the workflows in this repo for example: https://github.com/ismay/superwolff/runs/2766011890. Which has 6 workflows, of which 5 have to implement almost the exact same boilerplate just to check whether secrets are available.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md
