### ISSUE TITLE
docker-compose run can't run

### ISSUE THREAD

**Issue by yuzujoe** [actions/runner#1139]
**Describe the bug**
I'm using Gtihub Actions' self hosted runner on AWS EC2  to run Ruby on Rails tests built with docker and docker-compose.  

I tried docker-compose run command on Github Actions to run bundle install and migration and rspec task, but docker-compose run command itself is running, but the container is not started and the step is still running.

**To Reproduce**
1. You can create the same environment by using the Terraform repository here.
https://github.com/yuzujoe/github-actions-runner

2. Create a rails application with the rails new command and create a simple dockerfile and docker-compose.

3. define simple github actions workflow see below.

```
name: Test

on: pull_request

jobs:
  test:
    name: test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose build
        run: |
          docker-compose build

      - name: bundle install
        run: docker-compose run --rm api bundle install
```

**Expected behavior**
docker-compose run should complete tasks such as bundle install.

## Runner Version and Platform
- Version of your runner?
v2.278.0

- OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
docker-compose run does not work as expected

<img width="997" alt="スクリーンショット 2021-06-08 8 30 38" src="https://user-images.githubusercontent.com/39491874/121100013-ea04c300-c833-11eb-8fff-830627339307.png">

## Runner and Worker's Diagnostic Logs

Which do you need for information on this issue?
I'd like to know so I can provide the appropriate information.
