### ISSUE TITLE
Workflow starts automatically 

### ISSUE THREAD

**Issue by dynamicat** [actions/runner#1141]
**Describe the bug**
We have two workflows:
test.yml
release.yml

The test.yml workflow is triggered by a push to the develop and master branches like below with also paths defined:

```
on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/*.yml
      - package.json
      - phpinclude/composer.*
      - ruleset.xml
      - "**/*.html"
      - "**/*.php"
      - "**/*.css"
      - "**/*.scss"
      - "**/*.js"
```
The release.yml is triggered with the creation of a tag like so:

```
name: release
on:
  create:
    tags:
      - '*.*.*'

```
When a new feature branch is pushed to the repository the test workflow triggers but also for some reason the release workflow starts on its own, even though we have specified for the workflow to be triggered manually upon tag creation.

What could make this happen and/or is this normal?

**Expected behavior**
The test workflow is the only thing that is supposed to run.

## Runner Version and Platform
Cloud hosted github
