### ISSUE TITLE
Containers: overriding HOME environment variable with mismatching /etc/passwd home causes issues

### ISSUE THREAD

**Issue by hoxu** [actions/runner#1146]
GitHub Actions runner currently seems to set container `HOME` environment variable to `/github/home`. Unfortunately, this is different from what the home directory is set to in the container's `/etc/passwd`. For example, if the container is run as `root`, the home directory in `/etc/passwd` is usually `/root`.

This mismatch causes some unexpected issues like making caching more difficult. When caching Java M2 dependencies for example, the following does not work:

```
- uses: actions/cache@v2
   with:
     key: m2
     path: ~/.m2
```

This is because the Java `user.home` property is set to whatever is in `/etc/passwd`.

Would it be possible to have the runner not change `HOME` by default?

On a related note, it would be really nice if the GitHub runner's parameters to docker containers were documented clearly somewhere.

**Comment by justfalter** [comment]
I've encountered this issue when two different workflows have executed on the same runner, but in containers running as different users.

The following will run as root, and create a file in the home directory `test-file`. This file is owned by uid=0, gid=0.
```
jobs:
  runs-as-root:
    runs-on: [self-hosted, docker]
    container:
      image: node:latest
    steps:
      - run: |
          id
          touch ~/test-file
```

The following will do the same as above, but run as the `node` user with uid=1000, gid=1000. This fails with a `Permission denied` error because the `~/test-file` already exists, but is owned by uid=0, gid=0.
```
jobs:
  runs-as-node:
    runs-on: [self-hosted, docker]
    container:
      image: node:latest
      options: --user node:node
    steps:
      - run: |
          id
          touch ~/test-file
```

We've come to the conclusion that the safest course of action is to try to run all containers as the root user, but this can be challenging when some software packages behave differently when running as root (ex: npm version 6 won't execute lifecycle scripts when run as root), while others refuse to run at all (ex: postgresql's pg_ctl refuses to run as root).
