### ISSUE TITLE
Test step in build keeps on running until timeout

### ISSUE THREAD

**Issue by pramay-n** [actions/runner#1154]
**Describe the bug**
I want to setup a workflow, so that I can test my django application on every push. But I don't know for some reason the test step keeps on running, logs are also stuck after a point. Not able to track what could have gone wrong. The tests work fine on my local system along with the logs.

**Expected behavior**
Step should have resulted either in a success or failure (if any). 

## Runner Version and Platform
Ubuntu Latest [ Github Owned Runner]

Here's my workflow file:
```
name: Build & Test Staging

on:
  push:
    branches:
      - dev

  jobs:
    build:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:10.8
          env:
            POSTGRES_USER: XXX
            POSTGRES_PASSWORD: XXX
            POSTGRES_DB: XXX
          ports:
            - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
        - uses: actions/checkout@v2
  
        - name: Setup python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7.10
  
        - name: psycopg2 prerequisites
          run: sudo apt-get install libpq-dev
  
        - name: Install packages
          run: |
            pip install -r deployment/commons/requirements.txt
        - name: Configure sysctl limits
          run: |
            sudo swapoff -a
            sudo sysctl -w vm.swappiness=1
            sudo sysctl -w fs.file-max=262144
            sudo sysctl -w vm.max_map_count=262144
        - name: Runs Elasticsearch
          uses: elastic/elastic-github-actions/elasticsearch@master
          with:
            stack-version: 6.8.5
  
        - name: Test Elasticsearch
          run: |
            curl http://localhost:9200/
        - name: Python Run Test
          run: |
            export PYTHONPATH=project
            cd project
            python manage.py test --settings=project.settings.test user.tests
```

![Screenshot (1)](https://user-images.githubusercontent.com/84841097/122048323-b9f28c80-cdfe-11eb-98cb-15c847584800.png)
