### ISSUE TITLE
Add inputs block for scheduled events

### ISSUE THREAD

**Issue by rnett** [actions/runner#1160]
**Describe the enhancement**
The `workflow_dispatch` event has a nice `inputs` block that allows us to specify inputs that can be set by the user and accessed by `github.event.inputs`.  I would like to have a similar block for `schedule` for each `cron`, obviously without the user input (it would be more similar to `with`, syntax wise).

For example, suppose you want to run your workflow every week for `main` but every day for `dev`.  There is currently no way to do this without duplicating workflows, but with an input block it's easy:
```yml
on:
  schedule:
    - cron: "0 0 * * 6"
      inputs:
        branch: "main"

    - cron: "0 0 * * *"
      inputs:
        branch: "dev"

...


      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

```

Another example: what if you have a scheduled workflow (like the one above) with defaults, but want to be able to manually run the workflow with user inputs.  For the above example, say you want the ability to run it on any branch on command.  This is currently possible by checking `github.event_name` and hardcoding the scheduled value, but requires duplicating steps, where if we have scheduled inputs it is as simple as:
```yml
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch"
        required: false
        default: 'main'
  schedule:
    - cron: "0 0 * * 6"
      inputs:
        branch: "main"

    - cron: "0 0 * * *"
      inputs:
        branch: "dev"
```
