### ISSUE TITLE
Workflow expression to read file content

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/runner#1180]
**Describe the enhancement**
It would be great to have some function or expression to read file content (`readFile` or `contents`).
Something like `{{ contents('.nvmrc') }}`

**Code Snippet**
```yml
uses: setup-node@v1
with:
  node-version: {{ contents('.nvmrc') }}
```

**Additional information**
We already have functions that works with FileSystem, for example `hashFiles`.
Introducing `contents` command will bring benefits to a bunch of 1st party actions.
A few examples:
- very popular request to add support for parsing `.nvmrc` in setup-node: https://github.com/actions/setup-node/issues/32
- add support for `.node-version` in setup-node: https://github.com/actions/setup-node/issues/206
- support for reading `.java-version` file in setup-java: https://github.com/actions/setup-java/issues/113

It doesn't make much sense to implement this logic in every action. It would be great to have ability to read files via simple expression:
```yml
uses: setup-java@v1
with:
  java-version: {{ contents('.java-version') }}
```
```yml
uses: setup-node@v1
with:
  node-version: {{ contents('.nvmrc') }}
```
