### ISSUE TITLE
Or Condition not working in if

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [actions/runner#1197]
I've been trying to build a CICD pipeline in Github actions and we're not able to process if and or conditions in the same. below is the example of our code snippet,

```yaml
    name: Build Non prod
    needs: [rules]    
    if: ${{ (needs.rules.outputs.branch_name != 'production') || (needs.rules.outputs.branch_name != 'staging') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
```
So this task should not run in `production` and `staging` branch, but when actions runs in `staging` branch, this job is also getting triggered along with other jobs which are not meant for `staging` environment.

Is there any way we can have `if` and `or` condition ?

**Comment by ChristopherHX** [comment]
You want && not ||
```yml
name: Build Non prod
    needs: [rules]    
    if: ${{ (needs.rules.outputs.branch_name != 'production') && (needs.rules.outputs.branch_name != 'staging') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
```

This expression is always true,
```yml
if: ${{ (needs.rules.outputs.branch_name != 'production') || (needs.rules.outputs.branch_name != 'staging') }}
```
because branch_name can never be 'production' and 'staging' at the same time.
