### ISSUE TITLE
Pushing a git tag triggers unrelated workflows

### ISSUE THREAD

**Issue by ronilan** [actions/runner#1202]
**Describe the bug**
In a repo with several workflows, a git tag push will trigger unrelated workflows that should not be triggered by the tag push. The unrelated triggered workflows include those which should only be triggered by a branch push as well as those which include a path filtered branch push trigger.

**To Reproduce**

Create a repo with the following workflows:
```
name: 'Push'

on: 
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo I run on push with ${{ github.ref }}
```
```
name: 'Push Path'

on: 
  push:
    paths:
      - '*.md'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo I run echo on push path '*.md' with ${{ github.ref }}
```
```
name: 'Push Tag'

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo I run on push tags 'v[0-9]+.[0-9]+.[0-9]+' with ${{ github.ref }}
```

Run the following test cases:
1. Branch Push:
`touch foo`
`git add .`
`git commit -m "foo"`
`git push origin main`

2. Markdown Push:
`touch foo.md`
`git add .`
`git commit -m "foo.md"`
`git push origin main`

3. Tag Push (to trigger):
`git tag -a v1.2.4 -m "v1.2.4"`
`git push origin tag v1.2.4`

4. Tag Push (to not trigger):
`git tag -a v1.2.5-1 -m "v1.2.5-1"`
`git push origin tag v1.2.5-1`

**Expected behavior**
We expect the:
1. Branch Push will trigger `Push` workflow. ✅ 
2. Markdown Push will trigger `Push` and `Push Path`. ✅ 
3. `Push Tag` workflow to run when a semantic version tag is pushed,  but not run in any other. ❌  `Push` & **`Push Path`** ran...
4. Nothing to run  ❌ . `Push` and **`Push Path`**  ran...

## Runner Version and Platform
GitHub's default runner.
```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210712.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210712.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210712.0
```
## What's not working?
Filtering logic is broken leading to unrelated workflows being triggered by tag push.

## Job Log Output
<img width="908" alt="Screen Shot 2021-07-15 at 10 57 54 AM" src="https://user-images.githubusercontent.com/891105/125835627-12ad9057-3821-4b19-9ce7-fa75dc153862.png">
