### ISSUE TITLE
Container working directory is owned by runner which is non existing user in the container

### ISSUE THREAD

**Issue by ronilan** [actions/runner#1203]
**Describe the bug**
When a container is created using [container directive](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer), the working directory is created by the runner and mounted to the container.  The runner is not a user in the container. The working directory stays owned by a non existing user in the container.

**To Reproduce**
Create a repo with the following workflow:
```
name: 'Container Workdir Ownership' #

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest 
    container:
      image: node:16

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Ownership
        run: |
          whoami
          id
          ls -al
```
Run it manually.

**Expected behavior**
That working directory in a container will be owned by a user in the container (specifically the user set by `create` which in the default case will be `root`).

## Runner Version and Platform
```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210712.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210712.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210712.0
```

## What's not working?
The working directory is owned by user 1001 of group 121 which is not a user in the container.

<img width="950" alt="Screen Shot 2021-07-15 at 5 28 56 PM" src="https://user-images.githubusercontent.com/891105/125874096-2b373270-3c1b-4fd9-8521-df1acd8cce1d.png">

## Job Log Output
```
Run whoami
  whoami
  id
  ls -al
  shell: sh -e {0}
root
uid=0(root) gid=0(root) groups=0(root)
total 140
drwxr-xr-x 5 1001  121  4096 Jul 16 00:25 .
drwxr-xr-x 3 1001  121  4096 Jul 16 00:25 ..
-rw-r--r-- 1 root root   163 Jul 16 00:25 .eslintrc.js
drwxr-xr-x 8 root root  4096 Jul 16 00:25 .git
drwxr-xr-x 4 root root  4096 Jul 16 00:25 .github
-rw-r--r-- 1 root root   459 Jul 16 00:25 .gitignore
-rw-r--r-- 1 root root     1 Jul 16 00:25 README.md
-rw-r--r-- 1 root root    33 Jul 16 00:25 hello.js
-rw-r--r-- 1 root root   130 Jul 16 00:25 index.js
-rw-r--r-- 1 root root 91527 Jul 16 00:25 package-lock.json
-rw-r--r-- 1 root root   865 Jul 16 00:25 package.json
-rw-r--r-- 1 root root   141 Jul 16 00:25 symlink.js
drwxr-xr-x 2 root root  4096 Jul 16 00:25 test
```
