### ISSUE TITLE
Composite actions which contains external bash script doesn't run if the jobs are executed with container 

### ISSUE THREAD

**Issue by girishenoy2003** [actions/runner#1221]
## Bug!!!
I am trying to create my own composite action and run in my workflow as described [here](https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#running-local-scripts)

When I run my workflow job with **container** then the bash script then the bash script is not accessible to run.
The error in the logs I see as:

```
/__w/_temp/75ecb274-82d9-459d-8632-54e0099fe49e.sh: line 1: /home/xxx/actions-runner/_work/_actions/abc/ooo-action/v1.0/deploy.sh: No such file or directory
Error: Process completed with exit code 127.
```
But on the other hand, if I see in the runner, the script exists in the specified path.

**To Reproduce**
1. Setup the composite action as described [here](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)
2. Write your workflow to run the action but run the jobs on **container**
```
runs-on: [self-hosted]    
    container: 
      image: myregistry/xxx/abc/abc-image:1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```
3. The action will fail

**Expected behavior**
Bash script in the composite action should have been executed but it resulted in error stating _there is no such file_.

## Runner Version and Platform
Runner version - 2.278.0
Running on Linux - x64

## What's not working?
The script in composite action is not running with below error:
```
/__w/_temp/75ecb274-82d9-459d-8632-54e0099fe49e.sh: line 1: /home/xxx/actions-runner/_work/_actions/abc/ooo-action/v1.0/deploy.sh: No such file or directory
Error: Process completed with exit code 127.
```
