### ISSUE TITLE
how to run job depending on other any job success?

### ISSUE THREAD

**Issue by sriedjx** [actions/runner#1251]
I need to run current job based on previous jobs.Which means if I have 2jobs before current job , I need to run current job if any one job is triggered/success.
I tried `needs` event by putting 2 jobs inside.but it is running current job only if 2 jobs got success. Basically I'm expecting `or` functionality. Any solution?

**Comment by fhammerl** [comment]
Try this example workflow. You can use `always()` to trigger a job regardless of other jobs failing.
Then, in your job that has dependencies, you can set its run condition to `if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}`.

```
name: Run job if any dependency succeeds
on:
  push:
    branches: [ main ]
jobs:
  dep1:
    runs-on: ubuntu-latest
    steps:
      - name: Run FAILING script
        run: exit 1 
  dep2:
    runs-on: ubuntu-latest
    steps:
      - name: Run SUCCESS script
        run: echo Success
  job:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [dep1, dep2]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"
  nextjob:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"
```


Please note that if you ever add `continue-on-error: true` to the failing job `dep1`, it will set its result to `success`, so `needs.dep1.result` will always be `success`, thus rendering the check in `job` useless.

**Comment by sriedjx** [comment]
thanks, you made my day

**Comment by sriedjx** [comment]
sorry to reopen , I got what I required, but after that condition(`if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}` It makes me to put on every job to run if not job's are skipping.
```
name: Run job if any dependency succeeds
on:
  push
jobs:
  dep1:
    runs-on: ubuntu-latest
    steps:
      - name: Run FAILING script
        run: exit 1 
  dep2:
    runs-on: ubuntu-latest
    steps:
      - name: Run SUCCESS script
        run: echo Success
  job:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [dep1, dep2]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"
  fail:
    runs-on: ubuntu-latest
    needs: [job]
    steps:
      - name: Run fail script
        run: echo fail
  nextjob:
    runs-on: ubuntu-latest
    if: always()
    needs: [fail]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"
```
here, upto `job` job name my requirement is satisfied but next job's are skipping if I don't pass `always()` in if condition.why? my next job's are interlinked with previous job's but why job's are skipping. from above example `fail` job is skipping and executing next job(even `fail` job is not executed yet).
**my requirement**
- your last reply fit my requirement
- after above condition satisfies,then if any job is failed then next job shouldn't execute
