### ISSUE TITLE
Stdout missing from composite action after failure

### ISSUE THREAD

**Issue by saraedum** [actions/runner#1275]
**Describe the bug**
When a step fails, following steps sometimes show no output even though they are run.

This happens for me with a step that uses a composite action. When I change this step and inline the composite action, the output shows.

**To Reproduce**
I am not sure how to reproduce this behavior since the problem does not happen reliably. For me the problem can be seen frequently with this setup:

In my workflow I use the following steps:
```yaml
      - name: show logs
        shell: bash -l {0}
        run: for log in `find . -name '*.log'`; do echo "::group::$log"; cat $log; echo "::endgroup"; done
        if: ${{ always() }}
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}
```

In theory, the first step should be exactly the same as the second step since the [`show-logs` action](https://github.com/flatsurf/actions/blob/main/show-logs/action.yml) reads:

```yaml
name: show log files
description: Show all .log files in groups

runs:
  using: composite
  steps:
    - name: show logs
      shell: bash -l {0}
      run: for log in `find . -name '*.log'`; do echo "::group::$log"; cat $log; echo "::endgroup"; done
```

However, when a step further up in the workflow fails, often only the first step produces any output.

**Expected behavior**
I expected a composite action that runs a bash script to behave the same as a step that runs the same bash script.

## Runner Version and Platform
I am using the provided runners on github.com.

## What's not working?
For example in [this run](https://github.com/flatsurf/e-antic/pull/204/checks?check_run_id=3370077595), only one of the two steps produces any output though they are supposedly executing the same script.

![image](https://user-images.githubusercontent.com/373765/130047597-fe0dc5bc-8850-45e6-83d4-03f3c5431678.png)
