### ISSUE TITLE
Private Composite Action cannot checkout current Repository

### ISSUE THREAD

**Issue by rethab** [actions/runner#1300]
When a private composite action that checks out the current repository is checked out and then run, it always fails.

In other words: Composite actions don't work well together with private actions.

**Reproducer**
- https://github.com/rethab/composite-action-user

**Describe the Bug**

When using private actions, it is common to use the checkout action (`uses: action/checkout@v2` & specify repository) and then use `uses: ./` to trigger them. I'm not aware of a better way to trigger private actions, but please enlighten me if I'm missing something (other than https://github.com/github/roadmap/issues/74).

When this private action happens to be a composite action that checks out itself (by using the checkout action w/o any parameters), then that clears the entire current directory.

While having the entire current directory cleared may be okay for the workflow itself, the "Post" step of the outer workflow expects the action.yml to be present, but that will have been deleted as well.

Error message:

> Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/composite-action-user/composite-action-user/.actions/composite'. Did you forget to run actions/checkout before running your local action?

**To Reproduce**
1. Checkout a composite action
    - Make sure the composite action includes a `uses: actions/checkout@v2`
2. Trigger the (now local) action like so `uses: path-to-my-action`
3. The Post step is going to error

**Expected behavior**
Would be nice if this was somehow possible. Or if passing a working directory to `uses` would be possible :)

## Runner Version and Platform
2.280.3

Ubuntu / self-hosted

@thboop since you wanted to be tagged for issues with composite actions :)

**Comment by KyleKotowick** [comment]
I was having this issue as well, but found a solution. I believe the problem is that when you use `actions/checkout@v2`, it checks out the files to the current directory. After your composite action steps are finished, it runs the POST step for `actions/checkout@v2`, which seems to _delete_ all of the files in the directory where the repository was originally checked out to. Since this defaults to the base directory of the action, where your `action.yml` file is, it will also delete the `action.yml` file. Now that `action.yml` has been deleted, the POST step of the composite action will fail with the message saying it can't find `action.yml`.

The solution is to specify a directory to checkout to (for the `actions/checkout@v2` **within the composite action**), and then reference that directory for subsequent steps (using the `working-directory` parameter or whatever else is relevant):
```
name: 'Composite Test'
description: 'Composite Test'

inputs: {}

runs:
    using: "composite"
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2
        path: ./source-repo/

      - name: Demo Step
        working-directory: ./source-repo/
        run: ls .
        shell: bash
```

**Comment by thboop** [comment]
This is working by design in the `actions/runner`, but I can understand that this interaction of features can be particularly frusturating.

When https://github.com/github/roadmap/issues/74 ships, this issue should go away.

For now, there's a workaround [here](https://github.com/actions/runner/issues/1300#issuecomment-990373768)

And you may want to follow up with the maintainers at `actions/checkout` to see if they can expose a flag to not delete the directory in the post step, to avoid this scenario.

With that in mind, I'm going to close out this issue, but thank you for the report!

**Comment by marcellodesales** [comment]
# 🐞 Bug on suggestion

@thboop @KyleKotowick 

* The correct syntax needs `with` object for the suggestion at https://github.com/actions/runner/issues/1300#issuecomment-990373768

```yaml
    - name: Checkout Current Repository
      uses: checkout/checkout@v2
      with:
        path: ./source-repo/
```
