### ISSUE TITLE
Support [skip checks] with github actions

### ISSUE THREAD

**Issue by krtschmr** [actions/runner#1313]
It's quite normal to have required status checks prior of merging such as `run test suite`, `run e2e suite`, `run rubocop/linting`, `run typo checks`. 

Assuming your Pipeline is time intense and thus costs a bit of money for each run,  a simple README.md change is often commit with `[skip ci]` in order to save some runtime on the pipeline.

With required checks, this becomes problematic as now a pipeline is indeed required to run, to satisfy the checks.

I propose that `[skip checks]` within the commit message should allow to merge without any checks - if enabled on repository level.

**Comment by rcowsill** [comment]
Skipping workflow runs based on file path can be done with [paths-ignore](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths), eg: 
```yaml
name: Test
on:
  pull_request:
     paths-ignore: "**/*.md"

[...]
```

Skipping based on PR title is also fairly straightforward:
```yaml
name: Test
on:
  pull_request:

jobs:
  slow_build:
    if: ${{ !startsWith(github.event.pull_request.title, '[Skip Checks]') }}

[...]
```

Skipping based on commit title is tricky though, because a push or pull_request event can contain multiple commits.
