### ISSUE TITLE
Access error between files created by docker and host (EACCES)

### ISSUE THREAD

**Issue by thisismydesign** [actions/runner#1317]
**Describe the bug**

When creating files on the host or via Docker (e.g. volume sync) there are access issues when they try to access each other's data.

For example, if I run `npm install` in docker which creates `node_modules` also on the host, then running an action on the host that interacts with the folder will run into access issues (`cypress-io/github-action@v2` in my case).

Things created in docker have the owner and group `root` and things created on the host have the owner `runner` and group `docker`:

```
drwxr-xr-x  2 runner docker   4096 Sep  9 14:14 folder created on the host (cannot be accessed from docker by bower)
drwxr-xr-x  2 root   root     4096 Sep  9 14:15 folder created from docker (cannot be accessed from the host by cypress action)
```

See also https://github.com/actions/runner/issues/434 describing other implications for self-hosted runners and https://github.com/actions/runner/issues/1282.

In addition, I want to point out that this issue goes both ways: you can also have trouble accessing a host volume from docker.

Workaround for the host accessing a folder created by docker: `mkdir folder` from the host before running docker.

#### Below is the exact issue I had 

Getting access error when writing within the project directory. I have a multi-repo docker setup with this structure:

```yml
jobs:
  cypress:
    runs-on: ubuntu-18.04
    defaults:
      run:
        # Default work dir is /home/runner/work/<project-name>/<project-name>
        # It's not possible to checkout into the parent dir, therefore another level of nesting is used
        working-directory: /home/runner/work/<project-name>/<project-name>/docker-services

    steps:
    - uses: actions/checkout@v2
      with:
        repository: org/<project-name-1>
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: <project-name-1>

    - uses: actions/checkout@v2
      with:
        repository: org/<project-name-2>
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: <project-name-2>

   # ... Start project with docker-compose up and run cypress
```

`pwd`
```
/home/runner/work/<project-name>/<project-name>/docker-services
```

`ls -la ../`
```
drwxr-xr-x  5 runner docker 4096 Sep  9 09:25 .
drwxr-xr-x  3 runner docker 4096 Sep  9 09:24 ..
drwxr-xr-x  5 runner docker 4096 Sep  9 09:25 docker-services
drwxr-xr-x 12 runner docker 4096 Sep  9 09:25 <project-name-1>
drwxr-xr-x 15 runner docker 4096 Sep  9 09:25 <project-name-2>
````

Here I expect that I can write to anywhere within `/home/runner/work/<project-name>/<project-name>`. Yet I'm getting various access errors.

#### Case 1
Trying to run cypress
```
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: <project-name-1>
```
Output:
```
/opt/hostedtoolcache/node/16.7.0/x64/bin/npm ci
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/runner/work/<project-name>/<project-name>/<project-name-1>/node_modules/@cypress
```

#### Case 2
The setup runs `bower install` in docker that writes to the root of `<project-name-1>` (from within docker, but it's mapped as a volume to the host)

Volume in docker-compose: `<project-name-1>:/app`

Error within docker:
```
EACCES EACCES: permission denied, mkdir '/app/.cache/bower'
```

If I create this directory up-front in the action it works:
```
    - name: Make GH Actions happy
      run: mkdir ../<project-name-1>/.cache
```

**To Reproduce**

Private org, can't give access but will provide more info if needed.

## Runner Version and Platform

ubuntu-18.04
