### ISSUE TITLE
Docker action fails with a env with value `" A`

### ISSUE THREAD

**Issue by Menci** [actions/runner#1323]
**Describe the bug**
Run a Docker-based action with a env with value `" A`. The action will fail with:

```
Run azure/CLI@v1
  with:
    inlineScript: echo 'Hello, world'
    azcliversion: latest
  env:
    TEST_ENV: " A
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
Error: Error: docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

cleaning up container...
Warning: Error: No such container: MICROSOFT_AZURE_CLI_1631364550959_CONTAINER
```

It seems the runner doesn't escape environment variables correctly in the `docker run` command.

**To Reproduce**

Create an empty repo and add a `.github/workflows/bug.yaml`:

```yaml
name: Bug
on:
  workflow_dispatch:
env:
  TEST_ENV: '" A'
jobs:
  bug:
    runs-on: ubuntu-latest
    steps:
      - name: A Docker-based action step
        uses: azure/CLI@v1
        with:
          inlineScript: echo 'Hello, world'
```

Click to run action in actions page and see the result.

**Expected behavior**

The action should run and print `Hello, world`.

## Runner Version and Platform
Version of your runner?

`ubuntu-latest`

## What's not working?

![image](https://user-images.githubusercontent.com/11341955/132948458-311b3723-3c54-4e75-b152-bbcc0ae784fe.png)
