### ISSUE TITLE
Secrets context unavailable for Strategy path

### ISSUE THREAD

**Issue by krishna-elear** [actions/runner#1330]
**Describe the enhancement**
Need of secrets in matrix. Currently secrets context is unavailable in strategy path. However, this makes running private docker containers in matrix not possible.

**Code Snippet**
NOTE: The following doesn't work currently.
```
name: CI

  workflow_dispatch:

jobs:
  containers_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        container:
          - image: 'docker.your.org/ubuntu:latest'
            credentials:
              username: ${{ secrets.docker_username }}
              password: ${{ secrets.docker_password }}
            env:
              container_secret: ${{ secrets.container_secret }}

    container: ${{ matrix.container }}

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
```

**Additional information**
However this is possible to do by having individual job for each container as mentioned [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainercredentials).

**Comment by ChristopherHX** [comment]
> However, this makes running private docker containers in matrix not possible.

Are you shure? Just a random workflow, if you really need a different username / password foreach matrix job.

Known issue, if secret docker_username, docker_username2, docker_password or docker_password2 is an empty string your job will be invalid and exit with failed. Maybe fromJSON - format can solve this too.
```yaml
name: CI
on:
  workflow_dispatch:

jobs:
  containers_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        container:
          - image: 'docker.your.org/ubuntu:latest'
            credentials:
              username: docker_username
              password: docker_password
            env:
              container_secret: container_secret
          - image: 'docker.your.org/ubuntu2:latest'
            credentials:
              username: docker_username2
              password: docker_password2
            env:
              container_secret: container_secret2


    container:
       image: ${{ matrix.container.image }}
       credentials:
          username: ${{ secrets[matrix.container.credentials.username] }}
          password: ${{ secrets[matrix.container.credentials.password] }}
       env:
          container_secret: ${{ secrets[matrix.container.env.container_secret] }}

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
```
