### ISSUE TITLE
Question - Why some custom actions builds a docker image and some do not?

### ISSUE THREAD

**Issue by vikas027** [actions/runner#1340]
Hello,

I am fairly new to GitHub Actions and trying to understand why some actions build a docker image (before it can be used) and some do not. 

I have looked at the documentation but could not find the reason for this behaviour.

In the below example, [aevea/commitsar@v0.16.0](https://github.com/aevea/commitsar) or  [vikas027/github-action-echo-md5sum@main](https://github.com/vikas027/github-action-echo-md5sum) (my test action) always builds a docker image and [act10ns/slack@v1](https://github.com/act10ns/slack) do not. Obviously, not having the action build a docker image every time reduces the workflow time to run the jobs

```yaml
# Builds  docker image every time
- name: Commitsar check
   uses: aevea/commitsar@v0.16.0

# Builds  docker image every time
- name: Find md5sum
  id: find_md5sum
  uses: vikas027/github-action-echo-md5sum@main
  with:
    find_md5sum: HelloVikas
    find_md5sum_short: 'false'

# Does not build a docker image
- uses: act10ns/slack@v1
  with:
    status: ${{ job.status }}
    steps: ${{ toJson(steps) }}
    channel: '#mychannel'
```

I am not sure if it matters but these are the screenshots of the GitHub Action Build.

![2021-09-15_09-02-11](https://user-images.githubusercontent.com/6998650/133345317-b75d2ffb-c8e3-4ce6-9efe-f4c28a7b9eba.png)

![2021-09-15_09-03-08](https://user-images.githubusercontent.com/6998650/133345328-c90fecdc-a26e-447a-beb2-65a3bb3769d5.png)

![2021-09-15_09-05-32](https://user-images.githubusercontent.com/6998650/133345374-93e36843-5bbe-419e-9afc-bfd374fc672f.png)
