### ISSUE TITLE
Bazel daemon is killed after at the end of a job in a self-hosted runner

### ISSUE THREAD

**Issue by yasushi-saito** [actions/runner#1354]
**Describe the bug**
Bazel daemon is killed after at the end of a job in a self-hosted runner

**To Reproduce**

We have a simple workflow that runs bazel build & test:

```
name: Run bazel test
on: [push]
jobs:
  build:
    name: Bazel test
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Build and test
        run: |
          cd ${GITHUB_WORKSPACE} && bazel test //...
```

The job runs fine, but it takes much longer than it should. The problem seems to be that the actions runner kills the bazel daemon process after the job completes.

Usually, the "bazel" command starts a daemon process that persists across runs, and the daemon caches the build status so that repeated invocations of "bazel build" or "bazel test" starts instantaneously.

However, when bazel is started in github actions (using a self-hosted runner), the daemon seems is killed killed immediately after the job completes. So every "bazel test" invocation spends extra 40 seconds scanning the repository.

I verified that that the daemon process was running with ppid=1, and uid of the github runner. Iet it is killed (or maybe it exists on its own?) after the job finishes.

## Runner Version and Platform
2.282.1

Ubuntu 20.04
