### ISSUE TITLE
seperate the runner and deploy machine, how to pass previous job‘s outputs to the deploy machine？

### ISSUE THREAD

**Issue by stardustman** [actions/runner#1374]
**Describe the enhancement**
A clear and concise description of what the features or enhancement you need.
1. the `github runner install on hostA` and ` the software which is  built in job build needs to deploy on hostB` is seperate.
2. question is: after I use ssh to login the `hostB` how to get the `${{ needs.build.outputs.version }}` ?

the workflow is：
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
       version: ${{ github.sha }}
  deploy:
    needs: build
    runs-on: self-hosted  # `hostA`
    steps:
      - name: Run commands remotely on host to deploy
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts: xxx.xxx.xxx   # the `hostB` to deploy
          user: root
          private_key: ${{ secrets.PRIVATE_SSH_KEY_INTEGRATION_RUNNER }}
          commands: |
            echo "get version from build job is: "
            echo ${{ needs.build.outputs.version }}
```

if the github runner was installed on the deployed machine(HostB), there is no this question. But in reality，I need to use the self-hosted github runner installed on hostA to login hostB to do something with the build job‘s output，how to do it？
Thanks a lot.
