### ISSUE TITLE
Support Windows Containers

### ISSUE THREAD

**Issue by sirredbeard** [actions/runner#1402]
**Describe the enhancement**

Support for Windows Containers in the GitHub Actions runner, even if only available on self-hosted runners, as in:

```
jobs:
  build:
    runs-on: windows-2022
    container:
      image: docker.pkg.github.com/sirredbeard/nim-windows-container/nimstable-ltsc2022:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```

Currently GitHub Actions can be used to build and push Windows Containers to the GitHub Container Registry however GitHub Actions cannot *pull* Windows Containers to use for building or testing.

This is unfortunate and limits the adoption of Windows Containers for use on GitHub.
