### ISSUE TITLE
When using composite actions, the output grouping in the console is not correct

### ISSUE THREAD

**Issue by pbartolome** [actions/runner#1404]
**Describe the bug**
No output grouping on composite actions

**To Reproduce**
Create a composite action that uses log grouping with `echo "::group::Start.."` `echo "::endgroup::"`

````yaml
name: 'Issue'
description: 'Composite example'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: false
    default: '2.6.0'
runs:
  using: "composite"
  steps:
    - name: Setup rbenv
      run: |
        echo "::group::Installing rbenv..."
        brew list rbenv || brew install rbenv
        echo "~/.rbenv/shims" >> $GITHUB_PATH
        echo "::endgroup::"
      shell: bash

    - name: Setup Ruby
      run: |
        echo "::group::Setting up ruby environment..."
        rbenv install ${{ inputs.ruby-version }} -s
        rbenv local ${{ inputs.ruby-version }}
        rbenv rehash
        which ruby
        rbenv which ruby
        echo "::endgroup::"
      shell: bash
    
    - name: Bundle Install
      run: |
        echo "::group::Running bundle install..."
        gem env home
        gem install bundle
        bundle install
        echo "::endgroup::"
      shell: bash
````

Using this composite action on another action has the following output:

````
Prepare all required actions
➤ Run ./.github/actions/issue
➤ Run echo "::group::Installing rbenv..."
➤ Installing rbenv...
➤ Run echo "::group::Setting up ruby environment..."
➤ Setting up ruby environment...
➤ Run echo "::group::Running bundle install..."
➤ Running bundle install...
````

**Expected behavior**

````
Prepare all required actions
➤ Run ./.github/actions/issue
➤ Installing rbenv...
➤ Setting up ruby environment...
➤ Running bundle install...
````

This was the output of a job running on '2.280.3'

## Runner Version and Platform
Version of your runner?
2.281.1

OS of the machine running the runner? 
OSX
