### ISSUE TITLE
counter() expression

### ISSUE THREAD

**Issue by mumby0168** [actions/runner#1408]
**Describe the enhancement**
Azure DevOps pipelines offers an expression named counter see here https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter

**Code Snippet**
From an azure DevOps pipeline
```yaml
variables:
  - name: majorVersion
    value: 1
  - name: minorVersion
    value: 0
  - name: patchVersion
    value: $[counter(variables['minorVersion'], 0)]
  - name: version
    value: $(majorVersion).$(minorVersion).$(patchVersion)
```

**Additional information**
This would be greater feature to have in github actions.
