### ISSUE TITLE
Passing in secrets to reusable workflow does not work without secrets in env

### ISSUE THREAD

**Issue by martin-svanberg-northvolt** [actions/runner#1413]
We are trying out Github Actions and have run into a curious issue which we think is a bug. We have configured secrets at the organization level, and are trying to pass those secrets in to a reusable workflow as shown below:

```yaml
name: example

on:
  pull_request:
    branches:
      - gh-actions

jobs:
  test:
    uses: northvolt/example/.github/workflows/review-common.yml@gh-actions
    secrets:
      password: ${{ secrets.PASSWORD }}
```

This does not work. `password` shows up blank in the reusable workflow instead of having the value of the secret.

If we instead add `env: ${{ secrets }}` to the top-level of the manifest, all of a sudden the secret gets passed in to the workflow. This seems quite counterintuitive since passing in secrets should not be related to the env, and this behavior does not appear to be documented anywhere. In fact, [this example of secrets in reusable workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#example-caller-workflow) does not need an `env` key set at the top-level.

**Comment by AllanOricil** [comment]
I have the same issue :/ 
It is kind insane Github is allowing these buggy features to get merged.
- We can't use relative paths to reference workflow templates
- Secrets are not available
...

**Comment by AllanOricil** [comment]
@martin-svanberg-northvolt could you show exactly what is the solution. Could you post the job and the template here, please.
Thank you

**Comment by ericsciple** [comment]
@martin-svanberg-northvolt i tried to reproduce the issue and it seems to be working correctly now.

We rolled out some recent fixes in related code, which perhaps fixed this issue as well :)

**Comment by martin-svanberg-northvolt** [comment]
Thanks @ericsciple! Closing this for now. Will reopen if there are further issues.

**Comment by param-finder** [comment]
Spent hours on this dreaded issue. CircleCI is so much better when it comes to re-usability. Github Actions lack good documentation and features!

**Comment by woutersf** [comment]
For future me: 
`Secrets:inhherit` fixed it for me: 
In the calling job:
```
jobs:  
  deploy-tst-custom:
    uses: ./.github/workflows/thejob.yml
    secrets: inherit
```

**Comment by M-Farag** [comment]
Yeah (secrets: inherit) did the trick to me.
Just add it to the caller workflow ;)

**Comment by rednevals** [comment]
Using **secrets: inherit** did allow for organization and repository secrets to be passed in, but not **environment** secrets. These are still unavailable. Anyone having this issue?

**Comment by jdjuan** [comment]
@rednevals, I found [this article](https://colinsalmcorner.com/consuming-environment-secrets-in-reusable-workflows/), and realized that you can pass the **environment** name as an **input** variable, and simply use `environment` inside the reusable workflow. It worked for me, see the screenshot below:

<img width="1315" alt="Bildschirmfoto 2022-09-01 um 13 03 55" src="https://user-images.githubusercontent.com/3171900/187899342-bcb8f6bf-93e3-494e-b78a-b51519f04cd5.png">

**Comment by flobernd** [comment]
Yeah, this is very unintuitive. Found this workaround myself a while ago, but I'm not happy with it. The secrets are passed by the `caller` and imho the same should be the case for the `environment` (as it is tightly bound to the secrets). Having to use a workaround like introducing a custom input, just does not feel right.

**Comment by rednevals** [comment]
I had opened a support ticket with GitHub and they explained it better... I was passing the environment in, but mistakenly trying to reference the value using "github.event.inputs.env" instead of "inputs.env". Ooops...

**Comment by 3dfoster** [comment]
> I posted about how I got this to work for me over here https://github.community/t/reusable-workflows-secrets-and-environments/203695/26?u=cloin

Link is broken 💔

**Comment by naghiloo** [comment]
Guys, 
I'm using nested reusable workflows. Is there anyway to use github secrets without passing them in calling workflow?
I mean I wanna make my calling workflow as simple as possible.

**Comment by michaelpetri** [comment]
> Guys, I'm using nested reusable workflows. Is there anyway to use github secrets without passing them in calling workflow? I mean I wanna make my calling workflow as simple as possible.

From the [docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#re-running-workflows-and-jobs-with-reusable-workflows):

Workflows that call reusable workflows in the same organization or enterprise can use the inherit keyword to implicitly pass the secrets.

```yaml
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
```
