### ISSUE TITLE
Kotlin time

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [actions/runner#1417]
**Describe the enhancement**
I am running doing a simple benchmark about bash vs kotlin in GitHub Actions and Kotlin is taking around x1.8 to 2x time with respect to bash.

Is it possible to improve the Kotlin time via caching or something so?

**Code Snippet**

<details>
<summary>bash</summary>

```yaml
name: bash-shell-inline

on:
  workflow_dispatch:
    inputs:
      machines:
        description: 'GitHub virtual environments (`ubuntu-latest`, `windows-latest`, ...)'
        default: 'ubuntu-latest, windows-latest, macos-latest'
        required: false

jobs:
  setup-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}

    steps:
      - name: Setup matrix
        id: setup-matrix
        run: |
          MACHINES=$(echo "\"${{ github.event.inputs.machines }}\"" | tr -d '[:space:]' | sed 's/,/", "/g')
          echo $MACHINES
          echo "::set-output name=matrix::{\"os\": [$MACHINES]}"

  matrix-consumer:
    runs-on: ubuntu-latest

    needs: setup-matrix

    steps:
      - run: echo "${{needs.setup-matrix.outputs.matrix}}"

```

</details>

<details>
<summary>kotlin</summary>

```yaml
name: kotlin-shell-inline

on:
  workflow_dispatch:
    inputs:
      machines:
        description: 'GitHub virtual environments (`ubuntu-latest`, `windows-latest`, ...)'
        default: 'ubuntu-latest, windows-latest, macos-latest'
        required: false

jobs:
  setup-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}

    steps:
      - name: Setup matrix
        id: setup-matrix
        shell: kotlin -howtorun .main.kts {0}
        run: | 
          val machines = "${{ github.event.inputs.machines }}".filterNot(Char::isWhitespace).split(',').joinToString(",") { """"$it"""" }
          println("""::set-output name=matrix::{"os": [$machines]}""")

  matrix-consumer:
    runs-on: ubuntu-latest

    needs: setup-matrix

    steps:
      - shell: kotlin -howtorun .main.kts {0}
        run: println("""${{needs.setup-matrix.outputs.matrix}}""")

```

</details>
