### ISSUE TITLE
Run actions inside a submodule path?

### ISSUE THREAD

**Issue by 2joocy** [actions/runner#1421]
Currently I have a submodule repo, that contains 8 or so github actions. These will be shared between many repos that use the same github actions. I cannot seem to retrigger the actions inside the submodule path, and it only runs the initial action which pulls the submodules 

```
on:
  pull_request:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.BOT_GITHUB_ACCESS_PACKAGES_TOKEN }}
        submodules: recursive
    - name: Checkout submodules
      run: git submodule sync && git submodule update --init --recursive
```

which pulls the submodule into `.github/workflows/service-workflows`
