### ISSUE TITLE
Subprocess does not get run, errors with "Container allready exists"

### ISSUE THREAD

**Issue by tarjei** [actions/runner#1428]
**Describe the bug**

Hi, I'm trying to use PHP's Paratest within a github action. Most of the tests run fine, but some tests call a subprocess that runs node to convert a JS object to HTML.

The problem is that the calls to the process time out. This does not happen when running the tests outside the GH runner.

**To Reproduce**
Workflow file:

```
name: Build

defaults:
  run:
    working-directory: mydir

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Why?"
        required: false
        default: "Because I can"

  push:
    paths:
      - "*"
  pull_request:
    paths:
      - "*"
jobs:
  main_test:
    name: "Run tests for project"
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        working_dir:
          - "src"
        os:
          - ubuntu-latest

        php:
          - "7.4"
          
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC', post_max_size=256M, max_execution_time=-1
          extensions: mbstring, intl, pcntl, redis, sqlite3, PDO, pdo_mysql, pdo_sqlite, gd, zip
          coverage: xdebug    

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install yarn
        run: |
          npm install -g yarn

      # setup js 
      - run: yarn install
      - run: yarn build

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'       
        run: composer install

      - name: Run tests
        if: always()
        run:  |
          bin/paratest --runner WrapperRunner --configuration phpunit.xml --phpunit=bin/phpunit --log-junit ./junit.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name:  Test Results
          comment_title: Test Statistics
          hide_comments: all but latest
          comment_mode: 'update last'
          files: junit.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

```

**Expected behavior**
calling out to the node (`/opt/hostedtoolcache/node/16.11.1/x64/bin/node`) binary from the php process should succeed. Instead it times out. The best error message I have managed to extract is: 

```
Container allready exists
```

## Runner Version and Platform
Latest, ubuntu

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu latest

## What's not working?
Calling node from PHP.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
