### ISSUE TITLE
Support setting job `timeout-minutes` globally for a workflow

### ISSUE THREAD

**Issue by toast-gear** [actions/runner#1449]
**Describe the enhancement**
As part of the `default` attribute it would be great if you could set the `timeout-minutes` attribute so you don't need to set a timeout in every job. This will apply to each job independently. You can then override this default global level at the job or step level if those steps or jobs need a lower timeout.

With the current default being set to 6 hours almost every job in every workflow needs a `timeout-minutes` attribute set. I don't mind the default being high, I understand a high timeout reduces confusion, but it is inane that you end up having to set a timeout at every job in every workflow as a result instead of just once at the global level per workflow.

It's worth noting that I am talking about setting the job timeouts globally, not a timeout on the total workflow run time which would be introducing new behaviour. Someone might find a timeout on the workflow run useful but I would think that enhancement would be much more involved. This enhancement would cover most people's needs and is just reducing the amount of syntax you write without changing any behaviour.

**Code Snippet**

The below would mean every job in that workflow would have its timeout set to 60 minutes.

```yaml
name: My Awesome Workflow

on:
  push:

default:
  run:
    timeout-minutes: 60

jobs:
  job-one:
    # This job gets a timeout of 60 minutes as set by the global attribute
    runs-on: ubuntu-latest
    steps:
      - name: my awesome step
        run: echo foo
  job-two:
    # This job gets a timeout of 60 minutes as set by the global attribute
    runs-on: ubuntu-latest
    steps:
      - name: my awesome step
        run: echo bar
  job-three:
    # This job gets a timeout of 5 minutes as set by the job level override
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: my awesome step
        run: echo baz
```

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaults 
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
