### ISSUE TITLE
github context not available in environnment

### ISSUE THREAD

**Issue by wichert** [actions/runner#1454]
**Describe the bug**

I want to use a workflow for deployment to different environments. This workflow takes the environment as input using workflow dispatch:

```yaml
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment to deploy to
        required: true
        default: dev

jobs:
  deploy:
    name: Update active theme
    environment: ${{ github.event.inputs.env }}
```

This fails with an error:

```
The workflow is not valid. .github/workflows/deploy.yaml (Line: 21, Col: 18): Unrecognized named-value: 'github'. Located at position 1 within expression: github.event.inputs.env
```

**To Reproduce**
1. Create a workflow with a `workflow-dispatch` trigger
2. Add a job with an `environment` reference a dispatch input, for example `environment: ${{ github.event.inputs.env }}`
3. Trigger the workflow

**Expected behavior**
I would expect it to be possible to use event input to set the job environment.

## Runner Version and Platform
GitHub Enterprise 3.1.7

## What's not working?
The `github` context is not available when evaluation the expression for `environment` in a job.

**Comment by wichert** [comment]
There is an  unexpected workaround: the github context is available in the `jobs.environment.name` field.

```yaml
jobs:
  deploy:
    name: Update active theme
    environment: 
      name: ${{ github.event.inputs.env }}
```
