### ISSUE TITLE
Add ability to use continue-on-error from composite Action steps

### ISSUE THREAD

**Issue by AlexDHoffer** [actions/runner#1457]
**Describe the enhancement**
Add the ability to use ``continue-on-error`` option for steps of composite actions.

**Code Snippet**
````yaml
runs:
  using: "composite"
  steps:
    - name: Unstable Step
      uses: risky-step/risky-step@v1.0.0
      continue-on-error: true
      with:
         output_log_location: /var/log/my_risky_build.txt

    - name: Check Result
      shell: bash
      run: 
        cat /var/log/my_risky_build.txt 
````

**Comment by caumond** [comment]
When the step is a run, you can just enrich it you script to accept error code:
```yaml
runs:
  using: "composite"
  steps:
    - name: Unstable Step
      run : bin/my-maybe-failing-script
      with:
         output_log_location: /var/log/my_risky_build.txt

    - name: Check Result
      shell: bash
      run: 
        cat /var/log/my_risky_build.txt 
```
into
```yaml
runs:
  using: "composite"
  steps:
    - name: Unstable Step
      run : bin/my-maybe-failing-script || true
      with:
         output_log_location: /var/log/my_risky_build.txt

    - name: Check Result
      shell: bash
      run: 
        cat /var/log/my_risky_build.txt 
```
