### ISSUE TITLE
Workflow Template not using Container

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1475]
**Describe the bug**
I have a Workflow Template and a workflow that uses it. There is a Job in the template that specifies a Container (docker image). When I run this workflow based on a workflow template, the Container is not downloaded, nor used while running the workflow.

**To Reproduce**
1. Create a Workflow Template
2. Add a Job in this workflow that use the `container` keyword. You can make it do anything
3. Create a Workflow that uses this Workflow template
4. Execute it and verify that the Job starts, but it does not download the Container, nor use it to run the Job
5. Now, instead of using a Workflow Template, make that Job a workflow directly.
6. Run that Workflow and verify that now the Container is donwloaded and used while running the Job
7. Conclude that it is a Bug with Workflow Templates

A simple example:

my-workflow-template.yml
````yml
name: MY WORKFLOW TEMPLATE

on:
    workflow_call:
        inputs: 
            SOME_VAR:
                required: true
                type: string
                
jobs:
    super-job:
        name: super-job
        runs-on: ubuntu-latest
        container: allanoricil/sfdx-cli:v2
            
        permissions:
            contents: write
            packages: read

        steps:
            - uses: actions/checkout@v2

            - run: echo "Hello World"
````

````yml
name: MY WORKFLOW

on:
    push:
        branches:
            - some_random_branch
                
jobs:
    super-workflow-job:
        uses: <USER>/<REPOSITORY>/.github/workflows/my-workflow-template.yml@ref
        with:
            SOME_VAR: bla
````

When running this simple workflow, you will notice that the container image is ignored

Now, if you just remove the workflow template and run the same Job, you will notice that the container is downloaded and used to run the job.
 
**Expected behavior**
If a Workflow Template has Jobs that run on a Container, using the `container` keyword. Then the Job should download the container and run inside of it

## Runner Version and Platform
ubuntu-latest
running in Github Actions

## What's not working?
There is no error message related to the runner. I just noticed it because there is a CLI that I installed in my Docker Image, and when the Job needs it, it is not available there.

**Comment by AllanOricil** [comment]
@ChristopherHX  would you be able to help here too?

**Comment by ChristopherHX** [comment]
> When running this simple workflow, you will notice that the container image is ignored

No idea, I always get your expected behavior and the specified container is used.

**Comment by AllanOricil** [comment]
@ChristopherHX when you use a workflow template can you see downloading/setup step for the container?

**Comment by ChristopherHX** [comment]
Yes I see the "runner downloading and setup step for the container" in reusable workflows on github.com.
![image](https://user-images.githubusercontent.com/44845461/141282021-68217d69-bdf5-464d-bdbd-90afb775abc7.png)

**Comment by AllanOricil** [comment]
I will try a second time and take pictures of it.

**Comment by AllanOricil** [comment]
@ChristopherHX Im running again. But let me share with you my real workflow and workflow templates. I can't see any mistakes on it

workflow template
````yml
name: Deploy Job Template

on:
    workflow_call:
        inputs:
            SF_ORG_ALIAS:
                required: true
                type: string
            SF_USERNAME:
                required: true
                type: string
            SF_CLIENT_ID:
                required: true
                type: string
            SF_INSTANCE_URL:
                required: true
                type: string
        secrets:
            SF_SERVER_KEY:
                required: true

env:
    DEFAULT_FROM: main
    VLOCITY_DEPLOY_TYPE: FULL

jobs:
    deploy-validation:
        name: deploy-validation
        runs-on: ubuntu-latest
        container: allanoricil/sfdx-cli:v2
            
        permissions:
            contents: write
            packages: read

        steps:
            - uses: actions/checkout@v2

            - uses: ./.github/actions/validation
              with:
                  SF_ORG_ALIAS: ${{ inputs.SF_ORG_ALIAS }}
                  SF_USERNAME: ${{ inputs.SF_USERNAME }}
                  SF_CLIENT_ID: ${{ inputs.SF_CLIENT_ID }}
                  SF_INSTANCE_URL: ${{ inputs.SF_INSTANCE_URL }}
                  SF_SERVER_KEY: ${{ secrets.SF_SERVER_KEY }}
                  DEFAULT_FROM: ${DEFAULT_FROM}

    quick-deploy:
        name: quick deploy
        needs: [deploy-validation]
        runs-on: ubuntu-latest
        container: allanoricil/sfdx-cli:v2

        permissions:
            contents: write
            packages: read

        steps:
            - uses: actions/checkout@v2

            - uses: actions/download-artifact@v2
              with:
                  name: Distribution
                  path: dist

            - name: Deploy Vlocity
              run: |
                  ./build/scripts/set_username.sh -e ${{ inputs.SF_ORG_ALIAS }}
                  ./build/scripts/quick_deploy.sh -u ${{ inputs.SF_ORG_ALIAS }}

    vlocity-deploy:
        name: vlocity deploy
        needs: [quick-deploy]
        runs-on: ubuntu-latest
        container: allanoricil/sfdx-cli:v2

        permissions:
            contents: write
            packages: read

        steps:
            - uses: actions/checkout@v2

            - uses: actions/download-artifact@v2
              with:
                  name: Distribution
                  path: dist

            - name: Deploy Vlocity
              run: ./build/scripts/vlocity_deploy.sh -o ${{ inputs.SF_ORG_ALIAS }}

    tag:
        name: tag
        needs: [vlocity-deploy]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: fregante/setup-git-user@v1

            - name: tag deploy
              run: ./build/scripts/add_git_tag.sh -t release/${{ inputs.SF_ORG_ALIAS }}

````

workflow
````yml
name: Deploy Job

on:
    push:
        branches:
            - test_actions

jobs:
    deploy-newp:
        uses: VodafoneIS/sf-metadata/.github/workflows/deploy-template.yml@workflow_template_tests
        with:
            SF_ORG_ALIAS: NEWP
            SF_USERNAME: tobi@vodafone.is.newp
            SF_CLIENT_ID: 3MVG9w8uXui2aB_ryu1Xo7JYO5Qkq8sDgJTkE3q6tlb_mptMEnX8ZY0SK8jKAAA2.AzFnQwMPkMW52UoY8Rb1
            SF_INSTANCE_URL: https://test.salesforce.com
        secrets:
            SF_SERVER_KEY: ${{ secrets.SF_SERVERKEY }}

````
