### ISSUE TITLE
Add environment to "Reusable Workflows/Workflow Templates" implementation

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1482]
**Describe the enhancement**

At the moment I can't use environment when I use a workflow template. I will have to duplicate the template just to add the environment protection rules.

````yml
name: Deploy to Production

# this Workflow can only be triggered manually.
on:
    workflow_dispatch:

jobs:
    deploy-production:
        uses: VodafoneIS/sf-metadata/.github/workflows/deploy-template.yml@workflow_template_with_docker_image_tests
        environment: production
        with:
            SF_ORG_ALIAS: PRODUCTION
            SF_USERNAME: tobi@vodafone.is
            SF_CLIENT_ID: 3MVG9SOw8KERNN0.2IY8hWi2wR7ZOKSkWlmUq3jbn5JNdHUuVBWN87vTDCGzxrQsJ99JM626qlBSweV0UrtOU
            SF_INSTANCE_URL: https://test.salesforce.com
        secrets:
            SF_SERVER_KEY: ${{ secrets.SF_SERVERKEY }}
````

then you would get the environment passed to the parent and write it down to where ${{ input.environment }} is used
