### ISSUE TITLE
Environment Secrets are not available on Reusable Workflow / Workflow Templates

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1490]
**Describe the bug**

obs: this feature works as designed, but I believe it could be improved.

Problem:
Passing an environment containing secrets to a reusable workflow is not enough to have the environment secrets avaiable.

Example:
In a repository, there is an environment called "myenv", which contains a single secret called "MY_SECRET". 
In this repository, there is also a workflow calling a reusable workflow.

This is the reusable workflow
````yml
name: Reusable Workflow

on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                required: true
                type: string            
jobs:
    some-job:
        runs-on: ubuntu-latest
        environment: ${{ inputs.ENVIRONMENT }}

        steps:
            - run: env
````

And this is the workflow
````yml
name: Workflow Caller

on:
    push:
        branches:
            - **

jobs:
    some-job:
        uses: Org/repo/.github/workflows/reusable-workflow.yml
        with:
            ENVIRONMENT: myenv
```` 

When running this workflow, `MY_SECRET` isn't available. I see something like this in the logs:

````shell
...
MY_SECRET:
...
````

instead of this

````shell
...
MY_SECRET:***
...
````

In order to make `MY_SECRET` available in the reusable workflow, I must explicitly write it in the workflow caller, like so:

````yml
name: Workflow Caller

on:
    push:
        branches:
            - **

jobs:
    some-job:
        uses: Org/repo/.github/workflows/reusable-workflow.yml
        with:
            ENVIRONMENT: myenv
        secrets:
            MY_SECRET: ${{ secrets.MY_SECRET }}
```` 

Why can't the reusable workflow load all of the environment secrets automatically using just the environment's name? Is there a reason for not doing it?

In this repo you can find all of my experiments:
https://github.com/AllanOricil/workflow-template-bug

**Expected behavior**
"Deployment Environment" secrets should be available in reusable workflows

## What's not working?
"Deployment Environment" secrets are not available in reusable workflows

## Job Log Output
````shell
 ...
    MY_SECRET:
 ...
````

**Comment by AllanOricil** [comment]
@ChristopherHX could you help me with this. Im not seeing anything wrong here :/

**Comment by AllanOricil** [comment]
I also tried this template. The difference is that I add a `env` section on the job with the variables that Im interested: 


````yml
name: Deploy Workflow Template

on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                required: true
                type: string
        secrets:
            SF_SERVER_KEY:
                required: true
            
jobs:
    deploy-validation:
        name: deploy-validation
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vodafoneis/salesforce-build-image:main
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.ENVIRONMENT }}

        permissions:
            contents: write
            packages: read

        env:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}
            SF_USERNAME: ${{ secrets.SF_USERNAME }}
            SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
            SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
            SF_SERVER_KEY: ${{ secrets.SF_SERVERKEY }}

        steps:
            - uses: actions/checkout@v2

            - run : |
                echo 'printing envs'
                env

            - uses: ./.github/actions/validation
              with:
                DIFF_FROM: release/${{ env.SF_ORG_ALIAS }}

    quick-deploy:
        name: quick deploy
        needs: [deploy-validation]
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vodafoneis/salesforce-build-image:main
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.ENVIRONMENT }}

        permissions:
            contents: write
            packages: read
        
        env:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/download-artifact@v2
              with:
                  name: Distribution
                  path: dist

            - name: quick deploy
              run: |
                  /scripts/set_username.sh -e ${{ env.SF_ORG_ALIAS }}
                  /scripts/quick_deploy.sh -u ${{ env.SF_ORG_ALIAS }}

    vlocity-deploy:
        name: vlocity deploy
        needs: [quick-deploy]
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vodafoneis/salesforce-build-image:main
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.ENVIRONMENT }}

        permissions:
            contents: write
            packages: read

        env:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}
            VLOCITY_DEPLOY_TYPE: ${{ secrets.VLOCITY_DEPLOY_TYPE }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/download-artifact@v2
              with:
                  name: Distribution
                  path: dist

            - name: vlocity deploy
              run: /scripts/vlocity_deploy.sh -o ${{ env.SF_ORG_ALIAS }}

    tag:
        name: tag
        needs: [vlocity-deploy]
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vodafoneis/salesforce-build-image:main
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.ENVIRONMENT }}
        
        env:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}

        steps:
            - uses: actions/checkout@v2

            - uses: fregante/setup-git-user@v1

            - name: tag
              run: /scripts/add_git_tag.sh -t release/${{ env.SF_ORG_ALIAS }}


````


and this is the output, which is missing all SF_* variables:

````bash
Run ./.github/actions/validation
Run echo 'printing envs'
printing envs
SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true
SHELL=/bin/bash
GITHUB_WORKSPACE=/__w/sf-metadata/sf-metadata
SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
SFDX_JSON_TO_STDOUT=true
HOSTNAME=88ea045a7ddd
GITHUB_PATH=/__w/_temp/_runner_file_commands/add_path_f0080f81-a134-47e1-bd5c-1b8b6d7c8860
GITHUB_ACTION=__self
GITHUB_RUN_NUMBER=3
RUNNER_NAME=Hosted Agent
GITHUB_REF_TYPE=branch
YARN_VERSION=1.22.15
PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
***
GITHUB_ACTIONS=true
SF_USERNAME=
GITHUB_SHA=20ef60c880711514e2dcbeb12752f018cb402816
GITHUB_REF=refs/heads/test_actions
RUNNER_OS=Linux
GITHUB_REF_PROTECTED=false
HOME=/github/home
GITHUB_API_URL=https://api.github.com
SF_SERVER_KEY=
RUNNER_ARCH=X64
SFDX_AUTOUPDATE_DISABLE=false
RUNNER_TEMP=/__w/_temp
SF_INSTANCE_URL=
SFDX_DOMAIN_RETRY=true
GITHUB_ENV=/__w/_temp/_runner_file_commands/set_env_f0080f81-a134-47e1-bd5c-1b8b6d7c8860
GITHUB_EVENT_PATH=/github/workflow/event.json
GITHUB_EVENT_NAME=push
GITHUB_RUN_ID=1467740055
SF_CLIENT_ID=
GITHUB_ACTOR=AllanOricil
SF_ORG_ALIAS=
GITHUB_RUN_ATTEMPT=1
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_ACTION_PATH=/__w/sf-metadata/sf-metadata/./.github/actions/validation
GITHUB_SERVER_URL=https://github.com
SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true
SHLVL=1
RUNNER_TOOL_CACHE=/__t
GITHUB_REF_NAME=test_actions
GITHUB_JOB=deploy-validation
GITHUB_REPOSITORY=VodafoneIS/sf-metadata
GITHUB_RETENTION_DAYS=90
RUNNER_WORKSPACE=/__w/sf-metadata
GITHUB_ACTION_REPOSITORY=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GITHUB_BASE_REF=
CI=true
GITHUB_REPOSITORY_OWNER=VodafoneIS
GITHUB_HEAD_REF=
GITHUB_ACTION_REF=
NODE_VERSION=17.1.0
GITHUB_WORKFLOW=Deploy Workflow
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
_=/usr/bin/env
Run /scripts/authenticate.sh
ERROR No SF_USERNAME provided in the environment variables, can't continue
Error: Process completed with exit code 1.
````

**Comment by AllanOricil** [comment]
The funny thing here is that the protection rule works, but the environment variables for the given environment are not available :/

**Comment by AllanOricil** [comment]
I have updated the bug description with a repro case showing the problem.

**Comment by ChristopherHX** [comment]
You probably have to pass all environment secrets you want to use in a reusable workflow **explicitly**. You only set the environment in your called workflow ( which is required, but not enough ), but you didn't explicitly pass environment secrets.
See https://github.community/t/reusable-workflows-secrets-and-environments/203695/18.

**Comment by AllanOricil** [comment]
@ChristopherHX Will it get the `environment` secrets or the repository secrets? It does not seem intuitive to do it like that :/

**Comment by AllanOricil** [comment]
@jenschelkopf could you help here as well.

**Comment by ChristopherHX** [comment]
> Will it get the environment secrets or the repository secrets?

Try and see, I never tried it.
> It does not seem intuitive to do it like that :/

Yeah ask GitHub why. I'm not affiliated with GitHub, microsoft etc.

**Comment by AllanOricil** [comment]
It seems to have worked. But It is extremelly weird this solution because it seems the variables will come from outside.


this is counter intuitive

````yml
name: Workflow Template

on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                required: true
                type: string
        secrets:
            SF_CLIENT_ID:
                required: true
            SF_ORG_ALIAS:
                required: true
            SF_USERNAME:
                required: true
            SF_INSTANCE_URL:
                required: true
            SF_SERVER_KEY:
                required: true
            
jobs:
    do-something:
        name: do-something
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vodafoneis/salesforce-build-image:main
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.ENVIRONMENT }}

        steps:
            - uses: actions/checkout@v2

            - run : |
                echo 'printing envs'
                env
````

````yml
name: Workflow Implementation

on:
    push:
        branches:
            - test_actions

jobs:
    deploy-newp:
        uses: VodafoneIS/sf-metadata/.github/workflows/deploy-template.yml@workflow_template_with_docker_image_tests
        with:
            ENVIRONMENT: newp
        secrets:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}
            SF_USERNAME: ${{ secrets.SF_USERNAME }}
            SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
            SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
            SF_SERVER_KEY: ${{ secrets.SF_SERVERKEY }}


`````

This is intuitive

````yml
name: Workflow Template

on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                required: true
                type: string
            
jobs:
    do-something:
        name: do-something
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vodafoneis/salesforce-build-image:main
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.ENVIRONMENT }}

        steps:
            - uses: actions/checkout@v2

            - run : |
                echo 'printing envs'
                env
````

````yml
name: Workflow Implementation

on:
    push:
        branches:
            - test_actions

jobs:
    deploy-newp:
        uses: VodafoneIS/sf-metadata/.github/workflows/deploy-template.yml@workflow_template_with_docker_image_tests
        with:
            ENVIRONMENT: newp

`````

**Comment by MostefaKamalLala** [comment]
@AllanOricil I just faced the same problem, it obligates us to have secrets with the environment prefix. 
Like newp_SF_ORG_ALIAS, prod_SF_ORG_ALIAS.
We do not leverage the power of environment secrets... I think this issue should reopen.
Do we know if it is tracked?

**Comment by AllanOricil** [comment]
It is closed because their suggestion works. Check this repo I created that show common mistakes people will make because of the way they implemented it. https://github.com/AllanOricil/workflow-template-bug

**Comment by ivellios** [comment]
> It is closed because their suggestion works. Check this repo I created that show common mistakes people will make because of the way they implemented it. https://github.com/AllanOricil/workflow-template-bug

Shouldn't [this line](https://github.com/AllanOricil/workflow-template-bug/blob/master/.github/workflows/workflow-inplementation.yml#L42) in your code actually point to `workflow-template-fix-without-required-secret.yml`? 

Anyway, your fix is what I've done and it does not work. I still don't get any secrets from the environment. 

Also: required secret does not throw error for me. 

And I have tried multiple cases:
- `env_name` in my case replaced with `ENVIRONMENT` input name
- putting only env secrets into the `on` expression (because others should be - and are - available anyway)

Nothing helps at this point for me. The only solution I see is to copy-paste the workflow code instead of using reusable workflows.

**Comment by brandongallagher-tag** [comment]
Can this please be re-opened? This is just extremely inefficient and resulted in my having to move our deployment steps into the release steps workflow file which is unpleasant to look at and couples our entire release pipeline too closely together from a structural point of view. 

How Github thought this was acceptable is beyond me.

**Comment by MostefaKamalLala** [comment]
> Can this please be re-opened? This is just extremely inefficient and resulted in me having to move our deployment steps into the release steps workflow file which is unpleasant to look at and couples our entire release pipeline too closely together from a structural point of view.
> 
> How Github thought this was acceptable is beyond me.

Honestly I thought GitHub actions would offer every useful features from Azure Pipelines and more.

**Comment by austinsasko** [comment]
See here: https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

This is done by design and is identical to the behavior for actions. The _called_ workflow/action can never access environmental things like secrets. It must be passed into the workflow/action from the callee workflow environment

**Comment by brandongallagher1999** [comment]
That's not adding anything to the conversation, and quite frankly, is not helpful in the slightest. That's the point of opening Issues in the first place. @austinsasko 

It's already established that GitHub implemented that by design, as that's what our quarrel is with. Thus why we opened this Issue in the first place.

We opened the issue because:

1. Environments are the only way to protect workflows with approval
2. We want to have a deployment/workflow template that is able to be protected by approval.
3. Reusable workflows do not allow for environments and require you to pass secrets into the workflow call.
4. You can not protect the reusable workflow from neither the initial call from Workflow A nor inside of reusable Workflow B.

As a result, you are left with the only option of including each deployment job within the first workflow file which:

1. Crowds the CD workflow file with every single deployment job, which makes for one massive workflow file.
2. Forces you to potentially repeat the same deployment process for X amount of environments.
3. Couples each CD job too tightly together which stacks tech debt in the future.

For TL;DR:
We need to protect workflows, and their respective secrets such as CD pipelines while allowing for templates to avoid copy pasta level engineering practices.

**Comment by nopol10** [comment]
Does `secrets: inherit` solve this issue? Works for me but I'm not using it with Environments.

https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

**Comment by brandongallagher1999** [comment]
Hi @nopol10 ,

The problem still exists that we can't use environments to protect workflows with approval. That was the main issue that we are concerned about.

Ideally, I'd like to call a reusable workflow and also couple it with workflow approval. So that only certain org/repo members can trigger staging/prod deployment workflows.

**Comment by StephenWithPH** [comment]
https://github.com/orgs/community/discussions/25238#discussioncomment-3247035 shows a simplified example that works.

**Comment by bswmservices** [comment]
do you have any solution for this case?

**Comment by brandongallagher1999** [comment]
@bswmservices I suggest combining all jobs on a workflow that require approval into 1 massive workflow file. It's the only solution, unfortunately.

**Comment by ahmedelnaggartmr** [comment]
Bump as this is an issue for us as well.

**Comment by DamianKedzior-Unity** [comment]
> AllanOricil

Your solution worked for me but I agree it is very not intuitive. Thanks for finding workaround.

**Comment by cb-shivamagarwal** [comment]
It would be great if GitHub allows us to use environment with reusable workflows in an intuitive way with good documentation.

**Comment by joshmello** [comment]
+1

**Comment by Djulio** [comment]
This issue is especially funny when the reusable workflow is in the same repo as the caller workflow :)

**Comment by AllanOricil** [comment]
Environment "Variables" are loaded without passing them in the caller workflow.  Different behaviour for the same thing is kind weird. For example:

Considering:
- an Environment called `myenv` with a Variable called `test` with value equal to `test`
- and the following workflows (caller and reusable):

````yaml
name: Workflow Caller

on:
    push:
        branches:
            - **

jobs:
    some-job:
        uses: Org/repo/.github/workflows/reusable-workflow.yml
        with:
            ENVIRONMENT: myenv
````

`````yaml
name: Reusable Workflow

on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                required: true
                type: string            
jobs:
    some-job:
        runs-on: ubuntu-latest
        environment: ${{ inputs.ENVIRONMENT }}

        steps:
            - run: echo ${{ vars.test }}
````

This is the output:

````bash
...
test
...
````

As you can see, I did not pass Environment "Variables" (vars) from the workflow caller and yet they were loaded in the reusable workflow. Why can't the Environment "Secrets" (secrets) behave the same way?

**Comment by tao-zhang-shell** [comment]
Thank you, @AllanOricil . I'm seeing exactly the same issue.

**Comment by Jangsukwoo** [comment]
I think this is bug.

**Comment by AllanOricil** [comment]
@gyund I agree with it. It is just not intuitive. I had to spend some time running experiments because the docs were not clear about this behavior.

**Comment by AllanOricil** [comment]
I also think It is kind weird to bind an expression that isn't resolved to a secret in the caller workflow in order to make the secret available in the reusable workflow. So, I would prefer to do something like shown below in order to "opt in".

````yml
name: Workflow Caller

on:
    push:
        branches:
            - **

jobs:
    some-job:
        uses: Org/repo/.github/workflows/reusable-workflow.yml
        with:
            ENVIRONMENT: myenv
        secrets:
            - SECRET_ONE
            - SECRET_TWO
````

**Comment by tmehlinger** [comment]
@AllanOricil the way you've described it is _exactly_ how it should work. This is a completely absurd limitation in Actions that entirely defeats the purpose of reusable workflows. If a reusable workflow is coupled to identifiers in the calling workflow, why bother writing reusable workflows?

Github, please fix this. If I can _opt into_ passing secrets to a downstream workflow, there is no security issue.

**Comment by AllanOricil** [comment]
Their design makes kind of sense. Developers must choose which secrets they want to pass to reusable workflows, or pass all, since there could exist 3rd party workflows that could send our secrets to services we are not aware of.

**Comment by brandongallagher1999** [comment]
Shouldn't be closed. This is a horrible design. Completely restrictive, especially in 2023 when we want to implement basic DRY principles into our DevOps lifecycle. That's what approvals are for, if anyone's concerned about using 3rd party workflows with their secrets.

**Comment by xeroc** [comment]
> Does `secrets: inherit` solve this issue? Works for me but I'm not using it with Environments.
> 
> https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/
> 
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

This one weirdly resolved it for me **despite** using environments.
So the workflow has no knowledge over the environment I use (other than passing a variable), and the re-usable puts and loads the environment, and apparently feeds the correct secrets into `${{secrets*}}`.

**Comment by samoht9277** [comment]
@xeroc How can I declare the `environment` key on the caller workflow, when I need to create a new job to call the reusable workflow, and i can't declare the `environment` key inside that job?

**Comment by ben-umble** [comment]
@samoht9277 

Not sure if this is too late, but may be useful for anyone else struggling.

I've run into this and using `secrets: inherit` as mentioned above sort of solves the issue. You can't define `environment` as such but you can pass it down as an `input`.

The reusable workflow needs to have an input to receive the environment. Then on your job, you can use `environment: ${{ inputs.env }}`.

```
name: Build and deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.env }}
```

On the caller workflow, pass down the `environment` and declare `secrets: inherits` like this:

```
jobs:
  deploy:
    uses: org/repo/.github/workflows/build.yml@main
    with:
      env: Development
    secrets: inherit
```

The only thing I'm not clear on is if this passes the secrets down further into third-party workflows so treat with caution.

**Comment by sap147** [comment]
> > Does `secrets: inherit` solve this issue? Works for me but I'm not using it with Environments.
> > https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/
> > https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
> 
> This one weirdly resolved it for me **despite** using environments. So the workflow has no knowledge over the environment I use (other than passing a variable), and the re-usable puts and loads the environment, and apparently feeds the correct secrets into `${{secrets*}}`.

@xeroc  - Can you please elaborate how you are feeding secrets into `${{secrets*}}` in the reusable workflow?  Thanks.

**Comment by wkhatch** [comment]
@sap147 secrets: inherit solved the issue for me. For completeness:

```
jobs:
  deploy-development:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      environment: development
    secrets: inherit
```
and in the reusable:

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
        <whatever you expect to be passed via the inherit, so list each one. maybe don't have to do this, but it can't hurt and it works for me>

and then elsewhere in the reusable workflow where you want to reference a secret, it's the normal syntax ${{ secrets.SOME_SECRET}}

**Comment by obaqueiro** [comment]
I think this issue should be reopened. We are hitting the same issue which prevents us from using the "reusable workflows".

In our case, the problem we have is that the keyword `environment` under `jobs.job-name` is not accepted when using the `uses:` key. So, our Github configured secrets (in different environments) are not visible to the *called* yml workflow.  We need either a way to define an `environment` (where secrets are pulled from ) at the  workflow level , or to be able to use the `environment` key within a job that calls a sub-workflow witht he `uses:` keyword.

**Comment by michealroberts** [comment]
I am also seeing this issue, anything in the "Environment Secrets" section of my repository are coming through as empty in the workflow runner ...

**Comment by connorads** [comment]
Well that's a few hours I won't get back 😅 

The `secrets: inherit` "workaround" is working for me.

FYI @wkhatch, regarding your CRITICAL UPDATE: I don't have any overlapping names in repo/org secret, `SOME_ENVIRONMENT_SECRET` is only defined in environments. But it still works.

```yml
# calling-workflow.yml
jobs:
  example-dev:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      env: dev
    secrets: inherit
```

```yml
# reusable_workflow.yml
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      SOME_REPOSITORY_SECRET:
        required: true
      SOME_ENVIRONMENT_SECRET:
        required: true

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: echo "${{ secrets.SOME_REPOSITORY_SECRET }}"
      - run: echo "${{ secrets.SOME_ENVIRONMENT_SECRET }}"
```
