### ISSUE TITLE
`continue-on-error` cannot evaluate expression on environment variable

### ISSUE THREAD

**Issue by tribbloid** [actions/runner#1492]
**Describe the bug**
jobs/continue-on-error cannot use environment variable in expression

**To Reproduce**
Using an expression in `continue-on-error` like this:

```
env:
  fullySupportedScalaVersions: "2.13.6"

  test:
    runs-on: ubuntu-latest

    continue-on-error: ${{ contains(env.fullySupportedScalaVersions, matrix.scalaVersion) }}
```

example: https://github.com/tek/splain/blob/6b12e57954aae0852e9b948e12ef5637c478b53d/.github/workflows/main.yml

**Expected behavior**
`fullySupportedScalaVersions` should be used to interpolate the expression

## Runner Version and Platform
Version of your runner: latest

OS of the machine running the runner: ubuntu-latest

## What's not working?

Invalid workflow file : .github/workflows/main.yml#L38
The workflow is not valid. .github/workflows/main.yml (Line: 38, Col: 24): Unrecognized named-value: 'env'. Located at position 10 within expression: contains(env.fullySupportedScalaVersions, matrix.scalaVersion) .github/workflows/main.yml (Line: 38, Col: 24): Unexpected value '${{ contains(env.fullySupportedScalaVersions, matrix.scalaVersion) }}'

**Comment by nikola-jokic** [comment]
Hi @tribbloid,

Thank you for filing this issue! We have published a list of contexts and what yaml fields they are available in on the [GitHub Docs Website](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability). Currently, we don't support this feature, but I've added the appropriate labels so we may consider it in the future.

**Comment by akikanellis** [comment]
> I have a similar case by [reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) where I want let the caller of the reused workflow decide about `continue-on-error`
> 
> I found the following workaround, where the input variable type is `string` instead of `boolean` which is casted to `boolean` by `fromJSON` later on:
> 
> ```
> on:
>   workflow_call:
>     inputs:
>       continue-on-error:
>         type: string
>         required: false
>         default: false
> 
> jobs:
>   my-job:
>     name: 'my job'
>     runs-on: ubuntu-latest
>     env:
>       CONTINUE_ON_ERROR: ${{inputs.continue-on-error}}
>     steps:
>       - uses: actions/checkout@v2
>       - name: run foo
>         shell: bash
>         continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
> ```

Excellent suggestion @kagahd!

To add on this solution, I found that you don't need to cast the string to boolean and can instead pass a boolean directly from one workflow to another.

_caller-workflow.yml_

```yaml
---
name: Caller Workflow

"on":
  push:
    branches: [main]

jobs:
  call-reusable-workflow:
    name: Call reusable workflow
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      continue-on-error: true
```

_reusable-workflow.yml_

```yaml
---
name: Reusable Workflow

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false

jobs:
  reusable-workflow-job:
    name: Reusable workflow job
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
```
