### ISSUE TITLE
Unable to use single port from matrix in job.services.exasol.ports

### ISSUE THREAD

**Issue by theory** [actions/runner#1508]
**Describe the bug**

I tried using a single port from a matrix variable job.services.exasol.ports, but [it complained](https://github.com/sqitchers/sqitch/actions/runs/1501590600):

> The workflow is not valid. .github/workflows/exasol.yml (Line: 51, Col: 35): Unexpected symbol: '${{'. Located at position 27 within expression: job.services.exasol.ports[${{ matrix.port

**To Reproduce**
1. Create a new workflow within a port in the matrix config
2. Configure it with

    ```
    ports: [  "${{ matrix.port }}" ]
    ```

    Or

    ```
    ports:
      - ${{ matrix.port }}
    ```

3. Run the workflow

**Expected behavior**
The variable should simply resolve to the port number and start the service

## Runner Version and Platform
GitHub Actions, Debian-Latest

## What's not working?

This works:

``` yaml
jobs:
  Exasol:
    strategy:
      matrix:
        include:
          - { version: '7.1', image: 'latest-7.1', port: 8563 }
    name:  Exasol ${{ matrix.version }}
    runs-on: ubuntu-latest
    services:
      exasol:
        image: exasol/docker-db:${{ matrix.image }}
        ports:
          - 8563:${{ matrix.port }}
        options: --privileged
```

But this does not:

``` yaml
jobs:
  Exasol:
    strategy:
      matrix:
        include:
          - { version: '7.1', image: 'latest-7.1', port: 8563 }
    name:  Exasol ${{ matrix.version }}
    runs-on: ubuntu-latest
    services:
      exasol:
        image: exasol/docker-db:${{ matrix.image }}
        ports:
          - ${{ matrix.port }}
        options: --privileged
```

And neither does:

``` yaml
jobs:
  Exasol:
    strategy:
      matrix:
        include:
          - { version: '7.1', image: 'latest-7.1', port: 8563 }
    name:  Exasol ${{ matrix.version }}
    runs-on: ubuntu-latest
    services:
      exasol:
        image: exasol/docker-db:${{ matrix.image }}
        ports: [ "${{ matrix.port }}" ]
        options: --privileged
```
