### ISSUE TITLE
Excluding struct from matrix doesn't work

### ISSUE THREAD

**Issue by MoetaYuko** [actions/runner#1512]
**Describe the bug**
I have a workflow like this:
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        attr1:
          - key1: val1
            key2: val2
          - key1: val3
            key2: val4
        attr2:
          - key1: val5
            key2: val6
            key3: val7
          - key1: val8
            key2: val9
            key3: val10
    steps:
      - run: |
          echo ${{ matrix.attr1.key1 }}
          echo ${{ matrix.attr1.key2 }}
          echo ${{ matrix.attr2.key1 }}
          echo ${{ matrix.attr2.key2 }}
          echo ${{ matrix.attr2.key3 }}
```
That is to say, there are two attributes `attr1` and `attr2` (can be more in practice) in the matrix, with each one using "structs" as alternatives rather than string literals. This allows me to tie additional information with the key. The syntax is legal according to https://github.com/actions/runner/issues/343#issuecomment-590634907 and works well in practice. Note that the jobs (attr1.key1, attr1.key2, attr2.key1, attr2.key2, attr2.key3) triggered are:
* (val1, val2, val5, val6, val7)
* (val1, val2, val8, val9, val10)
* (val3, val4, val5, val6, val7)
* (val3, val4, val8, val9, val10)

However, I'm unable to exclude configurations from the matrix. For example, the following doesn't work:
```yaml
exclude:
  - attr1:
    - key1: val1
      key2: val2
```

**To Reproduce**
Run the above workflow with the excluding rule added.

**Expected behavior**
Only
* (val3, val4, val5, val6, val7)
* (val3, val4, val8, val9, val10)

get triggered.

## Runner Version and Platform
2.284.0 (Github hosted runner)

OS of the machine running the runner? ubuntu-20.04 20211122.1

## What's not working?
All four jobs got triggered.

**Comment by ruvceskistefan** [comment]
Hi @MoetaYuko,
Thanks for reporting this issue! I managed to reproduce your problem and I'm currently working on a solution, so I'll contact you as soon as I have more information.

**Comment by ruvceskistefan** [comment]
I think I have an explanation and a solution to your problem. If you look at the [documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions), you will notice that there are no examples where matrix options are complex types (structures in this case). If you use in-browser GitHub editor, you will notice that you also receive a warning for such a definition of matrix options (image below).

<img width="388" alt="issue 1512" src="https://user-images.githubusercontent.com/96768603/156158098-5df42fd5-8b53-4a00-9e62-7dcb6499ca05.png">

However, it is also possible to define the workflow in this way, although the nesting of matrix option is a workaround solution. If you want to exclude an option (or options) defined this way, you can do it like this: 
```
exclude:
  - {attr1: {key1: val1, key2: val2}}
```
In this way the expected behavior is obtained, ie only:
- (val3, val4, val5, val6, val7)
- (val3, val4, val8, val9, val10)

get triggered.

I hope this solves the problem you reported. Please just give me feedback so that I can close the issue if the problem is solved.

**Comment by MoetaYuko** [comment]
Thank you for the reply @ruvceskistefan , the syntax you provided:
```yaml
exclude:
  - {attr1: {key1: val1, key2: val2}}
 ```
actually works, but I have some questions and it would be appreciated if you could address them.

1. Why does it differ from:
```yaml
exclude:
  - attr1:
    - key1: val1
      key2: val2
```
aren't they both parsed as dictionaries?

2. Are there alternatives to the nested curly brackets allowing wrapping lines? It would be ugly to write long strings in one single line.
3. If "structure as matrix option" works just in case, are there chances to make it "officially" supported? I find it pretty useful in some scenarios.

**Comment by MoetaYuko** [comment]
Thanks for the response, feel free to close this issue.

**Comment by exsesx** [comment]
Hey! Excuse me for writing here. I have a similar issue (well, at least it's the closest I could find).

```yml
strategy:
      fail-fast: false
      matrix:
        include:
          - service: my-service-1
            repository: string
            executor: string

          - service: my-service-2
            repository: string
            executor: string

          - ...
            
        exclude: ?
```
I'm using the "include" syntax to build multiple services (in this case, two). Is there any way to exclude some of them? I was thinking about adding the `shouldBuild` boolean flag and then checking it. I could've just added `if` to my job, but I don't think it's clean.
