### ISSUE TITLE
Service Containers can be defined in Composite Action but don't initialise

### ISSUE THREAD

**Issue by pattwell** [actions/runner#1526]
**Describe the bug**
When a `service` [block](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) is defined in a composite action, the containers do not initialise although no syntax errors are thrown.

Either it is not possible for this to work, so there should be an error not allowing e to include service block in composite action; or it is possible but isn't working as expected.

**To Reproduce**

Composite Action Definition: (./.github/actions/example/action.yml)
```yaml
name: "Run RSpec Tests"

inputs:
  spec:
    required: true

services:
  postgres:
    image: postgres:13.3
    env:
      POSTGRES_USER: example
      POSTGRES_DB: example
      POSTGRES_PASSWORD: "example"
    ports: ["5432:5432"]
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
  redis:
    image: redis 
    ports:
      - 6379:6379
    options: >-
      --health-cmd "redis-cli ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
      
runs:
  using: "composite"

  steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Restore Ruby Cache
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4 
        bundler-cache: true 

    - name: Setup DB 
      run: bundle exec rake db:setup 
      shell: bash

    - name: RSpec Tests
      run: bundle exec rake spec:${{ inputs.spec }}
      shell: bash
```

And to call it in your main workflow yml:
```yaml
jobs:
  setup_and_lint:
    name: Setup Ruby and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4 
          bundler-cache: true 
      - name: Linting 
        if: ${{ github.event_name == 'pull_request' }}
        uses: HeRoMo/pronto-action@v1.27.0

  rspec_tests_example1:
    name: RSpec Tests (example1)
    runs-on: ubuntu-latest
    needs: setup_and_lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: RSpec Tests
        uses: ./.github/actions/rspec_test
        with:
          spec: example1

```
And the example1 block could be replicated for many Specs.

**Expected behavior**

Either:

- RSpec Tests jobs should run in parallel as normal, and when they execute, initialise the service containers specified in the composite action

OR,

- If this is not possible (I realise that I'm calling the action at the Step level but Services are defined at Job level, so perhaps it's not intended to work) then the syntax of the Composite action should throw an error to show that this is the case. 

If that is the case, then it would be great to find another way of resuing Service definitions to save duplicated code.

## Runner Version and Platform
ubuntu-latest

## What's not working?

- The automated "Initialise Containers" step simply does not run
- Because the containers aren't created, the spec jobs fail due to nothing running on the defined ports.

## Job Log Output

![Screenshot 2021-12-02 at 11 46 35](https://user-images.githubusercontent.com/75476610/144416619-541ce63a-8f21-4620-b245-1494d0a27176.png)

**Comment by nikola-jokic** [comment]
Hi @pattwell,

Runner currently does not support services within composite actions. We will be adding this to the documentation. 

I will file an issue to notify users if a bad yaml is provided.

**Comment by Panukulf** [comment]
Runner#1526

**Comment by pattwell** [comment]
> Hi @pattwell,
> 
> Runner currently does not support services within composite actions. We will be adding this to the documentation.
> 
> I will file an issue to notify users if a bad yaml is provided.

Hi @nikola-jokic thank you for the response and for confirming this! 

I hope Services are supported for Composite actions sometime in the future, or there is another way to reduce duplicated code.

**Comment by nikola-jokic** [comment]
Hi @pattwell,

I have added a Pull Request as an explanation to the docs. Since we are using this issue board to track problems related to the runner itself, I will close this issue now.  Could you please post your suggestion on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored? Using the forum ensures that we route your request to the correct team. 😃 Thank you!

**Comment by pattwell** [comment]
@nikola-jokic  I actually already posted on there at the same time, see here: https://github.community/t/service-containers-in-composite-actions/215326

Let me know if I should re-post with updated phrasing or something though!

**Comment by nikola-jokic** [comment]
Great @pattwell! No, you don't need to re-post it. Other people are maintaining the community support forum. It was my mistake not seeing it. Thank you again!

**Comment by pattwell** [comment]
@nikola-jokic Okay great, thank you so much for your help! 😄

**Comment by y-nk** [comment]
@pattwell if that can help, i'm currently solving this issue by abusing the `matrix` feature. you can define one generic job with specific data in the matrix like this:

```
rspec_tests_example:
    name: RSpec Tests
    runs-on: ubuntu-latest
    needs: setup_and_lint

    matrix:
      specs:
        - example1
        - example2

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: example
          POSTGRES_DB: example
          POSTGRES_PASSWORD: "example"
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
      redis:
        image: redis 
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore Ruby Cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4 
          bundler-cache: true 

      - name: Setup DB 
        run: bundle exec rake db:setup 
        shell: bash

      - name: RSpec Tests
        run: bundle exec rake spec:${{ matrix.spec }}
        shell: bash
```

there will be limitations to that but for the usecase i'm having (which seems similar to yours) it works just ok.

thank you for the great amount of reporting you did (here and in github community with the follow-ups etc)
