### ISSUE TITLE
`concurrency` with properties now causes "syntax error"

### ISSUE THREAD

**Issue by ablakey** [actions/runner#1532]
By making a trivial change to an existing `test_build.yaml`, GitHub Actions complains about a syntax error in the `concurrency` property.

```
Invalid workflow file : .github/workflows/test_build.yaml#L3
You have an error in your yaml syntax on line 3
```

- I'm running in the github.com Actions environment, not my own.
- If I re-order the properties it remains broken.
- If I remove the properties from `concurrency` it works again.
- I've validated that the yaml is valid yaml. So the error is confusing and unhelpful.

**Note**: This exact yaml file has been working for months. The only change I made was to rename a job.

## Broken Example
```
name: Project CI
concurrency:
  cancel-in-progress: true  # "Syntax error" here?
  group: muffins
on:
  pull_request:
    branches: [devel, staging, prod]
  push:
    branches: [devel, staging, prod]
jobs:
  test_ui:
    defaults:
      run:
        working-directory: ./ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run validate
 ```

## Working Example
```
name: Project CI
concurrency: muffins
on:
  pull_request:
    branches: [devel, staging, prod]
  push:
    branches: [devel, staging, prod]
jobs:
  test_ui:
    defaults:
      run:
        working-directory: ./ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run validate
```

**Comment by frenck** [comment]
Confirmed on this end as well, workflows for Home Assistant are broken because of this.

**Comment by scottfavre** [comment]
We are seeing this across all workflows with concurrency blocks like:

```yml
concurrency: 
  group: ${{ github.event.inputs.identifier }}
  cancel-in-progress: true
```

**Comment by kraftbj** [comment]
It also appears to be breaking without any changes to the workflow file. https://github.com/Automattic/jetpack/actions/runs/1535959387/workflow with the last change on Oct 26th.

**Comment by smith-it** [comment]
+1 As of this morning, all my workflows are failing with a syntax error on the line defining the concurrency group value.

**Comment by yuriydzobak** [comment]
+1

**Comment by marcellp** [comment]
Yup, we started experiencing this problem at around 15:52 GMT. We narrowed it down to the issue to `concurrency` being used with a `group`. I spent about an hour debugging it, good to know it was GitHub Actions.

**Comment by ebk45** [comment]
+1 we've got the same issue on all of our repositories and all syntax issues are pointing at the concurrency property.

**Comment by shshe** [comment]
Our pipelines have all stopped as well. The Github Actions status at https://www.githubstatus.com/ is still showing "Normal" - is there any acknowledgement of this issue on Github's side?

**Comment by justin-masse** [comment]
+1 same issue here when using "group" on concurrency

**Comment by johnnybenson** [comment]
Yes, can't / won't deploy without working jobs. 

Removing the `concurrency` setting all together lets the jobs run successfully.

But you know, don't want to do that.

**Comment by darrenswhite** [comment]
+1 same issue

**Comment by mrparkers** [comment]
I have also posted an issue about this on the community page: https://github.community/t/breaking-change-to-concurrency-group-syntax/215604

A lot of folks appear to be affected by this.

**Comment by famod** [comment]
FTR, fails for https://github.com/quarkusio/quarkus as well:
```
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'quarkusio/quarkus' }}
```

**Comment by drdavella** [comment]
Can confirm, getting the same error with this configuration:
```yaml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
```

**Comment by amirtoole** [comment]
We're experiencing this as well; our current workaround:
```
concurrency:
  group: ${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.head_ref }}
  cancel-in-progress: true
```

**Comment by ashb** [comment]
@amirtoole You are my hero.

**Comment by ablakey** [comment]
It seems that the original problem is no-longer happening. I reverted to my original .yaml file and it works now without complaining about a syntax error.

**Comment by frenck** [comment]
Confirmed, reverting worked for us as well. Thanks for keeping us posted @ablakey 👍

**Comment by mrparkers** [comment]
I don't think I'm the biggest fan of the "silently fix the issue without acknowledging its existence" approach that GitHub seems to have taken here, but I suppose I'm glad that my workflow is working again.

**Comment by drdavella** [comment]
@mrparkers It's possible they resolved this issue without being aware of this ticket yet, but I agree with what you're saying.

**Comment by ablakey** [comment]
I'll leave this issue open to give the GitHub Actions team an opportunity to chime in on how it was resolved. It's possibly too soon to assume it was a stealth fix.

**Comment by frenck** [comment]
@drdavella I'm pretty sure they are aware, as I've had escalated it with them.

**Comment by ashb** [comment]
My guess is they noticed by elevated numbers of builds failing and rolled back the change before the support message made it to them.

**Comment by JamesKyburz** [comment]
seems to be working now

**Comment by androidacybot** [comment]
People, do everyone a favor and instead of useless "+1" or "me too" or similar comments, hit the thumbs up button on the original post. Thank you.

**Comment by frenck** [comment]
In a response from GitHub I was told engineers were on it before reports came in. Anyways, still this issue is open at this point.

**Comment by ethomson** [comment]
We believe that this has been resolved, so I'm closing this.  Please let me know if you're still seeing problems here.

**Comment by frenck** [comment]
@ethomson Could you elaborate on the incident a bit?

**Comment by ethomson** [comment]
This wasn't a runner bug, so I don't have complete details. 

We were making a change to the way `concurrency` is supported for reusable workflows and introduced a bug parsing some workflows with groups specified under concurrency.  We rolled back the feature changes when we became aware of problems in production.  We've added additional monitoring and tests for these configurations so that we will not have similar issues in the future.

**Comment by nitrocode** [comment]
hit this issue again and our workaround was to comment it out

```yaml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
```

but @amirtoole's [workaround](https://github.com/actions/runner/issues/1532#issuecomment-985705051) is promising!
