### ISSUE TITLE
Actions Steps in Container defaults to sh shell instead of bash

### ISSUE THREAD

**Issue by henrygriffiths** [actions/runner#1533]
**Describe the bug**
When using a container for a job, the default shell is sh instead of bash.

**To Reproduce**
1. Specify a container running on a linux runner.
```
runs-on: ubuntu-latest
container:
  image: python:3.10-bullseye
steps:
- name: Debug Shell
  run: echo $0
```
2. Run the action
3. See that command has run in the sh shell instead of bash

**Expected behavior**
Command run in the bash shell (same as if running without container).

The expected behavior (bash shell) can be achieved by specifying `shell: bash` for each step, or as a job default. However, when specifying `/bin/bash` in the Dockerfile (in any/all of `SHELL`, `CMD`, or `ENTRYPOINT`, the shell still defaults to sh. I believe the shell should default to bash, as it does without the container.

## Runner Version and Platform
Platform: GitHub Hosted ubuntu-latest (or ubuntu-20.04), self-hosted (Debian Linux 11 (bullseye))
Runner Version: 2.285.0 (both GitHub Hosted and Self-Hosted)

## What's not working?
Commands run, but in sh shell instead of bash.

## Job Log Output
1: GitHub Hosted Runner without Container
```
hosted_action:
  name: 'Hosted Action'
  runs-on: ubuntu-latest
  steps:
  - name: Debug Shell
    run: echo $0
  - name: Debug Bash Shell
    run: echo $0
    shell: bash
  - name: Debug sh Shell
    run: echo $0
    shell: sh
```
![image](https://user-images.githubusercontent.com/42880130/144665550-4ff17df4-3436-4d08-a1de-e2fac3beadee.png)

2: GitHub Hosted Runner with Container
```
hosted_action_container:
  name: 'Hosted Action Container'
  runs-on: ubuntu-latest
  container:
    image: python:3.10-bullseye
  steps:
  - name: Debug Shell
    run: echo $0
  - name: Debug Bash Shell
    run: echo $0
    shell: bash
  - name: Debug sh Shell
    run: echo $0
    shell: sh
```
![image](https://user-images.githubusercontent.com/42880130/144665687-5b3ed066-6720-42be-bfed-b2024e4bab22.png)

3: GitHub Hosted Runner with Container with Shell Specified in Dockerfile
Dockerfile:
```
FROM python:3.10-bullseye
SHELL ["/bin/bash", "--login", "-c"]
CMD [ "/bin/bash" ]
```
```
hosted_action_container_shell:
  name: 'Hosted Action Container Shell'
  runs-on: ubuntu-latest
  container:
    image: ghcr.io/***/python-runner:latest
    credentials:
      username: ***
      password: ***
  steps:
  - name: Debug Shell
    run: echo $0
  - name: Debug Bash Shell
    run: echo $0
    shell: bash
  - name: Debug sh Shell
    run: echo $0
    shell: sh
```
![image](https://user-images.githubusercontent.com/42880130/144666002-db39ed0a-28f3-48a5-ba7f-bb54cafb4ae2.png)

4: Self Hosted Runner without Container
```
local_action:
  name: 'Local Action'
  runs-on: self-hosted
  steps:
  - name: Debug Shell
    run: echo $0
  - name: Debug Bash Shell
    run: echo $0
    shell: bash
  - name: Debug sh Shell
    run: echo $0
    shell: sh
```
![image](https://user-images.githubusercontent.com/42880130/144666182-36203236-f303-4fe4-bc93-e2e25ee9a5f7.png)

5: Self-Hosted Runner with Container
```
local_action_container:
  name: 'Local Action Container'
  runs-on: self-hosted
  container:
    image: python:3.10-bullseye
  steps:
  - name: Debug Shell
    run: echo $0
  - name: Debug Bash Shell
    run: echo $0
    shell: bash
  - name: Debug sh Shell
    run: echo $0
    shell: sh
```
![image](https://user-images.githubusercontent.com/42880130/144666329-1293c0ff-c44c-4dbd-bee6-51c4b6690c68.png)

6: Self-Hosted Runner with Container with Shell Specified in Dockerfile
Dockerfile:
```
FROM python:3.10-bullseye
SHELL ["/bin/bash", "--login", "-c"]
CMD [ "/bin/bash" ]
```
```
local_action_container_shell:
  name: 'Local Action Container Shell'
  runs-on: self-hosted
  container:
    image: ghcr.io/***/python-runner:latest
    credentials:
      username: ***
      password: ***
  steps:
  - name: Debug Shell
    run: echo $0
  - name: Debug Bash Shell
    run: echo $0
    shell: bash
  - name: Debug sh Shell
    run: echo $0
    shell: sh
```
![image](https://user-images.githubusercontent.com/42880130/144666463-707d9f58-6b15-4213-ae8f-2484d18ad5e5.png)
