### ISSUE TITLE
Allow using an expression to specify a reusable workflow

### ISSUE THREAD

**Issue by R-VdP** [actions/runner#1541]
**Describe the enhancement**
Following syntax is currently not supported:
```yml
jobs:
  call:
    uses: 'org/repo/path/workflow.yml@{{ github.sha }}'
```
It fails with `invalid value workflow reference: version cannot have whitespace: ${{ github.sha }}`
