### ISSUE TITLE
Pull Request Edited event stop working after editing the Title a third time.

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1547]
**Describe the bug**
Yesterday I was able to trigger actions when editing PR title or description (body). Later in the same day it stopped!  And there is no issue reported in the Github Status website.

Later today I discovered that Im able to trigger the action after editing the Title or Description up to 2 times. If I try editing it a third time, it simply does not trigger the Action.

This is my action:

````yml
name: Bump Version Workflow

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

  workflow_dispatch:

jobs:
  get-mulesoft-apps:
    name: Get Mulesoft Apps
    uses: VodafoneIS/mulesoft/.github/workflows/get-mulesoft-apps.yml@main

  bump-version:
    name: bump version
    needs: get-mulesoft-apps
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/mulesoft-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        MULESOFT_APP: ${{ fromJson(needs.get-mulesoft-apps.outputs.MULESOFT_APPS) }}

    defaults:
      run:
        working-directory: ${{ matrix.MULESOFT_APP }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: print app name
        run: echo ${{ matrix.MULESOFT_APP }}

      - uses: fregante/setup-git-user@v1

      - name: set bump type
        id: get-bump-type
        run: |
          bump_type=$(/scripts/get_bump_type.sh -a ${{ matrix.MULESOFT_APP }} -t ${{ github.event.pull_request.title }} -b ${{ github.event.pull_request.body}})
          echo "::set-output name=BUMP_TYPE::$bump_type"

      - name: bump version
        run: /scripts/bump_version.sh -a ${{ matrix.MULESOFT_APP }} -b ${{ steps.get-bump-type.outputs.BUMP_TYPE }}

````

**To Reproduce**
1. Create an Action that triggers when editing the PR title or description (type: edited)
2. Edit the Title 3 times. 
3. Verify you have 2 actions running, but the third never started.

**Expected behavior**
When editing the Title or the Description, the Action MUST be triggered if the Action was configured properly, and the PR is against "main"

pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

## Runner Version and Platform
ubuntu-latest

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Github seems to not dispatch PR edit events to start Github Actions

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by AllanOricil** [comment]
If I change the trigger event to this one

````yml
on:
  pull_request:
    types: edited
    branches:
      - main
````

It works! But now the action won't trigger on the other events.

I want my action to be triggered whenever a new commit arrives in the branch and whenever the pr title/description is updated.
