### ISSUE TITLE
timeout-minutes should allow for inputs parameter.

### ISSUE THREAD

**Issue by jetersen** [actions/runner#1555]
**Describe the bug**
step/job `timeout-minutes` only supports number and the runner will not run the workflow with an configurable inputs timeout.
```
timeout-minutes: ${{ inputs.test-timeout }}
```

**To Reproduce**
```
name: DotNet Test

on:
  workflow_call:
    inputs:
      test-timeout:
        required: false
        type: number
        default: 10

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        timeout-minutes: ${{ inputs.test-timeout }}
        run: |
          dotnet test
```

**Expected behavior**
With reusable workflows I would hope that I was allowed to pass a timeout-minutes as configurable.

## Runner Version and Platform
N/A

## What's not working?
```
inputs.test-timeout specshell/.github/.github/workflows/dotnet-build.yml@main (Line: 98, Col: 26): Unexpected value '${{ inputs.test-timeout }}'
```

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by ChristopherHX** [comment]
I thought this was just documentation bug like for `concurrency` ( which accepts inputs, even if the documentations tells the opposite ), but you are right the official actions service blocks `inputs` as valid context and refuse to process your workflow.

Simple Workaround via matrix
```yaml
name: DotNet Test

on:
  workflow_call:
    inputs:
      test-timeout:
        required: false
        type: number
        default: 10

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-timeout:
        - ${{ inputs.test-timeout }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        timeout-minutes: ${{ matrix.test-timeout }}
        run: |
          dotnet test
```

_The actions/runner accepts and runs your job with inputs in timeout-minutes, I tested it_

**Comment by jetersen** [comment]
great that a workaround exist but that just shows it should also allow inputs

**Comment by TingluoHuang** [comment]
@ericsciple does the service pass down the `inputs` context to the runner for reusable workflow?

**Comment by jessemyers** [comment]
I just ran into this issue trying with a reusable workflow. I wanted a parent workflow to have control over an action defined by the reusable workflow. Attempts to make the `timeout-minutes` value process an input value result in:

```
Unrecognized named-value: 'inputs'.
```

**Comment by ljharb** [comment]
Mine seemed to work with `timeout-minutes: ${{ input.timeout-minutes }}` directly (still with an explicit input).

**Comment by Piedone** [comment]
For me, it works as well, [removing the workaround](https://github.com/Lombiq/GitHub-Actions/pull/201/files#diff-bf76a1867732a5eb7d7d723023afeb6cb4c29e07229854d9a8224403853ddc9c) yields a working build still. And now that I see it, we actually have not been using the workaround in newly created workflows, at least since last November.

**Comment by jetersen** [comment]
Maybe they fixed it without closing this issue?

**Comment by rehangit** [comment]
It works but the schema is still broken causing linting errors: https://json.schemastore.org/github-workflow.json

**Comment by thejeff77** [comment]
I don't think `number` is a valid input type...

```
 input type of workflow_dispatch event must be one of "string", "boolean", "choice", "environment" but got "number" [syntax-check]
   |
46 |         type: number
 
```

**Comment by ruvceskistefan** [comment]
Hey all,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by vrathore18** [comment]
I am trying to the same but keep getting error. Can anyone post how we can set the timeout using the input parameter please

**Comment by broskoTT** [comment]
I'm also having troubles with this, this is the error I get:

Error when evaluating 'timeout-minutes' for job 'xxx'. .github/workflows/xxx.yaml (Line: 14, Col: 22): Unexpected value '10'

**Comment by giginet** [comment]
I found the solution you can use `fromJSON`.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#fromjson

```yaml
name: DotNet Test

on:
  workflow_call:
    inputs:
      test-timeout:
        required: false
        type: number
        default: 10

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-timeout:
        - ${{ fromJSON(inputs.test-timeout) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        timeout-minutes: ${{ fromJSON(matrix.test-timeout) }}
        run: |
          dotnet test
```
