### ISSUE TITLE
pull_request_review event not triggering the workflow

### ISSUE THREAD

**Issue by akramdhiabii** [actions/runner#1566]
**Describe the bug**
In brief, the pull_request_review event isn't triggering my test workflow.

````
name: Test Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  get-repos-info:
    runs-on: ubuntu-latest
    steps:
      - name: get Repos info
        run: |
           curl \
           -H "Accept: application/vnd.github.v3+json" \
           -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/orgs/xxx/repos
````

**To Reproduce**
1. Open a PR
2. Ask for a PR review

**Expected behavior**
The workflow should run.

## Runner Version and Platform
Ubuntu latest

## What's not working?
The workflow didn't run automatically when submitting the PR review request. I am missing something? should I add the workflow to the master default branch in order to make it run?
