### ISSUE TITLE
Unable to test on PR request_reviewers logins

### ISSUE THREAD

**Issue by akramdhiabii** [actions/runner#1576]
Hi,
In brief, have this test workflow that should run on review_requested action.
The first Build job should run when one or both of two logins are added as a reviewer, otherwise, it should not.
````
name: Dev Env

on:
  pull_request:
    types: [opened, review_requested]

jobs:
  Build:
    if: |
        ${{ contains(github.event.pull_request.requested_reviewers.*.login, 'XXX') || 
            contains(github.event.pull_request.requested_reviewers.*.login, 'YYY')  }}
`````
1. Ask for review on PR.

**Expected behavior**
The Build job should not run when none of the logins is added as a reviewer.

## Runner Version and Platform
Ubuntu latest

## What's not working?
The problem is the Build job always runs when review_requested and doesn’t qualify the above IF statement.
Am I missing something?
