### ISSUE TITLE
Composite Actions don't support steps.step_id.outcome

### ISSUE THREAD

**Issue by dreinhardt-terminus** [actions/runner#1578]
**Describe the enhancement**
You currently can't use steps.step_id.outcome in composite action if statements.

**Code Snippet**
Below always results in an empty string.
```
steps.test.outcome
```

**Comment by aleto-ms** [comment]
I can add more specific example (also described here: https://github.com/github/feedback/discussions/9599):
One step is running some tests. And I want to create a Check in the next step denoting the status of unit tests.

```yaml
    - name: Run Benchmarks 
      uses: Happypig375/github-action-benchmark@v1
      id: benchmark-reporter

    - name: Checkrun for benchmark
      uses: LouisBrunner/checks-action@v1.2.0
      with:
        conclusion: ${{ steps.benchmark-reporter.outcome }}
        output_text_description_file: ./BenchmarkDotNet.Artifacts/results/joined-report-github.md
```

The above works when in a workflow directly, but in a Composite Action I get nothing from `steps`. Tried other properties as described in [Steps Context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context), still nothing.

```
    - shell: bash
      run: echo ${{ toJson(steps) }}
```
I get just an empty `{ }` object. 

Any ideas? I couldn't find any mentioning of this behavior in documentation is that a bug?
