### ISSUE TITLE
Composite actions conditionals does not work on self hosted runner Latest version

### ISSUE THREAD

**Issue by ashajoy** [actions/runner#1593]
**Describe the bug**

- We are using self hosted runners which is on version 2.285.1 . We are trying to use conditionals in composite actions and it does not work . When we try the same steps on github hosted runner it works 

**To Reproduce**
1. Create a Composite action that has conditionals based on success /failure of previous step 
2. Run 

**Expected behavior**

Conditional steps should run 

## Runner Version and Platform
2.285.1 - ubuntu

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
It fails at the conditional step 

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
@ashajoy do you mind sharing some YAML workflow, actions YAML and also the output log that shows what is not working?

**Comment by ashajoy** [comment]
if : ${{ failure() }} && ${{ steps.deploy-preview.outcome == 'failure' }} - I was trying to use this statement 
Looks like if condition works on our self hosted runner , issue is with **steps.deploy-preview.outcome** .It is always an empty string

**Comment by phasebash** [comment]
I can reproduce this about one out of every 3 runs using composite actions, I cannot share links to repositories as they are `internal` enterprise accounts, but a cut down version of those YMLs might look like:

`.github/actions/with-salutation/action.yml`

```yaml
name: 'With Docker Environment'
description: 'Runs a Makefile target with a Docker environment running'

on:
  workflow_call:
    inputs:
      salutation:
        required: true
        type: string

runs:
  using: 'composite'
  steps:
    - name: Compose Down
      shell: bash
      if: ${{ always() }}
      run: echo "${{ inputs.salutation }}"
```

`.github/workflows/cicd.yml`
```yaml
  salutation_test:
    timeout-minutes: 10
    needs: [test, image]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Elixir
        uses: ./.github/actions/common-elixir

      - name: Load Build Cache
        uses: ./.github/actions/cached-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Salutation
        uses: ./.github/actions/with-salutation
        with:
          salutation: "its broke please fix it"
```
