### ISSUE TITLE
Bug in IF conditions on inputs for reusable workflows

### ISSUE THREAD

**Issue by stevengonsalvez** [actions/runner#1602]
## Problem: 

When a reusable workflow (called workflow), contains if conditions (based on the input of the job) at job level, there is a observation that the if condition seems to execute and use value globally (causing jobs which are being skipped because of a check). 

### Example

> Caller workflow: Simple workflow calling a reusable workflow passing in the github event (PR or push) to the reusable workflow

```yaml
name: caller-workflow
on:
  pull_request:
  push:
    branches:
      - master
# 2
jobs:
  call-the-workflow:
    uses: action-foobar/action-testing/.github/workflows/called_workflow.yml@master
    with:
      TRIGGER_EVENT : ${{ github.event_name }}
```

> Reusable workflow: Workflow with a sequence of job which has conditions based on the input (whether it is a pull_request or a push) 

```yaml
name: tf-app-dns-reusable

on:
  workflow_call:
    inputs:
      TRIGGER_EVENT:
        description: trigger event for the workflow
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Validate terraform configuration

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: debug
        run: |
          echo ${{ inputs.TRIGGER_EVENT }}
  plan-non-prod:
    if: ${{ inputs.TRIGGER_EVENT == 'pull_request' }}
    needs: lint
    runs-on: ubuntu-latest
    name: Plan Application DNS Non Prod
    steps:
      - name: debug
        run: |
          echo "triggered event"
          echo ${{ inputs.TRIGGER_EVENT }}
  plan-prod:
    if: ${{ inputs.TRIGGER_EVENT == 'pull_request' }}
    needs: "plan-non-prod"
    runs-on: ubuntu-latest
    name: Plan Application DNS Prod
    steps:
      - name: debug
        run: |
          echo "triggered event"
          echo ${{ inputs.TRIGGER_EVENT }}
  apply-non-prod:
    if: ${{ inputs.TRIGGER_EVENT == 'push' }}
    needs: lint
    runs-on: ubuntu-latest
    name: apply non prod
    steps:
      - name: debug
        run: |
          echo "triggered event"
          echo ${{ inputs.TRIGGER_EVENT }}
```

#### Observation

![image](https://user-images.githubusercontent.com/9320602/148933591-a27da9b3-e743-4534-81aa-a40afe01b53e.png)

- Job 3 gets the check skipped , even though the condition is valid and matches as Job 2 (Job 3 only depends on success of job 2 and the same `IF` condition as job2.

- On removal of the `IF` condition on Job 4 , then Job 3 executes fine . 

Which implies of some sort of "state" of the IF condition (since there is no relationship between Job 4 and Job 3).

The observation of runs can be found in this repository here -> https://github.com/action-foobar/action-testing/actions/runs/1682109402

# PS:
This was working perfectly fine till  11PM GMT 10th Jan . (as we have a lot of jobs in our org on this setup)

**Comment by bjacques** [comment]
I am also experiencing issues today with a reusable workflow where dependent steps that were running are not showing as "This check was skipped" for no apparent reason.

I'm expecting there to have been a logic change in GH actions around the use of `needs` and `if` statements

**Comment by dptcs** [comment]
Facing the same issue. 

Replicated in https://github.com/dptcs/actions/blob/4e809878b3d836e1fceef318de0cdcf98fdf060b/.github/workflows/called.yml#L29

<img width="1638" alt="Screenshot 2022-01-11 at 12 55 45 PM" src="https://user-images.githubusercontent.com/38645813/148946777-a380b868-ca39-4ece-af84-8ba9239521e7.png">

**Comment by skgandikota** [comment]
+1

**Comment by uoboda-splunk** [comment]
We are facing the same issue

**Comment by lolletsoc** [comment]
We're facing this issue

**Comment by thboop** [comment]
Our team is looking into this and will follow up shortly. 

Thank you for your patience!

**Comment by jacek-jablonski** [comment]
I'm using reusable workflows and also face very similar issue. I don't have if conditions, only `needs`, f.e.: 
```
jobs:
  prepare:
    name: "Prepare"
    runs-on: "ubuntu-latest"

    steps:
       # cut

  prepare-deployment:
    name: "Prepare deployment"
    runs-on: "ubuntu-latest"
    needs: "prepare"

    steps:
       # cut

  build:
    name: "Build dev"
    runs-on: "ubuntu-latest"
    needs: "prepare"

    steps:
       # cut

  ci:
    name: "Continuous integration"
    runs-on: "ubuntu-latest"
    needs: "build"

    steps:
      # cut
```

`ci` job sometimes fires, sometimes not (no changes in code, only rerun button is clicked). I've noticed some pattern like when `build` job finishes and `prepare-deployment` is still in progress, then `ci` job will fire. But when `build` job finishes and `prepare-deployment` has already finished, then `ci` job will not fire.

**Comment by borisyordanov** [comment]
@thboop Can we have an ETA on the fix?

**Comment by thboop** [comment]
The root cause was a server side change we cannot cleanly revert at this time, we are working on a fix that should rollout to all users over the next day or two.

Thank you everyone for your patience as we address this issue. This issue will be updated when the bug is fixed and rolled out to everyone.

**Comment by jacek-jablonski** [comment]
Until the rollout is finished the incident in GitHub Actions should be fired. Workflows are erroneously marked as successful despite not completing all jobs and people may not even be aware of it.

**Comment by benjaminhobbs** [comment]
> Until the rollout is finished the incident in GitHub Actions should be fired. Workflows are erroneously marked as successful despite not completing all jobs and people may not even be aware of it.

While I don't agree with the demand for someone to be fired, it is an extremely bad error that put all users of GHA at risk of downstream errors. It's a risk to all GHA users' products stability and a fix taking days is simply unacceptable. 

I'm sure many people will have to evaluate whether GHA are ready to be used as a proper CI system, because quite frankly this is a very elementary error (it is such a prevalent feature to use) that somehow wasn't tested before release.

Furthermore it skipping the check and it being marked as successful are distinct errors, the former is forgivable the latter is lamentable.

**Comment by lolletsoc** [comment]
> While I don't agree with the demand for someone to be fired, it is an extremely bad error that put all users of GHA at risk of downstream errors. It's a risk to all GHA users' products stability and a fix taking days is simply unacceptable.

I didn't interpret it as someone being fired. I interpreted it as "the incident should be submitted" e.g. maybe being recognised on https://www.githubstatus.com/

**Comment by benjaminhobbs** [comment]
> > While I don't agree with the demand for someone to be fired, it is an extremely bad error that put all users of GHA at risk of downstream errors. It's a risk to all GHA users' products stability and a fix taking days is simply unacceptable.
> 
> I didn't interpret it as someone being fired. I interpreted it as "the incident should be submitted" e.g. maybe being recognised on https://www.githubstatus.com/

Good catch, will correct my comment.

**Comment by jlouros** [comment]
Experiencing the same issue
![GH_WF_bug_1](https://user-images.githubusercontent.com/587250/149202752-d7551de5-7e6b-464c-a43d-a6ee9e5938ce.jpg)

**Comment by ericsciple** [comment]
:wave: Hi folks, I'm sorry about this disruption.

The fix should finish rolling out in the next ~20 minutes. After that, all new runs going forward should work correctly.

Again, I'm sorry about the disruption. We'll review this, and we'll do better going forward.

**Comment by ralvarez-globant** [comment]
Can we get clarification on what exactly happened?
We had to refactor most of our pipes just in case this issue would be extended in time. 

Also, I agree this should have been reported on the status page.

**Comment by stevengonsalvez** [comment]
Retested and the setup is back to working now @ericsciple  - thanks 


Separate question though. Is there any documentation on how to run previous versions of the private runner (to counter regression bugs like these) , as we are dependent on CI being production criticality level. Atleast gives us a option of fault tolerance for ourselves

**Comment by marianhlavac** [comment]
We're experiencing similar issue, only the condition is at the root job level, not inside of the reusable workflow.

<img width="1697" alt="Screenshot 2022-01-18 at 10 37 46" src="https://user-images.githubusercontent.com/3010503/149910757-4ddfb00f-a701-43b7-ba86-f2a5004ca462.png">

```yaml
jobs:
  check-integration:
    name: Check for previous integration
    runs-on: ubuntu-20.04
    outputs:
      result: ${{ steps.check.outputs.found }}
    steps:
      - id: check
        name: Check previously run workflow
        uses: .../.github/actions/check-previous@master
        ...

  integration:
    name: Run integration
    needs: check-integration
    if: ${{ needs.check-integration.outputs.result == false }}
    uses: .../.github/workflows/integration.yaml@master
    ...

  release:
    name: Release new version
    needs: [integration, check-integration]
    uses: .../.github/workflows/semantic-release.yml@master
    ...
```

The _"Run Integration"_ workflow is a reusable workflow, that is run conditionally. If this workflow is skipped, the rest of the job gets skipped too and is marked as successful.

Any ETA when this will gets resolved?

**Comment by benjaminhobbs** [comment]
@thboop  @ericsciple this was a really bad bug, I've already explained my concerns here: https://github.com/actions/runner/issues/1602#issuecomment-1010895916 is it really possible that GitHub thinks it can not report this as an outage and also not explain what happened? Failing builds passed, that's literally the most fundamental failure a CI system can make.

If there's someone else I should address, pls let me know.

**Comment by Amaladavis** [comment]
@thboop @ericsciple I am still facing this issue with steps containing 'if' condition skipped in reusable workflows. Anybody else facing the same?

**Comment by Tchekda** [comment]
Issue still happening with the following code.

Both `api-deploy-prod` and `api-deploy-stage` are triggered at the same time, independent of the input value....
```yml
name: API workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to run the workflow against"
        type: string
        required: true

jobs:
  api-build:
    name: Build the API package
    uses: myorg/reusable-workflows/.github/workflows/docker.yml@main
    with:
      env: ${{ inputs.environment }}
      image-name: ${{ github.event.repository.name }}-api
      docker-file-path: packages/api/infra/docker/Dockerfile
    secrets: inherit

  api-deploy-prod:
    name: Deploy the API package to production environment
    uses: myorg/reusable-workflows/.github/workflows/k8s.yml@main
    needs: api-build
    if: ${{ inputs.environment }} == "production"
    with:
      env: ${{ inputs.environment }}
      image-name: ${{ github.event.repository.name }}-api
      manifest-path: packages/api/infra/k8s/production
    secrets: inherit

  api-deploy-stage:
    name: Deploy the API package to staging environment
    uses: myorg/reusable-workflows/.github/workflows/k8s.yml@main
    needs: api-build
    if: ${{ inputs.environment }} == "staging"
    with:
      env: ${{ inputs.environment }}
      image-name: ${{ github.event.repository.name }}-api
      manifest-path: packages/api/infra/k8s/stage
    secrets: inherit
```

**Comment by jason-edstrom** [comment]
@thboop @ericsciple

Can confirm that this is still happening.  My scenario is needing to conditionally execute a step based on platform (e.g. `if: ${{inputs.platform}} == 'android'`).

**Comment by nathanneibauer** [comment]
> @thboop @ericsciple I am still facing this issue with steps containing 'if' condition skipped in reusable workflows. Anybody else facing the same?

I just hit this issue today. We are using an on-prem instance of enterprise github. Upstream workflows correctly dereference the input variable, but the `if ${{ inputs.var == "value"}}` is not being respected, causing the workflow to skip that step but still mark as "success"

**Comment by ceborgemo** [comment]
In my case I have 3 steps each with the following conditionals:
if: ${{ inputs.var == 'value1' }}
if: ${{ inputs.var == 'value2' }}
if: ${{ inputs.var == 'value3' }}

The 3 steps are being executed even when inputs.var is 'value1'.

**Comment by nolik** [comment]
Today we faced the same bug that if doesn't work in downstream jobs with workflow_call.

**Comment by JennieLi** [comment]
We faced the same bug today. I think we should reopen it.  The job in reusable workflow which has condition `if: ${{ inputs.var }} == 'value'` was ignored, the job was still executed.

**Comment by KatarinaMah** [comment]
As Ive been struggling with this more and more the past days, not to mention that this is apparently a re-occurring issue, Ive put together a workaround which parses input variables to environment variables.
This is also fairly useful when a workflow has multiple triggers(e.g. `on: push` and `on: workflow_call`)

Here is an example that Ive found to be working

```
on:
  push:
    branches:
      - 'develop'
  workflow_call:
    inputs:
      ENABLE_QUALITY_GATE:
        description: 'Enable quality gate'
        required: true
        type: boolean
        default: false

env:
  ENABLE_QUALITY_GATE: ${{ inputs.ENABLE_QUALITY_GATE || false }}

jobs:

  setEnvironment:
    runs-on: ubuntu-latest
    outputs:
      enable_quality_gate: ${{ steps.envVars.outputs.enable_quality_gate }}
    steps:
      - name: Pass inputs as job output(s)
        id: envVars
        run: |
          enable_quality_gate=${{ env.ENABLE_QUALITY_GATE }}
          
          if [[ "$enable_quality_gate" = true ]]; then
            echo "Quality Gate is ENABLED"
          else
            echo "Quality Gate is DISABLED"
          fi
          
          echo "enable_quality_gate=$enable_quality_gate" >> $GITHUB_OUTPUT

  someJob:
    name: Some job does things
    needs: setEnvironment
    runs-on: ubuntu-latest

    steps:

      # [...]

      - uses: sonarsource/sonarqube-quality-gate-action@master
        if: ${{ needs.setEnvironment.outputs.enable_quality_gate }}
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
