### ISSUE TITLE
docker compose run does not output any container log

### ISSUE THREAD

**Issue by ste26054** [actions/runner#1627]
**Describe the bug**
Hello, we are using a `docker compose run` command in a particular step as part of our CI process to run specs against a Dockerized Ruby on Rails application.
**Since a few days**, we are unable to see the output from Docker in this step. 

**To Reproduce**
I created [this sample repo](https://github.com/ste26054/ci_test) which mimics parts of our pipeline. It is enough to reproduce the [issue visible in step "Run Specs with docker compose run"](https://github.com/ste26054/ci_test/runs/4926925432?check_suite_focus=true).

The relevant workflow part : 
```yaml
- name: Run Specs with docker compose run
  run: |
    # GENERATES NO OUTPUT :
    docker compose -p ci_test -f docker-compose.test.yml run --name ci_test_output ci_test sh run-tests.sh
    
    # RETRIEVES LOGS FROM PREVIOUS COMMAND AND OUTPUTS CORRECTLY :
    docker logs ci_test_output
- name: Run Specs with docker run
  run: |
    # OUTPUTS LOGS CORRECTLY :
    docker run ci_test:latest sh run-tests.sh
```

The script which is being run by `docker compose run` (nothing special):
```shell
#!/bin/sh

echo "******* Loading database schema *******"
bundle exec rake db:schema:load
echo "***************************************"

echo "******* Running pending database migrations *******"
bundle exec rake db:migrate
echo "***************************************"


echo "******* Running tests *******"
bundle exec rails test -v
```

**Expected behavior**
The output of the `docker compose run` command should be displayed in the job log output.

## Runner Version and Platform
Runner `2.286.1` on `Ubuntu 20.04.3 LTS`
I also noticed that affected runner has the following docker compose version : `Docker Compose (Docker Inc., 2.2.3+azure-1)`
Whereas an unaffected job had the following version : `Docker Compose (Docker Inc., 2.2.2+azure-1)`

## What's not working?
![image](https://user-images.githubusercontent.com/3840020/150853870-a2a2490d-d534-4e9e-a4d5-a0464c9219a3.png)

Note that we can get the logs by using `docker run` instead of `docker compose run`:
![image](https://user-images.githubusercontent.com/3840020/150854305-b463eeb0-fe87-49eb-900c-24583f0c4eb3.png)

But we need to use `docker compose run` for our real world workflow due to the complexity of the app.

Thanks for your help!
