### ISSUE TITLE
Environment Variables on "Windows-Latest" not available in later steps

### ISSUE THREAD

**Issue by SonarSonic** [actions/runner#1636]
**Describe the bug**
When trying to set an environment variable on `windows-latest` using the steps described in the official documentation the variable is not available in the following steps. When using `ubuntu-latest` it works as expected.

**To Reproduce**
1. Create a new workflow with this template below.
2. Run the workflow.

N.B This code is directly lifted from the documentation [here](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-6). 

```
name: ENV VARIABLE TEST
  
on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
```

**Expected behavior**
In the "Use the value" step, the expected result is "yellow" but the result is "";
If you run the same workflow but instead use `ubuntu-latest`, it will echo "yellow" as expected.

P.S. I'm sorry if I've missed something and further steps are required to use this functionality on windows-latest.

**Comment by thboop** [comment]
Hey @SonarSonic , I think the confusion is coming from the default shell on windows. While Mac and Ubuntu use bash, for windows, we use `pwsh` as the default shell. If you use the powershell syntax to write to the file, this works

```
name: ENV VARIABLE TEST
  
on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" | Out-File -FilePath $env:GITHUB_ENV -Append # no need for -Encoding utf8
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
```

Notice the change to use Out-File `echo "action_state=yellow" | Out-File -FilePath $env:GITHUB_ENV -Append # no need for -Encoding utf8`

Please let me know if that fixes the issue you are seeing!
