### ISSUE TITLE
Cannot use ${{ toJson(github) }} when a ' appears in the commit message.

### ISSUE THREAD

**Issue by petersutter5** [actions/runner#1656]
**Describe the bug**
When trying to use ${{ toJson(github) }} when there is a ' in the commit message, you get an error. The error looks like,
 unexpected EOF while looking for matching `"'

**To Reproduce**
1. Have a workflow bash script that tries to run ${{ toJson(github) }} that runs on a PR
2. Leave a commit message including a ' character
3. Trigger the workflow by opening a PR
4. You should see the toJson step fail with the error message above.

**Expected behavior**
Expected to see the full pretty printed github context

## Runner Version and Platform
Current runner version: '2.287.1'

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu
  20.0[4](https://github.com/CareRevolutions/api_app/runs/5054326356?check_suite_focus=true#step:1:4).3
  LTS

## What's not working?
toJson expression

## Job Log Output
 unexpected EOF while looking for matching `"'

**Comment by nikola-jokic** [comment]
Hi @petersutter5, thank you for submitting this issue!

We are reproducing this issue now and we will get back to you as soon as we can.

**Comment by nikola-jokic** [comment]
Hi @petersutter5,

I reproduced the issue. toJSON will create a JSON object, and since ' is a valid thing to be inside the name (strings are enclosed using "), it will not be escaped. Now, if you are using an expression like `echo '${{ toJSON(github) }}'`, it will trigger a parsing error when it gets to the ' inside the `"title"`.

One suggestion can be to pass in the context as env variable, and then printing or using it would not cause an issue:
```
jobs: 
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
```
This is a bash error, and you can take advantage of bash's built-in escaping of env variables to solve the problem like in the workflow above.
