### ISSUE TITLE
Bad error message when using job container on selfhosted macos runner

### ISSUE THREAD

**Issue by ericsciple** [actions/runner#166]
Attempting to use a job-container on macos self hosted, fails with the error message: `Could not find a part of the path '/proc/1/cgroup'`

Here is the repro:

```
on: [push]
jobs:
  build:
    runs-on: [self-hosted, macos]      
    container: ubuntu:18.04    
    steps:
      - run: printenv|sort
```

Note, after commenting out the offending code, the runner fails downstream with a better error message: `Container operation is only supported on Linux`. So i think we just need to add better validation sooner.
