### ISSUE TITLE
Setting strategy.matrix.value to expression throws invalid type error

### ISSUE THREAD

**Issue by pakalas** [actions/runner#1660]
Getting "Invalid type found: array was expected but string was found" at 
matrix:
   value: ${{fromJson(needs.setup.outputs.matrix)}}

Any ${{}} expression fails. 
Only [] is allowed now, with at least one value. But the value cannot be an expression.

`name: Test Matrix

on:
  workflow_dispatch:
  
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::[\"a\", \"b\", \"c\"]'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"`

**Comment by pakalas** [comment]
Related: https://github.com/actions/runner/issues/751

**Comment by nikola-jokic** [comment]
Hi @pakalas,

Thanks for opening this issue and relating it to the previous one. We will try to reproduce it to understand the cause of the issue and we will get back to you as soon as possible!

**Comment by nikola-jokic** [comment]
Hi @pakalas,

Could you please tell me, if you commit your workflow with the "syntax error", does the action start? In other words, a syntax error is shown in the editor, but when it is committed, actions specified by the "invalid" YAML are performed?

When I reproduced it, actions were executed. The only problem was that, while editing the file in-browser editor, a syntax error was shown, but after committing it, the workflow was executed without problems.

Can you please tell me if that is the case with your workflow as well?

**Comment by sujanp-kr** [comment]
> Hi @pakalas,
> 
> Could you please tell me, if you commit your workflow with the "syntax error", does the action start? In other words, a syntax error is shown in the editor, but when it is committed, actions specified by the "invalid" YAML are performed?
> 
> When I reproduced it, actions were executed. The only problem was that, while editing the file in-browser editor, a syntax error was shown, but after committing it, the workflow was executed without problems.
> 
> Can you please tell me if that is the case with your workflow as well?

Yes. Only browser editor error. Workflow seems to execute fine after commit.

**Comment by ag-monk** [comment]
@nikola-jokic  The same issue I too get, the editor shows syntax error but after commiting the file actions execute and workflow fails with error as below:

ERROR when evaluating ‘strategy’ for ‘Test-Actions’. .github/workflows/main.yml (Line:33, col: 15): Unexpected type of value ‘false’, expected type: Mapping.

**Comment by nikola-jokic** [comment]
Hi @ag-monk,

Could you please provide an example of your workflow file so I can take a look?
While investigating this, I used workflow file:
```
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.value }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=value::['a','b','c']"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: echo "${{ matrix.value }}"
```
Also, please keep in mind this example: https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object.

Both of them worked so there might be some issues within your definition that are causing this syntax error.

**Comment by nikola-jokic** [comment]
Hi everyone,

Since there is no response for a while, and this does not seem to be a runner error, I will now close this issue. And about this red underline inside the in-browser editor, please post this to [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52), which is actively monitored. Using the forum ensures that we route your problem to the correct team.

**Comment by nikola-jokic** [comment]
Hi @bragdonjm,

I am not sure if I understand you correctly, but if an array is being wrapped around with the ('), that makes it a string, which is not an expected type. But if I did not understand you correctly, could you please provide me with an example, so I can look at it?

**Comment by bragdonjm** [comment]
Hello @nikola-jokic
Thanks for the response. No matter how I controlled the output, and modified the echo, it's like actions is wrapping the single quote not the thing producing the output. The only way I found around this was to change the return into Jason and import the matrix from Jason.

**Comment by nikola-jokic** [comment]
For sure, you are completely right. Because of it, you should always use `fromJSON`. We have a similar situation with declaring booleans in inputs. They will be treated as strings, so `fromJSON` is there to help you parse it to the data type which will be accepted.

**Comment by nikola-jokic** [comment]
Hi @bragdonjm,

I will file an issue and a PR in the future, updating the docs to help with this problem 😊

**Comment by bskiefer** [comment]
I'm getting the invalid type error when attempting to add the example:

`Invalid type found: object was expected but string was found`

```
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo hello
 ```

**Comment by bragdonjm** [comment]
> 
Yeah, its the nested bracket I think. There is probably a better way to do it but the way I handle it right now is generate a map in a flat plane and repeat it within the matrix. I cannot remember if its a listed set of maps or just straight maps. so either:
[{"Name" : "Jeff", "Age": "109"}, {"Name": "John", "Age":  "42"}] or just {"Name" : "Jeff", "Age": "109"}, {"Name": "John", "Age":  "42"}. This would run two instances of Job2 both with access with the matrixed data. If you want a better example shoot me a contact.

**Comment by AlexSCorey** [comment]
@bragdonjm I have a job that pulls PR from github and sorts them into different types of prs based on their labels.  I am trying to get the values into an object that I can parse through in job2

I keep getting 1 of several syntax errors....either unexpected value string, or unexpected token ':'
Here is `job1`.  The commented out echo commands at the bottom are different ways I have tried to extract the values I need
`job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch-branch-names.outputs.values}}
    steps:
      - name: Fetch branch names
        id: fetch-branch-names
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pulls = github.paginate call to my repo to return the prs.


            const uiBranches=[];
            const apiBranches = [];
            let uiPrs = [];
            let apiPrs=[];

            for (const pull of pulls) {
              const branch = pull['head']['ref'];
              let isUIPr = false
              let isAPIPr = false
              for (const label of pull.labels){
                if(label.name == 'component:ui'){
                  isUIPr = true
                }
                if(label.name == 'component:api'){
                  isAPIPr = true
                }
              }
              if (branch.startsWith('dependabot')) {
                if(isUIPr){
                  uiBranches.push(branch)
                  uiPrs.push('#' + pull['number'] + ' ' + pull['title']);
                }

                if(isAPIPr){
                  apiBranches.push(branch)
                  apiPrs.push('#' + pull['number'] + ' ' + pull['title']);
                }
              }
            }

            if (uiBranches.length == 0  && apiBranches.length == 0) {
              core.setFailed('No PRs/branches matched criteria');
              return;
            }


            const uiPrStrings = uiPrs.join('\n')
            const apiPrStrings = apiPrs.join('\n')
            const uiCombinedBranches = uiBranches.join(' ')
            const apiCombinedBranches = apiBranches.join(' ')


        # echo '::set-output name=values::{\"values\":[{\"branches\": $uiCombinedBranches, \"prStrings\": $uiPrStrings, \"combinedBranchName\": \"UIDependencyUpgrade\",\"label\": \"component:ui\"}, {\"branches\": $apiCombinedBranches, \"prStrings\": $apiPrStrings, \"combinedBranchName\": \"APIDependencyUpgrade\", \"label\":\"component:api\"}]}'

        # core.setOutput('values', [{branches: uiCombinedBranches, prStrings: uiPrStrings, combinedBranchName: 'UIDependencyUpgrade',label: "component:ui"}, {branches: apiCombinedBranches, prStrings: apiPrStrings, combinedBranchName: 'APIDependencyUpgrade', label:"component:api"}])


Any ideas here?

**Comment by snowe2010** [comment]
@bskiefer it works fine if you pull out the `include:` key from your manual json. e.g.

```yaml
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: 
		include: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo hello

```

**Comment by ashish-raj-wenovate** [comment]
I am trying the exact sample on the doc [here ](https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object) but looks like it matrix is not picking up the json abject.

![image](https://user-images.githubusercontent.com/99645359/168799086-cdddb358-eeb8-4ccc-8f9d-22431ec71ca1.png)

**Comment by satheeshcvcet** [comment]
Yes I am also facing the same problem as [ashish-raj-wenovate] faced.

**Comment by filipagh** [comment]
Hi @nikola-jokic 
i also hit this problem and all examples in this issue like you mention in [comment](https://github.com/actions/runner/issues/1660#issuecomment-1032521718) or from [doc](https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object)   fail with error `Invalid type found: array was expected but string was found `

can you reopen this issue thanks

**Comment by gfrid** [comment]
same here, seems to a bug

name: States
on: 
[push, pull_request]

  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v2
      - id: matrix
        run: echo "::set-output name=value::$(cat accounts.txt | jq -R -s -c 'split("\n")[:-1]')"
  check:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
        matrix:
           value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      - run: |
          echo ${{ martix.value }}

**Comment by filiptibell** [comment]
Just ran into the abovementioned issue (not being able to use expressions for calculating matrix).

We have a limited amount of self-hosted runners and right now it seems our only option is to manually list out all values in the matrix and waste runner startups/time instead of having the exact matrix that depends on previous jobs 😞

**Comment by bukowa** [comment]
````bash

CI: .github#L1
Error when evaluating 'strategy' for job 'matrix-job'. .github/workflows/changed.yaml (Line: 25, Col: 15): Unexpected type of value '{"chart":["http-headers"]}', expected type: Mapping.

````
What's wrong? Looks like Mapping to me.
````bash
Unexpected type of value '{"chart":["http-headers"]}', expected type: Mapping.
````

**Comment by javierlga** [comment]
This was driving me crazy, originally I was using `cat` and `jq` together to get the content into a string:
`cat releases.json | jq 'tostring'` and then adding it to the `GITHUB_OUTPUT`:
```
echo "matrix=$(cat releases.json | jq 'tostring')" >> $GITHUB_OUTPUT
```
but when I ran the workflow I always got this error:
```
Unexpected type of value '[{"name":"XXX","ip_address":"XXX"},{"name":"XXX","ip_address":"XXX"}]', expected type: sequence.
```
**Note**: I've been using the `include` property when defining the matrix. 

Anyways, for some reason a pair of single quotes were added even removing with sed threw another error message:
```
Error parsing fromJson,.github/workflows/XXX.yaml (Line: 164, Col: 18): Invalid property identifier character: \. Path '[0]', line 1, position 2.,.github/workflows/XXX.yaml (Line: 164, Col: 18): Unexpected type of value '', expected type: Sequence.
```

The solution that I found was to use a [multiline string](https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings), e.g.:
```
    steps:
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          cat releases.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      new_content: ${{ steps.get-json-content.outputs.JSON_CONTENT }} 
```

Job using matrix: 
```
  matrix_job_test:
    name: Matrix job test
    runs-on: ubuntu-latest
    needs: test_job
    strategy:
      matrix:
        include: ${{ fromJSON(needs.test_job.outputs.new_content) }}
    steps:
      - run: |
          echo $STACK_NAME
          echo $STACK_IP
        env:
          STACK_NAME: ${{ matrix.name }}
          STACK_IP: ${{ matrix.ip_address }}
```

In case someone wonder, this is the JSON content structure:
```
[
  {
  "name": "string",
  "ip_address": "string"
  },
  {
    "name": "string",
    "ip_address": "string"
  }
]
```

I hope this helps other people, cheers!

**Comment by bukowa** [comment]
I used this:
````bash
DATA=$(echo ${{ steps.changed-files-specific.outputs.all_changed_files }} | jq -c '. | map(split("/")[1]) | unique')
````

**Comment by mohas556** [comment]
Is there any intention to fix this or make the documentation on it intuitive at all?

**Comment by MikaelStudios** [comment]
I found a fix:
you need to add [ ' *** ' ]

`   steps:
   - id: Log
     run: |
          echo "matrix=['$input']" >> $GITHUB_OUTPUT
     env:
          input: ${{ github.event.inputs.platform }}`

**Comment by RobinHoutevelts** [comment]
I'm having the same issue.

> Error when evaluating 'strategy' for job 'disable-replication'. .github/workflows/deploy.yml : Error parsing fromJson,.github/workflows/deploy.yml : Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/deploy.yml : Unexpected type of value '', expected type: Sequence.

```yaml
disable-replication:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      server: ${{ fromJson(vars.SERVERS_JSON) }}
  steps:
    - name: Hello world
      run: echo ${{ matrix.server.name }}
```

<details><summary>My <code>SERVERS_JSON</code> variable looks like this:</summary>


```json
[
  {
    "name": "backend",
    "host": "backend.example.com",
    "user": "www-example"
  },
  {
    "name": "frontend-a",
    "host": "frontend-a.example.com",
    "user": "www-example"
  },
  {
    "name": "frontend-b",
    "host": "frontend-b.example.com",
    "user": "www-example"
  }
]
```

I also tried to change it to a oneliner JSON:

```json
[{"name": "backend","host": "backend.example.com","user": "www-example"},{"name": "frontend-a","host": "frontend-a.example.com","user": "www-example"},{"name": "frontend-b","host": "frontend-b.example.com","user": "www-example"}]
```

But that did not resolve it either.

</details>

-----

When I change my job to inline the array, everything works fine.

<details><summary>Inlined working example</summary>

```yaml
disable-replication:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      server: [
        {
          "name": "backend",
          "host": "backend.example.com",
          "user": "www-example"
        },
        {
          "name": "frontend-a",
          "host": "frontend-a.example.com",
          "user": "www-example"
        },
        {
          "name": "frontend-b",
          "host": "frontend-b.example.com",
          "user": "www-example"
        }
      ]
  steps:
    - name: Hello world
      run: echo ${{ matrix.server.name }}
```

</details>
