### ISSUE TITLE
runs-on a self-hosted runnner bug in workflow_call (queued forever)

### ISSUE THREAD

**Issue by dennybaa** [actions/runner#1671]
**Describe the bug**
Called workflow runner can not be scheduled on a self-hosted runner.

```
  build:
    name: Build and Push
    needs: [setup]
    runs-on: ${{ fromJSON(needs.setup.outputs.runs-on) }}
```

**Expected behavior**
Runner must be picked up from the caller's workflow organization rather than the organization where the `workflow_call` repository is located.

## Runner Version and Platform
v2.287.1
