### ISSUE TITLE
Environment variable from .env file is not visible inside container

### ISSUE THREAD

**Issue by retzero** [actions/runner#1685]
**Describe the bug**

I added the following to the `.env` file inside my self-hosted runner root directory to apply the common environment variable.

```
$ cat .env
LANG=en_US.UTF-8
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
MY_TEST_ENV=true
```

However, this variable could not be accessed in workflow using container.
In container, is it the design that the variables written in the runner configuration file (`.env`) are not passed?

```yaml
  build:
    runs-on: "my-runner"
    container: python:3.8.10
    steps:
      - name: Check the env
        run: echo ${MY_TEST_ENV} ## <<= nothing printed...
```

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

Environment variables should be visible inside container.

## Runner Version and Platform
Version of your runner?

2.284.0

OS of the machine running the runner? OSX/Windows/Linux/...

Ubuntu 20.04

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
