### ISSUE TITLE
Github actions repository redirect

### ISSUE THREAD

**Issue by stevengonsalvez** [actions/runner#1695]
When a repository name changes , github auto redirects the repository 

eg: `https://github.com/nick-invision/retry`  will auto redirect to `https://github.com/nick-fields/retry`

But when used in an action as such 

```
      - name: Validate version number (domain)
        uses: nick-invision/retry@v2.6.0
        with:
          timeout_seconds: 20
          max_attempts: 15
          retry_wait_seconds: 10
          command: |
            set -x
            IP=$(curl "https://something")
            echo $IP | grep ${{ github.sha }}
```

This fails with a repository not found.
