### ISSUE TITLE
Event is triggering for every tag without matching the pattern

### ISSUE THREAD

**Issue by tharindu-dif** [actions/runner#1699]
I have setup a mobile deployment for on create tag with specific regex pattern. But the deployment is starting for every tag regardless the pattern. Following is my yml code snippet.

```
on:
   create:
     tags:
       - '^v(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)(\()(\d+)(\))$'
```
Then I have tried with the simplest pattern which was mentioned in the documentation.

```
on:
   create:
     tags:
       -v*
```
But still the same results. It was triggering for every tag was created.

**To Reproduce**
Add one of above trigger to your yml file and create a new tag named "test"

**Expected behavior**
Deployment event should not have been started.

**Comment by ruvceskistefan** [comment]
Hi @tharindu-dif,
Thanks for filing this issue! We are working on reproducing the issue, so we will get back to you as soon as we have more informations.

**Comment by ruvceskistefan** [comment]
I have successfully reproduced the problem you described and I think I have a solution. The problem is that the filter in `create` will not prevent the workflow from starting when pushing the tag to a remote repository. The solution is to use event `push`, ie to make your yml file look like this (yml code snippet):
```
on:
  push:
    tags:
      - v*
```
@tharindu-dif does this work for you, ie. does this solve the problem you described?
