### ISSUE TITLE
Private repo w/tag in workflow

### ISSUE THREAD

**Issue by stoked10** [actions/runner#1718]
**Description:** 
We want to use a workflow action to lint and test our code on push, We use three private repos with oauth keys in our package.json.

**Bug:**
Each private repo reference in our package.json references a tag for that repo. The work flow fails with "Repository not found". For example:

package.json dependency:
`"Private-Repo1": "https://<PAT>:x-oauth-basic@github.com/project/Private-Repo.git#v1.0.0",`

The oauth key is set to allow checking out the repo as well as workflow access. When attempting to run the work flow we get:

```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ***github.com/project/Private-Repo.git
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/project/Private-Repo.git/' not found
```
our yaml:
```
name: API auto test and lint workflow

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: git config --global url."https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"
    - run: npm ci
    - run: npm run lint
    - run: npm run test
```
(I know the replace is redundant, we tried everything we could find)

Local testing is pointing to the reason that we’re failing is that `git ls-remote` fails when you point to a private repo with a tag number, if I remove the tag it works.

**To Reproduce**
1. Create a prviate repo and tag a version
2. Create an oauth key, give it git and workflow access
3. Create a secret named GIT_TOKEN that is your key
4. Add the private repo with oauth key to your repo package.json
5. Create a workflow for your repo with the above YAML
6. Run the workflow

**Expected behavior**
To be able to reference a private repo w/tag in our package.json that also works in a workflow
