### ISSUE TITLE
ubuntu-latest runner fails to download qemu package

### ISSUE THREAD

**Issue by horzsolt** [actions/runner#1725]
**Describe the bug**
Action failed as it couldn't download the qemu package: qemu_4.2-3ubuntu6.19_amd64.deb. Was this package removed from the archive?

**To Reproduce**
Create a simple action and execute it:
```
name: GitHub issue repro
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sudo apt-get install qemu binfmt-support qemu-user-static"
      - run: sudo apt-get install qemu binfmt-support qemu-user-static

```
**Expected behavior**
Package download is successful

## Runner Version and Platform
ubuntu-latest

## What's not working?
![image](https://user-images.githubusercontent.com/8521887/156338624-1b7fd19f-9520-4c86-b84a-d340c02be8ac.png)

## Job Log Output
```
Run sudo apt-get install qemu binfmt-support qemu-user-static
  sudo apt-get install qemu binfmt-support qemu-user-static
  shell: /usr/bin/bash -e {0}
Reading package lists...
Building dependency tree...
Reading state information...
binfmt-support is already the newest version (2.2.0-2).
binfmt-support set to manually installed.
The following NEW packages will be installed:
  qemu qemu-user-static
0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.
Need to get 21.3 MB of archives.
After this operation, 208 MB of additional disk space will be used.
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 qemu amd64 1:4.2-3ubuntu6.19
  404  Not Found [IP: 40.119.46.219 80]
Err:2 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 qemu-user-static amd64 1:4.2-3ubuntu6.19
  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_4.2-3ubuntu6.19_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_4.2-3ubuntu6.19_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
