### ISSUE TITLE
toJson has error with particular value

### ISSUE THREAD

**Issue by JaviRpo** [actions/runner#1776]
**Describe the bug**
I have a github action with some inputs in `workflow_dispatch`, and I want to print them in my first step. if I put a particular value in one of the inputs, I have an error => `Error: Process completed with exit code 127.`
The problem is only present when I put the value in URL

**To Reproduce**
1. Create the next action
```yaml
name: Validate

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: App Name
        required: true
        type: string
      app-facturacion:
        description: ¿Habilitar Facturación Electrónica?
        default: false
        type: boolean
      app-nomina:
        description: ¿Habilitar Nómina Electrónica?
        default: false
        type: boolean
      app-url-dian:
        description: URL Token Dian (requerido si alguno de los 2 anteriores ha sido chequeado)
        type: string
      client-nit:
        description: Cliente - Nit
        type: string
        required: true
      client-email:
        description: Cliente - Email
        type: string
      client-regimen:
        description: Cliente - Régimen Tributario
        default: 'RESPONSABLE DE IVA'
        type: choice
        options:
        - RESPONSABLE DE IVA
        - GRAN CONTRIBUYENTE
        - NO RESPONSABLE DE IVA
      client-autoretenedor:
        description: Cliente - Autoretenedor
        default: false
        type: boolean
      client-ciuu:
        description: Cliente - Actividad Económica
        type: string
      client-city:
        description: Cliente - Ciudad
        type: string

jobs:
  validate-data:
    name: ✅ Validate
    runs-on: ubuntu-latest
    steps:
    - name: Parámetros de entrada
      run: |
        echo "Parámetros de entrada: ${{ toJSON(github.event.inputs) }}"

```
2. Go to the action an run it manually with the next values
```
App Name: name1
URL: https://catalogo-vpfe-hab.dian.gov.co/User/AuthToken?pk=10910094%7C71791661&rk=901522531&token=0ae68675-c410-4869-af89-d63a0c755cd7
Cliente Nit: 1111
```
<img width="329" alt="image" src="https://user-images.githubusercontent.com/8562436/159599372-6c9d5137-7aa6-4fb9-aef4-518dc7c9ef89.png">

3. Run the action

4. See error in the print step
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/8562436/159599425-bcd9caf2-9643-4ac0-9411-9ab3f2f9b699.png">

**Expected behavior**
I expect not having the error 127.
The error only happen with that particular URL input.

## Runner Version and Platform
Version of your runner?
Current runner version: '2.288.1'

OS of the machine running the runner? OSX/Windows/Linux/...
```
  Ubuntu
  20.0[4](https://github.com/JaviRpo/syna/runs/5653332363?check_suite_focus=true#step:1:4).4
  LTS
```

## What's not working?
Please include error messages and screenshots.
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/8562436/159599425-bcd9caf2-9643-4ac0-9411-9ab3f2f9b699.png">

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ruvceskistefan** [comment]
Hi @JaviRpo,
Thanks for filling this issue! We will try to reproduce the bug, so I will get back to you as soon as I have some news.

**Comment by ruvceskistefan** [comment]
Hi @JaviRpo,

The problem was '&' character in some of the workflow parameters (in your case URL). The simplest solution is to export this `toJSON(github.event.inputs)` into an environment variable, like this:
```
- name: Parámetros de entrada
   env:
      PARAMS_ENTERED: ${{ toJSON(github.event.inputs) }}
      run: echo $PARAMS_ENTERED
```
Here is the example of successful workflow run: https://github.com/ruvceskistefan/git-runner-test/actions/runs/2040713539
I'm going to close this issue, since given solution works. If you have more questions, feel free to ask and reopen the issue.
