### ISSUE TITLE
Unable to launch the workflow from an autogenerated hello world workflow yaml file

### ISSUE THREAD

**Issue by prx0** [actions/runner#1782]
**Description**
Hi, I'm trying to launch a workflow from a private github repository without success but I got a message "Workflow run was successfully requested. " It seems very strange. Maybe a bug ?

**To Reproduce**
1. Create an existing valid workflow file in yaml from your computer inside a .github/workflows created by mkdir -p.
2. Go to action page from the repository. Then click on `New workflow` button. 
3. On `Choose of wokflow` page, click on the link `set up a workflow yourself `. It generates the following yaml file.

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
```
4. Give an available name for this file, then click on `Start commit` and choose the ` Commit directly to the main branch. ` option and `Commint new file`.
5. Go on `Action` page, Click on `CI` workflow, then click on `Run workflow` with `Use workflow from` main branch. You will have the message "Workflow run was successfully requested. "

**Expected behavior**
I expect to see the workflow running, but I have a page with the message `This workflow has no runs yet.`.

## Runner Version and Platform
I use free pricing plan for a private repository.

OS ubuntu-latest

## What's not working?
I cannot trigger the workflow.
