### ISSUE TITLE
Error when evaluating 'environment' for job 'core'. Unexpected type 'BasicExpressionToken' encountered while reading 'job environment'. The type 'MappingToken' was expected.

### ISSUE THREAD

**Issue by omsmith** [actions/runner#1828]
Hello

Our jobs just started failing to run with the following error about 1 hour ago (12:15pm Eastern):

> Error when evaluating 'environment' for job 'core'. Unexpected type 'BasicExpressionToken' encountered while reading 'job environment'. The type 'MappingToken' was expected.

Our workflow looks like this:

```yaml
jobs:
  core:
    name: Core

    environment: ${{ github.event_name == 'pull_request' && 'ci' || 'release' }}

    # ...
```

Was there a breakage deployed in the orchestrator parsing environment for single names?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-single-environment-name

Thanks
