### ISSUE TITLE
Badge always incorrectly displayed as "failing"

### ISSUE THREAD

**Issue by mihaigalos** [actions/runner#1830]
[This](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg) badge is shown as "failing" but the [tasks' statuses](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml) are all green.

**Describe the bug**
The badge was green since CD pipeline is prechecked before running, meaning it normally should never fail. The badge for it was green and it suddenly went to red - "failing", even though all constituent tasks are succeeding.

**To Reproduce**
See 1st paragraph.

**Expected behavior**
The badge is green when all tasks successful, red when at least one fails.

## Runner Version and Platform
Full yaml snapshot available [here](https://github.com/mihaigalos/aim/blob/2e9dff70d9a0df97ee6f4b25b8e9d9656e067339/.github/workflows/cd.yaml).

Simplified yaml:
```yaml
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch: # Run with Run Workflow button in GitHub Action Job.
    inputs:
      is_manual_cd:
        default: true
        description: Manual trigger

jobs:
  common-assertions:
    runs-on: ubuntu-latest
```

## OS of the machine running the runner?
Linux
