### ISSUE TITLE
Jest test failed but Github Action said that is success/pass

### ISSUE THREAD

**Issue by tin-pham** [actions/runner#1851]
**Describe the bug**
I run test on Github Action, it failed some test but it still pass the process
It failed some
![image](https://user-images.githubusercontent.com/20679090/165708091-5a740d73-f433-4772-a164-ab013bc9b55c.png)
Why it still pass
![image](https://user-images.githubusercontent.com/20679090/165707970-fb69547e-b9b8-4daf-852b-8534cf2aa375.png)

**To Reproduce**
This is my script to run the test in global project
![image](https://user-images.githubusercontent.com/20679090/165708264-4456731a-df38-4ffd-bf0e-75b449f12e5b.png)
My yml

```yml
name: Tech API
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/products
      API_VERSION: v0.2
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.2', '4.4', '5.0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          npm: cache

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm run install:server
      - run: npm run test:api
```

**Expected behavior**
It pass although the test failed
