### ISSUE TITLE
gh: command not found + brew: command not found

### ISSUE THREAD

**Issue by yonat-ateam** [actions/runner#1865]
**Describe the bug**

Using `macos-latest` bash step in a composite action (that worked last week), suddenly executing `gh` command fails with error:

`gh: command not found`

Same thing with `brew`.

**To Reproduce**

The `action.yml` is:

```yml
...
runs:
  using: "composite"
  steps:
    - name: the misbehaving step
      shell: bash
      run: |
        SCRIPTS_PATH=${{ github.action_path }}/../../scripts
        $SCRIPTS_PATH/misbehaving-script.sh
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ inputs.token }}
```

Where `misbehaving-script.sh` is:

```sh
#!/bin/bash
...
gh pr comment $PR_NUMBER --body-file some-important-comment.txt
```

**Expected behavior**

New PR comment added.

## Runner Version and Platform

macos-latest

## What's not working?

I get the following error:

`gh: command not found`
