### ISSUE TITLE
Show composite action name at step level

### ISSUE THREAD

**Issue by bombillazo** [actions/runner#1877]
**Describe the bug**
Given the use of a custom composite action:

```yml
# Composite Action ./.github/actions/build-api/action.yml
name: 'Build API'
description: 'Build the API'
runs:
  using: 'composite'
  steps:
    ...

# Main Workflow
name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      # Configure Environments
      - uses: ./.github/actions/build-api
```

The runners do not show the step name of the composite action, instead a generic `Run action... ` step name. Having to update this step name when it can be extracted from the action itself can get tedious when managing lots of actions and workflows.

**To Reproduce**
1. Setup a composite action
2. Do not give a name to the step when using the composite action
3. Run the action

**Expected behavior**
The runner shows the name of the composite action for the step taken from the composite action metadata.

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? All

## What's not working?
<img width="375" alt="image" src="https://user-images.githubusercontent.com/44002321/167024795-e128d2f9-2afd-4af1-b73b-0e00e91aa0ec.png">

**Comment by ruvceskistefan** [comment]
Hi @bombillazo,

Thanks for reporting this issue! I agree with everything written, if the step name is not defined, the name of the action itself should be displayed. I added this to the board so we will work on it and create a PR that solves this problem.

**Comment by AlekSi** [comment]
The same can be done for action steps. For example, given that composite action

```yaml
name: 'Action name'
runs:
  using: 'composite'
  steps:
    - name: Action step 1
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash
```

I get

![image](https://user-images.githubusercontent.com/11512/167244757-26a135f5-95ff-4e08-a7e6-5b0a855c16d6.png)

Both "Action name" and "Action step 1" are not visible. `runs.steps.name` is a required field, but seems to be unused.

**Comment by acabarbaye** [comment]
I would be also great if each step could be "collapsable" in the same way it is for other types of actions

**Comment by zupo** [comment]
Until this is properly fixed, is there any workaround to show a nicer name in the action output?

**Comment by joaoluiznaufel** [comment]
still waiting for this

**Comment by anthonwellsjo** [comment]
Still waiting for this too 🙏 This is a big advantage to be able to create a clean code bases with composite actions, without compromising readability in the UI...

**Comment by cezar-tech** [comment]
still waiting for this as well

**Comment by behdad088** [comment]
Any updates on that?

**Comment by asvishnyakov** [comment]
+1 awaiter here

**Comment by basimbd** [comment]
+1 awaiter here (2)

**Comment by alan-sanchez2-kr** [comment]
_*anxiously awaiting for this as well_ 😅

**Comment by jamesloosli** [comment]
+1

**Comment by Marcin-Lach** [comment]
+1

**Comment by brandonja991** [comment]
+1 Still waiting

**Comment by ArminArdekani** [comment]
+ 1 waiting too

**Comment by fabianorosa1** [comment]
+1 awaiter here

**Comment by KarimGl** [comment]
+1 still waiting

**Comment by nuryupin-kr** [comment]
+ 1 still waiting

**Comment by paveldedourek-eaton** [comment]
+1 awaiter here

**Comment by jaymecd** [comment]
Knowing that GHA renders 1st line of the `run` script as step title, this workaround allows to have nicer rendering:

```yaml
    - name: Verify installed ASDF tools
      shell: bash
      run: |
        : Verify installed ASDF tools
        awk '{print $1}' .tool-versions \
          ...
```

that provides nice rendering:

collapsed:
<img width="358" alt="Screenshot 2024-03-10 at 14 11 01" src="https://github.com/actions/runner/assets/824109/adfd114d-8427-410a-9131-66cc9ea95571">

expanded:
<img width="322" alt="Screenshot 2024-03-10 at 14 09 40" src="https://github.com/actions/runner/assets/824109/7130d193-4d4a-4c6c-956b-cf23f8a2daff">

Instead of `: step name`, one might use `true shell - step name`
<img width="377" alt="Screenshot 2024-03-10 at 14 12 44" src="https://github.com/actions/runner/assets/824109/50600eef-dc73-463f-be61-61216eead885">

Both `:` and `true` commands do not affect execution flow
