### ISSUE TITLE
Annotation links from composite actions have incorrect step numbers in links

### ISSUE THREAD

**Issue by konradpabjan** [actions/runner#1901]
**Describe the bug**

On a similar pattern as https://github.com/actions/runner/issues/1742 Annotations from composite actions are a bit broken compared to their normal counter parts. Recently support was added for annotations to link out directly to the log position they were created from so it's easier to see where they came from. For this linking the step number and line number information need to be saved and provided by the runner. For composite actions the step number that is provided does not match and links are incorrect.

**To Reproduce**

1. Create a simple composite actions that generates annotations
```
name: 'Annotation example'
description: Test annotations
runs:
  using: "composite"
  steps:
    - run: echo Hello there once!
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error::Testing error"
      shell: bash
    - run: echo Hello there
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error::Testing error"
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::warning::Testing warning"
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::notice::Testing notice"
      shell: bash
```

2. Run the workflow from another repository (or locally)

3. Inspect or click the the annotation from the run summary page

<img width="592" alt="image" src="https://user-images.githubusercontent.com/16109154/168944786-af608e9d-b62b-480b-85a6-ca9edfc0f354.png">

**Expected behavior**
Clicking the annotation should directly link out to the log line, expand the correct step and scroll to the exact position the annotation originates from.

## Runner Version and Platform
Version of your runner? 2.291.1

Linux, but this is most likely on all types of runners

## What's not working?

From the screenshot above, the annotation link should work but it fails because the step number is wrong: The line number the annotation originates from is correct (35), however the step number (16), is way off compared to what it should be (something like 2,3 or 4).

Specifically the step number that gets used in the URL gets set here: https://github.com/actions/runner/blob/02b52e8497a98194484c08ec84e0721393a6178a/src/Runner.Worker/ExecutionContext.cs#L559-L564

For composite actions `issue.Data["stepNumber"]` needs to be set to something else like the parent of the composite action that houses the entire step. Not sure how easy that will be to do 🤷 

The original work to save this information for other annotations was done as part of this PR: https://github.com/actions/runner/pull/1744

## Job Log Output
Not applicable

## Runner and Worker's Diagnostic Logs
Not applicable
