### ISSUE TITLE
Attempt to base64 encode a multiline secret fails

### ISSUE THREAD

**Issue by pkaramol** [actions/runner#1942]
**Describe the bug**
I have a GCP service account key, which is a `json` multiline string saved as a repo secret.

I am trying to use an action that requires the SA key in `base64` encoded format,

```yaml
    - name: base64 encode the staging gcr sa
      id: base64-staging-gcr
      shell: bash
      run:
        echo "::set-output name=STAGING_GCR_SA_BASE64::$(echo '${{ secrets.STAGING_GCR_SA }}' | python -m base64 -e)"

    - name: build and push to staging gcr
      id: stg_img_build
      uses: RafikFarhad/push-to-gcr-github-action@v4
      with:
        gcloud_service_key: ${{ steps.base64-staging-gcr.outputs.STAGING_GCR_SA_BASE64 }}
        registry: gcr.io
        project_id: $STAGING_GCR_PROJECT
        image_name: ${{ github.event.inputs.image_name }}
        image_tag:  ${{ github.event.inputs.image_tag }}
```

This however fails as follows:

```
Error response from daemon: Get "https://gcr.io/v2/": unknown: Unable to parse json key.
```

When saving the contents of the `STAGING_GCR_SA_BASE64` var to an artifact and downloading it to verify its contents, it seems that it is partially encoded?

```
Desktop echo ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm90ZWQtaGFu | base64 --decode
{
  "type": "service_account",
  "project_id": "noted-han%  
```

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/... : `ubuntu-latest`

## What's not working?
Base64 encoding of a multiline secret fails
