### ISSUE TITLE
service containers with registry volumes dir not create

### ISSUE THREAD

**Issue by willzhang** [actions/runner#1945]
**Describe the bug**
service containers with registry:2 , and config   volumes: ${{ github.workspace }}/registry:/var/lib/registry

but the ${{ github.workspace }}/registry directory will not ctreate by default when the registry have been started and runing.

**To Reproduce**
```
name: gen-artifacts
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      registry:
        image: registry:2
        volumes: 
          - ${{ github.workspace }}/registry:/var/lib/registry
        ports:
          - 5000:5000

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
        with:
          driver-opts: network=host
      - name: Build and Push kubespray Image
        run: |
          docker pull nginx
          docker tag nginx localhost:5000/nginx:latest
          docker push localhost:5000/nginx:latest
```
**Expected behavior**
${{ github.workspace }}/registry should be  exist， and push image success

## Runner Version and Platform

Current runner version: '2.292.0'

OS of the machine running the runner? OSX/Windows/Linux/...
Requested labels: ubuntu-22.04

## What's not working?
docker pull nginx
docker tag nginx localhost:5000/nginx:latest

the push will failed
docker push localhost:5000/nginx:latest

## Job Log Output
```
2022-06-14T09:31:10.7719178Z  time="2022-06-14T09:29:48.280647997Z" level=error msg="response completed with error" err.code=unknown err.detail="filesystem: mkdir /var/lib/registry/docker: no such file or directory" 
```
## Runner and Worker's Diagnostic Logs
https://pipelines.actions.githubusercontent.com/serviceHosts/66f6b59e-2fc6-43a7-a622-ddde91c6c5a3/_apis/pipelines/1/runs/95/signedlogcontent/3?urlExpires=2022-06-14T09%3A23%3A40.4902449Z&urlSigningMethod=HMACV1&urlSignature=pBRay8yWQeUZZ8CYXK1aV8oZ5LTuNq4ZfpM6oSyQYV0%3D
