### ISSUE TITLE
Composite Action: Incorrect State Value when composite action is used twice in the workflow

### ISSUE THREAD

**Issue by aparna-ravindra** [actions/runner#1947]
**Describe the bug**
When a composite action that saves [state](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#sending-values-to-the-pre-and-post-actions) is used twice in a workflow, the post-step stage receives incorrect value. It appears that the second execution of the action overrides the value set by the first. 

**To Reproduce**
1. Consider this simple action that saves state in the `main` method and prints the value of the state in the `post` method. ([example](https://github.com/aparna-ravindra/set-state))
<details>
     <summary> main.ts: </summary>

```
import * as core from "@actions/core";

async function run(): Promise<void> {
    try {
        const statevalue = core.getInput("stateValue", { required: true });
        core.info(`Saving state: ${statevalue}`);
        core.saveState("state_value", statevalue);
    } catch (error: unknown) {
        core.setFailed((error as Error).message);
    }
}

run();

export default run;
```
</details>

<details>
     <summary> post.ts: </summary>

```
import * as core from "@actions/core";

async function run(): Promise<void> {
    try {
        const statevalue = core.getState("state_value");
        core.info(`saved state_value= ${statevalue}`);
    } catch (error: unknown) {
        core.setFailed((error as Error).message);
    }
}
run();
export default run;
```
</details>

2. Write a composite action that uses the above action:
Example:
<details>
     <summary> /.github/actions/action.yml</summary>

```
name: Set-State
description: Sets the state twice

inputs: 
  stateValue:
    description: "stateValue"
    required: true
runs:
  using: "composite"
  steps:
    - uses: aparna-ravindra/set-state@main
      with:
        stateValue: ${{ inputs.stateValue }}
```
</details>

3. Write a workflow that uses this composite action twice:
Example:

<details>
     <summary> /.github/workflows/test_set_state_composite.yaml</summary>

```
name: Set State Composite
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      name: state_1
      id: state1
      with:
        stateValue: 'test1'
    - uses: ./.github/actions
      name: state_2
      id: state3
      with:
        stateValue: 'test2'
```
</details>

**Expected behavior**
The state variables should be isolated for each step. The issue is not reproducible if the action is used twice directly in the workflow. It is seen only if the action is made part of a composite action and if the composite action is used twice in the workflow.

## Runner Version and Platform
Version of your runner?
 '2.293.0'
OS of the machine running the runner? OSX/Windows/Linux/...
Environment: ubuntu-20.04
Version: 20220605.1

## What's not working?
Both the `post` stages for the two executions of the composite action prints the same value of the state variable though different values were set in the `main` step.
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/82894348/173993943-f7a4bde8-e48f-48ee-969e-a59a576614e9.png">
## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
