### ISSUE TITLE
Fail-fast/pipefail behaviour for default shell inconsistent with documentation 

### ISSUE THREAD

**Issue by choffa** [actions/runner#1955]
**Describe the bug**
[The documentation states that](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)
> Fail-fast behavior using set -eo pipefail: Default for bash and built-in shell. *It is also the default when you don’t provide an option on non-Windows platforms.* (my emphasis)

The last statement does not appear to be true, as `false | true` passes on `ubuntu-latest` when not explicitly setting the `shell` option.

**To Reproduce**
1. Run workflow file:
```yml
name: Test pipefail

on:
  push

jobs:
  test-pipefail:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run command false first
        if: always()
        run: false | true
      
      - name: Run command false last
        if: always()
        run: true | false
```
2. Observe that only second step fails

**Expected behavior**
I expect that the behaviour of the runner to be consistent with the documentation, ie. that _both steps_ in the above example fails, or that the documentation is updated to reflect the actual behaviour.

## Runner Version and Platform
Built in runner using `ubuntu-latest`
