### ISSUE TITLE
Runner does not re-run dependent jobs for "Re-run failed jobs"

### ISSUE THREAD

**Issue by ashanka25** [actions/runner#1961]
**Describe the bug**
When re-running failed jobs in a workflow, Github Actions claims to run all failed jobs and their dependents, but the dependent jobs are not actually run. Instead, the outputs from the previous runs of the dependent jobs are spliced in.

**To Reproduce**
1. Create this workflow:
    ```yaml
    name: Rerun Dependencies Test
    on: workflow_dispatch
    jobs:
      prep:
        runs-on: ubuntu-latest
        outputs:
          uuid: ${{ steps.generate-uuid.outputs.uuid }}
        steps:
          - id: generate-uuid
            run: echo "::set-output name=uuid::$( uuidgen )"
    
      job:
        runs-on: ubuntu-latest
        needs: [prep]
        steps:
          - run: echo "::notice::RUN-ATTEMPT=${{ github.run_attempt }}, UUID=${{ needs.prep.outputs.uuid }}"
          - run: false # Deliberately fail job
     ```
2. Run the workflow. The run fails and generates a notice with the UUID generated in the `prep` job:
    ```
    RUN-ATTEMPT=1, UUID=6b30a63f-8e2a-445c-807f-c086fc77bd4e
    ```
3. Trigger a "Re-run failed jobs"
4. This run also prints out the same UUID from the first run:
    ```
    RUN-ATTEMPT=2, UUID=6b30a63f-8e2a-445c-807f-c086fc77bd4e
    ```
5. On the other hand, if "Re-run all jobs" is picked instead of "Re-run failed jobs", the `prep` job actually runs and generates a new UUID:
    ```
    RUN-ATTEMPT=3, UUID=c1b645e4-baf4-4736-9fcc-bd89287096f1
    ```

**Expected behavior**
"Re-run failed jobs" is supposed to run the `prep` job as the failed job depends on it, which should result in a new UUID being generated.

## Runner Version and Platform
Version of your runner?  Github-hosted runner

OS of the machine running the runner? Github-hosted runner

## What's not working?
Dependent jobs are not being triggered during "Re-run failed jobs".

## Job Log Output
https://github.com/ashanka25/actions-rerun-deps/actions/runs/2541898253

## Runner and Worker's Diagnostic Logs
N/A
