### ISSUE TITLE
Reusing containers generated from prior jobs

### ISSUE THREAD

**Issue by chapmanjacobd** [actions/runner#1962]
**Describe the enhancement**
I would like to use an image generated in a prior job as a `job.*.container` input

**Code Snippet**

```yaml
name: pytest

on:
  push:
    branches-ignore:
      - main # it should already have ran before pushing to main

jobs:
  pull_image:
    name: Pull latest image as base
    runs-on: ubuntu-latest

    steps:
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_KEY_SANDBOX }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.PROJECT }}
          export_default_credentials: true

      - name: Pull
        run: |
          gcloud --quiet auth configure-docker
          docker pull $REMOTE_TAG
          docker tag $REMOTE_TAG local/dataprocessor

  test:
    needs: [pull_image]

    name: Pytest inside container
    runs-on: ubuntu-latest
    container:
      image: local/dataprocessor

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test with pytest
        run: pytest
```
