### ISSUE TITLE
Intermittent error: Docker Login failed with exit code 1 running jobs in container

### ISSUE THREAD

**Issue by rlinstorres** [actions/runner#1978]
**Describe the bug**
I am running a job in a [container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) using `self-hosted` runners and sometimes an error related to `docker login` occurs so we need to re-run the job again and everything works fine.

I know it can be related to my credentials but I have another job running `aws ecr get-login-password` command to get the token before this job below.

Note: I am using a private ECR.

My job:

```yaml
job_name:
    name: Job Name
    runs-on: self-hosted
    container:
      image: 12345678910.dkr.ecr.eu-west-1.amazonaws.com/ecr_name:tag
      credentials:
        username: AWS
        password:  ${{ secrets.password }}
```

**Expected behavior**

Run job without docker login error

## Runner Version and Platform

EKS version: `v1.22.9-eks-a64ea69`
Current runner version: '2.293.0'

## What's not working?

<img width="1020" alt="Screen Shot 2022-06-29 at 11 19 26 AM" src="https://user-images.githubusercontent.com/11336131/176401199-86e4c662-b2e9-4348-a4ad-15ae3e599449.png">

**Comment by rlinstorres** [comment]
> We faced a similar issue. We had a workflow that explicitly performed a login using the GITHUB_TOKEN. Example: ` - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin`
> 
> Since GITHUB_TOKEN is only valid for the duration of the action execution, on subsequent actions docker holds onto invalid credentials for ghcr.io.
> 
> The fix for us was to use https://github.com/docker/login-action which performs a docker logout at the end.

Hi @ksdc-andreo, thank you for your tip but I guess it is a different use case. Regarding this current error, it is related to the container service and there is no way to configure a `docker login` first to pull and execute the docker image as a service, we must pass the `username` and `password` together. Let me describe better my workflow making it clear.

```yaml
ecr_login:
    name: Login to ECR
    runs-on: self-hosted-runner
    steps:
      - uses: actions/checkout@v3
      - run: aws ecr get-login-password --region $AWS_REGION | gh secret set password
        env:
          ommited

container:
    name: Container
    needs: [ecr_login]
    runs-on: self-hosted-runner
    container:
      image: 12345678910.dkr.ecr.eu-west-1.amazonaws.com/ecr_name:tag
      credentials:
        username: AWS
        password:  ${{ secrets.password }}
```

**Comment by rsilva-rs** [comment]
@rlinstorres Adding to the proposed fix by @ksdc-andreo you may be facing an intermittent escaping or special char mismatch. Have you tried the following?
```yaml
- run: echo `(aws ecr get-login-password --region $AWS_REGION)` | gh secret set password
```

**Comment by rlinstorres** [comment]
> @rlinstorres Adding to the proposed fix by @ksdc-andreo you may be facing an intermittent escaping or special char mismatch. Have you tried the following?
> 
> ```yaml
> - run: echo `(aws ecr get-login-password --region $AWS_REGION)` | gh secret set password
> ```

I tried it but I am still having the same issue

**Comment by rlinstorres** [comment]
Hi, sorry about my delay in answering this issue but I was able to fix this error by creating a dedicated `schedule` workflow to handle the ECR token, like this:

```yaml
name: ecr-login-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */10 * * *'

env:
  AWS_REGION: value
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # it's needed for GH CLI

jobs:
  ecr_login:
    name: Login to ECR
    runs-on: self-hosted-runner
    steps:
      - uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          ...
          
      - run: echo `(aws ecr get-login-password --region ${{ env.AWS_REGION }})` | gh secret set ECR_PASSWORD
```

**Comment by tom-robo** [comment]
Hi, I have exactly the same issue. However, I have found that logging into to docker to access an image stored in a private AWS ECR registry does work with docker/login-action@v2

**Comment by tom-robo** [comment]
However, this does mean that I can't start a job inside a container (I can only launch containers, etc. as steps within a job).

**Comment by chandrakanthbala** [comment]
Hi, we are facing same issue with our self hosted runners. We have docker images in GHCR. We are seeing this issue intermittently (more often), but we are not able to reproduce this error on demand. Is there any resolution for this?

We are using runner version 2.292. Is this a runner software issue?

**Comment by nittendev** [comment]
We have the exact same issue as @chandrakanthbala. We've confirmed that we can login with the same username/token on the runner, etc. But the second we try to use a container in actions we get an exit code 1 on login.

**Comment by chandrakanthbala** [comment]
> We have the exact same issue as @chandrakanthbala. We've confirmed that we can login with the same username/token on the runner, etc. But the second we try to use a container in actions we get an exit code 1 on login. 

Hello 

For my issue, we are not able to find the root cause. But it got resolved itself after few days. We didn't apply any fix. And our issue is occurring intermittently. 

And if you are facing the issue constantly, can you check if you have assigned any permissions for the GITHUB_TOKEN? If we define permissions in workflow, we need to give ```packages: read``` for workflow to pull image. 

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

Thanks

**Comment by rlinstorres** [comment]
> Hi, sorry about my delay in answering this issue but I was able to fix this error by creating a dedicated `schedule` workflow to handle the ECR token, like this:
> 
> ```yaml
> name: ecr-login-schedule
> 
> on:
>   workflow_dispatch:
>   schedule:
>     - cron: '0 */10 * * *'
> 
> env:
>   AWS_REGION: value
>   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # it's needed for GH CLI
> 
> jobs:
>   ecr_login:
>     name: Login to ECR
>     runs-on: self-hosted-runner
>     steps:
>       - uses: actions/checkout@v3
>       
>       - uses: aws-actions/configure-aws-credentials@v1
>         with:
>           ...
>           
>       - run: echo `(aws ecr get-login-password --region ${{ env.AWS_REGION }})` | gh secret set ECR_PASSWORD
> ```

Hi, there!

In our case, we currently moved to this [solution](https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions#credentials) and it's working pretty well and stable.

```
permissions:
  id-token: write
  contents: read

jobs:
  login_to_ecr:
    name: Login to ECR
    runs-on: ubuntu-latest
    outputs:
      docker_username: ${{ steps.login-ecr.outputs.docker_username_ACCOUNT_ID_dkr_ecr_eu_west_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_ACCOUNT_ID_dkr_ecr_eu_west_1_amazonaws_com }}
    steps:
      - name: Setup AWS permissions
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: iam_role
          aws-region: region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: false
```

**Comment by jakobhyke** [comment]
Having the same issue. It seems the container launch cannot get any repository or environment secrets. 

```
container:
      image: ${{ vars.BASE_IMG }}
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

Hard-coding image-name and using {{github.actor}} works, but i cant find any way to use the appropriate password here.

Seems like a massive flaw, please fix asap
