### ISSUE TITLE
Colored output misaligned 

### ISSUE THREAD

**Issue by pasdam** [actions/runner#1990]
**Describe the bug**
When the output contains colored output, the text is misaligned when checking the workflow output on the GIthub website.

**To Reproduce**

I'm running a workflow similar to:

```yaml
name: 'CI'

on:
  push:

jobs:

  ci:
    name: 'Production'
    runs-on: [ self-hosted ]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Terraform Init
        working-directory: debug
        run: terraform init

      - name: debug
        working-directory: debug
        run: |
          terraform plan

```

The terraform doesn't really matter, but to reproduce it you can use this

```terraform
terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
      version = "3.1.1"
    }
  }
}

provider "null" {
  # Configuration options
}

resource "null_resource" "cluster" {
}
```

**Expected behavior**
Output aligned as per image:
<img width="377" alt="Screen Shot 2022-07-11 at 15 25 02" src="https://user-images.githubusercontent.com/11477201/178210572-495826bf-8828-4978-b4ef-af02e25a32bc.png">

## Runner Version and Platform
Version of your runner? `2.294.0`

OS of the machine running the runner? `Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1021-aws x86_64)`

## What's not working?
The output is misaligned.
<img width="405" alt="Screen Shot 2022-07-11 at 15 25 29" src="https://user-images.githubusercontent.com/11477201/178210654-4ebfb73b-b885-4ee9-8b85-aa8798dcc368.png">

The behavior changed in the last month or 2, before it was working fine.

## Job Log Output

```log
2022-07-11T07:00:37.4554782Z Terraform will perform the following actions:
2022-07-11T07:00:37.4554953Z 
2022-07-11T07:00:37.4555174Z [1m  # null_resource.cluster[0m will be created[0m[0m
2022-07-11T07:00:37.4555611Z [0m  [32m+[0m[0m resource "null_resource" "cluster" {
2022-07-11T07:00:37.4555962Z       [32m+[0m [0m[1m[0mid[0m[0m = (known after apply)
2022-07-11T07:00:37.4556189Z     }
2022-07-11T07:00:37.4556300Z 
2022-07-11T07:00:37.4556497Z [0m[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.
2022-07-11T07:00:37.4556748Z [0m[90m
```
