### ISSUE TITLE
IF conditions in step is ignored when called in a workflow_call

### ISSUE THREAD

**Issue by victor-chan-groundswell** [actions/runner#2005]
The workflow can be called from either a workflow_call or workflow_dispatch.  However, it seems that the step condition does not evaluate correctly when it's called from another workflow_call.  

For example, the workflow call is supposed to skip the slack notification if the environment input is 'dev'.  However, that step will fires, BUT when it is only called from a workflow_call.  When using a manual workflow_dispatch and making the right choice, the step skips, as intended.  I know that the ${{ github.event.inputs.environment || inputs.environment }} gets interpolated correct because i get a slack message that I do not want.
```yaml
name: Deployment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: false
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      environment:
        type: choice
        description: which environment
        options:
          - dev
          - stage
          - prod
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2
jobs:
  build-deploy-s3:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment }}
    env:
      CI: false
    steps:
      - name: Slack Notification
        if: ${{ github.event.inputs.environment || inputs.environment }} != 'dev'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: release
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: ${{ github.event.inputs.environment || inputs.environment }} Deployment started, branch ${{ github.event.inputs.branch || inputs.branch }}
          SLACK_TITLE: Message
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
```

What I am expecting:

On the slack notification step, if the environment input is 'dev', the step gets skipped.

What is happening:

If the called is called via a workflow, that logic doesn't work.  This logic works when I use workflow_dispatch to call the workflow directly.

**Comment by ihor-kanivets** [comment]
Hey @victor-chan-groundswell. I was looking for the same issue and looks like I found a working solution.

So first I tried to use the next condition:

```
- name: External-DNS Secrets PASSMAN
  if: contains( "${{ inputs.cluster }}", "cluster_name" )
   run: |
     echo "CLUSTER IS:"
     echo "${{ inputs.cluster }}"
```
It didn't work for me in the same way as you mentioned. During the debug process I tried the next approach:

```
- name: External-DNS Secrets PASSMAN
   if: ${{ contains(inputs.cluster, 'passman') }}
   run: |
     echo "CLUSTER IS:"
     echo "${{ inputs.cluster }}"
```

And it started to work. So I propose you try the next: replace `if: ${{ github.event.inputs.environment || inputs.environment }} != 'dev'` with something like that `if: ${{ github.event.inputs.environment != 'dev'  || inputs.environment != 'dev' }}`

Hope it will help you.

**Comment by tla** [comment]
I am having a very similar issue to this. The workflow in question only gets called, so I can't easily verify whether this exact definition would work with dispatch, but I can say that before I turned this into a reusable workflow it was working as intended on dispatch with essentially the same content. The workflow looks like this:

```
name: T-PEN backup and collate
on:
  workflow_call:
    inputs:
      forceCollate:
        description: "Whether or not to run the full collation process if no transcriptions changed"
        required: false
        type: boolean
        default: false
      [...]


jobs:
  create-tei-files:
    runs-on: [self-hosted, Linux]
    container:
      image: ghcr.io/dhuniwien/edition-tools
    # We want to know whether any relevant Github files changed as a result of this job
    outputs:
      filesChanged: ${{ steps.commitstep.outputs.committed }}
    steps:
    - [...]
    - name: Commit and push all updates
      id: commitstep
      uses: EndBug/add-and-commit@v9
      with:
        add: 'transcription/*.json transcription/tei-xml/*.xml'
        message: 'Daily T-PEN backup automagick'

  validate-tei-xml:
    needs: create-tei-files
    if: needs.create-tei-files.outputs.filesChanged || inputs.forceCollate
    [...]
```

I have verified in the workflow run log that forceCollate was passed as an input (set to false), and the create-tei-files job returned filesChanged as an output with a false value. And yet the validate-tei-xml job (and its dependent) runs when it shouldn't. 

Is there anything I can do to get this to work in the meantime?
