### ISSUE TITLE
Bug in strategy-matrix construct. Python version 3.10 is being treated as 3.1 instead.

### ISSUE THREAD

**Issue by diningPhilosopher64** [actions/runner#2015]
**Describe the bug**
Python version stored as a variable in the strategy-matrix construct is converting Python 3.10 to 3.1

<br/>

**To Reproduce**
1. In a github repository and a new workflow with the following code
```yaml
name: Testing strategy matrix in github actions

on:
  push:
    branches:
      - "main"

jobs:
  python_tests:
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        python-version: [3,6, 3,7, 3,8, 3.9, 3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install .[dev]


# Removed other jobs for brevity
```

**Expected behavior**
The python versions that are supposed to used for running the `python_tests` job are  3.6, 3.7, 3.8, 3.9 and `3.10`. 

## Runner Version and Platform
Version of your runner?
Github actions default runner provided by github

OS of the machine running the runner? OSX/Windows/Linux/...
The `ubuntu-latest` OS provided by github actions.

## What's not working?
Python version `3.10` is being converted/ treated as `3.1`

The Screenshot from the GH actions:
![image](https://user-images.githubusercontent.com/12293878/180410582-1e8380d6-da42-46ca-8edb-08d7add1a40c.png)

Graphical layout of the same:
![image](https://user-images.githubusercontent.com/12293878/180410983-bfa81734-aa35-4329-b469-c7c8a4334059.png)

## Temporary Workaround
As a temporary workaround, instead of specifying it as `3.10`, I've used `3.10.x` which has solved the issue.

This is how it looks like in workflow file:
```yaml
name: Testing strategy matrix in github actions

on:
  push:
    branches:
      - "main"

jobs:
  python_tests:
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        python-version: [3,6, 3,7, 3,8, 3.9, 3.10.x]   # UPDATING TO 3.10.x FROM 3.10 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install .[dev]


# Removed other jobs for brevity
```

This would make github actions pick the intended python version and run as expected:
![image](https://user-images.githubusercontent.com/12293878/180411677-21aa4d1c-1591-470c-8bb5-5ba0fba2b267.png)

As a graphical representation of the same:
![image](https://user-images.githubusercontent.com/12293878/180411853-127fcaf5-caef-457d-8dee-85bf166b18bf.png)
