### ISSUE TITLE
git config safe.directory inside docker containers

### ISSUE THREAD

**Issue by EdJoPaTo** [actions/runner#2033]
**Describe the bug**

Recent versions of git require the `.git` folder to be owned by the same user. (as described [here](https://github.blog/2022-04-12-git-security-vulnerability-announced/)).

the `actions/checkout` action sets this for the cloned repo (`/usr/bin/git config --global --add safe.directory …`).

Running a container (via `uses: docker://…`) however switches the user context and all git commands will fail with an error:

```plaintext
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

Inspecting the `docker run` command the `HOME` variable is set and the home inside the container seems to be `/github/home` which is mapped to `/home/runner/work/_temp/_github_home`.
Creating the `.gitconfig` in this location before running the container resolves this problem:

```yaml
- name: Fix git safe.directory in container
  run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
```

As these paths (`HOME` and `PWD` inside the container) are not stable and can be changed any time, the `git config …` logic should be done by the runner executing the docker command as its the only part in the process knowing these paths.

I do not think this is related to the images as the `uses: docker://` logic is handled by the runner itself?

**To Reproduce**

Create this minimal workflow and let it run

```yaml
on:
  push:

jobs:
  fails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker://docker.io/library/alpine:3.14
        with:
          entrypoint: /bin/ash
          args: -c "apk add git && git status"
```

(See above for the error message of the git command)

**Expected behavior**

The container should have a `.gitconfig` to run git commands normally like it is possible without container.
Stuff like the `.git` folder is mounted to the container too so a user can expect git to work fine.

## Runner Version and Platform
Version of your runner? Hosted Runners on GitHub

**Comment by nikola-jokic** [comment]
Hi @EdJoPaTo,

Thank you for reporting this so clearly! I have applied appropriate labels and added this issue to the backlog :relaxed:

**Comment by mefistotelis** [comment]
Got the same issue, though in different scenario. My workaround was to just change owner of the directory after checkout:

```
jobs:
  ubuntu-gcc:
    runs-on: ubuntu-20.04
    name: "Linux Ubuntu"
    container:
      image: ubuntu:20.04
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - name: Install GIT
        run: |
          # install GIT, as without it checkout would use REST API
          apt update
          apt install -y \
            git

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
```

**Comment by DanRStevens** [comment]
I've also encountered this issue when running my Docker images on GitHub Actions, and have been able to reproduce while running my container locally.

This seems to be more generally a problem with running a Docker container as the root user, while having data mounted for a regular user account. When testing locally, I can start my Docker container by adding the flag `--user="$(id --user):$(id --group)"` to the `docker run` command, and the error won't be shown. As an added bonus, any output generated by the build in the Docker container and written to the mounted folder will end up having correct ownership on the host system once I've exited the Docker container.

**Comment by SeanKilleen** [comment]
Hi all,

I'm trying to wrap my head around this a little better and I think I have a minimal repro that will allow someone to hopefully explain it to me.

I've got [a Dockerfile](https://github.com/nunit/docfx-action/blob/master/Dockerfile) for a GitHub action that is essentially: 

```docker
FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy

# Setting the path up to allow .NET tools
ENV PATH "$PATH:/root/.dotnet/tools"

RUN dotnet tool install --global docfx --version 2.60.0-preview.2

ENTRYPOINT [ "docfx" ]
```

And then in [our GitHub Action that I'm testing in a PR](https://github.com/nunit/docs/blob/ce46eda01897399e59f154135b93876ff1f8ec05/.github/workflows/build-process.yml): 

```yaml
...(other)...
  build:
    name: "Build the site with docfx"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: "nunit/docfx-action@v2.0.0-preview.1"
        name: Build with Docfx
        with:
          args: docs/docfx.json --warningsAsErrors true

...(other)...
```

When this build runs, I see the error about dubious ownership.

It sounds like the options I have here are:

* Try to run a command that marks a path as safe somewhere
* Try to modify the ownership of files at build time
* (or something else I'm not understanding).

In this case, what is the appropriate option for me to choose? I own the docfx-action container and so I can make the change there or if it's simpler I can make the change in my build process and advise others to do so. I'm just not sure if the best approach. Any help is appreciated!

**Comment by melroyvandenberg** [comment]
I think GitHub Action runners should use the git version from the host to avoid regression randomly.

Also, I think when using Docker images, GitHub Action should use the runner **user** (eg. `runner` user) ID/ group ID. Even if this UID or GID doesn't exists within the context of the Docker image.

**Comment by augustfengd** [comment]
I updated git (`3.36+`) in my container image so I could live dangerously: `git -c safe.directory='*' rev-parse --show-toplevel`.

:grin:.

**Comment by ervinb** [comment]
When running [jobs in a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container), the solution is to use the [`runner` user](https://github.com/actions/runner/blob/8415f13babf8199551f817eb16b718dcdd5b31e2/images/Dockerfile#L38) when starting the container:

```yaml
jobs:
  setup:
    runs-on: int-runner-set
    container:
      image: ci-image:v1.0.0
      options: --user 1001
 ...
```
