### ISSUE TITLE
`needs` is ignored for reusable workflows

### ISSUE THREAD

**Issue by ascott18** [actions/runner#2039]
**Describe the bug**

When you have a top-level workflow that invokes two reusable workflows, and you want those two reusable workflows to be executed serially, placing `needs: jobOne` on `jobTwo` is silently ignored and both workflows are executed in parallel.

**To Reproduce**

``` yml
jobs:
  jobOne:
    uses: ./.github/workflows/some-reusable-workflow.yml
    secrets: inherit

  jobTwo:
    uses: ./.github/workflows/some-other-reusable-workflow.yml
    needs: jobOne
    secrets: inherit
```

**Expected behavior**
`needs` is respected in this scenario. Or, at the very least is not silently ignored but instead generates a validation error.

## Runner Version and Platform
Hosted Github Actions 

## What's not working?
This definition:
``` yml
jobs:
  build:
    uses: ./.github/workflows/part-build.yml
    secrets: inherit
    with:
      prereleaseSlug: alpha

  publish:
    if: success() && github.event_name == 'push'
    uses: ./.github/workflows/part-publish.yml
    needs: build
    secrets: inherit
``` 

Is producing this run:
![image](https://user-images.githubusercontent.com/5017521/182916295-70af8e82-25e0-45ee-aec6-5db308bf48a8.png)

Whereas it should be doing this:
![image](https://user-images.githubusercontent.com/5017521/182916396-59c533d7-f518-4c63-8448-9be41e1986c8.png)
