### ISSUE TITLE
Allow "list" as the default value type for "choice"

### ISSUE THREAD

**Issue by stas-sbi** [actions/runner#2047]
**Describe the enhancement**
Allow "array" as the default value type for "choice"

**Code Snippet**
```yaml
on:
  workflow_dispatch:
    inputs:
      target:
        description: Deploy to
        default: [dev, canary]    # This is not allowed at the moment
        type: choice
        options:
        - [dev, test1]
        - [dev, test2]
        - [dev, canary]
```

**Additional information**
It is possible to define `options` for `choice` as arrays however it is not possible to set the default as array. Actions complain about wrong type. Can this be changed?

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md
