### ISSUE TITLE
hashFiles returns different hash for Windows and Linux

### ISSUE THREAD

**Issue by cesar-ibr** [actions/runner#2071]
**Describe the bug**
`hasFiles` returns different hash in Windows than in Linux. This is problematic if you have a one job running on Windows and one job running on Linux and you need consistent hashes generated from the same file. The problem might be caused for the differences of `EOL`  characters in both OS.

**To Reproduce**
1. Create a folder and init NPM
2. Install dependencies (e.g: *react*)
5. Use *Cache Action* with the key: `app-cache-build-${{ hashFiles('./package-lock.json') }}`
6. See that the `key` is different in Windows than Linux

Example Workflow:
```yml
name: Example
on: push
jobs:
    build_app:
        name: Build App
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Use Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 16

          - name: Install Dependencies
            run: npm install

          - name: Build App
            run: npm run build

          - name: Cache App Build
            uses: actions/cache@v3
            with:
              path: dist
              key: app-cache-build-${{ hashFiles('./package-lock.json') }}

    win_artifact:
        name: Build Windows Artifact
        runs-on: windows-latest
        needs: build_app
        steps:
          - uses: actions/checkout@v3

          - name: Use Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 16

          - name: Install Dependencies
            run: npm install

          - name: Get Cached App Build
            uses: actions/cache@v3
            with:
              path: dist
              key: app-cache-build-${{ hashFiles('./package-lock.json') }}

```

Output:

```
# jobs -> build_app -> Post Cache App Build
Post job cleanup.
Cache Size: ~15 MB (16035418 B)
Cache saved successfully
Cache saved with key: app-cache-build-43a072
```

```
# jobs -> win_artifact -> Get Cached App Build
Run actions/cache@v3
  with:
    path: packages/train.gl/dist
    key: app-cache-build-e7a8bb
Cache not found for input keys: app-cache-build-e7a8bb
```

**Expected behavior**
The hash returned by `hashFiles` should be the same in Linux and Windows

## Runner Version and Platform
Runner version: '2.295.0'
OS: Ubuntu 20.04.4 LTS

Runner version: '2.295.0'
OS: Microsoft Windows Server 2022 10.0.20348 Datacenter

## What's not working?
The generated hash are different in Linux and Windows therefore the cache key is different and the cache is not found in Windows.

## Job Log Output
n/a

## Runner and Worker's Diagnostic Logs
n/a

**Comment by nikola-jokic** [comment]
Hey @cesar-ibr,

Can you please confirm that `npm install` produces the same `package-lock.json` file when executed on Windows machine and on Linux machine? See [Stack Overflow Comment.](https://stackoverflow.com/a/48086845) :relaxed:

**Comment by cesar-ibr** [comment]
Hey @nikola-jokic,
Just a small **update**: I tested it out using **yarn v1** instead on npm.  The issue remains the same, even without running `yarn install` in a clean setup. Here's a minimal configuration that I use for testing:

```yml
name: Test CI Cache

env:
  nodeJs: '16.13.0'
  CACHE_DIR: packages/docs
  CACHE_KEY: app-cache

defaults:
  run:
    working-directory: ./packages

on:
  pull_request:
    branches: [main, master]

jobs:
  cache-ubuntu:
    name: Build Cache
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v${{ env.nodeJs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeJs }}

      - name: Save Cache
        uses: actions/cache@v3
        env:
          CACHE_KEY: ${{ env.CACHE_KEY }}-build-${{ hashFiles('**/yarn.lock') }}
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ env.CACHE_KEY }}

  cache-win:
    name: Use Cache
    runs-on: windows-latest
    needs: cache-ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v${{ env.nodeJs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeJs }}

      - name: Get Cache
        uses: actions/cache@v3
        env:
          CACHE_KEY: ${{ env.CACHE_KEY }}-build-${{ hashFiles('**/yarn.lock') }}
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ env.CACHE_KEY }}

```

Outputs:

```
# job: cache-ubuntu
# step: Save Cache
---
Run actions/cache@v3
  with:
    path: packages/train.gl/docs
    key: app-cache-build-3947762920e055e51e1402454d328f84cc1f80cd7cf2b7fe8daee70def8adfa2
  env:
    nodeJs: 16.13.0
    CACHE_DIR: packages/train.gl/docs
    CACHE_KEY: app-cache-build-3947762920e055e51e1402454d328f84cc1f80cd7cf2b7fe8daee70def8adfa2
Cache not found for input keys: app-cache-build-3947762920e055e51e1402454d328f84cc1f80cd7cf2b7fe8daee70def8adfa2
```

```
# job: cache-win
# step: Get Cache
---
Run actions/cache@v3
  with:
    path: packages/train.gl/docs
    key: app-cache-build-bd517c25e3abf46a64ee6221aea2dffeebef7bc2f43c59615948aecd1a033161
  env:
    nodeJs: 16.13.0
    CACHE_DIR: packages/train.gl/docs
    CACHE_KEY: app-cache-build-bd517c25e3abf46a64ee6221aea2dffeebef7bc2f43c59615948aecd1a033161
```

### Results

On Ubuntu `hashFiles('**/yarn.lock')` returns `394776...`
On Windows `hashFiles('**/yarn.lock')` returns `bd517c...`

**Comment by nikola-jokic** [comment]
Hey @cesar-ibr,

Can you please look at the diffs between those files? I cannot reproduce this issue without the package.json dependencies, but I guess that might not be an ideal thing to post here.

Hash can differ if contents of those files differ, so I am just trying to figure out if some transitive dependencies exist when you run build. One system may pull some transitive dependencies differently than the other, which causes package.lock or yarn.lock to be different. That can explain having different hash values

**Comment by cesar-ibr** [comment]
I was able to replicate the issue in a public repository: https://github.com/cesar-ibr/cesarsan/actions/runs/3015787354.

> Notice there are no `yarn` commands in the jobs

### GHA Configuration

```yml
name: Test CI Hash

env:
  nodeJs: '16.13.0'
  YARN_HASH: build

on:
  pull_request:
    branches: [main]

jobs:
  cache-ubuntu:
    name: Generate Hash (ubuntu)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Hash
        env:
          YARN_HASH: yarn-hash-${{ hashFiles('**/yarn.lock') }}
        run: echo $YARN_HASH

  cache-win:
    name: Generate Hash (windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Hash
        env:
          YARN_HASH: yarn-hash-${{ hashFiles('**/yarn.lock') }}
        run: echo $env:YARN_HASH

```
### GHA Output

```
# Generate Hash (ubuntu) -> Get Hash
> yarn-hash-8768706a98da1a4b331b9f0587530b33e6dcb1c0d7c21fc05c0a83c3a19b05ad
```

```
# Generate Hash (windows) -> Get Hash
> yarn-hash-a9b684892d413ed990c912590a11a85c061e80621275a3cd3195e05ce0bd1f8b
```

**Comment by nikola-jokic** [comment]
Hey @cesar-ibr, sorry for the late response. I am pretty sure that the reason for that is the difference between file formatting on Linux and Windows. Windows systems end lines with `\r\n` while Linux ends line with `\n`. 
I have checked the hex dump of files and that is how I figured it out.

**Comment by nikola-jokic** [comment]
I will close this issue now since this is expected behaviour. The purpose of `hashFiles` is to calculate sha256, and since contents are different, the result will be different. I just hope this is not causing you too much trouble :disappointed:

**Comment by cesar-ibr** [comment]
Can we at least mention this behaviour in the docs?

**Comment by Daggron** [comment]
Hey @flobernd @nikola-jokic , I am also facing this issue and I am not even using diff OS, I have two jobs setup, The first job install and caches the node_modules and then second job tries to bring those cached node_modules.

In My case both the jobs are using Linux system but still the sha is being generated differently for the same `package-lock` file.


JOB 1

```
- name: Cache node modules
        id: cache-base-dir
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
```

SHA generated in this `209714e00819ce8d5b477bef0c55fc134221fdb2290bdc7c65d95a366fc2e14c`

JOB 2
```
 - name: bring in cache
        id: cache-base-dir
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
```

SHA generated in this case is `76c158d411265620f02e297cd804574c661f6b86a0fb22a204d750cfa4e23ca2`
