### ISSUE TITLE
Masking an output from  another action

### ISSUE THREAD

**Issue by limistah** [actions/runner#2075]
It would be useful to have support masking responses from runners.

In the workflow below, I am pulling secrets from onboardbase, and want to output it to the console.

By default, this would log the exact value which is a secret from onboardbase.

```
name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v6.0.7
        with:
          apikey: ${{secrets.APIKEY}}
          passcode: ${{secrets.PASSCODE}}
          project: test_project
          environment: development

      - name: Use secrets
        # Output should be: The secret value is: https://test.com
        run: "echo 'The secret value is: $(echo ::add-mask::${{ steps.fetch-secrets.outputs.REDIS_HOST }})'"
```

The result of the action can be seen here: https://github.com/Onboardbase/onboardbase-action/runs/7676711424?check_suite_focus=true 
![image](https://user-images.githubusercontent.com/30846935/185956793-25f21e93-0cef-4e3f-a74a-70ff185da286.png)
