### ISSUE TITLE
Can't exclude included matrix jobs

### ISSUE THREAD

**Issue by exsesx** [actions/runner#2111]
**Describe the bug**
I'm using the "include" syntax to build multiple services (in this case, two). Is there any way to exclude some of them? I was thinking about adding the `build` boolean flag and then checking it. I could've just added `if` to my job, but I don't think it's clean.

```yml
strategy:
      fail-fast: false
      matrix:
        include:
          - service: my-service-1
            repository: string
            executor: string
            # build: false

          - service: my-service-2
            repository: string
            executor: string
            # build: true

          - ...
            
        exclude:
          # - build: false # doesn't work
```

**To Reproduce**
1. Use GHA snippet above
2. See error: `Matrix exclude key 'build' does not match any key within the matrix`

**Expected behavior**

## Runner Version and Platform
Latest.

OS of the machine running the runner? `ubuntu-latest`

## What's not working?
I expected some of the matrix jobs to be excluded, but I got an error.
