### ISSUE TITLE
Offer `split()` expression function as a pair for `join()`

### ISSUE THREAD

**Issue by jsoref** [actions/runner#2125]
**Describe the enhancement**
Provide an expression function `split()` as a pair to [`join()`](https://docs.github.com/en/actions/learn-github-actions/expressions#join)

**Code Snippet**
```yaml
name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ${{split(github.event.inputs.os, ' ')}}
    steps:
      - run: build
```

**Additional information**
This is based on PowerDNS/pdns#11960 and would greatly simplify:
https://github.com/PowerDNS/pdns/blob/d41e087ca092ff60f9fc79e177f8a61bfdffd1f9/.github/workflows/builder-dispatch.yml#L38-L55

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by flobernd** [comment]
I think this is not a runner feature but belongs to the "act" repository instead.

Other than that, I would love to have this feature as well. Especially as it's current not possible to pass array/list arguments to actions/reusable Workflows.

**Comment by jsoref** [comment]
`act` is an alternate implementation of `runner`. I definitely want it here (and then it'd have to be implemented there).

**Comment by cschleiden** [comment]
While a `split` function might make sense, for this scenario you could also accept the operating systems comma-delimited in your `inputs` and using something like:

```yaml
matrix:
  os: ${{ fromJson(format('[{0}]', inputs.os)) }}
```

to expand them to an array.

**Comment by ericsciple** [comment]
Interesting to note, the proposed solution is a workaround related to a limitation in workflow dispatch inputs. Wondering whether a change to workflow dispatch inputs would be a better solution.

**Comment by Habbie** [comment]
> Interesting to note, the proposed solution is a workaround related to a limitation in workflow dispatch inputs. Wondering whether a change to workflow dispatch inputs would be a better solution.

That would definitely work for me too.

**Comment by ericsciple** [comment]
@jsoref for this particular scenario, have you considered multiple boolean inputs that feed into job `if` conditions?

For example:

```yaml
on:
  workflow_dispatch:
    inputs:
      release-linux:
        type: boolean
      release-mac:
        type: boolean
      release-win:
        type: boolean
jobs:
  release-linux:
    if: ${{ inputs.release-linux }}
    uses: ./.github/workflows/release.yml
    with:
      runs-on: ubuntu-latest
  release-mac:
    if: ${{ inputs.release-mac }}
    uses: ./.github/workflows/release.yml
    with:
      runs-on: macos-latest
  release-win:
    if: ${{ inputs.release-win }}
    uses: ./.github/workflows/release.yml
    with:
      runs-on: windows-latest
```

**Comment by Habbie** [comment]
The job is actually mine - I nerdsniped @jsoref into realising `split()` would be neat here, and filing this ticket. The booleans would work, but are quite verbose. I would rather stick to some hack than go that verbose :)

**Comment by cschleiden** [comment]
> That looks like it would lack quotes around the individual entries, or am I missing something?

You would have to add those, yes. So input something like `"linux","windows 95","windows me"` when triggering the `workflow_dispatch` run.

**Comment by Habbie** [comment]
> You would have to add those, yes. So input something like `"linux","windows 95","windows me"` when triggering the `workflow_dispatch` run.

Understood - at that point the user might as well type actual JSON I think.

**Comment by jsoref** [comment]
I think the lack of a `split()` to match `join()` is an easy to recognize deficiency. 

Compare [`toJSON`](https://docs.github.com/en/actions/learn-github-actions/expressions#tojson) / [`fromJSON`](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson)

**Comment by fhammerl** [comment]
Hello, I wanted to give an update on this.

So personally, I really like the idea as a usability upgrade. Sadly though, we can't make this change in the runner at this time.

Regarding changes to how we parse yaml files, we normally receive from an upstream source (people working on the 'yaml parser'). The reason for this structure is that some yaml files are parsed by the runner (action.yml), but some (workflow.yml) are parsed server side.

I've forwarded this to the team working on the 'yaml parser'. We agree that `split()` would round out the functionality of `join()` nicely.

Normally, I would recommend to post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site, but this has already generated some internal attention so I'd say it's unnecessary at this point.

I'm closing the issue as this won't be resolved with a runner PR but rather with a dependency update down the line.

**Comment by timor-raiman** [comment]
+1

**Comment by paulohgodinho** [comment]
This is a feature request that "generated some internal attention" and it is dead for over a year. I am sure the entire Actions side of this site is run by a skeleton crew.

**Comment by jsoref** [comment]
@paulohgodinho: I don't think you're entirely wrong, but in this case, I think it's a bit worse, in that the upstream of the Runner is the thing with the skeleton crew.

Sadly, based on the response, I'm fairly certain the components aren't things we can touch -- my guess is that there are multiple implementations in various languages that would have to be changed at the same time, along with a fairly strong test suite.

**Comment by paulohgodinho** [comment]
@jsoref if the entire thing was open source we could fix and add so many things by ourselves, it is not fair to demand things from open source, but in this case they are consciously blocking us from helping, it all feeds to the irony of Github itself not being open source.

I really wish I could contribute to this, I like how actions work and I think there is a solid base to grow, but right now it is barebones and lackluster. I heard of on premisses colleagues having some luck customizing and improving it, but us using the default cloud offering are stuck.

**Comment by gisheri** [comment]
+1

There are situations without a workaround. At least, not one I can find. In my case accessing a specific segment of the ref (the pr number in the generated ref of a merge group event) to set as the concurrency group so I can canel in-progress merge queue checks when they are re-run

**Comment by jsoref** [comment]
@gisheri: you can work around this by adding an intermediate job (it's painful, and costs time=money):

```yaml
name: build
on: push
jobs:
  get-os:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.os.outputs.os_array }}
    steps:
    - id: os
      env:
        os_list: ${{ github.event.inputs.os }}
      run:
        echo "os_array=[$(echo "$os_list" | tr ' ' ',')]" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: get-os
    strategy:
      matrix:
        os: ${{ fromJSON(needs.get-os.outputs.os) }}
    steps:
      - run: build
```

(This code is untested, but it's a rough outline. -- The point is that people shouldn't have to cookie-cutter and risk a bad job of it code like this.)

**Comment by peilinok** [comment]
> [@gisheri](https://github.com/gisheri): you can work around this by adding an intermediate job (it's painful, and costs time=money):
> 
> name: build
> on: push
> jobs:
>   get-os:
>     runs-on: ubuntu-latest
>     outputs:
>       os: ${{ steps.os.outputs.os_array }}
>     steps:
>     - id: os
>       env:
>         os_list: ${{ github.event.inputs.os }}
>       run:
>         echo "os_array=[$(echo "$os_list" | tr ' ' ',')]" >> "$GITHUB_OUTPUT"
> 
>   build:
>     runs-on: ubuntu-latest
>     needs: get-os
>     strategy:
>       matrix:
>         os: ${{ fromJSON(needs.get-os.outputs.os) }}
>     steps:
>       - run: build
> (This code is untested, but it's a rough outline. -- The point is that people shouldn't have to cookie-cutter and risk a bad job of it code like this.)

This works fine for me

```
jobs:
  split-platforms:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.split-platforms.outputs.platforms }}
    steps:
      - id: split-platforms
        env:
          target_platforms: ${{ inputs.target_platforms }}
        run: |
          platforms=$(echo "$target_platforms" | sed 's/ //g' | tr ',' '\n' | sort -u | sed '/^$/d' | jq -R -s -c 'split("\n")[:-1]')
          echo "platforms=$platforms" >> $GITHUB_OUTPUT

  build:
    runs-on: ${{ matrix.os }}
    needs: split-platforms
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        platform: ${{ fromJson(needs.split-platforms.outputs.platforms) }}
```
