### ISSUE TITLE
Cache receiving stalled

### ISSUE THREAD

**Issue by mobigroup** [actions/runner#2146]
The same log line repeating indefinitely for 40+ minutes:
```Received 1653791515 of 1662180123 (99.5%)```

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/7342379/191427716-7e5aaea9-acba-4c4d-84f0-7446aa56c8e8.png">

```
    - name: Cache dataset
      uses: actions/cache@v3
      with:
        path: tests/S1A_Stack_CPGF_T173.tar.gz
        key: S1A_Stack_CPGF_T173.tar.gz
        restore-keys: S1A_Stack_CPGF_T173
```

This is the link to the job: https://github.com/mobigroup/gmtsar/actions/runs/3095306955/jobs/5009583727
