### ISSUE TITLE
Add env context to jobs.<job_id>.env 

### ISSUE THREAD

**Issue by zasaleh** [actions/runner#2170]
**Describe the enhancement**
The env context would be very helpful if it is accessible from `jobs.<job_id>.env`

**Code Snippet**
```
jobs:
  build-push:
    env:  
      tags: ${{ format('{0}/{1}/{2}:{4}', env.GCR, env.PROJ_NAME, env.APP_NAME, env.SHA) }}
```

**Additional information**
When I tried the above feature it failed with `Unrecognized named-value: 'env'` which is expected as the 
jobs.<job_id>.env | Have those contexts only => | github, needs, strategy, matrix, secrets, inputs
