### ISSUE TITLE
github.action_path contains wrong path when used inside a container

### ISSUE THREAD

**Issue by WIStudent** [actions/runner#2185]
**Describe the bug**
When using `${{ github.action_path }}` inside a local composite action and calling this action in a job that runs inside a container, `${{ github.action_path }}` gets resolved to `/home/runner/work/ga-test-public/ga-test-public/./.github/actions/repro` instead of `/__w/ga-test-public/ga-test-public/./.github/actions/repro`.

There are other closed issues describing the same problem (https://github.com/actions/runner/issues/716, https://github.com/actions/runner/issues/965) and a merged pull request (https://github.com/actions/runner/pull/1762) that should have fixed the issue, but I am still getting the wrong path on GitHub shared runners with version 2.297.0

**To Reproduce**
Here is a [reproduction repo](https://github.com/WIStudent/ga-test-public) and a [workflow run](https://github.com/WIStudent/ga-test-public/actions/runs/3197544889/jobs/5220901026) with the mentioned issue.

```yml
# .github/workflow/test.yml
name: Reploduce the bug

on: 
  push: {}
  workflow_dispatch: {}

jobs:
  bug-in-container:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/repro

      - run: echo runner.temp = ${{ runner.temp }}
      - run: ls -al ${{ runner.temp }} || true

      - run: echo runner.tool_cache = ${{ runner.tool_cache }}
      - run: ls -al ${{ runner.tool_cache }} || true
```
```yml
# .github/actions/repo/action.yml
name: 'Reproduce the bug'
description: ''
inputs: {}
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo github.action_path: ${{ github.action_path }}
        ls -al ${{ github.action_path }} || true
```

**Expected behavior**
`${{ github.action_path }}` should be resolved to a path inside the container, not to a path on the host machine.

## Runner Version and Platform
GitHub shared runner version 2.297.0

## What's not working?
![grafik](https://user-images.githubusercontent.com/2707930/194333103-96b613b3-a1c9-45b0-a04e-05814fd52215.png)

**Comment by abhijeetdhoke** [comment]
> 
What is end result in .yml file how to implement this change to .yml file

**Comment by MSAdministrator** [comment]
Has there been any updates to this issue? This is blocking some internal workflows.

**Comment by nikola-jokic** [comment]
Hey @MSAdministrator,

This [PR](https://github.com/actions/runner/pull/2517) is in review and as soon as it is in, and the feature flag is on, then it should be okay.
Until then, can you try passing actions_path as an env. Env variables are translated so container paths so it should be okay if you can use it :relaxed:

**Comment by nikola-jokic** [comment]
We merged the PR so the next release should have this functionality :relaxed: . We also have a feature flag in case something goes wrong

**Comment by BitProcessor** [comment]
For anyone struggling with this:

Let's say you created a custom action with a script, with the script called `run.sh` and residing in the root of the action.

```
runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      run: ${GITHUB_ACTION_PATH}/run.sh
```

That will get it to work if you are running your build inside a container.
