### ISSUE TITLE
HOME dir are being share between job for Self hosted Docker Runner

### ISSUE THREAD

**Issue by vuonghoainam** [actions/runner#2193]
**Describe the bug**
Hi, let's say I have this job:
```yaml
  # Test on ARM using docker containers
  test_arm_linux:
    needs: sanityCheck
    runs-on: self-hosted-arm-linux
    container: 
      image: ${{ matrix.docker-image }}
    strategy:
      fail-fast: false
      matrix:
        docker-image: ['python:3.8-bullseye', 'python:3.9-bullseye']

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.1.6 python3 -
          echo "/github/home/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest
```
Then will create 2 job like this:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/22463238/194933260-f5645942-561d-4348-a3cb-56b2d02a31b3.png">

One will run first and finish everything. The second run and then at step "Install Poetry" it see that oh poetry are already installed and dynamically linked to a python3.9 binary (from the last successful run) but will fail to run since the current container only have python3.8.

By investigating the log. I can see that some how the same home directory are being shared between 2 of these job. Even when one was completed. This is plain wrong ! 

Then I went and rerun the workflow again and see that the last successful run (the 3.9 one) to have the old home directory from the last run cached and don't actually run anything. Why is this the case ? I don't even use any caching feature, nor do I explicitly set a shared mount volume for both run ??

**Expected behavior**
No HOME dir are being share between any job nor being share between any runs as well.

## Runner Version and Platform
2.297.0 - Linux - ARM

## Job Log Output
Please refer to an actual failed run logs: https://github.com/h1st-ai/h1st/actions/runs/3221385204
