### ISSUE TITLE
Ubuntu images not sourcing ~/.bashrc

### ISSUE THREAD

**Issue by sidekick-eimantas** [actions/runner#2194]
**Describe the bug**
~/.bashrc is not being sourced

**To Reproduce**
1. Run the following workflow:
```yml
name: debug
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  debug:
    runs-on: "ubuntu-22.04"

    steps:
      - run: echo "echo SOURCED" > ~/.bashrc
      - run: ls
```

**Expected behavior**
At all steps ~/.bashrc should be sourced and at 2nd step `SOURCED` should be echoed and appear in the logs, as its in the ~/.bashrc file

## Runner Version and Platform
ubuntu-22.04

## What's not working?
~/.bashrc is not being sourced

This issue is not present in macos images, ~/.bashrc is being sourced correctly.
