### ISSUE TITLE
Runner context non available in expression in jobs.<job_id>.env

### ISSUE THREAD

**Issue by rdeago** [actions/runner#2204]
**Describe the bug**

Using the `runner` context inside an expression to set an environment variable leads to an "Unrecognized named-value: runner" error.

**To Reproduce**

1. Fork my minimal repro repository https://github.com/rdeago/runner-context-test
2. In your fork's Actions tab, select the "Test availability of runner context" workflow
3. Run the workflow

For reference, here's the workflow file:

```yaml
name: "Test availability of runner context"

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FOOBAR: ${{ runner.debug == '1' && 'foo' || 'bar' }}
    steps:
    - name: Show results
      run: echo $FOOBAR
```

I borrowed the expression syntax from [this answer on community discussions](https://github.com/orgs/community/discussions/27627#discussioncomment-3302259). According to the linked thread, it worked fine as of last July / August.

**Expected behavior**

The workflow runs and the log shows the string `bar` in console output.

## Runner Version and Platform

Version of your runner? 2.298.2

OS of the machine running the runner? Ubuntu Linux 20.04.5 LTS

## What's not working?

The workflow does not start.

![Workflow startup failure](https://user-images.githubusercontent.com/139223/195791201-69286075-9b0b-4331-a56e-a9d9152b1daa.png)

Re-running the workflow, with or without debug logging, yields the same result as above.

[Here's an example of failed run.](https://github.com/rdeago/runner-context-test/actions/runs/3248144866)

## Job Log Output

There's no log output because the workflow doesn't even start.

## Runner and Worker's Diagnostic Logs

I'm not using hosted runners.

**Comment by m4heshd** [comment]
Check [this documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability). `runner` context is not available for job's top level `env`. I know that's pretty odd. But it's available for `jobs.<job_id>.steps.env`. Which means you can do this:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Show results
      env:
        FOOBAR: ${{ runner.debug == '1' && 'foo' || 'bar' }}
      run: echo $FOOBAR
```
