### ISSUE TITLE
Jobs skipped when NEEDS job ran successfully

### ISSUE THREAD

**Issue by niekvanderreest** [actions/runner#2205]
**Describe the bug**
One or more jobs are skipped in a workflow when run after successfully running a job matching following conditions:
- Job has NEEDS dependency on one or more preceding jobs. (i.e. needs: [job1, job2])
- Job has if condition specifying behavior when NEEDS jobs are skipped. (i.e. if: always() && needs.job1.result == 'skipped')
- Preceding job is skipped (i.e. job1)

**To Reproduce**
Create a workflow as follows:
-------------------------------
name: Skipped Job Test

on:
  workflow_dispatch:
  
jobs:
  Skipped-Job:
    name: skipped job
    runs-on: [self-hosted]
    if: 1 !=1
    steps:
    - name: write to console 1
      run: Write-Host "I should be skipped"

  Needs-Job:
    name: needs conditional job
    needs: Skipped-Job
    if: always() && needs.Skipped-Job.result != 'failed' # this should run eventhough needs the skipped-job
    runs-on: [self-hosted]
    steps:
      - name: write to console 2
        run: Write-Host "Needs-Job completed"
  
  Next:
    name: Next job
    needs: Needs-Job
    # if: always() && needs.Needs-Job.result == 'success' # uncommenting this condition causes the job to not be skipped
    runs-on: [self-hosted]
    steps:
      - name: write to console 3
        run: Write-Host "I should print whenever Needs-Job succeeds"
------------------------------------------------------------------------------

 

**Expected behavior**
I'd expect the job "Next" to run, because the preceding job " Needs-Job" is completed successfully and is the only condition for this job to run (it needs Needs-Job), it is however skipped.
uncommenting the 3rd line in that job is a fix, but this feels hacky and is a workaround.

## Runner Version and Platform
Current runner version: '2.298.2'

Running on: Windows Server 2022 Standard
Version	21H2
OS build	20348.1006

**Comment by GennaroGreg** [comment]
I believe the status is the wrong word - try ‘failure’ instead of ‘failed’.

**Comment by niekvanderreest** [comment]
Hi @GennaroGreg, 

Thanks for the reply, the status 'failed' might indeed be the wrong word, however it shouldn't matter for job "Needs-Job" as the check is if it's not equal to, and since "Skipped-Job" is always skipped the status will always be 'skipped' (right?)

**Comment by DameonSmith** [comment]
I'm having a similar problem. Where a job earlier in the chain is skipped causes all down stream jobs to be skipped even if they don't explicitly state that they need that job to continue. 

Following pseudo code demonstrates what I'm seeing. 
```yaml
jobs:
  get-semaphor:
    runs-on: ubuntu-latest
    steps:
       - name: get-some-semaphor
       - run: echo "semaphor=false" >> $OUTPUT
       
  check-semaphor:
    runs-on: ubntu-latest
    needs: get-semaphor
    if: needs.get-semaphor.output.semaphor == true
    steps:
      - name: Do something here
      
  do-task-a:
    runs-on: ubntu-latest
    needs: ['check-semaphor', 'get-semaphor'] 
    if: alsways && (needs.check-semaphor.result == skipped || needs.check-semaphor.result == success) && needs.get-semaphor.result == success
    steps:
      - name: do something

  # This task-b will never run if check-semaphor is skipped or fails. Even though A succeeds. 
  do-task-b-aslong-as-a-works:
    needs: do-task-a
    steps:
      - name: do something
```

**Comment by mulhotavares** [comment]
@DameonSmith IIRC you'd need to add `if: always() && needs.do-task-a.result == success` in this case. Once a job in the workflow is failed or skipped, you need to overwrite the conditional for all subsequent jobs...

**Comment by niekvanderreest** [comment]
Hi @mulhotavares, thanks for the comment, I do know this works but I consider it a workaround. I could be wrong however and this could be intended behavior, do you perhaps have a link to Github documentation that explains this as intended behavior?

It feels like a bug that the run condition on job A would impact job C that has no condition on the skipped job (only on job B which is run and successful)

**Comment by mulhotavares** [comment]
Hi @niekvanderreest.
In terms of the documentation, I haven't found that mentioned directly, but the docs do state:
> A default status check of success() is applied unless you include one of these functions.

And
> success
> Returns true when none of the previous steps have failed or been canceled.

(both quotes from this: https://docs.github.com/en/actions/learn-github-actions/expressions#job-status-check-functions) 

So it is respecting both of those statementes, but I agree this looks awkward. Anyways, I was just trying to help, especially as others could find this in Google like I did. 😄

**Comment by kgreav** [comment]
This is really weird behaviour. As noted [here](https://github.com/orgs/community/discussions/45058) this definitely seems to be a bug (why are we all just running into this now? did everyone suddenly decide to use job ifs?).

A job being skipped seems to be treated as failed, so `success()` doesn't work for follow on jobs. As documented in the discussion, you should instead use `! failure()` which works a treat, but you then have to propagate it to all descendant jobs even if they don't directly depend on the skipped job, which is very confusing.

You should fix `success()` to not include skipped jobs, as skipped really should mean "this wasn't needed", not "this failed". And needs checks should only occur on the explicitly listed jobs, not ancestors of those jobs.

**Comment by jjoseph456** [comment]
I have a customer whose workflow skips or cancels as soon as it is executed 

A copy of their yaml
[staging.yml.txt](https://github.com/actions/runner/files/10483330/staging.yml.txt)

**Comment by niekvanderreest** [comment]
@jjoseph456 , I think your workflow has an execution order issue, the first job has a needs specifying the second job. Switching position of first and second job should fix this. 

I'm no expert at this field, most of the workflow I worked on have a strict order of execution.

**Comment by jjoseph456** [comment]
@niekvanderreest thanks will try that

**Comment by povisenko** [comment]
Having the same issue



> I'm having a similar problem. Where a job earlier in the chain is skipped causes all down stream jobs to be skipped even if they don't explicitly state that they need that job to continue.
> 
> Following pseudo code demonstrates what I'm seeing.
> 
> ```yaml
> jobs:
>   get-semaphor:
>     runs-on: ubuntu-latest
>     steps:
>        - name: get-some-semaphor
>        - run: echo "semaphor=false" >> $OUTPUT
>        
>   check-semaphor:
>     runs-on: ubntu-latest
>     needs: get-semaphor
>     if: needs.get-semaphor.output.semaphor == true
>     steps:
>       - name: Do something here
>       
>   do-task-a:
>     runs-on: ubntu-latest
>     needs: ['check-semaphor', 'get-semaphor'] 
>     if: alsways && (needs.check-semaphor.result == skipped || needs.check-semaphor.result == success) && needs.get-semaphor.result == success
>     steps:
>       - name: do something
> 
>   # This task-b will never run if check-semaphor is skipped or fails. Even though A succeeds. 
>   do-task-b-aslong-as-a-works:
>     needs: do-task-a
>     steps:
>       - name: do something
> ```

having the same issue, once always() used in job1, the next job that needs it will not be executed even if the job1 succeeds

**Comment by Jonath-z** [comment]
I'm having the similar problem, can someone help?
```yml
name: Release
on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main
      type: [closed]
jobs:
   release:
      if: github.event.pull_request.merged == true
      name: Release
      runs-on: ubuntu-20.04
      steps:
         - name: Checkout source code
           uses: actions/checkout@v3
         - name: Cache node_modules
           uses: actions/cache@v2
           with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: ${{ runner.os }}-node-
         - name: Install the dependencies
           run: npm ci --legacy-peer-deps
         - name: Run release
           run: npm run release --ci
         - name: End message
           run: echo "All done!"

```

**Comment by gcharondkt** [comment]
Hello, I had the same problem. The workaround proposed by @mulhotavares is working, but I agree with @niekvanderreest saying this is a workaround and should be solved.

The documentation says that a `success()` condition is applied by default, and that this function **_Returns true when none of the previous steps have failed or been canceled._** --> so it should return true when the job is skipped.

Moreover, the uses of `success()` and `needs.job-id.result == success` are inconsistent, because `success()` can return false when `needs.job-id.result == success` returns true, wherease it looks like the same meaning. See below : 

```yaml
  # This is working : the job3 is executed
  job3:
    needs: [job1, job2]
    if: always() && (needs.job1.result == 'success' || needs.job2.result == 'success')
```
versus
```yaml
  # This is not working : the job3 is skipped (documentation says that a success() function is applied by default
  job3:
    needs: [job1, job2]
    if: (needs.job1.result == 'success' || needs.job2.result == 'success')
```

**Comment by igorcezar** [comment]
Any news on this?

**Comment by OldSneerJaw** [comment]
FWIW, I have found that it works well to use an `if` statement like the following for all jobs that are dependent, either directly or indirectly, on one or more jobs that may be skipped:

```yaml
if: ${{ !failure() && !cancelled() }}
```

**Comment by rob1256** [comment]
I've had some success working around this by using sub-workflows, move the optional job into the sub-workflow and then the main workflow can use the `needs` as normal and not need the horrible `if` conditions on all subsequent jobs. The jobs in the sub-workflow still need the `if` statements on subsequent jobs but it can still reduce the amount needed depending on your workflows.  I think the sub-worlflow still needs at least on successful (not skipped) job to run within it but I've not tested this

**Comment by mw-root** [comment]
I cannot believe this is still an active issue. I just ran into this again.

**Comment by rrashi** [comment]
any solutions for this yet apart from introducing sub-workflows? the if conditionals are becoming even more inflated if there are multiple jobs that can be potentially skipped..

**Comment by sarthak-mnscorp** [comment]
Bumping up for visibility as I ran into a similar issue today and cam here searching!

**Comment by mrclrchtr** [comment]
I ran into this today and it's really annoying.. i'm coming across strange characteristics of gh actions more and more often...

**Comment by fbmaya** [comment]
I'm having the same problem here, we haven't had any updates on this yet?

**Comment by robert-nemet** [comment]
I run into this yesterday. Any news about this?

**Comment by marc-wilson** [comment]
joining the club. +1

**Comment by fbmaya** [comment]
Hi everyone,

This problem has been bothering me for a few months now and I've been following the resolution to find a better way.

But some people have commented on a workaround.

I'm doing it this way.

`if: !failure() && !canceled()`

It seems that "needs" understands that Job Skipped is an error
so adding this conditional seems to "trick" this status.

**Comment by szalapski** [comment]
@fbmaya's workaround doesn't work in all cases.  Can someone from GitHub/Microsoft acknowledge that this is a bug that should be fixed?

**Comment by rsorelli-hedgepoint** [comment]
Same issue here:

I have a job with a if condition that keeps skipping even with the condition evaluating as TRUE.
Here it is:

```
  provision-resources:
    if: |
      (needs.call-run-build.result == 'success' &&
      github.event_name != 'pull_request')
    needs: [call-run-build]
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
```

I have set another job to check the value of those variables and all trem returns correctly:

```
  test-provision-resources:
    if: ${{ always() }}
    needs: [call-run-build]
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:

      - name: echo conditions
        run: |
          echo "provision-resources-result=${{ needs.call-run-build.result }}"
          echo "github-event-name=${{ github.event_name }}"
```

The output:

```
provision-resources-result=success
github-event-name=push
```

**Comment by LoxXo** [comment]
The workaround is not always helpful. The jobs are skipped when using reusable workflows containing multiple jobs even though I used every mix of previously mentioned fixes.

**Comment by tyrelh** [comment]
We ran into this today. Thanks to folks who posted some workaround solutions.

Doing `if: always()` or `if: !failure() && !canceled()` doesn't work in all cases, our case in particular.

I _think_ (emphasis on think) that a general solution is you use `always()` but then also you need to explicitly check that the job you're depending on finished in the state you're expecting.

So our example looks something like this
```yaml
terminate-old-environments:
  needs: deployment-success
  if: |
    always() &&
    needs.deployment-success.result != 'skipped'
  uses: ./.github/workflows/terminate.yml
```

We wanted this workflow to run only when `deployment-success` is explicitly **not skipped**.

If `deployment-success` is _skipped_, that means our deployment failed and other jobs run in that situation. We also technically wanted this job to run if `deployment-success` specifically failed. In our case `deployment-success` is just a feedback job, notifying folks in Slack. We don't want that notification job to prevent environment cleanup.

Doing this we were able to get our job to trigger as expected.

Here's what it looks like in the successful deployment path
![Image](https://github.com/user-attachments/assets/7c1cdb0b-81d0-4d03-b336-a07db2b29603)

And here's what it looks like in the deployment failure path
![Image](https://github.com/user-attachments/assets/ecab02d2-9148-4157-938b-5a06f5251fe4)

The `terminate-old-environments` job is that final job on the right, dependent on the `deployment-success` job which itself is dependent on one none of the deployments failing, each of which is optional.

Note that our `terminate-old-environments` workflow only contains a single job. I assume the behaviour would be the same if it contained multiple jobs but I didn't verify this. @LoxXo noted there might be more odd behaviour in this case.
