### ISSUE TITLE
Inputs context not available in reusable workflows

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [actions/runner#2206]
**Describe the bug**
The inputs context does not seem available in the `with` context of reusable workflows

**To Reproduce**

- Create a reusable workflow that has the following input

```yaml
      stg_image_build:
        description: whether to build the staging image
        required: true
        type: boolean
        default: false
```

Invoke it as follows

```yaml
  workflow_dispatch:
    inputs:
      push_to_stg:
        description: "Build and push image to staging registry"
        type: boolean
        default: false
        required: true

...

  build-and-push-image:
    needs:
      - echo-input
    uses: Org/repo/.github/workflows/myreusableworkflow.yaml@master
    with:
      stg_image_build: ${{ inputs.push_to_stg }}
```

Fails

```
The template is not valid. .github/workflows/calling.yaml (Line: 15, Col: 24): Unexpected type of value '', expected type: Boolean.
```

**Expected behavior**
The `stg_image_build: ${{ inputs.push_to_stg }}` line should be passing to the reusable workflow a boolean.

## Runner Version and Platform
GitHub hosted runner

OS of the machine running the runner? OSX/Windows/Linux/...
`ubuntu-latest`

## What's not working?
```
The template is not valid. .github/workflows/calling.yaml (Line: 15, Col: 24): Unexpected type of value '', expected type: Boolean.
```

**Comment by yu-iskw** [comment]
I have a similar issue. I passed a number input to a reusable workflow and it was working well. But, it hasn't been working since 4 hours. 

```
The template is not valid. .github/workflows/validate.yml (Line: 30, Col: 20): Unexpected type of value '', expected type: Number.
```

**Comment by jacob-israel-turner** [comment]
> I have a similar issue. I passed a number input to a reusable workflow and it was working well. But, it hasn't been working since 4 hours.
> 
> ```
> The template is not valid. .github/workflows/validate.yml (Line: 30, Col: 20): Unexpected type of value '', expected type: Number.
> ```

I am experiencing the same error. This is when trying to pull a value off of `matrix`.

**Comment by ruvceskistefan** [comment]
Hey @pantelis-karamolegkos, I'll close this issue since this is not reproducible as @ChristopherHX says. If you are still heaving the same issue feel free to reopen it and we will continue with investigation.

**Comment by galcohen-redislabs** [comment]
Still getting a similar error message, using:
```
jobs:
   ...
   with:
      my_timeout: ${{ inputs.timeout }}
```
and running gh from the command line like this:
`gh workflow run <some-workflow>.yaml  --ref <some-branch>-f timeout=300`
the result is:
```
The template is not valid. ....yaml (Line: 15, Col: 20): Unexpected type of value '300', expected type: Number.
```

**Comment by mykola-lysenko** [comment]
still having the same issue when trying to access inputs in reusable workflows. Neither inputs, nor github.event.inputs are available.

Reusable workflow is defined as:
```
on:
  workflow_call:
    inputs:
      ci_repo_name:
        required: true
        type: string
        default: 'libbpf/ci'
      ci_repo_branch:
        required: true
        type: string
        default: 'master'
...
# later inputs are used as follows
...uses: ${{ inputs.ci_repo_name }}...
```

The error I am getting
```
Unrecognized named-value: 'inputs'.
```

**Comment by jtmullen** [comment]
@ruvceskistefan I am also still seeing this same issue: 

Passing a number input to a reusable workflow and getting: 

`The template is not valid. .....yml (Line: 29, Col: 23): Unexpected type of value '1', expected type: Number.`

**Comment by jenseng** [comment]
@galcohen-redislabs @jtmullen I ran into a similar issue, it appears that the type gets lost somewhere in the process and those input values become strings. As a workaround, you should be able to use `fromJSON` to convert them back to the appropriate type (e.g. number, boolean). For example, instead of this:

```yaml
jobs:
   ...
   with:
      my_timeout: ${{ inputs.timeout }}
```

give this a try:

```yaml
jobs:
   ...
   with:
      my_timeout: ${{ fromJSON(inputs.timeout) }} # 🙈 
```

**Comment by galcohen-redislabs** [comment]
@ruvceskistefan Please note the last three comments. The problem still exists.

**Comment by Yagya-omnius** [comment]
Could anyone please reopen this issue, it is still reproducible

**Comment by pascalro-croesus** [comment]
I get the same problem, for a 'number' input.

**Comment by Mikifarber1** [comment]
i got it also, for a "number" input.

**Comment by iamutkarshtiwari** [comment]
I am getting the same error.
Starting a [new issue](https://github.com/actions/runner/issues/3038).

**Comment by act-mreeves** [comment]
@pantelis-karamolegkos - Do you have the following within workflow_call or workflow_dispatch?
I believe it should be under/within workflow_call like shown below.

I think also you would remove default and required since you are always setting the value using "with" from the calling workflow but I may be wrong.

```
  workflow_call:
    inputs:
      stg_image_build:
        type: boolean
```

> **Describe the bug** The inputs context does not seem available in the `with` context of reusable workflows
> 
> **To Reproduce**
> 
> * Create a reusable workflow that has the following input
> 
> ```yaml
>       stg_image_build:
>         description: whether to build the staging image
>         required: true
>         type: boolean
>         default: false
> ```

**Comment by johnbatclari** [comment]
Unfortunately it doesn't seem like the fromJSON workaound works anymore. Or at least not in my use-case where this is happening with a boolean value. 

Either way, this is still very much reproducible as I've just tripped over it. 😉

**Comment by mmastrac** [comment]
I was able to work around this by using `== true` on the offending line.

**Comment by psazonparalect** [comment]
Hey, I still have this problem when I try to start a workflow
........
```shell
inputs:
  build:
    description: 'Run build process'
    required: true
    default: false
    type: boolean
``` 
.......
```shell
  with:
    build: ${{ github.event_name == 'push' || github.event.inputs.build }}
```
Have this
`The template is not valid. **** (Line: **, Col: **): Unexpected value 'true'`

**Comment by twz123** [comment]
> 
> ```shell
>   with:
>     build: ${{ github.event_name == 'push' || github.event.inputs.build }}
> ```
> 
> Have this `The template is not valid. **** (Line: **, Col: **): Unexpected value 'true'`

@psazonparalect Did you try this, as mentioned in https://github.com/actions/runner/issues/2206#issuecomment-1532246677?

```shell
  with:
    build: ${{ github.event_name == 'push' || fromJSON(inputs.build) }}
```

**Comment by twz123** [comment]
> Hi @twz123 , I saw this comment in thread and didn't try it

@psazonparalect As far as I can tell it still works.

**Comment by nlong-mufin** [comment]
```
on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      project-base-dir:
        description: 'The analysis base directory'
        required: false
        default: '.'
        type: string
      sonar-source:
        description: 'The source folder to scan'
        required: false
        default: '.'
        type: string
      exclusions:
        description: 'The exclusion folder'
        required: false
        type: string
      java:
        description: 'Sonar scan with Java option. Value: true or false. (Default: false)'
        required: false
        default: false
        type: boolean
      melos:
        description: 'Run melos command for mobile app. Value: true or false. (Default: false)'
        required: false
        default: false
        type: boolean
      pub-get:
        description: 'Install Flutter dependency command for mobile app. Value: true or false. (Default: false)'
        required: false
        default: false
        type: boolean

jobs:
  sonarscan:
    name: Sonar Scan
    permissions: write-all
    uses: org/github-workflows/.github/workflows/sonar-check.yaml@release
    with:
      project-base-dir: ${{ inputs.project-base-dir }}
      sonar-source: ${{ inputs.sonar-source }}
      exclusions: ${{ inputs.exclusions }}
      java: ${{ fromJSON(inputs.java) }}
      melos: ${{ fromJSON(inputs.melos) }}
      pub-get: ${{ fromJSON(inputs.pub-get) }}
```

I have try another way like: 

```
      java: ${{ inputs.java }}
      melos: ${{ inputs.melos }}
      pub-get: ${{ inputs.pub-get }}

```
or
```
      java: ${{ github.event.inputs.java }}
      melos: ${{ github.event.inputs.melos }}
      pub-get: ${{ github.event.inputs.pub-get }}
```

Still error: 
`The template is not valid. .github/workflows/sonar.yaml (Line: 51, Col: 13): Unexpected value '',.github/workflows/sonar.yaml (Line: 52, Col: 14): Unexpected value '',.github/workflows/sonar.yaml (Line: 53, Col: 16): Unexpected value ''`

Please help me to review this.
