### ISSUE TITLE
Job outputs doesn't works on Windows runner.

### ISSUE THREAD

**Issue by NeocaseDCosta** [actions/runner#2224]
# Description
Hi,
I use the sample about job outputs from the GitHub documentation (see code below).
When I use "ubuntu-latest" for the job1, I can use job1 outputs into Job2.
![image](https://user-images.githubusercontent.com/52035692/197506357-19063e65-de6a-4a00-933c-fe16caad866f.png)

When I use my self-hosted windows runner for the job1, I can't use job1 outputs into Job2.
In all tests, I use my self-hosted windows runner for the job2
![image](https://user-images.githubusercontent.com/52035692/197506400-69fd6f7c-1cb2-4c87-b429-e4ba832f7518.png)

In Diag files, we can see the "needs" node does not contains data informations in sub node "outputs".

![image](https://user-images.githubusercontent.com/52035692/197506271-d841167b-204b-4f1f-8a6f-4b7d77999b31.png)

it looks like a bug :-). 
Thanks for your help.

# To reproduce
Just change the runner used on job1.

# Runner version and OS
Version 2.298.2 on Windows Server 2019 Datacenter.

# Script

```
name: test
on:
  pull_request:
    branches: [ master ]

jobs:
  job1:
    runs-on: [self-hosted, windows]
    #runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: [self-hosted, windows, csd-back]
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
```
