### ISSUE TITLE
Canvas or WebGL application very slow on runners

### ISSUE THREAD

**Issue by gromanas** [actions/runner#2229]
**Describe the bug**
I am working for a software industry where we create canvas and WebGL games. We have created some functional tests for those games. We have tried using ubuntu, mac runners, and also have access to select a runner with better hardware specs, also we have dedicated runners, but the issue still remains. On chrome browser, the games are very slow and even miss some animations that are happening. On chrome 99 and below the game is slow but is playable. On chrome 100 and above the game is very very slow. We have calculated that the FPS is approximately 2-10.

**To Reproduce**
1. A canvas/WebGL application should 
2. Try to play a game on chrome browser version <100.0.0

**Expected behavior**
The game should be played at an acceptable FPS rate (above 15). 

## Runner Version and Platform
ubuntu-latest, mac-latest, and also the dedicated that are 4 cores and 16gb ram.

OS of the machine running the runner? 
Linux (ubuntu), macOS (mac)

**Comment by ruvceskistefan** [comment]
Hey @gromanas,

Thank you for reporting this issue. Can you please tell me, are you running your workflow in a container? Can you provide an example workflow, so we can reproduce this bug?

**Comment by gromanas** [comment]
Hello @ruvceskistefan,

Thank you very much. A sample of the workflow is:

```
name: Functional Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.eslintignore'
      - '.eslintrc.json'
      - '.github/**'

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'
      - '.eslintignore'
      - '.eslintrc.json'

jobs:
  functional-test:
    if: ${{ !startsWith(github.event.pull_request.title, '[skip-ci]') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        func_suite: [ suite1, suite2, suite3, suite4, suite5 ]

    steps:
      - name: 🛎️  Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: 🪢  Install Tesseract OCR
        run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr5
          sudo apt update
          sudo apt install -y tesseract-ocr
          tesseract -v

      - name: 🧶  NodeJS setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.18.1"

      - name: 🦚 Cache dependencies
        id: cache
        uses: pat-s/always-upload-cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: 🔧  Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 🏗️  Start Game and Selenoid
        run: npm run infra:up

      - name: 🍺  Verify Game is Running
        run: sh ./ci/scripts/wait-for-app-to-run.sh

      - name: 🚀  Run Functional Tests
        run: npm run test:selenoid-func-web -- --suite ${{ matrix.func_suite }}

      - name: 🌋  Upload Image Diffs
        if: always()
        uses: actions/upload-artifact@v2.2.1
        with:
          name: "image-diffs-${{ matrix.func_suite }}"
          path: .tmp
          retention-days: 5

      - name: 🏔️  Upload Functional Test report
        if: always()
        uses: actions/upload-artifact@v2.2.1
        with:
          name: "func-tests-report-${{ matrix.func_suite }}"
          path: reports
          retention-days: 5
```
