### ISSUE TITLE
Boolean inputs are not actually booleans in composite actions

### ISSUE THREAD

**Issue by flobernd** [actions/runner#2238]
**Describe the bug**

I'm not sure if closed issues are monitored, as there was no reaction from official side at all. This is a new issue related to https://github.com/actions/runner/issues/1483.

For **composite actions** boolean inputs are not actually booleans.

**To Reproduce**

```yaml
inputs:
  ...
  generate-release-notes:
    description: ...
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Create Release
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ...
            generate_release_notes: ${{ inputs.generate-release-notes && 'true' || 'false' }}
          });
```

Caller:

```yaml
- uses: flobernd/actions/github/create-release@master
  with:
    tag-name: v1.2.4
    generate-release-notes: true
```

This line always evaluates to `false`:

```
generate_release_notes: ${{ inputs.generate-release-notes && 'true' || 'false' }}
```

The explicit syntax does incorrectly evaluate to `false` as well:

```
generate_release_notes: ${{ inputs.generate-release-notes == true && 'true' || 'false' }}
```

Correct behavior is only observed when using string semantics:

```
generate_release_notes: ${{ inputs.generate-release-notes == 'true' && 'true' || 'false' }}
```

**Expected behavior**

```
generate_release_notes: ${{ inputs.generate-release-notes && 'true' || 'false' }}
generate_release_notes: ${{ inputs.generate-release-notes == true && 'true' || 'false' }}
```

Evaluates to `true`.

## Runner Version and Platform

GitHub managed runners (latest version). All platforms.

**Comment by veleek** [comment]
I was hoping to do something similiar with the output of a composite action, but there doesn't seem to be any way to force it to be a boolean either.  I'm using:

```
outputs:
  image_exists:
    description: true if an image with the given exists, false otherwise
    value: ${{ fromJSON(steps.verify_image_exists.outputs.image_exists) }}
```

**Comment by machulav** [comment]
Agree with @veleek - this is very frustrating to have conditions like the following:

```
if: needs.get-pr-labels.outputs.build-label-present == 'true' || needs.get-pr-labels.outputs.deploy-label-present == 'true'
```

It would be nicer if the outputs were boolean, so the condition looks like this:

```
if: needs.get-pr-labels.outputs.build-label-present || needs.get-pr-labels.outputs.deploy-label-present
```

The outputs in the composite actions looks like this:

```
on:
  workflow_call:
    outputs:
      build-label-present:
        description: "cicd:build label is present in the PR"
        value: ${{ contains(github.event.pull_request.labels.*.name, 'cicd:build') }}
      deploy-label-present:
        description: "cicd:deploy:* label is present in the PR"
        value: ${{ contains(toJSON(github.event.pull_request.labels.*.name), 'cicd:deploy:') }}
```

**Comment by sremp** [comment]
+1 to this. Just recently ran into this exact issue, with the only reasonable workaround being to use string semantics as detailed in the original post.

**Comment by justinmchase** [comment]
This appears to be true for docker based actions as well.

**Comment by SatishReddyBethi** [comment]
+1

**Comment by agileshaw** [comment]
Just ran into this issue as well. There doesn't seem to be any related information on the official documentation, and it is very non-intuitive to have `inputs` support multiple types in workflows and "normal" actions but not in composite actions. I hope this behavior can be changed.

**Comment by maschwenk** [comment]
Also worth nothing that if expressions are always evaluated to strings https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions

Then it seems unclear how this will ever work for passing variables from workflows. E.g.

```
workflow dispatch with boolean 
  -> calls composite action
      with:
        variable: ${{ inputs.from_workflow_dispatch_boolean }}
```

It's surprising that literals don't work, but also curious how expressions will *ever* work

**Comment by grossag** [comment]
I am also running into this and trying to sort out how to work around this.

I would suggest not doing a workaround that involves using `type: boolean` but then treating it as a string, such as `if: ${{ inputs.some-input-value == 'true' }}`. My reasoning is that if GitHub actually fixes this issue, those workarounds would no longer be expected to function. After a fix to this issue, comparing a boolean `== 'true'` would return false, which is not what you want in the long-term.

**Comment by veleek** [comment]
@grossag, while I think that you're correct in that this is simply not a supported feature of GHActions, I think the rest of this thread makes it very clear that people would REALLY like if it _we're_ supported.  The fact that it's nearly identical to other mechanisms for declaring inputs except that it's missing `type` is confusing on it's own and probably worth doing something about.

**Comment by Jardo-51** [comment]
This bug just cost me half of a work day. Why isn't anyone addressing this?

**Comment by libermansa** [comment]
it 2024 and GH actions doesn't treat booleans as booleans in any other software... that's a shame.

**Comment by LongBeachHXC** [comment]
Yeah, I just came across this scenario too, which led me here.

The docs are pretty explicit in defining the inputs for composite actions and workflow dispatch inputs.

However, I still found myself asking the question, 'Is the boolean input I am using in my workflow going to be passed in as a boolean or string when calling my composite action?'.

At minimum, there should be a Note block added to the docs to explicitly call this out. Until this actually gets implemented (Original issue was opened in 21 so it doesn't seem likely), the note block will eliminate any confusion people have.

**Comment by wallentx** [comment]
TIL that `type: x` isn't supported in composite actions. I guess this is why I had to quote my bool values in any of the dozen composite actions I've made. They were strings. Fantastic.

So, there are apparently rules and logic put into the schema for composite actions. It'd be great if GitHub actually published that schema somewhere so that actionlint could be put to use. A schema HAS to exist for this, right? Hold on...

...

Okay, I had to do some testing just now to verify something, and this is what I put in at the top of my composite action:
```
name: Create release
description: Create a GitHub release
with:
  type: testing something obviously incorrect
  shell: bash
  run: |
    uname -a

inputs:
  ...(normal stuff below)
```
And it ran with no problem. It didn't execute any of that, but it didn't complain about it at all.

So composite is yolo, and if you get something wrong, you might not get useful feedback about what is wrong, and why.

**Comment by marcwittke** [comment]
This is a real pain point. Assuming the example from the OP

```
inputs:
  ...
  generate-release-notes:
    description: ...
    required: false
    type: boolean
    default: "false"
```

so:

- providing no value, will `${{ inputs.generate-release-notes }}` evaluate to `true` because `"false"` is no empty string?
- providing `"TRUE"`, will `${{ inputs.generate-release-notes == 'true' }}` evaluate to `false` because `"TRUE" != "true"`?

:disappointed:
