### ISSUE TITLE
npm install not working on actions

### ISSUE THREAD

**Issue by julian-reactive** [actions/runner#2253]
error starts on line 19:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/97314902/201409356-e9184eca-c269-41cc-bcd6-33b09146b6d7.png">

same happens with any other library... like `webpack`

**Comment by nikola-jokic** [comment]
Hey @julian-reactive,

Can you please provide an example repo or a workflow file, so we can reproduce this issue?

**Comment by julian-reactive** [comment]
```
name: build-prod

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    name: 👷 Build PROD env
    runs-on: ubuntu-latest
    env:
        RECAPTCHA_KEY: ${{ secrets.recaptcha_key }}
        RECAPTCHA_METHOD: ${{ secrets.recaptcha_method }}
        NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14
      - name: Build App
        run: |
          npm i
          npm run lint
          npm run build
      - name: 📂 Sync APP files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 151.106.97.160
          username: u190936318.prod_user
          password: ${{ secrets.mqs_prod_pw }}
          local-dir: dist/
          server-dir: /app/
```
---
fails on `npm run lint` -> ` "lint": "eslint src --ext .ts --ext .tsx --ext .js"`

**Comment by julian-reactive** [comment]
```
name: build-prod

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    name: 👷 Build PROD env
    runs-on: ubuntu-latest
    env:
        RECAPTCHA_KEY: ${{ secrets.recaptcha_key }}
        RECAPTCHA_METHOD: ${{ secrets.recaptcha_method }}
        NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14
      - name: Build App
        run: |
          npm i
          npm run lint
          npm run build
      - name: 📂 Sync APP files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: xxxx
          username: xxxx
          password: ${{ secrets.mqs_prod_pw }}
          local-dir: dist/
          server-dir: /app/
```
--- fails on `npm run build` -> `"lint": "eslint src --ext .ts --ext .tsx --ext .js"`

**Comment by nikola-jokic** [comment]
To me, it seems like the npm run lint fails calling the linter that is not inside dependencies. Can you remove node_modules and try executing Build App commands one by one?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by nonodev96** [comment]
Hi, I have the same problem, sometimes the deployments work for me and other times they don't, I have tried `npm ci` and `npm i` and it is the same.


```yaml
name: 'Deploy'

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-stable:
    name: 'Deploy to netlify stable'
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          echo "${{ secrets.NETLIFY_ENV_FILE_STABLE }}" > .env.netlify
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STABLE }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          INSTALL_COMMAND: npm ci
          BUILD_COMMAND: npm run build:netlify
          BUILD_DIRECTORY: 'build'
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
```


```log
Run jsmrcaga/action-netlify-deploy@v2.0.0
Run /home/runner/work/_actions/jsmrcaga/action-netlify-deploy/v2.0.0/entrypoint.sh

added 996 packages, and audited 997 packages in 1m

174 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (1 low, 15 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> nets4learning@1.9.6 build:netlify-snapshot
> craco build --mode netlify-snapshot

sh: 1: craco: not found
Error: Process completed with exit code 127.
```
