### ISSUE TITLE
Mixed `${{ inputs }}` reusable workflow and caller workflow

### ISSUE THREAD

**Issue by laurentsimon** [actions/runner#2274]
**Describe the bug**
The `inputs` between `workflow_call` and `workflow_dispatch` are unified (https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/). However, I found a corner case that seems to behave incorrectly. When a workflow runs on workflow_dispatch event and calls a reusable workflow, the reusable workflow's `inputs` contain not only its defined inputs, but also the calling workflow's inputs (from the dispatch event)

**To Reproduce**
1. Create workflow.yml:
```yaml
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Release tag to test"
        required: false
        default: v1
        type: string
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  release:
    permissions:
    uses: <repo>/<name>/.github/workflows/reusable.yml@main
    with:
      name1: value1
```

2. create reusable workflow:
```yaml
on:
  workflow_call:
    inputs:
      name1:
        description: "name 1"
        required: true
        type: string

jobs:
  test:
    outputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "inputs: ${{ inputs }}"
```

This will show both the `name1` and `release-tag`, even though the input to the reusable workflow has only one input defined (`name1`).

**Expected behavior**
Only the `name1` input should show.

## Runner Version and Platform
Version of your runner?

ubuntu-latest
## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
