### ISSUE TITLE
Pass arguments to service containers

### ISSUE THREAD

**Issue by garciasdos** [actions/runner#2276]
**Describe the enhancement**
Related to https://github.com/actions/runner/discussions/1872, I haven't found any solution or documentation about how to pass arguments to service containers. 

I've seen the `options` argument, but this is only passing the argument to the inside `docker container create` command. Is there a way to do this? if not, are there any plans to implement it?

**Code Snippet**
```yml
   services:
       mockoon:
         image: mockoon/cli:2.1.0
         ports:
           - 4010:4010
         volumes:
           - ./mock:/data
         container-options: >- # or something like this 🤔
           --data /data/mockoon.json
```
