### ISSUE TITLE
GitHub Actions Job/Workflow environment variables DO NOT WORK ON WINDOWS, fine on ubuntu

### ISSUE THREAD

**Issue by SimonDarksideJ** [actions/runner#2281]
**Describe the bug**
Took a while to get to the root of this so bare with me, essentially when we were in the progress of updating all our "Set-Output" usage in our GitHub actions pipelines we hit a critical show-stopper issue in that Variables were NO LONGER passed between jobs or workflows.
All we changed was to update all "Set-Output" usage to the new ">> $GITHUB_OUTPUT" style, no names or anything else was changed. It didn't work.

Eventually, we tried to replicate this using GitHubs own example and found it worked, BUT ONLY FOR UBUNTU, when run on Windows, it failed.
https://github.com/orgs/community/discussions/39944

**To Reproduce**
1. Create a Reusable workflow using GitHubs own a samples, as shown below:

```yaml
name: GitHub Outputs

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string  
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.job1.outputs.output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.job1.outputs.output2 }}

jobs:
  job1:
    runs-on: windows-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
```

2. Run the above reusable workflow from a new action and display the output value

```yaml
${{needs.job1.outputs.workflow_output1}}
```

4. See error (output variable is blank)

**Expected behavior**

On Ubuntu the above workflow WORKS and outputs a value, on Windows, either self-hosted or via ms windows hosted agents, it does not.

## Runner Version and Platform
Version of your runner?

199.1

OS of the machine running the runner? OSX/Windows/Linux/...

* Windows - fail
* Ubuntu - works

## What's not working?

The GitHub Environment variables do not function on Windows, only on Ubuntu.
Which makes it impossible to upgrade from our "set-output" implementation which is working fine on Windows.
