### ISSUE TITLE
`-noLogo` broken on dotnet CLI included in 20221121.1 version of macos runner?

### ISSUE THREAD

**Issue by robin-aws** [actions/runner#2282]
**Describe the bug**
Something changed between the macos runner version `20221027.1` and `20221121.1` that causes a call to `dotnet test -v:n -noLogo <project file path>` to produce the error `MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

**To Reproduce**
Will be time-consuming to reproduce, but this was observed in the CI for the Dafny project as follows:

* Failing build that landed on a runner with version `20221121.1`: https://github.com/dafny-lang/dafny/actions/runs/3538283931/jobs/5938991371#step:1:9
* Retry that landed on a runner with version `20221027.1` and succeeded: https://github.com/dafny-lang/dafny/actions/runs/3538283931/jobs/5941155148#step:1:9

The same thing happened day before: https://github.com/dafny-lang/dafny/actions/runs/3529784188

As of today, no amount of retrying was enough to make the job succeed. I suspect that's because the rollout of the new version completed and so there were no runners left to run the job successfully.

It turns out that removing `-noLogo` from the call fixes the issue, and I'm guessing the problem is a slightly different build of the dotnet CLI misinterpreting that option and swallowing the following argument that is the path to the csproj file.

**Expected behavior**
Tests should pass on any runner.

## Runner Version and Platform
Version of your runner: `20221121.1`

OS of the machine running the runner: `macos-12`

## What's not working?
See above.

## Job Log Output

The output of the `actions/setup-dotnet` job looks relevant, as on the bad version it states the requested version of dotnet is already installed:

```
Run actions/setup-dotnet@v1.9.0
  with:
    dotnet-version: 6.0.x
  env:
    dotnet-version: 6.0.x
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.0/x64
/Users/runner/work/_actions/actions/setup-dotnet/v1.9.0/externals/install-dotnet.sh --version 6.0.403
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: .NET Core SDK version 6.0.403 is already installed.
dotnet-install: Adding to current process PATH: `/Users/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
/Users/runner/.dotnet:/Users/runner/hostedtoolcache/Python/3.11.0/x64/bin:/Users/runner/hostedtoolcache/Python/3.11.0/x64:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/[2](https://github.com/dafny-lang/dafny/actions/runs/3538283931/jobs/5938991371#step:4:2).9.1/x6[4](https://github.com/dafny-lang/dafny/actions/runs/3538283931/jobs/5938991371#step:4:4)
```

Whereas on the previous version you can see it downloading dotnet instead:

```
Run actions/setup-dotnet@v1.9.0
  with:
    dotnet-version: 6.0.x
  env:
    dotnet-version: 6.0.x
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.0/x64
/Users/runner/work/_actions/actions/setup-dotnet/v1.9.0/externals/install-dotnet.sh --version 6.0.403
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-osx-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-osx-x64.tar.gz
dotnet-install: Adding to current process PATH: `/Users/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
/Users/runner/.dotnet:/Users/runner/hostedtoolcache/Python/3.11.0/x64/bin:/Users/runner/hostedtoolcache/Python/3.11.0/x64:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/[2](https://github.com/dafny-lang/dafny/actions/runs/3538283931/jobs/5941155148#step:4:2).9.1/x6[4](https://github.com/dafny-lang/dafny/actions/runs/3538283931/jobs/5941155148#step:4:4)
```
