### ISSUE TITLE
github context not parsed correctly under defaults key

### ISSUE THREAD

**Issue by Bilge** [actions/runner#2292]
**Describe the bug**
`${{ github.workflow }}` cannot be parsed under `defaults:`.

**To Reproduce**
```yaml
name: Symfony quickstart

defaults:
  run:
    working-directory: ${{ github.workflow }}
```

**Expected behavior**
Working directory is set to `Symfony quickstart`.

## Runner Version and Platform
GitHub hosted

## What's not working?
It should be possible to use the workflow name as the working directory name, but it fails to even parse.

>Invalid workflow file: .github/workflows/Quickstart Symfony.yaml#L5
The workflow is not valid. .github/workflows/Quickstart Symfony.yaml (Line: 5, Col: 24): Unrecognized named-value: 'github'. Located at position 1 within expression: github.workflow
