### ISSUE TITLE
Confusing error: Invalid type for `on`

### ISSUE THREAD

**Issue by dimaqq** [actions/runner#2344]
[apologies if I filed this under the wrong repo, please move if that's the case]

If the user makes a mistake, all they see is this output:

```
Error: .github#L1
Invalid type for `on`
```

Can you guess what the error was?

Here are the common mistakes and the confusing errors that are currently triggered, for other developers to refer to:

```yml
---
"on":
  workflow_call:
    inputs: tag
```

Error: `Invalid type for "on"`

```yml
---
"on":
  workflow_call:
    inputs:
      tag:
```

Error: `Unexpected value '' Unexpected type 'NullToken' encountered while reading 'input tag'. The type 'MappingToken' was expected.`

```yml
---
"on":
  workflow_call:
    inputs:
      tag:
        required: true
```

Error: `Required property is missing: type The given key 'type' was not present in the dictionary.`

```yml
---
"on":
  workflow_call:
    inputs:
      tag:
        type: string
```

OK

Or to keep it simple, observe that YAML is a super-set of JSON:
```yml
"on":
  workflow_call:
    inputs: {tag: {type: string, required: true}}
```

OK
