### ISSUE TITLE
Ancestors included in conditional expressions when only parents should be included 🕵️‍♂️

### ISSUE THREAD

**Issue by alexandar1000** [actions/runner#2346]
**Describe the bug**
Given dependant jobs D -> A -> C <- B, and given that A and B might be skipped, I would like C not to run when:
a) A and B do not contain at least on successful job,
b) any of the jobs including C are cancelled, and
c) D has ran successfully

To solve all of these, I have used:
`!cancelled() && contains(needs.*.result, 'success')`

However, this does not prevent C from running if D is successful even if it is not the direct predecessor in the graph, and C needs only A and B.

**To Reproduce**

1. Create four jobs A, B, C, and D,
2. Configure the needs statement for C to depend on A and B,
3. Configure the needs statement for A to depend on D,
4. Set the if condition for both A and B to false to force both to skip,
5. Set the if condition on C to !cancelled() && contains(needs.*.result, 'success'),
6. Run the workflow,
7. Step C is executed even though neither A nor B have successfully ran.

Alternatively, use the following code:
```
name: Test
on:   
  push:

jobs:
  D:
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo D
  A:
    needs: [D]
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo B
  C:
    runs-on: ubuntu-latest
    needs: [A,B]
    if: ${{ !cancelled() && contains(needs.*.result, 'success') }}
    steps:
      - run: echo C
```

**Expected behavior**
The expression !cancelled() && contains(needs.*.result, 'success') should evaluate to false and job C should not run.

## Runner Version and Platform
Version of your runner? **ubuntu-latest**

OS of the machine running the runner? **Linux**

## What's not working?
![Screenshot from 2022-12-29 19-59-55](https://user-images.githubusercontent.com/27826165/210005915-00c987da-ca5b-4cf6-915b-6716742fb405.png)
![Screenshot from 2022-12-29 20-00-19](https://user-images.githubusercontent.com/27826165/210005963-fe4d1bd7-8543-4b69-a169-efb3a6f137bd.png)

**Comment by alexandar1000** [comment]
After a great festive debugging session :santa:, replacing the `contains(needs.*.result, 'success')` function with individual conjuncts as in the code bellow, makes this issue goes away.

This make it seem that it might be related to the contains function and how the wildcard operator processes the needs argument.

Could you please tell me whether I am overlooking something obvious, should I open another issue, or should I do something else?

```
name: Test
on:   
  push:

jobs:
  D:
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo D
  A:
    needs: [D]
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo B
  C:
    runs-on: ubuntu-latest
    needs: [A,B]
    if: |
      !cancelled() && 
      (
        needs.A.result == 'success' || 
        needs.B.result == 'success' 
      )
    steps:
      - run: echo B
```

**Comment by ruvceskistefan** [comment]
Hey @alexandar1000,
`contains(needs.*.result, 'success')` returns string representation of boolean so you can do something as below
`contains(needs.*.result, 'success') == 'true'`

Working example
```
name: Test
on:   
  push:

jobs:
  D:
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo D
  A:
    needs: [D]
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo B
  C:
    runs-on: ubuntu-latest
    if: always() && contains(needs.*.result, 'success') == 'true'
    needs: [A,B]
    steps:
      - run: echo contains(needs.*.result, 'success')  # output will be false
```

I'll close this issue for now, if you still have problem with your yaml file feel free to reopen it and we will investigate further.
