### ISSUE TITLE
Github context not available in reusable workflows

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [actions/runner#2349]
Filing this as a bug since the behaviour does not seem to adhere to the docs.

**Describe the bug**

According to the [docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows):

> When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. 

However, this does not seem to be the case.

**To Reproduce**

1. Invoke a reusable workflow, passing the context as input.

```yaml
  set-tag:
    name: set the build branch and image tag
    needs:
      - set-ref
    uses: MyOrg/my-repo/.github/workflows/reusable.yaml@master
    with:
      push_to_prd: ${{ inputs.push_to_prd }}
      tag: ${{ inputs.manual_version }}
      ref: ${{ needs.set-ref.outputs.ref }}
      event: ${{ github.event }}
```

**Expected behavior**
The `event` name (e.g. `push`) should be passed as `input` to the invoked / reusable workflow

## Runner Version and Platform
GH hosted runners

OS of the machine running the runner? OSX/Windows/Linux/...

`ubuntu-latest`

## What's not working?

The job above that calls the reusable workflow fails:

```
The template is not valid. .github/workflows/image_build.yaml (Line: 56, Col: 14): A mapping was not expected
```

due to this line: `event: ${{ github.event }}`
