### ISSUE TITLE
`needs.*` includes implicitly dependent jobs in job level if

### ISSUE THREAD

**Issue by cfbao** [actions/runner#2356]
**Describe the bug**

`needs.*` includes implicitly dependent jobs in job level `if`.
This affects both `needs.*.result` and `needs.*.outputs`.
This does _not_ affect job level `env`.

**To Reproduce**

Run the following workflow

```yaml
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.out.outputs.out }}
    steps:
      - id: out
        run: echo "out=1" >> "$GITHUB_OUTPUT"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"

  test-output:
    needs: job2
    if: contains(needs.*.outputs.out, '1')
    runs-on: ubuntu-latest
    env:
      NEEDS: ${{ toJSON(needs) }}
      CONDITION: ${{ contains(needs.*.outputs.out, '1') }}
    steps:
      - run: |
          echo "$NEEDS"
          echo "$CONDITION"
```

`test-output` would run and log the following

```
{
  "job2": {
    "result": "success",
    "outputs": {}
  }
}
false
```

You can see the same expression used in `if` evaluated to `false` when used in `env`, but the job ran nonetheless.

A more comprehensive repro (for both `needs.*.outputs` and `needs.*.result`) can be found here:
https://github.com/Brightspace/cbao-scratch/actions/runs/3863139528/workflow

**Expected behavior**

Job `test-output` doesn't run, because the only job in its `needs` (i.e. `job2`) doesn't have an `out` output set to `1`.

More generally, I should be able to check both outputs and result of all _directly_ dependent jobs (via `needs.*`) in job level `if`.
I have a use case illustrated by the following diagram, where `final` should run if at least one of `job-n` is successful, but not if all of `job-n` are skipped. I can't succinctly express this logic using `needs.*` right now, because `prep` is polluting `needs.*`.

```mermaid
flowchart LR
  prep --> job-1
  prep --> job-2
  prep --> job-3
  job-1 --> final
  job-2 --> final
  job-3 --> final
```

## Runner Version and Platform

Image: ubuntu-22.04
Version: 20221212.1
Linux

**Comment by ruvceskistefan** [comment]
Hey @cfbao 

Let me know if code below is helpful for your scenario

```
name: needs Test
on:   
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - run: echo prep
  job1:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - run: echo Job1

  job2:
    needs: prep
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo Job2
      
  job3:
    needs: prep
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo Job3

  test-output:
    runs-on: ubuntu-latest
    needs: [job1,job2,job3]
    if: ${{ always() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJSON(needs) }}
      CONDITION: ${{ contains(needs.*.result, 'success') }}
    steps:
      - run: |
          echo "$NEEDS"
          echo "$CONDITION"
```
