### ISSUE TITLE
Using 'diff' as job_id breaks outputs between jobs

### ISSUE THREAD

**Issue by Flydiverny** [actions/runner#2361]
**Describe the bug**
When using a job with id `diff` and trying to get the jobs output in another job using `needs` dependency the outputs will always be null.

Note that when using the actions debug it will appear like the job `diff` will actually set the expected outputs but they are not accessible in the job needing them.

**To Reproduce**
1. Create a workflow like this:
```yaml
on:
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
    steps:
      - id: step1
        run: echo "output1=hello-world" >> $GITHUB_OUTPUT

  diff:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
    steps:
      - id: step1
        run: echo "output1=hello-world" >> $GITHUB_OUTPUT

  job2:
    needs: [diff, job1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "outputs: ${{ toJSON(needs) }}"
```

3. Run the workflow!
4. See output of job2 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/326929/211353574-f41b788f-074e-40b9-8a68-ddfa647fa870.png">

**Expected behavior**

In the example above we have `job1` and `diff` which should both output the same `output1` with a value of "hello-world". In the case of the job with id `diff` the output will not be accessible.

## Runner Version and Platform

ubuntu-latest,
  Image: ubuntu-22.04
  Version: 20221212.1

## What's not working?
Please include error messages and screenshots.

See in screenshot how `job1` has outputs but not `diff`, both output and result is missing.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/326929/211353574-f41b788f-074e-40b9-8a68-ddfa647fa870.png">

## Job Log Output

```
outputs: {
  diff: {
    result: null,
    outputs: {}
  },
  job1: {
    result: success,
    outputs: {
      output1: hello-world
    }
  }
}
```

## Runner and Worker's Diagnostic Logs
N/A
