### ISSUE TITLE
Action matrix schema is invalid

### ISSUE THREAD

**Issue by ben-wilson-peak** [actions/runner#2366]
**Describe the bug**
The schema for validating actions is invalid for matrices. In the online editor it marks a job as invalid, but the runner understands the syntax and is arguably a completely valid and useful way to define the matrix

**To Reproduce**
1. Using the online action editor
2. Create a new action
3. Add a matrix like this:
```
    strategy:
      matrix:
        bar:
          - os: macos-latest
            version: 12
            environment: prod
          - os: windows-latest
            version: 16
          - os: ubuntu-latest
            version: 16
```
4. You should see (in the example foo) is underlined with `Matrix options must only contain primitive values`

**Expected behavior**
Linting should not highlight the matrix as invalid, the runner accepts it and is presumably supported syntax

## Runner Version and Platform
N/A

## What's not working?
See instructions

![image](https://user-images.githubusercontent.com/117664255/211821045-20837a8c-94c0-407b-8d1d-9cb238fd3337.png)

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by ben-wilson-peak** [comment]
I've filed this as a bug under this repository because the schema is located here, nor is this a support request. I'd like clarification on if it is intended to be supported and if so this should be considered a valid bug request.
Much appreciated for any help!

**Comment by ruvceskistefan** [comment]
Hey @ben-wilson-peak,

custom names are for primitive values, for example 

```
os: [macos-latest, windows-latest, ubuntu-latest]
```

If you want array of objects you can use `include` as shown below

```
matrix:
  include:
       - os: macos-latest
          version: 12
          environment: prod
       - os: windows-latest
          version: 16
       - os: ubuntu-latest
          version: 16
```
