### ISSUE TITLE
YAML Error: Did not expect 'map' when using Default group in runs-on

### ISSUE THREAD

**Issue by tyler-jewell** [actions/runner#2369]
**Describe the bug**
When I try to use ```group: Default``` as the `runs-on` argument in the workflow yaml, an error appears saying 'Did not expect 'map''

**To Reproduce**
Create a workflow yaml in .github/workflows:

```yaml
name: Test and analyze app

on: [push]

jobs:
  test_and_analyze:
    runs-on:
      group: Default
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: Check Flutter
        run: flutter --version

      - name: ✨ Check Formatting
        run: flutter format --set-exit-if-changed lib test

      - name: 🕵️ Analyze
        run: flutter analyze lib test

      - name: 🧪 Run Tests
        run: flutter test --coverage --test-randomize-ordering-seed random -x e2e
```

Configure YAML to use https://json.schemastore.org/github-workflow.json as the formatter. 

**Expected behavior**
The YAML should have no errors since this is a valid argument per https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job

## Runner Version and Platform
self-hosted macos

## What's not working?
![image](https://user-images.githubusercontent.com/72859335/212397370-9b23e094-fc72-4bf3-ab7c-b70e0c5c2135.png)

![image](https://user-images.githubusercontent.com/72859335/212397405-d5fab796-9abb-4277-89e9-50c9fe6b0902.png)
## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.
