### ISSUE TITLE
"Unrecognized named-value: 'env'. Located at position 1 within expression" when used in reusable workflow jobs

### ISSUE THREAD

**Issue by nive-copia** [actions/runner#2372]
**Describe the bug**
Usage of env in workflow that uses reusable workflow generates "Unrecognized named-value: 'env'. Located at position 1 within expression"

**To Reproduce**
Use the following yml:
```
name: Test Workflow

on:
  push:

env:
  SOMETHING: 1000

  test:
    name: call workflow
    uses: ./.github/workflows/callee.yml
    secrets: inherit
    with:
      run_url: "{run_url}"
      message: ${{ env.SOMETHING }}
```

**Expected behavior**
env.SOMETHING is usable and can be passed into reusable workflow

**Actual behavior** 

```The workflow is not valid. .github/workflows/create-branch.yml (Line: #, Col: ##): Unrecognized named-value: 'env'. Located at position 1 within expression: env.SOMETHING```

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner?
ubuntu-latest

## What's not working?
![image](https://user-images.githubusercontent.com/113383549/212578036-3f333f32-73aa-4e1f-aac6-e611715b4e6c.png)

**Comment by GrayJack** [comment]
I'm having the same issue

**Comment by nicole0707** [comment]
I have the same issue, there is workaround to use `$GITHUB_OUTPUT` instead.

**Comment by RajrupDasid** [comment]
Having the same issue . When it's going to fix?
any work around of it?

**Comment by nive-copia** [comment]
Hi GHA folks: Any update on providing this capability? Some of us are using workarounds, including the one suggested by @nicole0707. But, having this feature will make the intent very clear and clean.

**Comment by Gideavlik** [comment]
hello! if i can help u. or something need to do.say step b step

**Comment by lucasmellos** [comment]
workaround is to use as a secret in the main workflows and then you'll be able to parse it to env in the reusable workflow like 
```
env:
   SECRET: ${{secrets.MY_SECRET}}
```

**Comment by hoancs** [comment]
I'm having the same issue. Have we got any update?

**Comment by srinadhbh** [comment]
> workaround is to use as a secret in the main workflows and then you'll be able to parse it to env in the reusable workflow like
> 
> ```
> env:
>    SECRET: ${{secrets.MY_SECRET}}
> ```

In my case, git is considering subscription id as a secret. I am trying to print NSG/ASG id and git is omitting the output.

**Comment by hurricup** [comment]
Trying to use this approach to workaround #520 and bummer...

**Comment by hurricup** [comment]
It is also unavailable in called workflow. I tried to move check into there and got:
```
b5676355294c9b6943a4a68c5 (Line: 14, Col: 9): Unrecognized named-value: 'env'. Located at position 1 within expression: env.COVERALLS_REPO_TOKEN Camelcade/Perl5-IDEA/.github/workflows/_coverage.yml@d08cee137234bd0b5676355294c9b6943a4a68c5 (Line: 14, Col: 9): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ env.COVERALLS_REPO_TOKEN }}
    secrets: inherit
```

Called workflow is:
```
# re-usable workflow to merge and process coverage
name: Coverage

on:
  workflow_call:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  analyze:
    name: Analysis
    runs-on: ubuntu-latest
    if: ${{ env.COVERALLS_REPO_TOKEN }}
....
```

**Comment by carrill1** [comment]
I'm having the same issue 😐

**Comment by iBasit** [comment]
+1

**Comment by alexl-shopware** [comment]
+1. Get this fixed github, cmon.

**Comment by whsalazar** [comment]
The env context is not available from jobs.<job_id>.with.<with_id>. See https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#context-availability

**Comment by hurricup** [comment]
@whsalazar the question is what the reason behind this? And if there is no real reason, would be nice to have it.

**Comment by harrisrobin** [comment]
I guess I wasted 30 mins of my life and ended up here like the rest of us

**Comment by whsalazar** [comment]
You can't use the env context outside steps, [as described in the docs](https://docs.github.com/en/actions/learn-github-actions/contexts#env-context):

You can use the env context in the value of any key in a step except for the id and uses keys.  Feel free to submit feedback and feature request at https://github.com/orgs/community/discussions/categories/actions?discussions_q=is%3Aopen+env+jobs+category%3AActions

**Comment by guanyingjie** [comment]
I have the same issue, hope github action can pass the env variable in the furture

**Comment by rijnhard** [comment]
Nasty workaround: https://stackoverflow.com/a/74217028/834280

**Comment by kschaer** [comment]
Same problem here. I have several reusable workflows that should receive the same `with` inputs - it's a shame I cannot simply set up the environment variables in the parent (caller) workflow and pass to the reusable (child) workflows.

**Comment by miguelangelgil** [comment]
The solution is to pass the environment variables as the output of a job. Like this sample:

```
name: main
on: 
  push: { branches: [main] }

env:
    SOME_VAR: ${{ env.SOME_VAR }}
    OTHER_VAR: ${{ env.OTHER_VAR }}
jobs:
get-env:
    name: Get Enviroment VAR
    needs: [cache]
    if: ${{ always() }}
    runs-on: ubuntu
    outputs:
      SOME_VAR: ${{ env.SOME_VAR }}
      OTHER_VAR: ${{ env.OTHER_VAR }}
    steps:
      - run: echo "null"

  call-next-workflow:
    needs: [get-env]
    if: ${{ always() }}
    uses: ./path/reusableWrokflow.yml@main
    with:
      SOME_VAR: ${{ needs.get-env.outputs.SOME_VAR }}
      OTHER_VAR: ${{  needs.get-env.outputs.OTHER_VAR }}
```
For some reason the job that passes the varaibles has to have steps and a run.

**Comment by ffineis** [comment]
> 

Hey this got me really close - at least now i can reference names of env vars I need in `with`, but this approach won't work if the original env variable is a secret since GH doesn't export outputs that are secrets.

```
Warning: Skip output 'MY_SECRET' since it may contain secret.
```

**Comment by miguelangelgil** [comment]
@ffineis To pass secrets use `secrets` instead `with`. In the above case i use `secrets: inherit` that take the secrets that you define in yours reusable workflow if they are accessible  from the current workflow.

**Comment by ffineis** [comment]
@miguelangelgil yes thanks `secrets: inherit` was the trick to expose secrets in the reusable workflow - thx! Wish I had seen this after 3 hours of smashing head in.

**Comment by joshjohanning** [comment]
You can use `${{ vars.MY_VAR }}` stored in the repository instead of `env` when referencing in reusable workflows. Not perfect, but it works

**Comment by sajati** [comment]
2023 and still have the same issue

**Comment by SerGeRybakov** [comment]
Still doesn't work. It's weird.

**Comment by cvetinovic** [comment]
+1 same issue

**Comment by rmogio-encora** [comment]
+ 1

**Comment by pin007** [comment]
Still being an issue.

**Comment by ton77v** [comment]
+💯

**Comment by chrisk8er** [comment]
just use ```vars``` instead of ```env```

**Comment by Mansi-1** [comment]
@chrisk8er do u mean instead of ${{ env.SOMETHING }}, use ${{ var.SOMETHING }}?(this isn't working) can u give an eg?

**Comment by chrisk8er** [comment]
> @chrisk8er do u mean instead of ${{ env.SOMETHING }}, use ${{ var.SOMETHING }}?(this isn't working) can u give an eg?
Yes...

```
${{ vars.SOMETHING }}
```

**Comment by Ni55aN** [comment]
+1

**Comment by FredericVaugeoisFlo** [comment]
+1

**Comment by dleitter** [comment]
+1

**Comment by felipefrocha** [comment]
+1

**Comment by ansctrianta** [comment]
+1

**Comment by JackOdell** [comment]
+1

**Comment by h-rasi** [comment]
Why this issue is closed?!!! We are still seeing the error on our shared workflows that the `env` is unrecognised.

**Comment by ansctrianta** [comment]
> Why this issue is closed?!!! We are still seeing the error on our shared workflows that the `env` is unrecognised.

+1

**Comment by lpsm-nuageit** [comment]
+1

**Comment by Yingsheng-eroad** [comment]
+1

**Comment by kosswald** [comment]
+1

**Comment by vsamofal** [comment]
+1

**Comment by VLuizNoggo** [comment]
+1

**Comment by vsamofal** [comment]
I do use a prepared job for that, works quite nicely, no issues so far

example: 

```
jobs:
  prepare:
#    if: github.event.pull_request.merged == true || (github.event_name == 'workflow_dispatch' && startsWith(env.BRANCH_NAME, 'release/'))
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.define-envs.outputs.environment }}
      base-name: ${{ steps.define-envs.outputs.base-name }}
      image-tag: ${{ steps.define-envs.outputs.image-tag }}
      docker-url: ${{ steps.define-envs.outputs.docker-url }}

    steps:
      - name: Define envs information
        id: define-envs
        run: |
          echo BRANCH_SLUG=$(echo ${{ env.BRANCH_NAME }} | sed 's/[^a-zA-Z0-9]/-/g') >> $GITHUB_ENV
          echo image-tag=${{ startsWith(env.BRANCH_NAME, 'release/') && env.BRANCH_SLUG || format('{0}-{1}', github.run_id, github.run_attempt) }} >> $GITHUB_OUTPUT
          echo environment=${{ inputs.environment || 'dev' }} >> $GITHUB_OUTPUT
          echo base-name=${{ startsWith(env.BRANCH_NAME, 'release/') && 'last_release' || 'main' }} >> $GITHUB_OUTPUT
          echo docker-url=${{ format('{0}.dkr.ecr.{1}.amazonaws.com', vars.DEPLOYMENT_AWS_ACCOUNT_ID, vars.DEPLOYMENT_AWS_ACCOUNT_REGION) }} >> $GITHUB_OUTPUT

```

**Comment by AdamJudge** [comment]
+1 
Extremely frustrating implementing new ideas benefiting DRY methods of coding. Our workflows have up to 16 jobs, and we only want certain ones to run on certain branches.

We moved from GitLab years ago, and are still missing what we thought would be key/obvious features

**Comment by lure8225** [comment]
+1 
we intend to have a env variable set in the beginning by evluating some expression and then use this to conditionally trigger jobs. With this problem this will not work and the documentation clearly states that all contexts should be available.

**Comment by shgnplaatjies** [comment]
I bumped into this; and resolved it by using 
`${{ needs.your-job-name.outputs.YOUR_NON_SENSITIVE_VAR }}`

It's not a long-term solution since it leads to a deprecation warning, nor is it appropriate for sensitive variables: 

"
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
"

**Comment by tompreston** [comment]
We were trying to use a repeated container image name. For anyone still searching, [this part](https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#context-availability) of the docs explained it for us. The `env` context is not available in the `jobs.<job_id>.container` workflow key.
![Screenshot 2024-06-04 at 09 50 59](https://github.com/actions/runner/assets/669843/3b2aa163-10e4-486c-8dfa-b169ebb0616a)

It looks like [YAML anchors are not supported](https://github.com/actions/runner/issues/1182) and there might be a route forwards with repository variables in the `vars` context, but unfortunately it doesn't follow the same branch protection rules. For example requiring a review to merge to master.

**Comment by rupert-jung-mw** [comment]
This is highly unexpected and should just work.

**Comment by dror-g** [comment]
For others that might end up here, this is what worked for me in the interim for multi-line matrix passing between jobs
Credit to [Manu Magalhães](https://manumagalhaes.medium.com/github-actions-one-liner-solution-to-multiline-output-c228727722f8)  @magmanu (Thanks!!!)

In Github repo environment I define a multi-line var called `ENV_PARAMS_MATRIX`:
```
[
  {
  "name": "service-one",
  "params": {
    "SERVER_URL": "https://dev.example.com",
    "type": "express"
    }
  },
  {
  "name": "service-two",
  "params": {
    "SERVER_URL": "https://prod.example.com",
    "type": "flask"
    }
  }
]
```

<details><summary> <-- Matrix can also be defined in Workflow itself without repo env vars </summary>
<p>

```
name: example workflow
on: [push, fork]
env:
  AWS_REGION: aq-east-1
  ENV_PARAMS_MATRIX: |
    [
      {
      "name": "service-one",
      "params": {
      ...
      ...
```

</p>
</details>  
  
  
Jobs defined as:
```
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout build repo
      uses: actions/checkout@v4
    
    # Rest of job steps .. then this:
    
    - name: Prepare multiline payload
      id: payload
      run: |
          payload=$(printf '${{ vars.ENV_PARAMS_MATRIX }}')
          echo "PAYLOAD<<EOF"$'\n'"$payload"$'\n'EOF >> "$GITHUB_OUTPUT"
      shell: bash

    outputs:
      payload: ${{ steps.payload.outputs.PAYLOAD }}

  # Then second job uses matrix payload:

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        myservers: ${{ fromJSON(needs.build.outputs.payload) }}

    steps:

    # Consume matrix params in step
    - name: Fill iserver name in task definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        container-name: ${{ matrix.myservers.name }}-backend
```

This `printf` + `PAYLOAD<<EOF` is the best method I found of formatting multi-line matrix def.

**Comment by lukian-tabandzhov** [comment]
Hope this would help someone:

I recently faced the issue of not been able to access env form the job context. 

the solution is a bit tricky but covers:

- avoid using a separate job just to output predefined job matrix
- avoid using vars
- user is allowed to choose a matrix predefined group when running the workflow


`
name: Predefined Matrix
on:
  workflow_dispatch:
    inputs:
      matrix_group:
        type: choice
        options:
          - MATRIX-A
          - MATRIX-B
        description: 'Select Matrix Group'
        required: true

jobs:
  # 1. we define json string using the "format" expression as multiline strings as input parameter fails :/
  # 2. the result of the format expression (i.e. JSON string) we provide as input parameter to the fromJSON expression.
  # 3. we take the value of the user selected input form the fromJSON result object to pass as a matrix value
  #
  multi-deploy:
    strategy:
      matrix:
        option: ${{
          fromJSON(
            format(
              '{{{0}, {1}, {2}, {3}, {4}}}',
              '"MATRIX-A":["matrix A - value 1", "matrix A - value 2", "matrix A - value 3"]',
              '"MATRIX-B":["matrix B - value 100", "matrix B2 - value 101"]',
            )
          )[ inputs.matrix_group ] }}
    name: Processing ${{ matrix.option }}
    uses: ./A-REUSABLE-WORKFLOW.yaml
    with:
      option: ${{ matrix.option }}

`

**Comment by esaporski** [comment]
![image](https://github.com/user-attachments/assets/6f15cf4e-4b61-4ee0-80e0-4411e47d03fa)

**Comment by ulidtko** [comment]
@anajuliabit I'm mostly sure that exactly 0 of GH devs are subscribed to every issue and are reading every comment. You'd have to summon their attention via explicit pings.

For example, ping @ericsciple @TingluoHuang

**Comment by ericsciple** [comment]
The `env` context is not support under `jobs.<job_id>.with.<with_id>`

Refer https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability

**Comment by ericsciple** [comment]
To elaborate a bit more, `env` is for process environment variables. Also, secrets can be into `env`, so if `secrets` isn't allowed, then `env` isn't allowed either.

Similarly, the `secrets` context is generally only allowed within a job. It is not allowed within fields that are used by our server to manage the workflow orchestration.

**Comment by ericsciple** [comment]
Skimming the replies regarding use cases...

One solution might be to check-in a script which sets up your job environment variables. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable

Not perfect, but might work for many scenarios.

**Comment by ericsciple** [comment]
Also note, reusable workflows are sort of a security boundary. That is why `env` values don't flow to reusable workflows. Otherwise callers could influence the jobs in ways unintended by the reusable workflow author. E.g. consider https://github.blog/changelog/2022-03-21-github-actions-restrict-self-hosted-runner-groups-to-specific-workflows/

**Comment by ulidtko** [comment]
Hi @ericsciple thanks for responding :pray: 

I know it's tough to unbundle the assortment of various issues that are being conflated into one. Perhaps you can think of error message improvements that'd send people to corresponding docs explaining that certain usage isn't supported, neither will be? That'd be super helpful to reduce confusion, as apparently there's a lot of difficulty in locating the authoritative docs.

For example, I'm coming from a (prematurely closed) issue #1189 which reports the same error — but **without** reusable workflows, secrets, and under `jobs.<job_id>.env` (not in `jobs.<job_id>.with.<with_id>`).

I.e. this does not work, throws the error:

```yaml
jobs:
  acme-bundle:
    runs-on: ubuntu-20.04
    needs: build
    env:
      # if triggered from a branch containing /, use "wip", otherwise tag name
      version: ${{ contains(github.ref_name, '/') && 'wip' || github.ref_name }}
      fullfilename: acme-${{ env.version }}.${{ github.sha }}.bundle
    steps:
      [...]
      - name: Pack
        run: tar -czf $fullfilename --format posix -C DIST .
      - name: Upload
        run: aws s3 cp $fullfilename s3://$BUCKET/ACME/$version/$fullfilename

#-- NOTE: the workflow author wants both values as env-vars, to be used in shell steps.
#-- NOTE: the second var is defined using the first var ${{ env.version }}

# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
# The workflow is not valid. .github/workflows/release.yml (Line: 190, Col: 21):
# Unrecognized named-value: 'env'. Located at position 1 within expression: env.version
```

Can this be helped with somehow?

**Comment by ericsciple** [comment]
+1 thanks @ulidtko - good feedback. I will forward along internally.

**Comment by ben5311** [comment]
This didn't work back in late 2021 when reusable workflows were introduced and it still doesn't work three years later in 2024. See you in 3 years.

**Comment by KornevNikita** [comment]
Another +1. Hopefully by the 1001st comment we'll get this working.

**Comment by ulidtko** [comment]
Ping @ericsciple, any update you could give publically?..

**Comment by ab-smith** [comment]
Another +1 indeed; I understand that env is probably not ideal but we should have a proper alternative for reusibility.

**Comment by esaporski** [comment]
Soon we can wish this issue a Happy Birthday! 🎂

**Comment by Armadillidiid** [comment]
It seems like I'm early to the party. Just encountered this issue

**Comment by magusd** [comment]
well, looks like it's hopeless waiting for a solution, will try one of the workarounds

**Comment by roeezolantz** [comment]
Any chance? 😢

**Comment by hugtalbot** [comment]
Wow, we just faced this issue and discovered it's a real issue, not yet solved 😲 
Any solution would be appreciated

**Comment by ctw00412** [comment]
+1

**Comment by dyahnov** [comment]
Same here today, wtf?

**Comment by munyaradzi-hobbstech** [comment]
This needs to be fixed guys

**Comment by xjohnwu** [comment]
This needs to be fixed

**Comment by esaporski** [comment]
Forget about it guys, GitHub Actions is abandonware.

**Comment by rik-howard** [comment]
Please fix this

**Comment by mirek-capgemini** [comment]
`${{ vars.ACR_USERNAME }}`

this is valid syntax for variables

**Comment by ulidtko** [comment]
Github's [vars][] ≠ environment variables @mirek-capgemini 🤦 

[vars]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#vars-context

**Comment by nihal-aws** [comment]
Over 2 years old. Come on team.....

**Comment by dmavaleix** [comment]
+1
Just encountered this issue.
Interesting to note that some generative AIs (I tried with ChatGPT - GPT-4o) are generating buggy code because of that, and fail to identify and fix the issue, even when provided with the error message `Unrecognized named-value: 'env'`.
I guess it makes sense, as one would really expect that using `env` in this context should work 🤔

**Comment by BigNateBombBomb** [comment]
I have run into this issue today, so figured I would give my two cents for anyone out there still stuck on this, since the documentation is woefully inadequate.

The problem is that setting environment variables is scoped to runners. Anything you set there will be available in the appropriate runner (global, job, step, etc). Even setting environment variables for a job that you don't actually use a runner on is pointless (ie - using 'uses' to launch a secondary workflow)

So this setup... 

```
name: Build Application
run-name: Build Application 🚀

on:
  push:
    branches:
      - my_branch

env:
  REPO: ${{ github.event.repository.name }}
  BRANCH: ${{ github.head_ref || github.ref_name }}
  COMMIT: ${{ github.sha }}
```

Works perfectly fine for this job 

```
jobs:

  test-things:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "REPO: $REPO"
          echo "BRANCH: $BRANCH"
          echo "COMMIT: $COMMIT"
```

But not for this one...

```
jobs:

  do-work:
    uses: org/some-workflow-repo@main
    with:
      sha: $COMMIT
      repo: $REPO
      branch: $BRANCH
```

because the second example is not within the scope of a runner. The runner isn't set until later and none of the environment variables are passed to it through 'with', so it has no idea about anything in our setup.

You need to set the variables some other way. What I ended up doing is creating a job that sets those variables as outputs and then just make the other jobs wait for that one to finish

```
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      REPO: ${{ github.event.repository.name }}
      BRANCH: ${{ github.head_ref || github.ref_name }}
      COMMIT: ${{ github.sha }}
    steps:
       - run: echo "All set!"

  do-work:
    uses: org/some-workflow-repo@main
    needs: [ setup ]
    with:
      sha: ${{ needs.setup.outputs.COMMIT }}
      repo: ${{ needs.setup.outputs.REPO }}
      branch: ${{ needs.setup.outputs.BRANCH }}
```

Not the most elegant solution but it gets the job done :) I believe the reason they haven't 'fixed' this yet is because it is working as intended. 

Hope this helps!
