### ISSUE TITLE
Unable to use `env` variable in a container name

### ISSUE THREAD

**Issue by lukasz-mitka** [actions/runner#2394]
**Describe the bug**
I'm trying to use env variable inside container name and I'm getting Startup Failures.

**To Reproduce**
Use env variable in a container name specifier. Example:
```yaml
name: env in container name

on:
  push:

env:
  IMAGE: ubuntu:18.04

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ env.IMAGE }}
    steps:
      - name: env
        run: echo ${{ env.IMAGE }}
```

**Expected behavior**
Workflow should start with container from `env.IMAGE`
`env` context should be available: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

## Runner Version and Platform
Can't tell, it doesn't start.

OS: Linux

## What's not working?
Workflow doesn't start.
> Status Startup failure

> Invalid workflow file: .github/workflows/env_container_name.yaml#L12
The workflow is not valid. .github/workflows/env_container_name.yaml (Line: 12, Col: 16): Unrecognized named-value: 'env'. Located at position 1 within expression: env.IMAGE

## Job Log Output
n/a

## Runner and Worker's Diagnostic Logs
n/a
