### ISSUE TITLE
Reusable workflow paths are too opinionated

### ISSUE THREAD

**Issue by mbrancato** [actions/runner#2399]
**Describe the bug**
Reusable / shared actions allow a lot of flexibility in their path, for example:

```yaml
steps:
- uses: <my-org>/<my-action>@<ref>
- uses: <my-org>/<my-repo>/<my-action>@<ref>
- uses: <my-org>/<my-repo>/actions/<my-action>@<ref>
- uses: ./../../<my-local-path>/<my-action>
```

However, reusable / shared workflows are too strict and opinionated, inexplicably requiring the top-level `.github` folder in the repo.

```yaml
jobs:
  foo:
    uses: <my-org>/<my-repo>/.github/workflows/<my-workflow>.yaml@<ref>
    uses: ./.github/workflows/<my-workflow>.yaml
```

where `/.github/workflows/` is required - no more no less

By making workflows and actions reusable across an organization, they effectively became a product of engineering effort. As such, we'd like to organize them like other code. Use cases here include being able to iterate thru workflow files / folders to generate documentation, and cleaner / more  well-understood code.

I know the [documentation calls these paths out](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow), however, I feel this a missed requirement in making actions and workflows sharable - and actions work using a more flexible pattern.

Additionally, workarounds to map them to a local path are non-workable because they require `./.github/workflows/` as well and cannot be stored elsewhere locally - actions can also do this whereas workflows cannot. We could map them to the expected `./.github/workflows/` but since that is inside the code repo being tested, it would trigger failures on tests for things like `git diff` etc.

**To Reproduce**
1. Create a repo specifically for shared actions and workflows
2. Create workflows for the shared action and workflow tests in `.github/workflows/`
3. Create developed workflows to be shared under `my-workflow/`

**Expected behavior**
Workflows can be used

## Runner Version and Platform
Linux

## What's not working?
```
Invalid workflow file
invalid value workflow reference: workflows must be defined at the top level of the .github/workflows/ directory
```

```
Invalid workflow file
invalid value workflow reference: references to workflows must be prefixed with format 'owner/repository/' or './' for local workflows
```
