### ISSUE TITLE
github actions doesn't STOP event there is success

### ISSUE THREAD

**Issue by limsaehyun** [actions/runner#2408]
We are using Github Actions to build CI and conduct Unit Test.

Github Actions is working without stopping despite the successful test as shown in the picture and the success icon.

There is a bug that does not stop testing even though it is successful.

I will attach the photo and pipeline where the error occurs.

<img width="1512" alt="스크린샷 2023-01-31 오후 6 15 01" src="https://user-images.githubusercontent.com/80076029/215718390-0fdcac70-cd46-48e1-978b-96794d5c631a.png">

unit-test.yml
```
on:
  pull_request:
    branches: 
    - dev
    - stg
    - main

jobs:
  unit-test:

    name: Unit test
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check flutter doctor
        run: flutter doctor

      - name: Install flutter packages
        run: flutter pub get
        
      - run: flutter analyze

      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Run Flutter unit tests
        run: flutter test --coverage --coverage-path=./coverage/lcov.info && lcov --remove coverage/lcov.info 'ios/*/*.swift' 'android/*/*.kt' 'android/*/*.java' 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/*/*.graphql.dart'


      - name: Report code coverage
        uses: onuii-dev/github-actions-report-lcov@v1.4.1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 10
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
