### ISSUE TITLE
Composite workflows should support timeout-minutes

### ISSUE THREAD

**Issue by GergelyKalmar** [actions/runner#2415]
**Describe the bug**
The following workflow currently fails:

```
name: Test integrations
on:
  schedule:
    - cron: '8 10 * * *'

jobs:
  run-python-tests:
    name: Run Python tests
    uses: logikal-io/github-workflows/.github/workflows/run-python-tests.yml@v4
    with:
      pytest-options: --fast
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    timeout-minutes: 10
```

The error:
```
The workflow is not valid. .github/workflows/test-integrations.yml (Line: 16, Col: 5): Unexpected value 'timeout-minutes'
```

**To Reproduce**
You can see the issue in a public repository under https://github.com/logikal-io/stormware/blob/main/.github/workflows/test-integrations.yml.

**Expected behavior**
I would expect `timeout-minutes` to keep working after refactoring steps into a reusable workflow, which is not the case currently.
