### ISSUE TITLE
Error parsing `fromJson` from a reusable "matrixed" workflow

### ISSUE THREAD

**Issue by ShutdownRepo** [actions/runner#2424]
# Describe the bug
It seems there is an error when using parsing JSON with `fromJSON` when already inside a "matrixed" nested workflow.

## what works, but doesn't fit my needs
- a job `pre_test` defines a JSON structure
- then ext job, `test`, uses the structure to populate a matrix
- the `test` job then proceeds to call a reusable workflow with a two-dimensional matrix. One dimension is the runner's architecture (arm64, amd64) and the other is the JSON structure.
- the problem here is that I'd like to have a specific JSON structure for each runner. To achieve that, the workflow needs to be changed a bit, to something that sadly, and inexplicably, fails.

## what would fit my needs, but doesn't work
- a job defines a one-dimensional matrix, for the runner's architecture
- it then proceeds to call a reusable workflow
- the called workflow starts with a first job `pre_test` that defines a JSON structure
- it then proceeds to a second job `test` that parses the JSON structure to create a matrix <-- error here
- the matrix is then iterated with another call to another workflow

The error (see https://github.com/ShutdownRepo/github-actions-nested-workflows/actions/runs/4118994038):
```
Error when evaluating 'strategy' for job 'test'. [...]/.github/workflows/test.yml@[...] (Line: 41, Col: 16): 
   Error parsing fromJson,[...]/github-actions-nested-workflows/.github/workflows/test.yml@[...] (Line: 41, Col: 16): 
      Error reading JToken from JsonReader. Path '', line 0, position 0.,[...]/github-actions-nested-workflows/.github/workflows/test.yml@[...] (Line: 41, Col: 16): 
         Unexpected type of value '', expected type: Sequence.
```

The way the JSON structure is passed to the matrix is exactly the same in both methods, but the runner fails at parsing when doing so from a "matrixed" reusable workflow.

# Reproduce

**entrypoint.yml**
```yaml
name: Main

on:
  push:
    branches:
      - '**'


jobs:
  belt_conveyor:
    name: Belt
    uses: ./.github/workflows/belt.yml
    with:
      SUPPORTED_ARCH: '["amd64","arm64"]'
```

**belt.yml**
```yaml
name: Belt

on:
  workflow_call:
    inputs:
      SUPPORTED_ARCH:
        required: true
        type: string

jobs:
  pre_test:
    name: L1 prepping matrix
    strategy:
      matrix:
        arch: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
    runs-on:
      - self-hosted
      - ${{ matrix.arch }}
    steps:
      - name: Create matrix
        id: prepare
        run: |
          echo "matrix_tests=[\"['aaa', 'bbb', 'ccc']\",\"['ddd', 'eee', 'fff']\"]" >> $GITHUB_OUTPUT
    outputs:
      matrix_tests: ${{ steps.prepare.outputs.matrix_tests }}
  test:
    name: L1 handling matrix
    needs:
      - pre_test
    if: ${{ always() && needs.pre_test.result == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
        batch: ${{ fromJson(needs.pre_test.outputs.matrix_tests) }}
    uses: ./.github/workflows/batch.yml
    with:
      ARCH: ${{ matrix.arch }}
      TESTS: ${{ matrix.batch }}
  nested:
    name: Calling L2 workflow
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
    uses: ./.github/workflows/test.yml
    with:
      ARCH: ${{ matrix.arch }}
```

**test.yml**
```yaml
on:
  workflow_call:
    inputs:
      ARCH:
        required: true
        type: string


jobs:
  pre_test:
    name: L2 prepping matrix
    runs-on:
      - self-hosted
      - ${{ inputs.ARCH }}
    steps:
      - name: Create matrix
        id: prepare
        run: |
          echo "matrix_tests=[\"['aaa', 'bbb', 'ccc']\",\"['ddd', 'eee', 'fff']\"]" >> $GITHUB_OUTPUT
    outputs:
      matrix_tests: ${{ steps.prepare.outputs.matrix_tests }}
  debug:
    name: L2 debug
    runs-on:
      - self-hosted
      - ${{ inputs.ARCH }}
    needs: pre_test
    if: ${{ always() && needs.pre_test.result == 'success' }}
    steps:
      - name: Read tests
        run: |
          echo "${{ needs.pre_test.outputs.matrix_tests }}"
          echo "${{ fromJson(needs.pre_test.outputs.matrix_tests) }}"
  test:
    name: L2 handling matrix
    needs: pre_test
    if: ${{ always() && needs.pre_test.result == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        batch: ${{ fromJson(needs.pre_test.outputs.matrix_tests) }}
    uses: ./.github/workflows/batch.yml
    with:
      ARCH: ${{ inputs.ARCH }}
      TESTS: ${{ matrix.batch }}
```

**batch.yml**
```yaml
on:
  workflow_call:
    inputs:
      ARCH:
        required: true
        type: string
      TESTS:
        required: true
        type: string

jobs:
  test:
    runs-on:
      - self-hosted
      - ${{ inputs.ARCH }}
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(inputs.TESTS) }}
    steps:
      - name: Print values
        run: |
          echo ${{ matrix.value }}
```

## Runner Version and Platform

Tested with runner version: `2.301.1`, on Linux (amd64) and macOS (arm64).

**Comment by ShutdownRepo** [comment]
Thanks to @trueneu creating a ticket, issue seems to be fixed
Orginial discussion: https://github.com/orgs/community/discussions/32023#discussioncomment-5266298
Successful PoC: https://github.com/ShutdownRepo/github-actions-nested-workflows/actions/runs/4383907692
I'll let maintainers handle/close this issue in case there's something else to deal with here

**Comment by nikola-jokic** [comment]
Hey @ShutdownRepo,

Thank you for letting us know it has been resolved! Closing this one :relaxed:

**Comment by mhs4670go** [comment]
@nikola-jokic Hmm.. I think GHES 3.7 still has got same problem. The bug fix is only applied at higher GHES version?

**Comment by Mykp3** [comment]
Hey,

So we are also using in JSON as an input for matrix strategy like that:
include: ${{ fromJson(needs.EnvSetup.outputs.matrix) }}

It was very challenging to implement and now I see something changed in the past ~2 weeks as workflows are now unable to initialise (No changes to workflow itself were performed) 
Very sad! Noticed Today.
I verified json file is generating OK in the previous jobs, available, accessible and in right format 

`Error when evaluating 'strategy' for job 'plan'. operations-tpl.yml@(Line: 210, Col: 18): Error parsing fromJson,.github/workflows/operations-tpl.yml@(Line: 210, Col: 18): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/cluster-operations-tpl.yml@964075947889150de8d5a559662c75454a5a964c (Line: 210, Col: 18): Unexpected value ''`

**Comment by IanTaylor-catapult** [comment]
Same issue as @Mykp3. Tried passing both a json string (properly escaped), and a plaintext json from a GitHub repository environment variable to a matrix. No matter what I've done I get the same output listed above.
See...
`"TARGET_MACHINES={\"targets\": [{\"name\":\"xxxxxxxx\",\"ip\":\"xxxxxxxx\"}]}"`
`    # Matrix for target machines provided as JSON in a GitHub environment variable.
    strategy:
      matrix: ${{ fromJson(vars.TARGET_MACHINES) }}
    steps:`
![image](https://github.com/actions/runner/assets/109170332/ec960619-7b9e-4ae8-b724-424883063d21)

**Comment by trueneu** [comment]
@Mykp3 @IanTaylor-catapult the error message looks exactly like mine from https://github.com/orgs/community/discussions/32023#discussioncomment-5266298 . A wild guess on @IanTaylor-catapult issue would be, the parsing logic differs between input types (whether it's workflow inputs, or environment vars, or something else).
It would help the support if you'd prepare a minimal reproducible example for quick testing and iterations. Engineering team can enable certain workarounds just for you, in case they happen to break some other logic, or you don't want to wait for a global rollout.

**Comment by Mykp3** [comment]
> @Mykp3 @IanTaylor-catapult the error message looks exactly like mine from https://github.com/orgs/community/discussions/32023#discussioncomment-5266298 . A wild guess on @IanTaylor-catapult issue would be, the parsing logic differs between input types (whether it's workflow inputs, or environment vars, or something else). It would help the support if you'd prepare a minimal reproducible example for quick testing and iterations. Engineering team can enable certain workarounds just for you, in case they happen to break some other logic, or you don't want to wait for a global rollout.

HI,
m sure is not a thing about vars nor inputs nor type of values within json,
Our workflows, let's say, are in production and our primary way to update things and no changes were introduced on our side, I additionally confirmed all the inputs outputs logic, is about **Github MICROSOFT** rolled out new version of actions and **break everything for us.**
Link to the issue I created as this one is closed and Im not sure is about runner itself.
https://github.com/orgs/community/discussions/71024

**Comment by trueneu** [comment]
@Mykp3 I'm not saying it's your fault, I'm saying what it looks like. You don't need to be defensive, I'm not attacking you.

**Comment by Mykp3** [comment]
So, for us, that mechanism check was fairly simple and old-school, it checks value, if this value reminds of a secret - it prohibits outputs, 

I still think we should be in control of this, like having some flag, e.g. "skip all checks"

**Comment by drewid** [comment]
I am having the error mentioned when loading a value from an environment variable (also environment secret): 

`Error when evaluating 'strategy' for job 'some-job': Error parsing from some-file.yml: Error reading JToken from JsonReader. Path '', line 0, position 0`

I have json that should be fine - have very basic array structure and json structure tried:
["x","y"] and also with just the fields "x", "y"

**Comment by SergkeiM** [comment]
@drewid have you found a solution?

**Comment by smol-ninja** [comment]
I think this is still a problem. We use the following workflow to run scheduled CIs.

```yaml
on:
  schedule:
    - cron: "0 3 * * 0" # at 3:00am UTC every Sunday
  workflow_dispatch:
    inputs:
      unitFuzzRuns:
        default: '50000'
        description: "Unit: number of fuzz runs."
        required: false

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@main"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@main"

  test-unit:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: ${{ fromJSON(inputs.unitFuzzRuns) || 50000 }}
      foundry-profile: "test-optimized"
      match-path: "test/unit/**/*.sol"
      name: "Unit tests"
```

It does not work anymore, but, it was working 3 weeks ago. Also it always work if triggered manually.

It is throwing the following error when triggered by scheduler:

> The template is not valid. .github/workflows/ci-deep.yml (Line: 53, Col: 26): Error parsing fromJson, .github/workflows/ci-deep.yml (Line: 53, Col: 26): Error reading JToken from JsonReader. Path '', line 0, position 0.

Full list: https://github.com/sablier-labs/v2-core/actions/workflows/ci-deep.yml
Working CI: https://github.com/sablier-labs/v2-core/actions/runs/9728880840
Failed CI: https://github.com/sablier-labs/v2-core/actions/runs/10025126571

**Comment by smol-ninja** [comment]
@ChristopherHX I am not sure if I understood it correctly.

> three weeks ago it was workflow_dispatch and not schedule

No, it was `schedule`. Also, see [the latest run ](https://github.com/sablier-labs/v2-core/actions/runs/10128442257) from yesterday which failed. And [this run](https://github.com/sablier-labs/v2-core/actions/runs/9728880840) is from 3 weeks ago which was also `schedule` but succeeded.

**Comment by matterpale** [comment]
@smol-ninja Hello, same issue here, perfectly valid some weeks ago, broken now. But I don't see an answer here. Could you share how you overcame the problem in the end?

**Comment by smol-ninja** [comment]
Hi @matterpale, the following changes made it work for me:

1. Changed `fromJSON(inputs.invariantDepth) || 1000` to `fromJSON(inputs.forkFuzzRuns || '1000')` - use of single quotes around number in `OR`
2. Changed input valuetype from number to string: 

from 

```yaml
    inputs:
      unitFuzzRuns:
        default: 50000
        description: "Unit: number of fuzz runs."
        required: false
```
to

```yaml
    inputs:
      unitFuzzRuns:
        default: '50000'
        description: "Unit: number of fuzz runs."
        required: false
```
