### ISSUE TITLE
Step `timeout-minutes` isn't being respected in Windows

### ISSUE THREAD

**Issue by dundargoc** [actions/runner#2432]
**Describe the bug**
Step `timeout-minutes` on Windows is not being respected and jobs frequently run twice the amount of time.

**To Reproduce**
I truly don't know how I can produce anything close to a "minimal" reproduction steps that doesn't basically involve "run our tests", as there are too many moving parts in our tests to meaningfully recreate.

The step itself looks like the following:

```yaml
      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
        name: Run functionaltest
        timeout-minutes: 15
        run: cmake --build build --target functionaltest
```

[Full workflow](https://github.com/neovim/neovim/blob/master/.github/workflows/ci.yml#L449-L452)

All I can say it that `timeout-minutes` is not being respected, and that it frequently happens:

https://github.com/neovim/neovim/actions/runs/4137629319/jobs/7153034672
https://github.com/neovim/neovim/actions/runs/4138053477/jobs/7153989473
https://github.com/neovim/neovim/actions/runs/4138560953/jobs/7155113057

I can find more examples if you wish. It seems the only the job-level `timeout-minutes` is being respected in these cases.

**Expected behavior**
Timeout to timeout.

## Runner Version and Platform
windows-2019

## What's not working?
We don't get any error messages. The information I linked above is all we know.
