### ISSUE TITLE
Why is always() required in job if statement to work?

### ISSUE THREAD

**Issue by sidekick-eimantas** [actions/runner#2455]
Given the below workflow (simplified):

```yml
name: test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

  schedule:
    - cron: '0 8 * * 1-5' # At 08:00 on every day-of-week from Monday through Friday.

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  test:
    name: ${{ matrix.test-type }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - "ubuntu-22.04"
        test-type:
          - "acceptance"

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  alert:
    name: alert
    needs:
      - test
    if: ${{ always() && github.event_name == 'schedule' && contains(join(needs.*.result, ','), 'failure') }}
    runs-on: "ubuntu-22.04"

    steps:
      - run: echo "test"
```

Why is `always()` required in the alert jobs `if` statement, to function? Without it, even if the other two conditions of that `if` statement are met, the job doesn't trigger.

Thanks
