### ISSUE TITLE
GitHub Action incorrectly inferred type of empty strings

### ISSUE THREAD

**Issue by mon-jai** [actions/runner#2463]
**Describe the bug**

GitHub Action does not recognize empty strings as a string

**To Reproduce**

1. Run [this workflow file](https://github.com/mon-jai/github-action-error/blob/main/.github/workflows/error.yml)

	```yaml
	name: Error
	on: [push, workflow_dispatch]
	
	jobs:
	  error:
	    runs-on: windows-latest
	    concurrency:
	      group: ${{ matrix.arguments }}
	      cancel-in-progress: true
	    strategy:
	      matrix:
	        arguments: ["", "foo", "bar"]
	    steps:
	      - run: |
	          echo "Hello world"
	```

**Expected behavior**

GitHub Action should inferred empty strings as type `string`

## Runner Version and Platform

Version of your runner?  
2.302.1

OS of the machine running the runner?  
Hosted by GitHub

## What's not working?

The [following error is displayed](https://github.com/mon-jai/github-action-error/actions/runs/4264201104)

```
Error when evaluating 'concurrency' for job 'error'. .github/workflows/error.yml (Line: 8, Col: 14): Unexpected type of value '', expected type: String.
```
