### ISSUE TITLE
Using environment vars in job returns in empty strings

### ISSUE THREAD

**Issue by stickeraugust** [actions/runner#2472]
I'm trying to build a reusable workflow that dynamically picks the runner depending on the job environment. I'm triggering the job with a workflow dispatch with environment as an input, setting the environment of a job as "environment: ${{ inputs.environment }}" (but even if i hard code the environment it wont work).

But the problem I have seems to be a bug with using environment vars at the job level. For example ${{ vars.MY_VAR }} always returns an empty string. 

Unless I add the variable as a repository variable instead of an environment variable.

If I am to echo out ${{ vars.MY_VAR }} inside a step, the variable is there, but not when I'm trying to configure a job.

**To Reproduce**
Follow the example from the documentation. https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context

![image](https://user-images.githubusercontent.com/89836897/222740086-10a3adb1-9efc-45c6-a93f-1c884eb3fb96.png)

Setting a workflow environment variable works fine. But setting for example the job name or runs-on in a job would result in an empty string. Echoing the vars in a step works fine.

**Expected behavior**
Using vars.RUNNER (as in the example) would set the runner configured for that environment in the repository settings.

Found some similar reports on this but not quite. 
Have been trying out different workarounds and gone through the documentation a few times now but none will work.

**Comment by ruvceskistefan** [comment]
Hey @stickeraugust,
can you check [this](https://docs.github.com/en/actions/learn-github-actions/variables#defining-variables-for-multiple-workflows) link maybe it will help you with setting up envs.
In the image below you can see that envs are not empty strings after setting up env as done in the documentation.
![image](https://user-images.githubusercontent.com/96768603/223362839-b49dacb1-ba53-43b7-87a5-8ed6a4becfab.png)

**Comment by Alexnortung** [comment]
I am experiencing the same issue. Even when my environment is set to all branches, there are no variables set in the workflow. I check this with an extra step: `run: ${{ toJson(vars) }}. If I set a repository level variable, then I can access those.

I am doing this in an organization that I have admin access in and the repository is private.

**Comment by stickeraugust** [comment]
@ruvceskistefan That is the documentation i have been reading over and over. The repository and organization variables and secrets works. It's only the environment secrets and variables having issues. 
![image](https://user-images.githubusercontent.com/89836897/224647678-32beba2e-575d-4e24-bab5-41962e8df11b.png)

I found a workaround for it so my deploys work as intended now, but still odd

**Comment by ruvceskistefan** [comment]
Hey, @stickeraugust could you provide us with the repro workflow/repository so we can investigate further.

**Comment by glency-betterteem** [comment]
This is still ongoing issue. tagging this https://github.com/actions/runner/issues/2414 as it is releated.

**Comment by criskurtin** [comment]
We just stumbled upon the same issue. Repository and organization variables work as expected, but anything defined in the environments of a specific repository is blank when referenced in a workflow using `${{ vars.SOME_ENV_VAR }}` or `${{ secrets.SOME_ENV_SECRET }}`.
The repository is private and I have admin rights on it.

@stickeraugust would you mind sharing the workaround you are currently using?

**Comment by DavideCarvalho** [comment]
I'm trying to pass my secret as an env and I'm having the same issue, the variable is empty

The only way to work is if I pass the env variable directly, e.g: MY_ENV: VALUE_HERE_DIRECTLY

**Comment by antona-miro** [comment]
This page https://docs.github.com/en/actions/using-jobs/using-environments-for-jobs mentions that an expression can be used for the URL. But it doesn't mention that an expression can be for defining an environment name. I think that's the problem here

**Comment by stickeraugust** [comment]
@criskurtin Sorry for late reply, the repo i'm working on private unfortunately. But we basically got around it by accessing the environment secrets from a step within another job and outputting those secrets.

EXAMPLE
**Inside the "init" job, add the secret/env var as an output**
mysecret=${{vars.MY_SECRET}}"
echo "mysecret=$mysecret" >> $GITHUB_OUTPUT

**Then the variable can be accessed as usual by accessing the outputs.**
${{needs.init.outputs.mysecret}}

More on using outputs if you're not familiar: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

Not ideal but it gets the job done.

**Comment by djr4** [comment]
@stickeraugust the problem you're facing might be due this line:

environment: ${{ vars.ENVIRONMENT_STAGE }} 

if ENVIRONMENT_STAGE is actually only defined as environment variable then this will be empty and implication is that all other environment vars will be empty strings (because you're trying to assign environment: '' as job environment)

I think if you declare ENVIRONMENT_STAGE as repository or organization var (with existing environments you created), you will be fine and all environment vars / secrets will work as expected. 

--------
NOTE: For everyone that might face this issue, also make sure to assign environment to a job.
```
jobs:
 job-name:
    runs-on: some-runner
    environment: 'your_environment' 
```

otherwise job will not automatically read environment vars or secrets only based on branch selection rules.

**Comment by reed-hanger** [comment]
I believe we're seeing this same issue. I converted some non-sensitive values from environment secrets to environment variables, and in my reusable workflow we are now just getting blank values unless I define a repository variable (useless for us -- we need different values for each environment). I tested both passing it in as an input and a secret... It was blank either way. I think it's an issue where variables are being interpolated earlier than secrets, before it gets to the reusable workflow where we are "inside" the environment.

The suggested "output" workaround doesn't work well for us because the reusable workflow doesn't know which variables to output (the idea is for the caller workflow to pass arbitrary values needed for Terraform).

For context, the job in my caller workflow:
```yaml
  terraform:
    name: Terraform
    uses: my-org/my-reusable-workflows/.github/workflows/terraform-reusable-workflow.yml@main
    secrets:
      env: |
        KAFKA_API_KEY=${{ vars.KAFKA_API_KEY }}
        KAFKA_API_SECRET=${{ secrets.KAFKA_API_SECRET }}
        KAFKA_ID=${{ vars.KAFKA_ID }}
        KAFKA_REST_ENDPOINT=${{ vars.KAFKA_REST_ENDPOINT }}
    with:
      tfvars: |
        kafka_id = "${{ vars.KAFKA_ID}}"
        kafka_api_key = "${{ vars.KAFKA_API_KEY }}"
        kafka_rest_endpoint = "${{ vars.KAFKA_REST_ENDPOINT }}"
```

In my reusable workflow, the env secret doesn't have any values after the equal signs, and the tfvars input similarly sees a bunch of variables with values of "". The environment secret, KAFKA_API_SECRET, does populate in the env secret passed to the workflow as expected. I didn't include it in the tfvars input, since we can't pass secrets to inputs.

A snippet of the relevant parts of the reusable workflow:

```yaml
on:
  workflow_call:
    secrets:
      env:
        required: false
    inputs:
      runs-on:
      tfvars: # hcl
        required: false
        type: string

jobs:
  run:
    environment:
      name: test
    steps:
      - name: Set environment variables
        run: |
          (
          cat <<'_EOT'
          ${{ secrets.env }}
          _EOT
          ) >> "$GITHUB_ENV"
      - name: Plan
        run: |
          (
          cat <<'_EOT'
          ${{ inputs.tfvars }}
          _EOT
          ) | terraform plan -out=${{ runner.temp }}/tfplan -var-file=/dev/stdin
          terraform show -json ${{ runner.temp }}/tfplan > tfplan.json
```

**Comment by nix1** [comment]
I'm experiencing the same issue. It seems that essentially if an environment is selected dynamically then its variables don't get loaded.
The same happens with secrets, so they can't be used as a workaround.

**Comment by joshft91** [comment]
I think I'm seeing this too, but in particular I'm seeing blank secrets when created via API. This Stackoverflow post also seems to be talking about what I'm seeing: https://stackoverflow.com/questions/74741306/github-secrets-created-using-api-rest-but-returned-empty

I've attempted to create secrets via octokit, `actions/github-script@v3`, and the API directly via Postman. All return empty strings when attempting to access them.

If I manually update the secret in the GitHub UI, then I'm able to read the value correctly.

**Comment by SiddhantSadangi** [comment]
Same issue.

**Caller workflow:**

```yaml
jobs:
  test-scripts-ubuntu:
    uses: ./.github/workflows/test-scripts.yml
    with:
      os: ubuntu-latest
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}
```

**Called workflow**
```yaml
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    secrets:
      API_TOKEN:
        required: true
jobs:
  test-scripts:
    strategy:
        matrix:
            scripts:
                ...
    runs-on: ${{ inputs.os }}
    steps:
      - name: Test examples
        uses: nick-fields/retry@v2
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        with:
          timeout_minutes: 60
          max_attempts: 2
          retry_on: timeout
          command: |
            cd ${{ matrix.scripts }}
            bash run_examples.sh
```

`API_TOKEN` is blank in called workflow

**Comment by romina2001** [comment]
This is still a problem. I have the same issues when referencing environment secrets or variables.

**Comment by glency-betterteem** [comment]
This is out working workflow https://github.com/actions/runner/issues/2414#issuecomment-1661398465

**Comment by Nicolasvegam** [comment]
same issue here!

**Comment by ian-taylor-catapult** [comment]
Seeing the same issues here. Getting blank variable and secrets values when passing to actions from the main workflow.

**Comment by jonira** [comment]
same issue, is there any way to fix this

**Comment by viictor-vm** [comment]
Same issue here. I cannot access to any secret variable from my github actions. Any help?

**Comment by rjcoupe** [comment]
Yep, same here. Vars (and secrets) set within the environment config do not seem to be passed to subordinate jobs. This is an absolute show-stopper, IMHO.

**Comment by viictor-vm** [comment]
If you're using multiple Gtihub Actions, you should add the following statement:

```
  build-test:
    name: Tests
    if: CONDITION
    uses: IMAGE_URL
    secrets: inherit <----
```

It worked for me
