### ISSUE TITLE
Permission denied while executing node binary from externals folder

### ISSUE THREAD

**Issue by AlexShemeshWix** [actions/runner#2486]
**Describe the bug**
Running self-hosted github runner on Ubuntu (20/22) randomly fails workflow runs because of permission issues with node installed in externals folder.

**To Reproduce**
1. I have self hosted runners fleet running in AWS cloud.
2. I run jobs to test npm packages. So generally workflow looks like this

```
name: Run npm test
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  run-browser-it-no-cache:
    runs-on: [self-hosted, '${{ matrix.platform.os }}', x64, '${{ matrix.platform.label }}']
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        platform: [{ os: linux, label: aws-linux }]
        node-version: [18]       
    steps:           
      - uses: actions/checkout@v3
      - name: Use Node.js
        if: always()
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
```
4. Randomly it fails with error message 
5. See error
```Error: An error occurred trying to start process '/opt/actions-runner/externals/node16/bin/node' with working directory '/opt/actions-runner/_work/myfolder/myfolder'. Permission denied```

**Expected behavior**
I expect my workflow to execute successfully or fail consistently. Not fail randomly.

## Runner Version and Platform
Github runner 2.302.1
Ubuntu 22

## What's not working?
```Error: An error occurred trying to start process '/opt/actions-runner/externals/node16/bin/node' with working directory '/opt/actions-runner/_work/myfolder/myfolder'. Permission denied```

## Job Log Output
```
Run actions/setup-node@v3
  with:
    node-version: 18
    registry-url: https://registry.npmjs.org/
    cache: yarn
    cache-dependency-path: /opt/actions-runner/_work/test/test/yarn.lock
    always-auth: false
    check-latest: false
    token: ***
Error: An error occurred trying to start process '/opt/actions-runner/externals/node1[6](https://github.com/org/test/actions/runs/43955715/jobs/76974545#step:5:6)/bin/node' with working directory '/opt/actions-runner/_work/test/test'. Permission denied
```

## Runner and Worker's Diagnostic Logs
Runners are ephemeral, it fails randomly so its hard to collect logs from failing instance.
