### ISSUE TITLE
Files created in a container job will be left in the host machine after execution

### ISSUE THREAD

**Issue by DaHuoKolmostar** [actions/runner#251]
**Describe the bug**
I need to use a self-hosted runner to run some tests, and I want the tests can be isolated from the host machine due to some security issues, that meaning the host machine won't get access to the source code.
GitHub Actions provides a "[container](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer)" syntax within a job, indicating the whole job will be running within the container. 
However, after I run it, the files can be found within the _work/code-repo/code-repo directory in the runner. 

I thought about adding a final clean up step at the end of the job, but it won't work if the job gets cancelled during execution and therefore the final clean up step won't run.

**To Reproduce**
1. I have the workflow.yaml file as follows:
```
on: [push]

jobs:

  action_test:
    runs-on: self-hosted
    container:
      image: localhost:5000/ubuntu-own
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: examine
        run: |
          ls
          pwd
      - name: fail clean up
        if: failure()
        run: |
          rm -rf *

      - name: clean up
        run: |
          rm -rf *
```

2. Push code to Github to trigger the self-hosted runner to run.
3. All the source files obtained through checkout can be seen under the folder of ~/github-actions-runners/test-repo/actions-runner/_work/test-repo/test-repo.

**Expected behavior**
The source code files cannot be seen by the host machine anytime.

## Runner Version and Platform
Version is 2.163.1.

OS of the machine running the runner? Linux

## Runner and Worker's Diagnostic Logs
I can see the logs within **Initialize containers** indicating the creation of the docker does some volume mounts.
`
/usr/bin/docker create --name 4625a0cc672e4786a61168dd09ed22eb_localhost5000ubuntumcu_8b5abb --label 63b318 --workdir /__w/test-repo/test-repo --network github_network_5b545002914b4c118fdae38bef600c83 --privileged -e "HOME=/github/home" -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/kolmostar/github-actions-runner/runner/_layout/_work":"/__w" -v "/home/kolmostar/github-actions-runner/runner/_layout/externals":"/__e":ro -v "/home/kolmostar/github-actions-runner/runner/_layout/_work/_temp":"/__w/_temp" -v "/home/kolmostar/github-actions-runner/runner/_layout/_work/_actions":"/__w/_actions" -v "/home/kolmostar/github-actions-runner/runner/_layout/_work/_tool":"/__w/_tool" -v "/home/kolmostar/github-actions-runner/runner/_layout/_work/_temp/_github_home":"/github/home" -v "/home/kolmostar/github-actions-runner/runner/_layout/_work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" localhost:5000/ubuntu-mcu "-f" "/dev/null"
`

**Comment by RammusXu** [comment]
I have same issue: https://github.community/t5/GitHub-Actions/Self-hosted-Runner-can-t-mount-workspace-correctly/m-p/42016/highlight/false

It's about docker-in-docker problem. When you start a runner container and run jobs. Job will mount runner container's volume. But docker-in-docker will treat this as "job mount docker-host volume". That's why you can't find any files in the job's workspace.

Here's my kubernetes example: https://github.com/swaglive/docker-github-actions-runner/pull/4/files
The point is "mount workspace into your runner container".
```
      containers:
      - name: agent
        image: swaglive/github-runner:2.163.1-ubuntu18.04
...
        volumeMounts: 
          - name: runner-workdir
            mountPath: /home/runner/_work

      - name: dind-daemon 
        image: docker:19.03-dind
...
        volumeMounts: 
          - name: runner-workdir
            mountPath: /home/runner/_work
...
      volumes: 
        - name: runner-workdir
          emptyDir: {}
```
