### ISSUE TITLE
[Windows Self-Host] Can't copy files in self-hosted for some reason

### ISSUE THREAD

**Issue by mcagabe19** [actions/runner#2545]
Idk why it not finds the path.

![Screenshot_2023-04-17-11-51-41-768](https://user-images.githubusercontent.com/82843871/232434835-202c9921-2738-43c1-84af-f250552f2274.jpeg)

but in windows works fine maybe did i do smth wrong at workflow?

```yml
name: Android Build CI (Self Host)

on:
  workflow_dispatch:

jobs:
  build:
    name: Android
    runs-on: self-hosted
    steps:
      - name: Build ARMV7
        # shell: cmd
        run: cd C:\Users\mcagabe19\Github\VSNull-Mobile; haxelib run lime build android -armv7; copy /Y C:\Users\mcagabe19\Github\VSNull-Mobile\export\release\android\bin\app\build\outputs\apk\debug\VSNull-debug.apk C:\Users\mcagabe19\ToGDrive\VSNull-armv7.apk
```
