### ISSUE TITLE
Unrecognized named-value: 'steps'

### ISSUE THREAD

**Issue by doichev-kostia** [actions/runner#2562]
**Describe the bug**
`Syntax error: Unrecognized named-value: 'steps'` appears on the `environment` property when I'm trying to dynamically set the name and the URL of the environment

**To Reproduce**
```yaml
name: temp-env-deployment

concurrency:
  group: temp-env-deployment-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - major/*
      - hotfix/*

env:
  TEMP_ENV_CONFIG_FILENAME: temp-env.yaml


jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    environment:
      name: ${{ steps.service_metadata.outputs.service_name }}
      url: ${{ steps.service_metadata.outputs.service_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:staging

      - name: Generate service name
        # transform major/feature-name to major-feature-name
        # write env variable to $GITHUB_ENV to persist it across steps
        run: |
          branch=${{ github.ref_name }}
          feature_name=$(echo $branch | sed 's/\//-/g' )
          echo "feature_name: $feature_name"
          echo "FEATURE_NAME=$feature_name" >> $GITHUB_ENV


      - name: Generate app engine config
        run: |
          echo "
          runtime: nodejs18
          service: $FEATURE_NAME

          handlers:
          #####
          " > $TEMP_ENV_CONFIG_FILENAME

      - name: Deploy to app engine
        uses: <action>
        with:
          workload_identity_provider: #####
          service_account: #####
          service_id: $FEATURE_NAME
          project_id: #####
          app_yaml_path: $TEMP_ENV_CONFIG_FILENAME

      # get the service name and url for better GitHub experience via environments
      - name: Get metadata
        id: service_metadata
        run: |
          url=$(gcloud app browse --service=$FEATURE_NAME --no-launch-browser)
          echo "service_url=$url" >> $GITHUB_OUTPUT
          echo "service_name=$FEATURE_NAME" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: log
        run: |
          echo ${{ steps.service_metadata.outputs.service_url }}
          echo ${{ steps.service_metadata.outputs.service_name }}
```

**Expected behavior**
The environment values are set dynamically after the GCP App Engine deployment

## Runner Version and Platform
ubuntu-latest-4-cores

OS of the machine running the runner? Linux

## What's not working?
```
The workflow is not valid. .github/workflows/temp-env-deployment.yml (Line: 27, Col: 13): Unrecognized named-value: 'steps'. Located at position 1 within expression: steps.service_metadata.outputs.service_name
```

**Comment by doichev-kostia** [comment]
The same happens with passing an environment variable

```yaml
env:
  FEATURE_NAME_2: $(echo ${{ github.ref_name }} | sed 's/\//-/g' )

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: ${{ env.FEATURE_NAME_2 }}
      url: ${{ steps.service_metadata.outputs.service_url }}
```

Error: `The workflow is not valid. .github/workflows/temp-env-deployment.yml (Line: 28, Col: 13): Unrecognized named-value: 'env'. Located at position 1 within expression: env.FEATURE_NAME_2 `
