### ISSUE TITLE
Job env variables cant be computed based on Workflow env variables

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#2565]
**Describe the bug**
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/55927613/234248631-6c874828-a48c-452e-a94d-3fc29e7cc8f8.png">

**To Reproduce**
````yml
name: Test Workflow Env Variables

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  TEST: ${{ github.event_name == 'push' && 'A' || 'B' }}

jobs:

  # verify if the workflow env variables are computed before job variables
  job:
    runs-on: ubuntu-latest
    env:
      COMPUTED_TEST: ${{ env.TEST }} # does not compile
    steps:
      - run: |
          echo ${{ env.COMPUTED_TEST }}
          echo $COMPUTED_TEST
````

**Expected behavior**
Job env variables should be determined based on Workflow env variables. 

Considering the above workflow, the output on pull_request events should be B, and for push events A

## Runner Version and Platform
Ubuntu-latest

## What's not working?
Job env variables cant be computed based on Workflow env variables

## Job Log Output
It is in the image above

## Runner and Worker's Diagnostic Logs
N/A
