### ISSUE TITLE
Misleading error, when using runs-on: self-hosted

### ISSUE THREAD

**Issue by oerp-odoo** [actions/runner#2573]
**Describe the bug**

**To Reproduce**

If you specify `runs-on: self-hosted` in job that has `needs` (for other jobs), it gives some misleading errors.

I was getting:

```
The workflow is not valid. .github/workflows/project.yml (Line: 111, Col: 5): Unexpected value 'uses' .github/workflows/project.yml (Line: 112, Col: 5): Unexpected value 'with'
```
I was scratching my head, thinking why `uses` value is unexpected for some time. After I realized that I had runs-on specified (also did not see in docs mentioning that you can't specify it on jobs that depend on other jobs?). After I removed `runs-on: self-hosted`, issue disappeared.

My job was defined like this:

```yml
  maraplus_stage:
    runs-on: self-hosted
    needs: [project_names_wkf, build_odoo]
    strategy:
      # We want other test jobs to still run, to see overall picture.
      fail-fast: false
      matrix:
        name: "${{ fromJSON( needs.project_names_wkf.outputs.names_json ) }}"
    uses: ./.github/workflows/_maraplus.yml
    with:
      project: ${{ matrix.name }}
      mode: stage
    secrets: inherit # pragma: allowlist secret
```
![Selection_559](https://user-images.githubusercontent.com/7812986/235164120-e76ccaa1-6fa2-48a3-a26b-5812a8e33fd7.png)

If I change it to:

```yml
  maraplus_stage:
    needs: [project_names_wkf, build_odoo]
    strategy:
      # We want other test jobs to still run, to see overall picture.
      fail-fast: false
      matrix:
        name: "${{ fromJSON( needs.project_names_wkf.outputs.names_json ) }}"
    uses: ./.github/workflows/_maraplus.yml
    with:
      project: ${{ matrix.name }}
      mode: stage
    secrets: inherit # pragma: allowlist secret
```
It works fine

**Expected behavior**
It should throw error pointing to actual issue or maybe add extra context information, if `runs-on` changes the way values can be used. As its quite confusing, differentiating from cases when its specified and when its not (if it behaves differently).
