### ISSUE TITLE
Reusable Workflows - predefined variables load for the called job

### ISSUE THREAD

**Issue by orizerah** [actions/runner#2577]
**Describe the bug**
The environment variables that the runner loads contain information only about the called job and not about the caller.
For example: Assuming we have a workflow with a job `build`, which uses another workflow with a job called `test`, the job name in GitHub will be `build / test`, but the value of `GITHUB_JOB` will be `test`.
This denies me from having access in runtime to data about the job.

**To Reproduce**
Go to a GitHub repository and create 2 workflows:
`called.yaml`
```yaml
name: Called
on: workflow_call
jobs:
  child:
    runs-on: ubuntu-latest
    steps:
       - name: Print Envs
         runs: prinenv
```
`caller.yaml`
```yaml
name: Caller
on: workflow_dispatch
jobs:
  parent:
  uses: ./.github/workflows/called.yaml
```

**Expected behavior**
There should be a GITHUB_JOB_ID env with the correct job id
The `GITHUB_JOB` env should include the full name of the actual job.

## Runner Version and Platform
`ubuntu-latest`

**Comment by ruvceskistefan** [comment]
Hey @orizerah,

you can pass values from parent to child as described in [docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)

reusable workflow
```
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.envPAT }}
        configuration-path: ${{ inputs.config-path }}
```

caller workflow
```
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
```
