### ISSUE TITLE
self-hosted runner ignores variable in working-directory

### ISSUE THREAD

**Issue by JulianGro** [actions/runner#2596]
**Describe the bug**
When using a variable inside the working-directory field, it just gets ignored.

**To Reproduce**
Create a variable. For example via `echo "FOO_WORKSPACE=/foo/" >> $GITHUB_ENV`
Try using it inside the working-directory
```yaml
    - name: Foo
      working-directory: ${{ env.FOO_WORKSPACE }}/build
      shell: bash
      run: pwd
```
It will now try to go into `/__w/REPOSITORY/REPOSITORY/build` instead of `/foo/build`.

**Expected behavior**
The variable should be used, the same way as in GitHub hosted runners.

## Runner Version and Platform
Version of your runner? 2.304.0

OS of the machine running the runner? Linux aarch64
