### ISSUE TITLE
[0-9]{4}-[0-9]{2}-[0-9]{2}  or  ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$ patterns don't work

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#2600]
**Describe the bug**

pushing tags with this format `YYYY-MM-DD` won't start workflows with the following trigger configuration:

````yml
on:
  push:
    tags:
      - "[0-9]{4}-[0-9]{2}-[0-9]{2}" 
````

````yml
on:
  push:
    tags:
      - "^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$"
````

while when using this trigger configuration, things work as expected

````yml
on:
  push:
    tags:
      - "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]"
````

All patterns match `YYYY-MM-DD` but workflows don't start

<img width="975" alt="image" src="https://github.com/actions/runner/assets/55927613/3bc55f42-e9f6-46f8-8128-15027e40fd84">

<img width="966" alt="image" src="https://github.com/actions/runner/assets/55927613/e244d7db-1889-446e-8a5a-abf1a8565c6a">

<img width="985" alt="image" src="https://github.com/actions/runner/assets/55927613/f98a480e-32af-47ea-9802-69718a3cf70e">

**Expected behavior**

Workflow with the following trigger configuration

````yml
on:
  push:
    tags:
      - "[0-9]{4}-[0-9]{2}-[0-9]{2}" 
````

must be triggered when pushing a tag `YYYY-MM-DD` 

## Runner Version and Platform
Does not matter

## What's not working?
Workflow is not triggered

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A
