### ISSUE TITLE
The containers feature downloads images before a registry cache can be configured in the environment

### ISSUE THREAD

**Issue by alexellis** [actions/runner#2603]
**Describe the bug**

The containers feature downloads images before a registry cache can be configured in the environment

Any steps to configure the Docker daemon with a cache are run _after_ any container images specified in the steps:

Example:

https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

```yaml
name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: node:14.16
    steps:
      - uses: some-org/configure-registry-mirror-cache@v1
      - name: Run some step inside the container image
        run: ls
```

**To Reproduce**
1. See example given

**Expected behavior**

The workflow needs to allow for a cache to be set up dynamically in the workflow itself - rather than assuming at the VM itself is preconfigured or pre-authenticated.

There are two reasons why a cache is needed:

1. The Docker Hub has rate limits for anonymous pulls which are hit by self-hosted runners which have a stable IP
  1.1. one option is to use a pull through cache on the host
  1.2. the other is to authenticate - which is repetitive, and questionable within an open source organisation due to leaking the secret
2. Large images need to be cached to speed up builds - i.e. 2+GB base images required during a build

If the containers feature is not used - then a cache can be used, however many people have adopted the containers feature already, and there doesn't seem to be a solution here?

Authenticating in the `containers` step is repetitive and a security risk which would leak the owner's Docker Hub credential to anyone who ran a build.

```yaml
container:
  image: docker.io/org/image
  credentials:
     username: hub_account_username
     password: ${{ secrets.HUB_API_KEY }}
```

## Runner Version and Platform
Version of your runner?

Latest runner

Linux
