### ISSUE TITLE
Add support for binding a service container to host network

### ISSUE THREAD

**Issue by Lctrs** [actions/runner#261]
**Describe the enhancement**

Selenium containers needs to be binded to host network. Looking at the documentation, I don't think this is supported yet.

**Code Snippet**

```yaml
jobs:
  my-job:
    services:
      my-service:
        image: "my-image:latest"
        network: host
```
