### ISSUE TITLE
`jobs.<job_id>.environment` not populated when using `inputs` context

### ISSUE THREAD

**Issue by hugohjerten** [actions/runner#2610]
**Describe the bug**
When setting the `environment` setting for a job using `inputs`, it doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Action workflow file:
   ```yml
   on:
      workflow_call:
        inputs:
          ...# other inputs removed 
          TF_MILIEU:
            required: true
            type: string
            description: Name of the tf milieu (environment).
   env:
      TF_MILIEU: ${{ inputs.TF_MILIEU }}
   jobs:
      tf-apply:
        name: Terraform apply
        runs-on: ubuntu-latest
        environment: ${{ inputs.TF_MILEU }}
        steps:
           - name: Checkout
             uses: actions/checkout@v3
             ...# remaining code removed
   ```
2. Run the workflow.

**Expected behaviour**
I expect the defined environment to be picked up. Especially important for our protected environment, where we want to require a manual approval from team members prior to applying our terraform code.

## Runner Version and Platform
Version: `'2.304.0'`
OS: Ubuntu 22.04.2 LTS

## What's not working?
Deployment to github environment is not registered, likely because the `environment` key is empty. (Could not find any value for `environment` when enabling debugging, however when enabling the debugging I could confirm that the `env.TF_MILIEU` was indeed populated).

**Comment by ruvceskistefan** [comment]
Hey @hugohjerten, you can use `github.event.inputs.` to use inputs as shown in code below. I also included small test of printing the input and also the env set by input.
```
name: a test input
on:
    workflow_dispatch:
     inputs:
       TF_MILIEU:
         required: true
         type: string
         description: Name of the tf milieu (environment).
env:
   TF_MILIEU: ${{ github.event.inputs.TF_MILIEU }}
jobs:
   tf-apply:
     name: Terraform apply
     runs-on: ubuntu-latest
     steps:
        - name: Checkout
          run: | 
            echo "evn: ${{ env.TF_MILIEU }}"    
            echo "input: ${{ github.event.inputs.TF_MILIEU }}"
```

![image](https://github.com/actions/runner/assets/96768603/fc6c8668-d734-4997-8b80-5e73f5b14a54)
