### ISSUE TITLE
Service containers will sometimes assign different ports between IPv4 and IPv6

### ISSUE THREAD

**Issue by Nican** [actions/runner#2616]
**Describe the bug**
My application will sometimes fail to connect to the redis service container inside of a GitHub action. The port is randomly assigned, and this bug is random. 

It looks like IPv4 and IPv6 sometimes get different ports, but `job.services.redis.ports[6379]` will return one entry or the other.

I can not find any information on how to force only IPv4, or figure out the correct listening address.

**To Reproduce**
1. Create a job with redis as a service container
2. Run the job on a self-hosted instance
3. Sometimes the application will fail to connect to the redis container.

Redis service defined as follow:
```yaml
      redis:
        image: redis:latest
        ports:
          - 6379/tcp
```

And then our service gets the port with an environment variable:
```yaml
      - run: npm run test:e2e:api:cover
        env:
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
```

**Expected behavior**
Possible solutions:
1. Force IPv4 only
2. Verify that IPv4 and IPv6 are listening on the same ports

## Runner Version and Platform
Version of your runner? 
Runner from actions-runner-linux-x64-2.303.0.tar.gz 

OS of the machine running the runner? Ubuntu 22.04 

## What's not working?
![image](https://github.com/actions/runner/assets/796294/6773356d-39af-447f-be79-7a5b7c16f68a)
