### ISSUE TITLE
Runner Container Hooks all `uses: docker://<image>:<tag>` steps are failing

### ISSUE THREAD

**Issue by ChristopherHX** [actions/runner#2623]
**Describe the bug**

After enabling runner container hooks all `uses: docker://<image>:<tag>` steps starts failing, due to a missing entry in `ActionManager.CachedActionContainers`.

This is not a Runner Container Hooks implementation bug, because the runner fails inside the docker step before trying to invoke the container hooks.

**To Reproduce**
1. Enable runner container hooks docker or kubernetes
   I used the docker hooks https://github.com/actions/runner-container-hooks/tree/main/packages/docker (allows dind)
3. add a workflow like this
    ```yaml
    on: push
    jobs:
      _:
        runs-on: self-hosted # Needs a self-hosted runner with Runner Container Hooks enabled
        container: node:latest
        steps:
        - run: ls -l
        - uses: actions/checkout@v3
        - name: Create script
          run: |
            uname -a
            ls        
          shell: cp {0} ${{ github.sha }}.sh
        - uses: docker://node:latest # The error happens once the runner tries to run this step, it doesn't even invoke the hook
          with:
            entrypoint: bash
            args: ${{ github.sha }}.sh
    ```

**Expected behavior**

I expect that the runner invokes the container hooks for this `docker://` step and don't fail due to an assert.

## Runner Version and Platform
Version: 2.304.0
Platform: Linux

## What's not working?
This line https://github.com/actions/runner/blob/8db8bbe13a0dabc165d0ff19a1ecb85a4fe86dd8/src/Runner.Worker/ActionManager.cs#L322-L322 prevents invoking the runner hooks for the docker step.
## Job Log Output

Once the runner tries to executes the docker step it displays
```
Value cannot be null. (Parameter 'container')
```

## Worker's Diagnostic Log of the failing step

```
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Processing step: DisplayName='Run node:latest'
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Evaluating: success()
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Result: true
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Starting the step.
[WORKER 2023-05-24 11:10:43Z INFO ActionManager] Load action that reference container from registry.
[WORKER 2023-05-24 11:10:43Z ERR  StepsRunner] Caught exception from step: System.ArgumentNullException: Value cannot be null. (Parameter 'container')
[WORKER 2023-05-24 11:10:43Z ERR  StepsRunner]    at GitHub.Runner.Worker.ActionManager.LoadAction(IExecutionContext executionContext, ActionStep action)
[WORKER 2023-05-24 11:10:43Z ERR  StepsRunner]    at GitHub.Runner.Worker.ActionRunner.RunAsync()
[WORKER 2023-05-24 11:10:43Z ERR  StepsRunner]    at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Step result: Failed
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Update job result with current step result 'Failed'.
[WORKER 2023-05-24 11:10:43Z INFO StepsRunner] Current state: job state = 'Failed'
```

## Workaround

Create an `action.yml` file
```yaml
runs:
  using: docker
  image: docker://node:latest
```
and replace `uses: docker://node:latest` with `uses: ./path/to/action`

_**Edit** fixed example and description of Workaround_
