### ISSUE TITLE
The self-hosted runner: xxx lost communication with the server

### ISSUE THREAD

**Issue by Subharanjan2055** [actions/runner#2624]
The self-hosted runner: xxx lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

Earlier i saw so many people have posted the same error that i currently facing the same and so many CI stuck due to this error , if anyone fix it please do let me know.

Thanks,

**Comment by ruvceskistefan** [comment]
Hey @Subharanjan2055 ,

Is this still happening for you on the newest version of Runner? If yes can you post steps for repro or workflow that you're using?

**Comment by Rotemsim3339** [comment]
For the last few weeks this issue keeps happening to me as well. we have an aws machine- M5.4xlarge. and our project is running on parallel with 4 threads.
we are running 4 CI workflows in a serial, one after the other in a day and the runner is "lost communication with the server" at least in one run of the 4. every day. 
There is nothing consistent that happens, so it is very difficult to investigate.
Any leads would be helpfull.

**Comment by Subharanjan2055** [comment]
@Rotemsim3339 
Pls check whether any antivirus running behind your server where the actions-runner configured whether windows defender or anyother antivirus active on it pls check

**Comment by bruno-zica** [comment]
This issue is happening on my repository too, frequently. 

The workflow is bellow:

```yml
name: Validate Code

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - docs/*
      - dependabot/**
  merge_group:
    branches:
      - main
  workflow_call:
    inputs:
      since:
        type: string

concurrency:
  group: "validate-code-${{ github.ref }}"
  cancel-in-progress: ${{ inputs.since == '' }}

jobs:
  unit-tests:
    name: Unit Tests (Backend)
    runs-on:
      - codebuild-UniteGithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Fetch main to compare
        if: github.ref != 'refs/heads/main'
        run: git fetch origin main:main --depth=50
      - name: Create swap space
        uses: ./.github/actions/create-swap-space
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Run unit tests
        run: yarn workspaces foreach -vvRp --since=${{ inputs.since || 'main' }} --exclude "{agent,appview,authn,canvas,imagine,usage,voicegen,sidekick,taskbuilder}-service" --exclude "{imagine-base,imagine-api,auth-fe,parent-link-fe,resource-fe,ai-hub-fe,artifact-cards,feedback-fe,taskconfig-fe}" run test

  unit-tests-fe:
    name: Unit Tests (Frontend)
    runs-on:
      - codebuild-UniteGithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Fetch main to compare
        if: github.ref != 'refs/heads/main'
        run: git fetch origin main:main --depth=50
      - name: Create swap space
        uses: ./.github/actions/create-swap-space
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Run unit tests
        run: yarn workspaces foreach -vvR --since=${{ inputs.since || 'main' }} --include "{agent,appview,authn,canvas,imagine,usage,voicegen,sidekick,taskbuilder}-service" --include "{imagine-base,imagine-api,auth-fe,parent-link-fe,resource-fe,ai-hub-fe,artifact-cards}" run test

  linting:
    name: Linting
    runs-on:
      - codebuild-UniteGithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Fetch main to compare
        if: github.ref != 'refs/heads/main'
        run: git fetch origin main:main --depth=50
      - name: Create swap space
        uses: ./.github/actions/create-swap-space
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Lint changed workspaces
        run: yarn workspaces foreach -vvRp --since=${{ inputs.since || 'main' }} run lint
        env:
          # increased memory because we were getting an out of memory error when running lint
          NODE_OPTIONS: "--max-old-space-size=8192"
      - name: Find unused files, dependencies and exports
        run: yarn knip

  type-checking:
    name: Type checking
    runs-on:
      - codebuild-UniteGithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Fetch main to compare
        if: github.ref != 'refs/heads/main'
        run: git fetch origin main:main --depth=50
      - name: Create swap space
        uses: ./.github/actions/create-swap-space
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Cache TypeScript build info
        uses: actions/cache@v4
        with:
          path: |
            **/tsconfig.tsbuildinfo
          key: ${{ runner.os }}-tsbuildinfo-${{ hashFiles('tsconfig.base.json', '**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-tsbuildinfo-
      - name: Type check changed workspaces
        run: yarn workspaces foreach -vvRp --since=${{ inputs.since || 'main' }} run type-check --incremental
        env:
          # increased memory because we were getting an out of memory error when running lint
          NODE_OPTIONS: "--max-old-space-size=8192"
```


It may be just a coincidence, but when I saw this issue happen, one of the workflows finished with error (it can completely, but finished with error, say, because some unit test failed). Then the other job that was running on the other runner stops executing in the middle. And then in the "Annotations" section I have that message: "The self-hosted runner: b4ac7d30-8387-4499-a899-f75d06e2941f lost communication with the server."

When I go check the logs of that runner on AWS, there is no error message. The build just stops running in the middle.

The error does not happen in a single job. It happens in any of the jobs on that workflow. Some jobs complete successfully, there is one that completes with an error (like unit test, type checking, linting error), and another job that is apparently aborted in the middle
