### ISSUE TITLE
adding a random string after an expression in a conditional job will be evaluated as true

### ISSUE THREAD

**Issue by v-rosa** [actions/runner#2629]
Adding a random string or even a single char in end of a conditional job after, is always interpreted as true.

See the following example:

```yml
name: reproduce-bug
  on:
    workflow_dispatch:
  jobs:
    a:
      name: a
      runs-on: ubuntu-latest
      steps:
        - run: echo "A"
        - id: set
          run: |
            echo "executed A"
    b:
      name: b
      runs-on: ubuntu-latest
      needs:
        - a
      steps:
        - run: echo "executed B"
    c:
      name: c
      runs-on: ubuntu-latest
      needs:
        - a
        - b
      if: ${{ !always() }}
      steps:
        - run: echo "executed C"
```

Job 3 is expected to never be executed. Now add a single quote `'` at the end of the expression and job3 will be executed.

```yml
name: reproduce-bug
  on:
    workflow_dispatch:
  jobs:
    a:
      name: a
      runs-on: ubuntu-latest
      steps:
        - run: echo "A"
        - id: set
          run: |
            echo "executed A"
    b:
      name: b
      runs-on: ubuntu-latest
      needs:
        - a
      steps:
        - run: echo "executed B"
    c:
      name: c
      runs-on: ubuntu-latest
      needs:
        - a
        - b
      if: ${{ !always() }} '
      steps:
        - run: echo "executed C"
```

The same would happen if you add any other char/string instead of `'`.

IMO this is a bug because if we remove the expression `${{ }}`, the workflow would be considered invalid, e.g.

`if: stringaaa`

> The workflow is not valid. .github/workflows/reproduce-bug.yml (Line: 26, Col: 9): Unrecognized named-value: 'stringaaa'. Located at position 1 within expression: stringaaa

## Runner Version and Platform

Runner version: `2.304.0`

OS of the machine running the runner: `Linux`
