### ISSUE TITLE
Why string input is converted into date format?

### ISSUE THREAD

**Issue by retzero** [actions/runner#2636]
Hello.
I'm not sure this is the right place to ask.
Here is my workflows;
```yaml
      - uses: MyAccount/TestRepo@main
        with:
          version: '2023-06-01T02:34:19'
```

And the composite action;

```yaml
inputs:
  version: 
    type: string

runs:
  using: "composite"
  steps:
    - run:  echo "${{ inputs.hyokeun }}"
      shell: bash
```

The `version` input is automatically converted into date format. 
```
Run echo "06/01/2023 02:34:19"
06/01/2023 02:34:19
```

How to disable this auto-conversion? I need the **actual** input string.
