### ISSUE TITLE
Steps failed and annotation showed failures but job showed passed

### ISSUE THREAD

**Issue by MeWu-IDM** [actions/runner#2639]
**Describe the bug**
We have a step running Rscript command looks like this
```
- name: Run Integration tests
        run: |
          Rscript -e "testthat::test_dir('tests/testthat/', stop_on_failure=TRUE, stop_on_warning=FALSE)"
          if errorlevel 1 echo "::error:: Integration tests failed" && exit 1
        shell: cmd
        continue-on-error: false
        env:
          NOT_CRAN: true
```
the console shows 2 tests failed and it putputs:

```
[ FAIL 2 | WARN 10 | SKIP 0 | PASS 167 ]

Don't worry, you'll get it.

Error during wrapup: object 'f' not found
Error: Error: no more error handlers available (recursive errors?); invoking 'abort' restart
[1] "Error: Test failures\n"
[1] "Error: Object cannot be printed to log\n"
```

**To Reproduce**
https://github.com/InstituteforDiseaseModeling/PACE-HRH/actions/runs/5150705092/jobs/9275148132

**Expected behavior**
Job should fail and notify users

## Runner Version and Platform
runner version: '2.304.0'

OS of the machine running the runner? Windows
