### ISSUE TITLE
Step stdout and stderr are not being set when continue-on-error is set to true.

### ISSUE THREAD

**Issue by dreinhardt-terminus** [actions/runner#2646]
**Describe the bug**
Step stdout and stderr are not being set when continue-on-error is set to true.

**To Reproduce**
1. Run the below code.
2. Check the console output.

**Expected behavior**
If continue-on-error is set to true the stdout / stderr should be set in the step outputs.

## Runner Version and Platform
2.304.0

Ubuntu 22.04.2

## What's not working?
Step default outputs (stderr/stdout) are not being set when exit code is non-zero and continue-on-error is set to true. Happens when running tflint. When running tflint I get an exit of 2 (tflint runs but found issues) I then want to be able to create a PR comment using the exit code and stdout/stderr but those values are not being set.

### Code
```yaml
runs:
  using: "composite"
  steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ env.SSH_KEY }}
    - name: Pull
      uses: actions/checkout@v3
        - name: TFLint - Setup
      if: ${{ inputs.tflint_enabled == 'true' }}
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
    - name: TFLint - Show Version
      run: tflint --version
      shell: bash
    - name: TFLint - Init
      run: tflint --init
      shell: bash
        - name: TFLint
      id: tflint_test
      continue-on-error: true
      run: |
        VAR_FILES=$(printf -- '--var-file=%s ' vars/${{ inputs.terraform_workspace }}*.tfvars)
        tflint $VAR_FILES || continue
      shell: bash
    - name: Test TFLint output
      run: |
        echo "steps.tflint_test.outputs.stdout"
        echo ${{ steps.tflint_test.outputs.stdout }}
        echo "steps.tflint_test.outputs.stderr"
        echo ${{ steps.tflint_test.outputs.stderr }}
      shell: bash
    - name: Test All Outputs
      run: |
        echo "Log all step outputs"
        echo ${{join(steps.tflint_test.outputs.*, '\n')}}
      shell: bash
```

## Step Log Output
```
16 issue(s) found:

Warning: `eks_deploy_oidc_idp` variable has no type (terraform_typed_variables)

  on variables-eks.tf line 108:
 108: variable "eks_deploy_oidc_idp" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `ssh_key` variable has no type (terraform_typed_variables)

  on variables.tf line 6:
   6: variable "ssh_key" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `artifactory` variable has no type (terraform_typed_variables)

  on variables.tf line 8:
   8: variable "artifactory" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `gh_read_token` variable has no type (terraform_typed_variables)

  on variables.tf line 10:
  10: variable "gh_read_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `gh_deployment_token` variable has no type (terraform_typed_variables)

  on variables.tf line 12:
  12: variable "gh_deployment_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `gh_pull_access_token` variable has no type (terraform_typed_variables)

  on variables.tf line 14:
  14: variable "gh_pull_access_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `gh_devops_token` variable has no type (terraform_typed_variables)

  on variables.tf line 16:
  16: variable "gh_devops_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `github_app_id` variable has no type (terraform_typed_variables)

  on variables.tf line 18:
  18: variable "github_app_id" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `github_app_installation_id` variable has no type (terraform_typed_variables)

  on variables.tf line 20:
  20: variable "github_app_installation_id" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `github_app_pem_file` variable has no type (terraform_typed_variables)

  on variables.tf line 22:
  22: variable "github_app_pem_file" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `buoyant_client_id` variable has no type (terraform_typed_variables)

  on variables.tf line 24:
  24: variable "buoyant_client_id" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `buoyant_client_secret` variable has no type (terraform_typed_variables)

  on variables.tf line 26:
  26: variable "buoyant_client_secret" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `pagerduty_api_token` variable has no type (terraform_typed_variables)

  on variables.tf line 28:
  28: variable "pagerduty_api_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: `slack_api_token` variable has no type (terraform_typed_variables)

  on variables.tf line 30:
  30: variable "slack_api_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Warning: variable "slack_api_token" is declared but not used (terraform_unused_declarations)

  on variables.tf line 30:
  30: variable "slack_api_token" {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_unused_declarations.md

Warning: `migrate_secrets` variable has no type (terraform_typed_variables)

  on variables.tf line 32:
  32: variable "migrate_secrets" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_typed_variables.md

Error: Process completed with exit code 2.
Run echo "steps.tflint_test.outputs.stdout"
steps.tflint_test.outputs.stdout

steps.tflint_test.outputs.stderr

Run echo "Log all step outputs"
Log all step outputs

```
