### ISSUE TITLE
"jobs.<job_id>.uses" and "jobs.<job_id>.runs-on" Two parameter conflict

### ISSUE THREAD

**Issue by p81061473525** [actions/runner#2654]
**Describe the bug**
Can't not use "jobs.<job_id>.uses" and "jobs.<job_id>.runs-on" together 
I've read the document , but it doesn't write any conflict with these two parameter

**To Reproduce**
main.yml
```
name: dev 環境 build-test-deploy

on:
  push:
    branches: [ "devops","dev-env" ]

jobs:
  build:
    runs-on: self-hosted
    uses: <private_name>/<private_name>.github/workflows/<private>.yml@dev
    secrets:
          SECRECTS: ${{ secrets. SECRECTS }}

  build_without_uses:
    runs-on: self-hosted
    steps:
   - name: 1
      run: |
      - echo "1" 
```

**Expected behavior**
I Can use "jobs.<job_id>.uses" and "jobs.<job_id>.runs-on" together 

## Runner Version and Platform
Version of your runner?
self-hosted 

OS of the machine running the runner? OSX/Windows/Linux/...
amazon linux 2

## What's not working?

The workflow is not valid. .github/workflows/main.yml (Line: 10, Col: 5): Unexpected value 'uses' .github/workflows/main.yml (Line: 11, Col: 5): Unexpected value 'secrets'

## Job Log Output
The workflow is not valid. .github/workflows/main.yml (Line: 10, Col: 5): Unexpected value 'uses' .github/workflows/main.yml (Line: 11, Col: 5): Unexpected value 'secrets'

## Runner and Worker's Diagnostic Logs
The workflow is not valid. .github/workflows/main.yml (Line: 10, Col: 5): Unexpected value 'uses' .github/workflows/main.yml (Line: 11, Col: 5): Unexpected value 'secrets'
