### ISSUE TITLE
Reusable workflows do not respect conditional steps based on inputs.

### ISSUE THREAD

**Issue by jason-edstrom** [actions/runner#2658]
**Describe the bug**
Reusable workflow does not respect conditional inputs.  The current behavior is that they run all steps listed in the reusable workflow.  This is related to #1602.

**To Reproduce**
1. Create a reusable workflow that uses inputs in its conditional steps.
2. Run
3. See error

**Expected behavior**
That I can conditionally run steps in a reusable workflow.

## Runner Version and Platform
Version of your runner? 2.304.0 

OS of the machine running the runner? OSX/Windows/Linux/...
macOS arm64

## What's not working?
My conditionals attached to steps in a reusable workflow should be respected.  They are not and both steps will trigger.

<img width="470" alt="image" src="https://github.com/actions/runner/assets/2515629/7bbea753-4f11-4b26-8627-1dcc9e08aa11">

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

[Runner_20230612-205711-utc.log](https://github.com/actions/runner/files/11738638/Runner_20230612-205711-utc.log)
[Worker_20230613-180512-utc.log](https://github.com/actions/runner/files/11738639/Worker_20230613-180512-utc.log)

**Comment by jason-edstrom** [comment]
Thanks for the reply, @ChristopherHX.  I changed the conditionals' syntax to match your code snippet, which is still failing.  The first conditional in the pair will always run (whether it should or not), and the second conditional fails shortly after entering the step.  I tried to "hide" the conditionals in a composite step, but it still failed.  The error message is not existent.  It only presents me with the following:
```
Error: Process completed with exit code 1.
```

![image](https://github.com/actions/runner/assets/2515629/f96396f7-d2f3-4f52-ad5d-381c585555da)

```yaml
name: Prepare CodePush
description: prepare codepush folder structure
inputs:
  app_name:
    description: "App to bundle/build"
    required: true
  platform:
    description: "Platform to prepare for"
    required: true



runs:
  using: 'composite'
  steps:
    - name: Prepare Codepush Folder (iOS)
      if: inputs.platform == 'ios'
      shell: bash
      run: |
        mkdir ${{ github.workspace }}/apps/rn-apps/${{ inputs.app_name }}/codepush &>/dev/null
        mkdir -p ${{ github.workspace }}/apps/rn-apps/${{ inputs.app_name }}/build/ios &>/dev/null
    - name: Prepare Codepush Folder (Android)
      if: inputs.platform == 'android'
      shell: bash
      run: |
        mkdir ${{ github.workspace }}/apps/rn-apps/${{ inputs.app_name }}/codepush &>/dev/null
        mkdir -p ${{ github.workspace }}/apps/rn-apps/${{ inputs.app_name }}/build/android/sourcemaps &>/dev/null
        mkdir -p ${{ github.workspace }}/apps/rn-apps/${{ inputs.app_name }}/build/android/assets &>/dev/null
        mkdir -p ${{ github.workspace }}/apps/rn-apps/${{ inputs.app_name }}/build/android/res &>/dev/null
```
