### ISSUE TITLE
Allow null container

### ISSUE THREAD

**Issue by cfoch** [actions/runner#2667]
**Describe the bug**
As a follow-up of https://github.com/actions/runner/pull/2235 having a null or empty container still is not allowed, and I get the following error:

```
Invalid workflow file: .github/workflows/build-recipes.yml#LXX
The workflow is not valid. .github/workflows/build-recipes.yml (Line: XX, Col: XX): Unexpected value ''
```

**To Reproduce**
Execute this workflow:
```
jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ''
    steps:
      - name: Hello
        run: echo 'Hello World'
```

**Expected behavior**
If container.image is empty, docker container creation should be ignored.

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
```
Invalid workflow file: .github/workflows/build-recipes.yml#LXX
The workflow is not valid. .github/workflows/build-recipes.yml (Line: XX, Col: XX): Unexpected value ''
```
