### ISSUE TITLE
Commands do not allow literal `%0A`

### ISSUE THREAD

**Issue by ericsciple** [actions/runner#267]
It should be possible to communicate literal `%0A` via commands. For example:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: foo
        run: |
          echo '::set-output name=bar::literal%250A'
      - env:
          bar: ${{ steps.foo.outputs.bar }}
        run: |
          echo "$bar"
```
