### ISSUE TITLE
Can a job be marked as successful even if one of its steps failed?

### ISSUE THREAD

**Issue by Mufasa** [actions/runner#2679]
### Discussed in https://github.com/actions/runner/discussions/2671

<div type='discussions-op-text'>

<sup>Originally posted by **Mufasa** June 25, 2023</sup>
I used to use CircleCI and have recently started trialing GitHub Actions. My project uses pnpm and nx. There is one scenario that I am finding difficult to implement as illustrated in this action:
```yml
name: CI/CD

on:
  push:
    branches: ['main']

jobs:
  lint_and_unit_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v3
        with:
          # Required by nx-set-shas
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v3
        with:
          error-on-no-successful-workflow: true
      - name: List affected projects
        run: pnpm list-affacted-projects
      - name: Run lint & unit tests on affected projects only
        run: |
          pnpm lint:affected
          pnpm test:affected
      - name: Run lint & unit tests on ALL projects
        if: ${{ failure() }}
        run: |
          pnpm lint:all
          pnpm test:all
```
The step `Derive appropriate SHAs for base and head for nx affected commands` makes use of nx to detect the last successful workflow. If it finds one, then it will only build the projects in my monorepo that were affected by the changes since the last successful workflow.

Now, I have made several checkins which all failed due to various reasons. Once I fixed those, then I hit the issue I am describing here. Since there is no "last successful" workflow, the step `Derive appropriate SHAs for base and head for nx affected commands` fails because I have set its `error-on-no-successful-workflow` to `true`. If I remove tis setting then it defaults to comparing what changed since `HEAD~1`. In my scenario that would yield the wrong set of files which is why I have set this parameter to `true`.

What I was expecting to happen, and what actually happens, is that the steps `List affected projects` and `Run lint & unit tests on affected projects only` get skipped due to the failure and instead the step `Run lint & unit tests on ALL projects` is run.

However, after a successful run of the step `Run lint & unit tests on ALL projects`, the job itself fails when in fact I wanted it to succeed unless of course the step `Run lint & unit tests on ALL projects` itself fails.

I was hoping that I could somehow reset the jobs failure marker in the step `Run lint & unit tests on ALL projects` - something along the lines of:
```yml
...
      - name: Run lint & unit tests on ALL projects
        if: ${{ failure() }}
        uses: actions/reset-job-failure
        run: |
          pnpm lint:all
          pnpm test:all
```
where I have made up a GitHub action named `uses: actions/reset-job-failure`.

Is this possible to do and, if not, would it be possible to add this enhancement? Alternatively, is there another way to achieve my requirements?</div>

**Comment by eddelbuettel** [comment]
The snippet above (in [the last comment](https://github.com/actions/runner/issues/2679#issuecomment-1645222952)) actually no longer works, but formed the basis for an updated, complete version:

#### Code

```yaml
# Play with continue on error
#
# cf https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#steps-context

name: continue_error

on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Initial Test"
      - run: exit 1
        id: badexit
        continue-on-error: true
      - run: echo "Catching NOT failure via outcome"
        if: steps.badexit.outcome != 'failure'
      - run: echo "Catching failure via outcome"
        if: steps.badexit.outcome == 'failure'
      - name: Debug step
        run: |
          echo "Outcome:    ${{ steps.badexit.outcome }}"
          echo "Conclusion: ${{ steps.badexit.conclusion }}"
```

#### Outcome

<img width="937" height="803" alt="Image" src="https://github.com/user-attachments/assets/3da7d3ca-0925-480c-aa91-02c47ed1f360" />

This shows
- overall job status 'successful' ie ✔️ 
- actual error occurred noted
- overall job continued due to `continue-on-error: true` in error step
- failure can be conditioned on via `if: steps.badexit.outcome == 'failure'` (if 'badexit' is name of erroring step)
- overall success is accessible via `steps.badexit.conclusion` (again if 'badexit' is name of erroring step)
