### ISSUE TITLE
No space left on device- container presteps support

### ISSUE THREAD

**Issue by Martin-Molinero** [actions/runner#2712]
**Describe the bug**
Using `container` there's no way to run presteps on the host, which in this case would be useful to delete unrequired tools (see related https://github.com/actions/runner-images/issues/7969) to avoid space issues or to run some custom configuration

**To Reproduce**
```
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
```
**Expected behavior**
Being able to run `df -h && rm -rf /opt/hostedtoolcache* && df -h` on the host

```
jobs:
  build:
    runs-on: ubuntu-20.04
   pre-steps:
       run: df -h && rm -rf /opt/hostedtoolcache* && df -h
    container:
        image: quantconnect/lean:foundation
```
See related https://github.com/QuantConnect/Lean/pull/7396
## Runner Version and Platform
`ubuntu-20.04`
## What's not working?
No space left on device when pulling see https://github.com/QuantConnect/Lean/actions/runs/5645968966/job/15292876421

## Job Log Output
Fails when pulling image see https://github.com/QuantConnect/Lean/actions/runs/5645968966/job/15292876421

## Runner and Worker's Diagnostic Logs
N/A
