### ISSUE TITLE
Bug while setting a step output parameter using $GITHUB_OUTPUT

### ISSUE THREAD

**Issue by suiluj** [actions/runner#2723]
**Describe the bug**

When trying to set a step output paramter the step fails.

**To Reproduce**

I just tried to use the example from the github actions docs:  
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

```bash
echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
```

**Expected behavior**
working like described in the docs

## Runner Version and Platform
2.296.3

OS of the machine running the runner? linux/selfhosted

## What's not working?

```
Error: Process completed with exit code 1.  
line 1: : No such file or directory
```

**Comment by nikola-jokic** [comment]
I think you need to update your runner version in order to make it work. 2.296.3 is too old, and switch to the GITHUB_OUTPUT was happening on version 2.297.0: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by suiluj** [comment]
@nikola-jokic ah thanks for the hint. It seems that the runners in our environment will get an update the next weekend. I will close this issue as soon as I checked with the new version.

**Comment by suiluj** [comment]
our runner got update to version 2.299.2

now the example works as expected but i noticed that you cannot use the step output of a step in a previous job in the following jobs.

here is the adjusted example which does not work:

```yaml
jobs:

  test-set-output:
    runs-on: [ self-hosted ]
    steps:
    - name: Set color
      id: random-color-generator
      run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    - name: Get color
      env:
        SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
      run: echo "The selected color is $SELECTED_COLOR"
  
  test-get-output:
    runs-on: [ self-hosted ]
    needs: test-set-output
    steps:
    # - name: Set color
    #   id: random-color-generator
    #   run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    - name: Get color
      env:
        SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
      run: echo "The selected color is $SELECTED_COLOR"
```

The variable is empty in the next job:
```
# output of the run logs
Run echo "The selected color is $SELECTED_COLOR"
The selected color is 
```

How do I use output of a previous step in a previous job in the following jobs?

**Comment by suiluj** [comment]
ah I found some information for job outputs:

- https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action
- https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

In my opinion this should be linked in the [docs for step output](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) so other users will not be confused.

I will try the job output now.

**Comment by suiluj** [comment]
Here is the color example with multiple jobs:

```yaml
jobs:
  # example docs job output which uses step output:
  # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job
  test-set-output:
    runs-on: [ self-hosted ]
    outputs:
      SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
    steps:
    - name: Set color
      id: random-color-generator
      run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    - name: Get color in same job
      env:
        SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
      run: echo "The selected color is $SELECTED_COLOR"
  
  test-get-output:
    runs-on: [ self-hosted ]
    needs: test-set-output
    steps:
    - name: Get color from previous job (must be "need dependency" of this job)
      env:
        SELECTED_COLOR: ${{needs.test-set-output.outputs.SELECTED_COLOR}}
      run: echo "The selected color is $SELECTED_COLOR"
```
