### ISSUE TITLE
`GITHUB_ENV` doesn't work properly

### ISSUE THREAD

**Issue by keraprogress** [actions/runner#2725]
```yaml
name: Build

on: repository_dispatch

jobs:
  windows-build:
    name: Windows
    runs-on: windows-latest
    outputs:
      version: ${{ steps.fetch.outputs.RELEASE_VERSION }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Fetch version
        run: |
          $version=$(python -c "print(open('version', 'r').read())")
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append // GITHUB_OUTPUT also doesn't work
          echo "test1 $version"

      - name: Print version
        run: echo ${{ steps.fetch.outputs.RELEASE_VERSION }}
```
![img](https://i.kek.sh/1VKCrBOuRLn.png)

I also tried to add a linux runner to the workflow, and use `echo "RELEASE_VERSION=$version" >> "$GITHUB_OUTPUT"` instead of `echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append` and accessing the variable with `needs.linux-build.outputs.version` instead of `steps.fetch.outputs.RELEASE_VERSION` but that didn't work either.
