### ISSUE TITLE
GitHub Actions Hang Indefinitely - no feedback to user.

### ISSUE THREAD

**Issue by petcuvio** [actions/runner#2730]
**Describe the bug**

Previously reported to [`runner-images`](https://github.com/actions/runner-images/issues/8024#issuecomment-1662157915)
 
I recently encountered an issue with GitHub Actions where a workflow was pending indefinitely. After some investigation, I discovered that the problem was caused by a typo in the image name specified in the runs-on field of the workflow YAML file. The image didn't exist, but instead of erroring out and providing feedback about the issue, the workflow just hung in a pending state.

```yaml
name: Cleanup Old Versions
on:
  workflow_dispatch: 
jobs:
  cleanup:
    env:
      PACKAGE_DOCKER: "container"
      PACKAGE_DOCKER_NAME: "rpg%2Frpg-dockerized"
      PACKAGE_NPM: "npm"
      PACKAGE_NPM_NAME: "rpg"
    runs-on: ubuntu:22.04    # !!! this should have been 'ubuntu-22.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
```

**To Reproduce**

1. take any workflow (workflow_dispatch)
2. replace the `runs-on` property with anything valid in `yaml`, but not a valid runner image: 
```yaml
runs-on: ubuntu:22.04

#or

runs-on: steam-power 

#or

runs-on: unicorn:dreams:and:rainbows

```
3. start the workflow (manually via GitHub UI)

**Expected behavior**

A comprehensive message along the lines of: 

` 🛑  runner image "ubuntu:22.04" does not exist`
or
` 🛑  label "ubuntu:22.04" not found`

## Runner Version and Platform

Current runner version: '`2.307.1`'

OS is irrelevant since this is happening before anything starts. 

## What's not working?

Workflow spins its wheels indefinitely, not __*even*__ re-running it with `debug` flag on, reveals something useful:

![image](https://github.com/actions/runner-images/assets/53478278/4765fa3a-1b73-4353-b6e7-ab5c23db4c00)

## Job Log Output
Job does not start

## Runner and Worker's Diagnostic Logs
Debug flag enabled (after manual stop and re-run) shows no additional output.
