### ISSUE TITLE
ANSI escape sequences mess with whitespace.

### ISSUE THREAD

**Issue by Qwerty-133** [actions/runner#2734]
Whitespace present at the start of lines aren't displayed when ANSI escape sequences are used.

Output from the runner:
![Runner output](https://github.com/actions/runner/assets/74311372/76508ca7-a18b-4164-b1d4-02b6e2d02a8f)

Output from the terminal:
![Terminal output](https://github.com/actions/runner/assets/74311372/265d4a93-988f-4115-8625-e5e9af026f11)

temp.txt contents:
```
[38;5;203mdescription[38;5;231m: [38;5;186mInstalls delta, and configures git to use it.[0m
[0m
[38;5;203mbranding[38;5;231m:[0m
[48;5;52;38;5;231m  [38;5;203micon[38;5;231m: [1;48;5;124;38;5;186mfile-plus[0m[48;5;52m[0K[0m
[48;5;52;38;5;231m  [38;5;203mcolor[38;5;231m: [38;5;186mgreen[0m[48;5;52m[0K[0m

---

[38;5;203mdescription[38;5;231m: [38;5;186mInstalls delta, and configures git to use it.[0m
[0m
[38;5;203mbranding[38;5;231m:[0m
  [38;5;203micon[38;5;231m: [1;48;5;124;38;5;186mfile-plus[0m[48;5;52m[0K[0m
  [38;5;203mcolor[38;5;231m: [38;5;186mgreen[0m[48;5;52m[0K[0m
```

The actions log contain the correct ANSI sequences. When simply printing the downloaded log output to the terminal, the white space is visible.

## Reproduction Steps
```yaml
name: Ansi

on:
  workflow_dispatch:

jobs:
  ansi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat temp.txt
```

## Runner Version and Platform
2.307.1, Github Actions. The bug appears on all platforms, Ubuntu, Windows and MacOS
