### ISSUE TITLE
ubuntu-latest large runners are unavailable

### ISSUE THREAD

**Issue by narekshs** [actions/runner#2742]
I am trying to use GitHub Actions hosted ubuntu large runners , but the job is not being picked up, endless waiting for the runner to pick up the job is happening . It is working fine with usual `ubuntu-latest` , but not with `ubuntu-latest-8-cores` or `ubuntu-latest-16-cores`
name: Test Executor
here is how I define the yml file 
```
on:
  workflow_dispatch:
    branches:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 4 * * *"

    # Inputs the workflow accepts.

jobs:
  build:
    runs-on: ubuntu-latest-8-cores
```
