### ISSUE TITLE
Github Actions predefined environment variables didn't pass to CI jobs

### ISSUE THREAD

**Issue by thoongnv** [actions/runner#2793]
I'm checking if CI env vars have `GITHUB_ACTIONS=true` inside Rust code to trigger my tests and found out that all of `GITHUB_*` variables didn't exist on os: `ubuntu-latest`

My debug Rust code

```rust
use std::env;

for (key, value) in env::vars() {
    println!("{key}: {value}");
}
```

Other OS (macos-latest, windows-latest) working fine

## Job Log Output
Here is my CI log (at steps: Run tests): https://github.com/thoongnv/trends-rs/actions/runs/5971557447/job/16200780296

**Comment by thoongnv** [comment]
As `HOME` env variable was set to `/` which is incorrect and I want to change that with this but didn't work

```yaml
- name: Set env
      if: matrix.os == 'ubuntu-latest'
      run: echo "HOME=/home/$USER" >> $GITHUB_ENV
```

Is there any way to change it?
