### ISSUE TITLE
Retry on failure does not retry dependent jobs when the failed job and dependent job are within a matrix

### ISSUE THREAD

**Issue by danowensdev** [actions/runner#2810]
**Describe the bug**
If a job with the matrix strategy uses a reusable workflow and one of the jobs in the matrix fails, clicking 'Retry failed jobs' will only start the jobs that failed, not the dependencies of those jobs as well.

**To Reproduce**

```
name: outer_workflow
on:
  workflow_dispatch:
jobs:
  main:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        grouping: ["1", "2", "3"]
    uses: ./.github/workflows/inner_workflow.yaml
```

```
name: inner_workflow
on:
  workflow_call:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
    - run: |
        number=$RANDOM
        echo $number
        if [ $number -gt 8000 ]
        then
          echo "failed"
          exit 1
        fi
  b:
    runs-on: ubuntu-latest
    needs: [a]
    steps:
      - run: |
          echo "Job B running"
```
**Expected behavior**
If job `a` fails within inner_workflow, and the user selects "Retry failing jobs", both jobs `a` and `b` should run (assuming job `a` is successful on the second run).

However, only job `a` is started, and then the matrix proceeds to the next entry without ever starting job `b`.

<img width="972" alt="image" src="https://github.com/actions/runner/assets/110904448/b42ddcb8-c95e-471e-846c-3472596d0d95">

<img width="367" alt="image" src="https://github.com/actions/runner/assets/110904448/12f9c515-ef88-4632-a34b-55d40be73b44">

## Runner Version and Platform
ubuntu-latest

Also see this discussion topic, where the bug is detailed: https://github.com/orgs/community/discussions/52505
