### ISSUE TITLE
Wrong runner runs on job

### ISSUE THREAD

**Issue by TommyGun-hyphen** [actions/runner#2825]
I have set up a server for staging purposes.
my staging workflow yaml file:

name: monbatiment STAGING

```
on:
    push:
        branches: [ staging ]
    pull_request:
        branches: [ staging ]
jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
              runner: [ STAGING-front ]
        steps:
        - uses: actions/checkout@v2
 ```
## in github actions:

[build (STAGING-front)](https://github.com/MonBatiment/**REPO**/actions/runs/6076138082/job/16483893891#logs)

but this is the output for "Setup Job":
```
Current runner version: '[2](https://github.com/MonBatiment/**REPO**/actions/runs/6076267689/job/16483963088#step:1:2).[3](https://github.com/MonBatiment/**REPO**/actions/runs/6076267689/job/16483963088#step:1:3)08.0'
Runner name: **'novadia-front'**
Runner group name: 'Default'
Machine name: 'novadia'
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:ee0669bd1cc5[4](https://github.com/MonBatiment/**REPO**/actions/runs/6076267689/job/16483963088#step:1:4)29[5](https://github.com/MonBatiment/**REPO**/actions/runs/6076267689/job/16483963088#step:1:5)c223e0bb666b733df41de1c5)
Complete job name: build (STAGING-front)
```
the runner **novadia-front** runs. but not the intended **STAGING-front** ???
earlier it was **mkhome-front** that was running. another separate runner i have for another workflow
