### ISSUE TITLE
User UUID changed between versions of the runner

### ISSUE THREAD

**Issue by yeikel** [actions/runner#2837]
**Describe the bug**

With runners `2.296.3` the UUID for the user was `1000` but with `2.303.0` (and possibly earlier) the UUID changed to `1001` 

This is a problem because in a fleet with runners of different versions, it is more challenging than necessary to run with a non-root user as the UUID needs to match depending on the version of the runner

**To Reproduce**

```yml
  find-uuid-new:
    runs-on: [ self-hosted,runner-2.303.0    ]
    steps:
      - run: |
          echo $(id -u)

  find-uuid-old:
    runs-on: [ self-hosted,runner-2.296.3   ]
    steps:
      - run: |
          echo $(id -u)
```

![image](https://github.com/actions/runner/assets/8935151/6af1823e-8a55-4e93-a566-79ecf69c2690)
![image](https://github.com/actions/runner/assets/8935151/553f36c4-765f-42fe-98b4-3286885fc919)

**Expected behavior**

The UUID should stay consistent between releases to allow having fleets with different versions running concurrently 

## Runner Version and Platform
Version of your runner?

I observed the difference between 2.296.3 and 2.303.0 but I do not know when it started

## What's not working?

To run unprivileged users with Github Actions, it is necessary to create users matching the expected UUID. The UUID should stay consistent between releases
