### ISSUE TITLE
Invalid Workflow File but succeeds for some runs 

### ISSUE THREAD

**Issue by Danielovich** [actions/runner#2862]
**Describe the bug**

I have a workflow file which sometimes fails and sometimes succeeds

This action is failing

![image](https://github.com/actions/runner/assets/273661/d8bf3791-66cd-4741-b0ea-e6066ac80a2e)

Exactly the same file succeeds

![image](https://github.com/actions/runner/assets/273661/ba19c356-f306-4eb0-af7a-c593421a1142)

```
name: ci-meshes

on:
  workflow_dispatch:
  push:
    branches:
      - master 
      - '*release*'
    paths:
      - 'Source/Meshes/**'
  pull_request:
    branches:
      - master 
      - '*release*'
    paths:
      - 'Source/Meshes/**' 

```

Failure:

I push code into "Source/BillGates/Money" on a some feature branch (not release or master)
I create a new pull request against a "*release*" branch.
Action fails.

Success:

I push code into "Source/Meshes/Tests" on a some feature branch (not release or master)
I create a new pull request against a "*release*" branch.
Action succeeds

In my mind this action should never even run when code is not pushed onto the given paths of the workflow file. But it does.

Not only does it run it then throws ans error based on my workflow file syntax (see failure image).

It might be that the precedence/order of how the workflow file is structured is wrong but it should imo not throw a syntax error and then on another run succeed.
