### ISSUE TITLE
self hosted runner stuck on queued,May be a bug in self hosted runner

### ISSUE THREAD

**Issue by joebnb** [actions/runner#2904]
### Discussed in https://github.com/actions/runner/discussions/2457

<div type='discussions-op-text'>

<sup>Originally posted by **tdubb123** February 22, 2023</sup>
i got self hosted runner on prem but its stuck in queued

Waiting for a runner to pick up this job...
Job is about to start running on the runner: k8gui (repository)

any idea? 

my workflow file is

name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        script: whoami

from the runner vm, I can ssh to HOSt without password</div>

as the upper question,the same question i have met and i was stunted on this about 2 days.the detail of information i can give.

that is the ssh-action seems many people were use and action even more.but i think there was a bug between ssh-action and runner when the case is self hosted runner.

the problem is the github runner can't ssh to server and it's throw permisison denined,i checked the setting of my server and pull up a container to test manual login via ssh key(it's success as expect).

and i was do serval times of generate and check my ssh key to ensure key correct and formate is openssh supported.

my environment is the runner under a docker container of UbuntuServer,and this server also is deploy target，the deploy flow is:
-  scp artifacts to Ubuntu Server
-  decompress artifacts into some path which were mapped by docker volume
-  restart docker service
-  finish deploy

the reproduce yaml is:
```
name: Node.js CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    build:
      
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v4
            - run: ip address
            - name: Set ENV 
              run: export no_proxy=127.0.0.0/8,172.17.0.0/16,192.168.0.0/16 && export NO_PROXY=127.0.0.0/8,172.17.0.0/16,192.168.0.0/16
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ vars.REMOTE_HOST }}
                username: ${{ vars.REMOTE_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: whoami

```
some vars and ssh private key need custom and may need a local VM.

the error is:
![image](https://github.com/actions/runner/assets/1646883/6781cc1a-beea-4750-8df4-2a5aadea25a0)

and i also try another ssh tool named ssh-deploy have similar problem

![image](https://github.com/actions/runner/assets/1646883/ce1dd906-db03-45fe-aa88-e1078fde3fe0)

i import these key into a ubuntu docker container and trying to no password login is success,the key pair is correct.
and i try rsa and ed25519 algorithm both.in ubuntu container is work,in runner is not work.

there are a lot help not fulfilled in: https://github.com/appleboy/ssh-action/issues/80  https://github.com/easingthemes/ssh-deploy/issues/143
