### ISSUE TITLE
Base64 Masking of Secrets should account for appending strings

### ISSUE THREAD

**Issue by thboop** [actions/runner#291]
The base 64 encoder handles the cases of base64(secret) and base64(prefix + secret) pretty well. However, the case of base64(secret+suffix) does not get masked in some cases.

For example, consider the workflow
```
name: Node CI

on: [pull_request,push]

jobs:
  testsecret:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{secrets.abc}} | base64
        echo ${{secrets.abc}}
        echo hello
```
We set the secret `abc` to `1234`

In our logs we see:
```
MTIzNAo=
***
hello
```
`MTIzNAo=` is the string `1234\n` converted to base 64. It appears in the log because we register the string `MTIzNA==` as a secret. We should register `MTIzN` as a secret in this case, so this will get partially masked.

We should:
- Trim `=` from base64 encoded versions of secrets, as it may prevent us from getting matches when we should. (`=` is a base64 padding character that gets removed when you append something to the string)
- Trim the last character from a base64 string that contains `=` as it may change
