### ISSUE TITLE
pnpm next build commad not working also not able to detect packages.json file

### ISSUE THREAD

**Issue by rajrupdasofficial** [actions/runner#2928]
**Describe the bug**
**First **problem****
When I am running pnpm install
action dashboard telling me  there is no package.json file found ,in my repository it is there on the root of my project workspace . But the same is running correctly on local host pc backed up by latest ubuntu.
**also to mention** 
When i explicitly adding pnpm install package.json it's installing packages that time.

**second problem**
I am getting this error -> 
```
undefined
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "next" not found
Error: Process completed with exit code 1.

```
when i am running pnpm next build . which is running properly on localhost on ubuntu latest

**Some things to mention**
Node version - v20.7.0
pnpm version on github - 8.9.0

**repository**
[Repository](https://github.com/RajrupDasid/nextjs_resume_blog_symmetrical-system)

**To Reproduce**
1. Make a github action pipeline 
```
name: Next.js build and deploy to s3
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Node management
        uses: actions/setup-node@v3
        with:
          node-version: "20.7.0"
      - name: Install packages
        run: |
          node --version
          npm install -g pnpm
          pnpm --version
          pnpm install package.json

      - name: Build static files
        run: |
          pnpm next build
```
3. Let it run

**Expected behavior**
It needs to run and properly because the same commands running on localhost just fine 

## Runner Version and Platform
Version of your runner?
Github hosted

OS of the machine running the runner? Linux/ ubuntu-latest

## What's not working?
Please include error messages and screenshots.
![Screenshot from 2023-10-13 21-34-36](https://github.com/actions/runner/assets/60233333/6279ae27-3489-4fb5-bc59-e4dd27db14a9)

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
