### ISSUE TITLE
Github Actions Error: Process completed with exit code 253

### ISSUE THREAD

**Issue by ooples** [actions/runner#2936]
I'm trying to create a github pipeline and I'm getting very generic errors when trying to generate code coverage reports and uploading them to Codacy. I don't see any errors at all in the output log other than the error from my title at the very end. All of my unit tests pass and code builds successfuly. Any ideas on how to find out what the error is? I have pasted the output log below:

[![enter image description here](https://i.stack.imgur.com/HlSjK.png)](https://i.stack.imgur.com/HlSjK.png)

```
- name: Restore .NET Tools
      run: dotnet tool restore
      working-directory: ./tests

    - name: Dotnet Test (Debug)
      run: dotnet dotcover test --dcOutput="AiDotNet.Coverage.xml" --dcReportType="XML"

    - name: Dotnet Build (Release)
      run: dotnet build -c Release
          
    - name: Send Coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
```

I followed a few different tutorials for how to setup the codacy github actions from the codacy website as well as github action examples.

UPDATE: I'm using the setup .net github action using the code below:

    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

UPDATE #2: I'm uploading the full debug log for the step where it is failing at: https://pastebin.com/Pc7AXiqb
