### ISSUE TITLE
Issues getting json input for matrix to parse correctly

### ISSUE THREAD

**Issue by IanTaylor-catapult** [actions/runner#2947]
Opening from previously closed ticket where the issue was seen.

Same issue as @Mykp3. Tried passing both a json string (properly escaped), and a plaintext json from a GitHub repository environment variable to a matrix. No matter what I've done I get the same as output listed above.
`TARGET_MACHINES={\"targets\": [{\"name\":\"xxxxxxxx\",\"ip\":\"xxxxxxxx\"}]}`
The JSON above is a repository environment variable.
```
    environment: ${{ inputs.env_name }}
    # Matrix for target machines provided as JSON in a GitHub environment variable.
    strategy:
      matrix: ${{ fromJson(vars.TARGET_MACHINES) }}
    steps:
      -
``` 
![image](https://github.com/actions/runner/assets/109170332/ec960619-7b9e-4ae8-b724-424883063d21)

_Originally posted by @IanTaylor-catapult in https://github.com/actions/runner/issues/2424#issuecomment-1775814579_
