### ISSUE TITLE
npm install not working with binaries

### ISSUE THREAD

**Issue by nonodev96** [actions/runner#2955]
Hello, I have the problem that sometimes the dependencies are not installed with npm, sometimes the deployments work and sometimes they don't, I have tried with `npm ci` and `npm i`.

This is the actions [Test CI](https://github.com/nonodev96/nets4learning/actions/runs/6653306313/job/18079004478)

Steps to reproduce:
1. Commit with tag "v*" to start the runner

## Runner Version and Platform

* Ubuntu - latest 
* Node - 18

## What's not working?

```
sh: 1: craco: not found
Error: Process completed with exit code 127.
```

## File YAML

```yaml
name: 'Deploy'

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-stable:
    name: 'Deploy to netlify stable'
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          echo "${{ secrets.NETLIFY_ENV_FILE_STABLE }}" > .env.netlify
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STABLE }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          INSTALL_COMMAND: npm ci
          BUILD_COMMAND: npm run build:netlify
          BUILD_DIRECTORY: 'build'
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
```

## Job Log Output

```log
Run jsmrcaga/action-netlify-deploy@v2.0.0
Run /home/runner/work/_actions/jsmrcaga/action-netlify-deploy/v2.0.0/entrypoint.sh

added 996 packages, and audited 997 packages in 1m

174 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (1 low, 15 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> nets4learning@1.9.6 build:netlify-snapshot
> craco build --mode netlify-snapshot

sh: 1: craco: not found
Error: Process completed with exit code 127.
```
