### ISSUE TITLE
It should be easier to force `shell: pwsh` to use a specific PowerShell installation;

### ISSUE THREAD

**Issue by tig** [actions/runner#2975]
It should be easier to force `shell: pwsh` to use a specific pwsh installation; it seems to always use `C:\Program Files\PowerShell\7\pwsh.EXE`. I tried `shell: C:\Users\runneradmin\.dotnet\tools\pwsh` and got an error.

I've found a workaround of having a step install the latest PS using `dotnet tool install` and changing `$env:GITHUB_PATH`, but it's clunky.

```yml
    - name: HACK - Install Latest PowerShell (so we get v7.3+ that uses .net 7)
      shell: pwsh
      run: |
            dotnet tool install --global PowerShell
            $content = Get-Content -Path $env:GITHUB_PATH
            $HOME + "/.dotnet/tools`r`n" + $content | Set-Content -Path $env:GITHUB_PATH -Encoding utf8
```

This (or something similar) should work:

`shell: $HOME + /.dotnet/tools/pwsh {0}`

_Originally posted by @tig in https://github.com/actions/runner-images/issues/8754#issuecomment-1796170450_
