### ISSUE TITLE
Different Behavior in Workflow vs Composite Action

### ISSUE THREAD

**Issue by SachinMeier** [actions/runner#2976]
**Describe the bug**

I have an elixir app for which I run Dialyzer in CICD. I recently tried moving the Dialyzer job from a reusable workflow into a composite action, and the job went from passing to failing. 

**To Reproduce**
1. Setup elixir project. Mine has actual Dialyzer warnings, which is why i have the special bash scripting to allow a certain number of them. 

Use the following workflow (note that it calls into the action):
```

name: Lint & Test

on:
  - workflow_call

env:
  MIX_ENV: test
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  ADMIN_POSTGRES_USERNAME: postgres
  ADMIN_POSTGRES_PASSWORD: postgres

permissions:
  contents: read

jobs:
  app:
services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.16.0
        with:
          elixir-version: '1.15.6'
          otp-version: '26.1'
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            apps/app/deps
            apps/app/build
          key: ${{ runner.os }}-mix-app-${{ hashFiles('apps/app/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-app-${{ hashFiles('apps/app/mix.lock') }}
            ${{ runner.os }}-mix-app-
      - name: Restore dialyzer PLTs cache
        uses: actions/cache@v3
        with:
          path: apps/app/plts/dialyzer.plt
          key: ${{ runner.os }}-plt-app
          restore-keys: |
            ${{ runner.os }}-plt-

      # TODO: this step might be useless
      - name: Install dependencies
        working-directory: ./apps/app
        run: mix deps.get

      - name: Dialyzer
        env:
          ALLOWED_WARNINGS: 92
        working-directory: ./apps/app
        run: |
          echo "$ALLOWED_WARNINGS allowed"
          mix dialyzer --format github |& tee dialyzer_output.txt
          TOTAL_ERRORS=$(grep -o 'Total errors: [0-9]*' dialyzer_output.txt | awk '{print $3}')
          SKIPPED=$(grep -o 'Skipped: [0-9]*' dialyzer_output.txt | awk '{print $2}')
          DIALYZER_WARNINGS_COUNT=$((TOTAL_ERRORS - SKIPPED))
          echo "Dialyzer has $DIALYZER_WARNINGS_COUNT non-skipped errors"
          if [ "$DIALYZER_WARNINGS_COUNT" -gt "$ALLOWED_WARNINGS" ]; then
            echo "Dialyzer has more warnings ($DIALYZER_WARNINGS_COUNT) than allowed ($ALLOWED_WARNINGS)"
            exit 1
          else
            echo "Dialyzer has $DIALYZER_WARNINGS_COUNT warnings, which is less than or equal to the allowed amount ($ALLOWED_WARNINGS)"
            exit 0
          fi

      - name: Lint
        uses: ./.github/actions/lint-phx-app
        with:
          app: app
          dialyzer_warns_allowed: 92
```

And a Composite action at ./.github/actions/lint-phx-app/action.yaml
```

name: Lint
description: Basic Linting of a Phoenix app in a Poncho repo
inputs:
  app:
    type: string
    description: "the name of the app to lint. It should be found at apps/{app}"
    required: true
  dialyzer_warns_allowed:
    type: number
    description: "the number of dialyzer warnings allowed"
    required: false
    default: 0

runs:
  using: 'composite'
  steps:
    - name: Dialyzer - ${{ inputs.app }}
      shell: bash
      env:
        ALLOWED_WARNINGS: ${{ inputs.dialyzer_warns_allowed }}
      working-directory: ./apps/${{ inputs.app }}
      run: |
        echo "$ALLOWED_WARNINGS allowed"
        mix dialyzer --format github |& tee dialyzer_output.txt
        TOTAL_ERRORS=$(grep -o 'Total errors: [0-9]*' dialyzer_output.txt | awk '{print $3}')
        SKIPPED=$(grep -o 'Skipped: [0-9]*' dialyzer_output.txt | awk '{print $2}')
        DIALYZER_WARNINGS_COUNT=$((TOTAL_ERRORS - SKIPPED))
        echo "Dialyzer has $DIALYZER_WARNINGS_COUNT non-skipped errors"
        if [ "$DIALYZER_WARNINGS_COUNT" -gt "${{ inputs.dialyzer_warns_allowed }}" ]; then
          echo "Dialyzer has more warnings ($DIALYZER_WARNINGS_COUNT) than allowed ($ALLOWED_WARNINGS)"
          exit 1
        else
          echo "Dialyzer has $DIALYZER_WARNINGS_COUNT warnings, which is less than or equal to the allowed amount ($ALLOWED_WARNINGS)"
          exit 0
        fi
```

**Expected behavior**

Ideally, the job should fail or succeed in the same way. 

## Runner Version and Platform

Deployed to k8s using `actions.summerwind.dev/v1alpha1`'s `RunnerDeployment`. 

## What's not working?

In both cases, Dialyzer results would be the same, but the composite action would fail earlier and fail the job. 

## Job Log Output

workflow results:
```
...other Dialyzer outputs...
Warning: The function call get_pdf will not succeed.
done (warnings were emitted)
Halting VM with exit status 2
Dialyzer has 88 non-skipped errors
Dialyzer has 88 warnings, which is less than or equal to the allowed amount (92)
```

action results:
```
Warning: The function call get_pdf will not succeed.
done (warnings were emitted)
Halting VM with exit status 2
Error: Process completed with exit code 2.
```

## Runner and Worker's Diagnostic Logs

The runners themselves are healthy. The behavior is just undesirable.
