### ISSUE TITLE
Two self-hosted runners incorrectly run the same job

### ISSUE THREAD

**Issue by DolceTriade** [actions/runner#3010]
**Describe the bug**
If you launch a multiple of workflows that run on selfhosted runners,  sometimes, two runners will run the same job. What this means is that if we have self hosted Runner A and Runner B and Workflow A and Workflow B, Runner A and Runner B will both run Workflow A leaving no runners to run Workflow B.

The GHA UI only shows the output from one of the runners, if looking at the logs on the other runner, we can see it is also running Workflow A and Workflow B remains queued.

**To Reproduce**
This doesn't happen *all* the time, but it definitely happens at least once every ~50 attempts
1. Launch multiple workflows that run on self hosted runners
2. Watch two self hosted runners pick up and run the same workflow.

**Expected behavior**
Only one runner picks up one workflow.

## Runner Version and Platform
Version of your runner?
v2.311.0

OS of the machine running the runner? OSX/Windows/Linux/...
Linux x86_64

**Comment by nicholasbergesen** [comment]
Hi, could you please clarify whether separate runners are running the same job in the same workflow run, or if different runners are running the same job in two different workflow runs.

Depending on what triggers you have on a workflow its very possible that you have multiple instances of Workflow A running at the same time, which would lead to the same job in workflow A being run by different runners. To prevent this you can use concurrency to ensure only 1 job is run at a time across all workflow runs for workflow A.

**Comment by nicholasbergesen** [comment]
Could you please share some more information like workflow triggers and the runner logs where the same job is picked up by multiple runners.

**Comment by DolceTriade** [comment]
An example workflow might be something like:

```
---
name: 'CI'

"on": push

permissions:
  contents: write
  id-token: write


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ["self-hosted", "bazel", "nix"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: bazel test //...
```

Unfortunately I don't have logs, but nothing in the logs pointed to anything suspicious. Both runners had messages like "Running job ci".

In the end, we worked around this problem by:
 - including the runner id in the tags (ie, adding `tags: ["self-hosted", "bazel", "nix", "${{ github.runner_id }}, "workflow-name"]`
 - Propagating these tags to the JIT runner to ensure that only the job that was provisioned for it can run on the runner, which is unfortunate, but it works well enough.

Again, we didn't do anything special.
