### ISSUE TITLE
Default branch workflows can be triggered from a workflow of a different branch 

### ISSUE THREAD

**Issue by Lukas113** [actions/runner#3025]
**Describe the bug**

Default branch workflows got accidentally triggered from a different branch. In my use-case, I intended to change from a workflow_run completed trigger to a locally referenced reusable workflow setup. This behavior can have serious side-effects to the project in case the workflow on the default-branch wasn't supposed to run at all.

**To Reproduce**

Here's a minimal example.

Default branch workflows:

workflowA.yml
```
name: A-Workflow

on:
  workflow_dispatch:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: stepA
        shell: bash -l {0}
        run: |
          echo "stepA default-branch"
```

workflowB.yml
```
name: B-Workflow

on:
  workflow_run:
    workflows: ["A-Workflow"]
    types:
      - completed

jobs:
  jobB:
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        shell: bash -l {0}
        run: |
          echo "stepB default-branch"
```

Other, non-default-branch workflows, changed from completed to workflow_call:

workflowA.yml
```
name: A-Workflow

on:
  workflow_dispatch:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: stepA
        shell: bash -l {0}
        run: |
          echo "stepA on-other-branch"
          
  trigger-locally-reusable-workflow:
    needs: jobA
    uses: ./.github/workflows/workflowB.yml
```

workflowB.yml
```
name: B-Workflow

on:
  workflow_call:

jobs:
  jobB:
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        shell: bash -l {0}
        run: |
          echo "stepB on-other-branch"
```

**Expected behavior**

It is expected that the workflows on the default-branch won't get triggered from a branch-commit workflow.

## Runner Version and Platform
Shouldn't matter I think.

## What's not working?

Here are screenshots from my repo, where I just triggered the `Conda Build` action manually on the branch `512_sarus`. The other two workflows are actually workflows triggered on the default branch.

Actions overview:
![image](https://github.com/actions/runner/assets/32157249/55af924e-327f-4797-821f-20eb4286e289)

`Conda Build` action
![image](https://github.com/actions/runner/assets/32157249/40063d3a-8dfb-42a1-8333-271bc4c9f0b2)
