### ISSUE TITLE
 Inputs context not available in reusable workflows #2206 

### ISSUE THREAD

**Issue by iamutkarshtiwari** [actions/runner#3038]
Facing the exact error as described in [this closed ticket.](https://github.com/actions/runner/issues/2206)

**Comment by lthoedt** [comment]
Same! I have the following code which calls the reusable workflow
```yml
  upload_android:
    needs: [create_release]
    uses: ./.github/workflows/jobs/ci/upload_android.yml
    with:
      release_url: ${{ needs.create_release.outputs.release_url }}
      build_id: ${{ needs.create_release.outputs.build_id }}
      build_path: build/app/outputs/apk/release/app-release.apk
    secrets: inherit
```
upload_android.yml is defined like this:
```yml
on:
  workflow_call:
    inputs:
      release_url:
        required: true
        type: string
      build_id:
        required: true
        type: string
      build_path:
        required: true
        type: string
permissions:
  contents: write
jobs:
  upload_android:
    name: Uploading android build
    runs-on: ubuntu-latest
    outputs:
      cache_hit: ${{ steps.cached-apk.outputs.cache-hit }}
    steps:
      - run: echo [${{ github.event.inputs.build_path }}]

      - name: Restore cached APK
        id: cached-apk
        uses: actions/cache/restore@v3
        with:
          path: ${{ inputs.build_path }}
          key: apk
          fail-on-cache-miss: true

      - name: Uploading Android Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ${{ inputs.build_path }}
          asset_name: ${{ inputs.build_id }}.apk
          asset_content_type: application/gzip
  ```
  None of the inputs are available; they are all empty.
  Running with: 
  ```bash
  gh act --input build_path=test
  ```
  does work.
  
  I have no clue what could be wrong. This is as far as i can find the exact same as their docs.
