### ISSUE TITLE
Service container not reachable by alias/DNS

### ISSUE THREAD

**Issue by ntang86** [actions/runner#3042]
**Describe the bug**
Service container can be pinged but not reachable by alias/DNS when using [setup-buildx-action](https://github.com/docker/setup-buildx-action).

![postgres2](https://github.com/actions/runner/assets/138027010/73b4b2c7-2e85-44fd-85de-31bdb993eb1b)
![postgres](https://github.com/actions/runner/assets/138027010/7369b73c-b631-4b47-aa43-a6549387d689)
<img width="773" alt="image" src="https://github.com/actions/runner/assets/138027010/2bf328dc-9efb-4931-8cf5-6647a664a267">

**To Reproduce**
Github action:

```yaml
name: PostgreSQL service container
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup postgres client
        run: |
          sudo apt update
          sudo apt install -y postgresql-client

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Show DB
        run: |
          PGPASSWORD=postgres psql -U postgres -h postgres -d postgres -c "SELECT current_database();"

```

**Expected behavior**

## Runner Version and Platform
Version of your runner? 2.311.0

OS of the machine running the runner? Linux
