### ISSUE TITLE
cronjob scheduled for non-existant date will run every few minutes

### ISSUE THREAD

**Issue by rogervdf** [actions/runner#3044]
cron job that is scheduled to run on a non-existent date will run every few minutes instead of never.

```
on:
  schedule:
  - cron: "* * 30 2 *"
  workflow_dispatch:

env:
```
![image](https://github.com/actions/runner/assets/43315295/83a9f117-d5f9-4457-9905-ffa0fe12f67e)
