### ISSUE TITLE
Is this a bug on Actions' YAML parser?

### ISSUE THREAD

**Issue by anr2me** [actions/runner#3061]
**Describe the bug**
First of all, i'm not sure whether this is the right place to report this bug.
I was testing a few `echo` with expression (some of them might be wrong), and seems to bump into a bug that can cause the whole workflow to be invalid and failed to start, which caused by a single line (regardless whether that line being commented or not)

Here is the workflow: https://github.com/anr2me/ppsspp/actions/workflows/test_bug.yml
```yaml
name: Testing Bug
on:
  workflow_dispatch:
    inputs:

      buildConfiguration:
        type: choice
        description: 'Build Configuration'
        required: true
        default: 'Release'
        options: 
        - Release
        - Debug

      buildPlatform:
        type: choice
        description: 'Build Platform'
        required: true
        default: 'x64'
        options: 
        - x64
        - ARM64
        - ARM

jobs:

  build-uwp:
    name: Generate ${{ github.event.inputs.buildConfiguration }} UWP
    runs-on: windows-latest

    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    fetch-depth: 0
      #    submodules: recursive
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Testing values
        run: |
          # Testing values ...
          env
          echo "Content of [env.GITHUB_WORKSPACE] = ${env.GITHUB_WORKSPACE}"
          echo "Content of [[env.GITHUB_WORKSPACE]] = ${{env.GITHUB_WORKSPACE}}"
          echo "Content of [env:GITHUB_WORKSPACE] = ${env:GITHUB_WORKSPACE}"
          # echo "Content of [[env:GITHUB_WORKSPACE]] = ${{env:GITHUB_WORKSPACE}}" # This line (commented or not) will make this YML file to be invalid and showing an error at the wrong line (a bug in the YAML parser may be?)
          echo "Content of [github.workspace] = ${github.workspace}"
          echo "Content of [[github.workspace]] = ${{github.workspace}}"
          echo "one ${ github.event.inputs.buildPlatform }"
          echo ${{github.workspace}}
          echo "two ${{ github.event.inputs.buildPlatform }}"
          echo $env:GITHUB_WORKSPACE
```

**To Reproduce**
1. Run the test_bug.yml workflow manually
2. See error, which is pointing to the wrong line number

**Expected behavior**
Should at least run, or shows the correct line number in case of error.
Also, commenting the problematic line should behave the same to deleting the line.
This is the result after deleting the problematic line https://github.com/anr2me/ppsspp/actions/runs/7335042995/job/19972491722

## Runner Version and Platform
Version of your runner? I'm not sure

OS of the machine running the runner? `windows-latest` at github's.

## What's not working?
Please include error messages and screenshots.
![image](https://github.com/actions/runner/assets/7974720/cc8c328a-1508-4c17-b3ff-d1b9dd905428)

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
