### ISSUE TITLE
[2.165.0 Only] Can't reference steps context in step's env block

### ISSUE THREAD

**Issue by TingluoHuang** [actions/runner#308]
```yaml
name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: output foo
      id: foo
      run: |
        echo "::set-output name=foo::BAR"
        echo "::set-output name=FOZ::BAZ"
    - name: run
      env:
        FOO: ${{ steps.foo.outputs.foo }}
        FOZ: ${{ steps.foo.outputs.FOZ }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: env
```

the run step now has FOO/FOZ set to an empty string (but works fine on 2.164.0)
