### ISSUE TITLE
Typo in "runs-on" results in indefinitely waiting for a runner to pick up workflow

### ISSUE THREAD

**Issue by PrinsFrank** [actions/runner#3081]
**Describe the bug**
When the value for 'runs-on' contains a typo, the workflow indefinitely stays in the "waiting to be picked up" state.

**To Reproduce**
1. Create a workflow that contains a typo in the runs-on key. For example:
```yml
jobs:
  test:
    name: Test
    runs-on: ubuntu-lates #Note the lack of a 't' here
    steps:
      - run: echo 'foo'
```

**Expected behavior**
Either of two options:
- The workflow doesn't run at all and errors with the 'invalid workflow file' error
- The job doesn't run and errors with a "invalid runner" error or similar

## Runner Version and Platform
Github hosted. (ubuntu-latst including the typo)

## What's not working?
The workflow is trying to be started when it shouldn't

## Job Log Output
```
Requested labels: ubuntu-latst
Job defined at: PrinsFrank/standards/.github/workflows/ci.yml@refs/heads/main
Waiting for a runner to pick up this job...
```

## Runner and Worker's Diagnostic Logs
N/A, bug happens before the job is started.
