### ISSUE TITLE
if: ${{ github.event_name != 'workflow_call' }} not working

### ISSUE THREAD

**Issue by kenorb** [actions/runner#3146]
**Describe the bug**

I'm reusing workflow by calling it from another repo, like:

```
jobs:
  test:
    uses: org/repo/.github/workflows/test.yml
```

And inside re-used workflow I've defined the following condition:

```
on:
  workflow_call:

jobs:
 cleanup:
   if: ${{ github.event_name != 'workflow_call' }}
   runs-on: ubuntu-latest
   steps:
     - uses: geekyeggo/delete-artifact@v4
       with:
         name: *
```

The issue is that `if: ${{ github.event_name != 'workflow_call' }}` condition doesn't work.

**Expected behavior**

I'm expected that job not to run from the calling workflow (uses: org/repo...).
So I want to call the job when I'm running workflow in the same repo.

## Runner Version and Platform
2.312.0

OS of the machine running the runner?

Linux

## What's not working?

Condition doesn't work as expected.

It's possible that conditions for workflows calls are ignored, because I've tested with different condition, and it didn't work either.

**Comment by tjarbo** [comment]
According to my understanding, this is an expected behavior:

> A workflow that uses another workflow is referred to as a "caller" workflow. The reusable workflow is a "called" workflow.
> [...]
> If you reuse a workflow from a different repository, any actions in the called workflow run as if they were part of the caller workflow. For example, if the called workflow uses actions/checkout, the action checks out the contents of the repository that hosts the caller workflow, not the called workflow.
Source: https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by marcodicro-dp** [comment]
The problem is `github.event_name` will have the value related to the caller workflow.

E.g. if the caller workflow was triggered by push, then `github.event_name` will be `push` inside the caller workflow and inside the called workflow too.

See here I ran a workflow manually (`github.event_name=workflow_dispatch`) that calls a reusable worklfow.

Inside reusable workflow (triggered by workflow_call) I run `echo "event_name=${{github.event_name}}"`and the result is `workflow_dispatch`.

![image](https://github.com/actions/runner/assets/121044623/0d54ff48-1178-4044-a8a0-9fe2e9465813)

**Comment by marcodicro-dp** [comment]
Maybe a possible workaround would be adding a input parameter E.g. `skip_cleanup`. And call the workflow with 
```
jobs:
  test:
    uses: org/repo/.github/workflows/test.yml
    with:
      skip_cleanup: 'true'
```

And then check for 

```
jobs:
 cleanup:
   if: ${{ inputs.skip_cleanup != 'true' }}
```

Not very elegant but works for running the job only on workflow_dispatch (IIUC is what you wanted).
Only downside is you'll have an extra param when running the workflow via UI.
