### ISSUE TITLE
job.steps.if: env.variable doesn't work?

### ISSUE THREAD

**Issue by kenorb** [actions/runner#3148]
**Describe the bug**

I've added condition for the job to not run, but it's still running it, despite the condition being false.

**To Reproduce**

```
env:
  CLEANUP: ${{ inputs.cleanup || false }}

on:
  workflow_call:
      cleanup:
        default: false
        description: Whether to run clean-up job
        required: false
        type: boolean

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        if: env.CLEANUP
        with:
          name: *
```

**Expected behavior**

Do not run job if the `if` condition is false.

## Runner Version and Platform

2.312.0

OS of the machine running the runner?

Linux

## Job Log Output

```
Run geekyeggo/delete-artifact@v4
  with:
    name: *
    token: ***
    useGlob: true
    failOnError: true
  env:
    CLEANUP: false
```

**Comment by ruvceskistefan** [comment]
Hey @kenorb,

here is a working solution for your problem:

```
on:
  workflow_call:
      cleanup:
        default: false
        description: Whether to run clean-up job
        required: false
        type: boolean

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        if: ${{ env.CLEANUP == 'true' }}
        with:
          name: *
```
