### ISSUE TITLE
"actions" not working under windows when needs to unzip things.

### ISSUE THREAD

**Issue by edpichler** [actions/runner#3152]
**Describe the bug**
I have a self hosted runner that is not being able to unzip installers. `action/setup-java` in the example.

**To Reproduce**
1. Install a self hosted runner in windows.
2. create a job :
```
 jobs:
  checkout_and_build:
    steps:
      - uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: '17'
          distribution: 'adopt'
```
3. Run it

**Expected behavior**
The action setups java.

## Runner Version and Platform
2.313.0

OS of the machine running the runner? OSX/Windows/Linux/...
Windows 11 

## What's not working?
![image](https://github.com/actions/runner/assets/358696/222ebd89-f5d8-4864-92bc-3213067b9179)
