### ISSUE TITLE
Can't curl public url on onrender.com to check for website health

### ISSUE THREAD

**Issue by zackees** [actions/runner#3156]
**Describe the bug**

**To Reproduce**

This is the url of the failure: https://github.com/TechWatchProject/kumquat/actions/runs/7934999258/job/21667193674

This job yml file reproduces the issue:

```yml
name: Test

on:  [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update CA certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
    
      - name: dig prod.kumquat.link
        run: |
            dig prod.kumquat.link

      - name: dig test2.kumquat.link
        run: |
            dig test2.kumquat.link

      - name: Production Site is up
        run: |
          output=$(curl -L https://kumquat-prod.onrender.com)
          echo "$output" | grep "Home Page"
      - name: Test Site is up
        run: |
          output=$(curl -L kumquat-test.onrender.com)
          echo "$output" | grep "About Page"
```

The "Update CA certificates" step may be optional. I was adding it as part of my debugging process.

**Expected behavior**

This curl command succeeds locally. The actual public URL is prod.kumquat.link and test2.kumquat.link. But neither this nor the onrender URL that prod/test2.kumqual.ink CNAMES to is succeeding on the github runner.

## Runner Version and Platform
Version of your runner?

ubuntu-latest

OS of the machine running the runner? OSX/Windows/Linux/...

ubuntu-latest

## What's not working?
Please include error messages and screenshots.

## Job Log Output

```
output=$(curl -L kumquat-test.onrender.com)
  echo "$output" | grep "About Page"
  shell: /usr/bin/bash -e {0}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    69  100    69    0     0    76[3](https://github.com/TechWatchProject/kumquat/actions/runs/7934999258/job/21667193674#step:7:3)      0 --:--:-- --:--:-- --:--:--   766

100     9    0     9    0     0     1[5](https://github.com/TechWatchProject/kumquat/actions/runs/7934999258/job/21667193674#step:7:6)      0 --:--:-- --:--:-- --:--:--    15
100     [9](https://github.com/TechWatchProject/kumquat/actions/runs/7934999258/job/21667193674#step:7:10)    0     9    0     0     15      0 --:--:-- --:--:-- --:--:--     0
Error: Process completed with exit code 1.
```
