### ISSUE TITLE
Exist pattern of not trrigered schedule event at leap day

### ISSUE THREAD

**Issue by totechite** [actions/runner#3176]
**Describe the bug**
In case of leap day, Not expected behavior exists when trrigered by `schedule` event .
Workflow not triggered at scheduled time.

**To Reproduce**
1. Set `schedule` event like this to your workflow.yaml.
    ```
   on:
      schedule:
        # Timezone: UTC+9
        # Runs at 0 minutes past the hour, every 2 hours, starting at 00:00+09:00, Monday through Friday
        - cron: "0 15/2 * * 1-5"
    ```
2. Wait the time of trigger event.
3. See logs the workflow runs.

**Expected behavior**
Running workflow in the scheduling of cron expression.

## Runner Version and Platform
Runner version: 2.309.0
Hosted on Debian 12 docker image
[debian:bookworm-slim](https://hub.docker.com/layers/library/debian/bookworm-slim/images/sha256-6bdbd579ba71f6855deecf57e64524921aed6b97ff1e5195436f244d2cb42b12?context=explore)
GitHub: GHE Server Version 3.11
