### ISSUE TITLE
Container/service volumes arent getting added to generated docker commands

### ISSUE THREAD

**Issue by dakale** [actions/runner#322]
**Describe the bug**

Give a workflow like:

```yaml
test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      volumes: 
      - src:dst
```

The appropriate docker option, `-v src:dst` is sometimes not generated when creating the container
