### ISSUE TITLE
Weird cache stickiness

### ISSUE THREAD

**Issue by soub4i** [actions/runner#3233]
**Describe the bug**

Hi
I had a strange behavior when I tried to create a simple github-action for my golang app. the action is linting and building app and after upload the artifact to release notes. 
The action is triggered by creating a new release. the issue is that Runner keep mentioning some old steps (Build skx/github-action-publish-binaries@master) that I removed from the workflow file.

**To Reproduce**

the repo is opensource:
https://github.com/soub4i/eircode/actions

the code: 

```yaml
# workflow name
name: release

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  Publish:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: go mod download

      - name: Lint and format code
        run: go fmt ./... && go vet ./...

      - name: Generate build files
        run: go build -o ./dist/ ./...

      - name: Archive build files
        run: cd dist && tar -czvf build.tar.gz eircode

      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: "./dist/*.tar.gz"
```

actual behavior

<img width="1040" alt="image" src="https://github.com/actions/runner/assets/11523791/3c8e9c69-5f88-41ea-9364-cda376058ef3">

**Expected behavior**
not executing this step 
<img width="663" alt="image" src="https://github.com/actions/runner/assets/11523791/28159d81-8fce-485b-a71d-ff6195e95b76">

## Runner Version and Platform
Version of your runner?

Linux

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
