### ISSUE TITLE
Expose GITHUB_JOB_ID as an environment variable

### ISSUE THREAD

**Issue by MarshallOfSound** [actions/runner#324]
**Describe the enhancement**
Expose `GITHUB_JOB_ID` as an environment variable to the running steps.  We need this in order for a job to be able to self-identify itself and potentially send it's own ID to a different service that would then use the GitHub API to perform actions (like check logs for instance).

**Code Snippet**
It looks like we need to add `job_id` to the whitelist here --> https://github.com/actions/runner/blob/master/src/Runner.Worker/GitHubContext.cs

Not sure though, hence raising this issue

**Comment by ericsciple** [comment]
Note, the job ID in yaml is the key in the `jobs` mapping (terminology aligns with step `id` keyword in yaml). So if we expose this via the context or env var, we should consider the terminology conflict.

**Comment by ericsciple** [comment]
@MarshallOfSound whitelist wont solve it. The job ID isn't in the github context.

```yaml
on: push
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

It sounds like for this scenario you need the number ([this job_id](https://developer.github.com/v3/actions/workflow_jobs/#get-a-workflow-job)), correct?

**Comment by MarshallOfSound** [comment]
@ericsciple Yes we'd need the `job_id` number that the GitHub API takes in.  If that's not in the context how can we get that exposed?

**Comment by ericsciple** [comment]
@TingluoHuang @juliobbv might be able to help drive an ADR for this change. IIRC logs are best effort (although lots of retries, so likely there) and uploaded asyncronously. It's unclear to me whether adding the value would actually enable the desired scenario. Ting or Julio can help figure out.

Also it doesn't look like the runner has the job ID at all. I dumped the worker log and confirmed it's not in the job message received from the server.

**Comment by ericsciple** [comment]
@chrispat fyi can help prioritize or redirect if there is a better place for the request

**Comment by chrispat** [comment]
@MarshallOfSound CodeCov does something similar but they just use the run_id which is in the environment and context.  Is there any specific reason you need to have the job_id?

**Comment by MarshallOfSound** [comment]
@chrispat It looks like the only way to get the logs of a job is with the `job_id`? Unless I'm missing something https://developer.github.com/v3/actions/workflow_jobs/#list-workflow-job-logs

Not sure how you can pull logs without it

**Comment by ericsciple** [comment]
The run id can be used [to get the job ids](https://developer.github.com/v3/actions/workflow_jobs/#list-jobs-for-a-workflow-run)

**Comment by MarshallOfSound** [comment]
@ericsciple Are you suggesting we iterate through all the jobs in the run and pull the logs for each job and if any one of them contains what we're looking for we can consider it valid?  That seems do-able but sub-optimable (it'll go through an API token faster than you otherwise would)

**Comment by MarshallOfSound** [comment]
@ericsciple Just circled back to this and it looks like with the new `GITHUB_JOB` variable we can do a more exact job lookup now using the API.  However I think I just hit this issue you predicted earlier.

> IIRC logs are best effort (although lots of retries, so likely there) and uploaded asyncronously. It's unclear to me whether adding the value would actually enable the desired scenario. Ting or Julio can help figure out.

They may be best effort but afaics the logs aren't available in the API at all until the job completes.  Are their any plans to allow us access to the logs before the job completes, otherwise I'm stuck behind a brick wall 😆

**Comment by dentarg** [comment]
I understand that `123805166` is `GITHUB_RUN_ID` (or `github.run_id`) in https://github.com/dentarg/actions-test/actions/runs/123805166

In https://github.com/dentarg/actions-test/runs/735126681, what is `735126681`? Is that the job ID that's requested here?

It would be nice to be able to construct https://github.com/dentarg/actions-test/runs/735126681 from a workflow run. My use-case is posting a direct link to the build in e.g. Slack.

**Comment by chrispat** [comment]
That is the `check_suite` id.  Depending on how you navigate sometimes you will get that URL.  However, for slack I would recommend using the http://github.com/dentarg/actions-test/actions/runs/<GITHUB_RUN_ID>

**Comment by chrispat** [comment]
@ericsciple given we called called the YAML id of the job `GITHUB_JOB` it seems we could add a `GITHUB_JOB_ID` with the API job id to mirror `GITHUB_RUN_ID`.

**Comment by relsqui** [comment]
> That is the `check_suite` id. Depending on how you navigate sometimes you will get that URL. However, for slack I would recommend using the [http://github.com/dentarg/actions-test/actions/runs/](https://github.com/dentarg/actions-test/actions/runs/)<GITHUB_RUN_ID>

This does not address the problem. When there are hundreds of jobs in a workflow matrix, linking directly to the one that matters vs. linking to the workflow summary makes a world of UX difference.

**Comment by cg14823** [comment]
By the looks of it the numeric job id is generated on the GitHub API but it is just not sent to the runner to be exposed. Is it possible to get it to the runner?

**Comment by Philippe-OPC** [comment]
Sry to dig this up, the numeric id of the job would be great. To explain a little bit my use case, i want to post the url of the job that failed to a database for a user to actually see logs of the CI tool i run in the github runner. The difficulty is that i use a matrix of var to run multiple times the "jobs". Here is some sample of the code i use to understand a little bit : 

action file :
```yml
name: Ci tool run

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env_suffix: ["DEV","UAT","PRD"]
    environment:
      name: ${{ matrix.env_suffix }}
    env: 
      BASE_REF: ${{ matrix.env_suffix }}
    
    steps:
      - name: run ci tools
        uses: mycitoolssharedaction
        with:
          var1: var1
          job_id: ?????
```

code to write in a database :
```js
const githubServerUrl = "https://github.com"
const githubRepository = process.env.GITHUB_REPOSITORY
const githubRunId = process.env.GITHUB_RUN_ID
const githubJobId = process.env.GITHUB_JOB_ID
const githubFullUrl = `${githubServerUrl}/${githubRepository}/actions/runs/${githubRunId}/jobs/${githubJobId}`

sql_client = new SQLClient();

query = 'INSERT INTO mytable VALUES(`${githubFullUrl}`)'

sq_client.run_query(query)
```

As an example

Thanks !

**Comment by untra** [comment]
for our use-case, we want to use the github api to post a reply to out PR, with a link to `https://github.com/company/repo/actions/$GITHUB_RUN_ID//jobs/$GITHUB_JOB_ID`, which is a sweet dashboard to give context to a failed build

**Comment by s0undt3ch** [comment]
Managing self hosted runners has not gotten simpler by GitHub.
The fact that we can use `ACTIONS_RUNNER_HOOK_JOB_COMPLETED` and `ACTIONS_RUNNER_HOOK_JOB_STARTED` helps a tad bit, but, **which job**?
We need that information to overcome the slim support for self hosted runners in the GH API.

**Comment by relsqui** [comment]
I respect the reasons to close this, but "as completed" seems disingenuous.

**Comment by s0undt3ch** [comment]
Closing this issue, as @relsqui pointed out, as completed, is not the right thing to do.

This is a feature request, and going to a forum to discuss is about the same as, yeah, we might read it, and even reply, but we won't do it.

If we were talking about, please add runner events X and Y to webhooks, and then you could possibly say, let's bring this to the forums because there might be other events other users might be interested in, then, potentially it could make sense, buy still, leave the issue open because it hasn't been resolved, nor rejected.

My .1 cent.

**Comment by qoomon** [comment]
You could use `qoomon/actions--context@v4` action to add additional environment variables.It will work also with matrix jobs and within reusable workflows.

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    environment: playground
    steps:
      - uses: qoomon/actions--context@v4
      - run: |
          echo "Job Id:         ${GITHUB_JOB_ID}"
          echo "Job Name:       ${GITHUB_JOB_NAME}"
          echo "Job Log URL:    ${GITHUB_JOB_URL}"
          echo "Environment:    ${GITHUB_ENVIRONMENT}"
          echo "Deployment URL: ${GITHUB_DEPLOYMENT_URL}"
```

This action determines the current job by listing all job of current workflow with current run id and then finds current job by matching the runner name or id.

Source: https://github.com/qoomon/actions--context
