### ISSUE TITLE
Cannot pass dynamic environment from input 

### ISSUE THREAD

**Issue by lamhktommy** [actions/runner#3307]
**Describe the bug**
Reusable workflow cannot get inputs passed from a main workflow

**To Reproduce**

_**dev/action.yml**_ 
```
name: Reusable workflow
on:
  workflow_dispatch:
    inputs:
      source-environment:
        required: true
        type: string
  workflow_call:
    inputs:
      source-environment:
        required: true
        type: string
jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.source-environment }}
    secrets: inherit
    steps:
      - run: echo "${{ inputs.source-environment }}"
        shell: bash
```

**_main_workflow.yml_**
```
jobs:
  action-dev:
    if: github.ref == 'refs/heads/main'
    environment: develop
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Reuse action
        uses: ./.github/actions/dev
        with:
          source-environment: develop
```

I have tried to use ```github.event.inputs.source-environment``` as well and also doesn't work

**Expected behavior**
Expection develop is output in the console

## Runner Version and Platform
ubuntu-latest

## What's not working?
```Unrecognized named-value: 'inputs'```
![image](https://github.com/actions/runner/assets/35717697/80064e15-1c7b-4218-9589-606b509470ff)
