### ISSUE TITLE
Segmentation Fault with Visual Studio 2022 on GitHub Actions Windows Runners - using C++ thread

### ISSUE THREAD

**Issue by pthom** [actions/runner#3331]
**Describe the bug**

I have encountered a segmentation fault when running a simple async program compiled with Visual Studio 2022 in release mode on GitHub Actions Windows 2022 runners.

**To Reproduce**

_Ready to use repro_

* [Full reproduction repository](https://github.com/pthom/study_ci_thread_fault)
* [GH Action result with the failure](https://github.com/pthom/study_ci_thread_fault/actions/runs/9481503691/job/26124415183)

_Step by step instructions_

1. Use the following C++ code in your repository:

main.cpp
```cpp
#include <future>
#include <cstdio>

int main() {
    auto handle = std::async(std::launch::async, []() { return 1; });
    int r = handle.get();
    printf("Result: %d\n", r);
}
```

2. Use the following CMakeLists:

```cmake
cmake_minimum_required(VERSION 3.5)
project("study_ci_thread_fault")
set(CMAKE_CXX_STANDARD 17)
add_executable(main main.cpp)
```

3. Use the following GitHub Actions workflow:

```yaml
name: ci

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - name: Build and Test
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          ./Release/main.exe
```

4. Observe the segmentation fault during the test execution.

**Expected behavior**
The async program should run without crashing.

**Actual Behavior**
The program crashes with a segmentation fault.

## Runner Version and Platform
windows-2022 (aka windows-latest)

OS of the machine running the runner? 
Windows

## Job Log Output

```
Run ./build/Release/main.exe
  ./build/Release/main.exe
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
Result: 1
```

## Insights

I posted this as a Stack Overflow question here. 

https://stackoverflow.com/questions/78612314/github-runners-issue-with-visual-studio-2022-segmentation-fault-with-the-simple

An helpful comment was given, which may be linked to this issue:

https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio
