### ISSUE TITLE
Macos runner gives randomly Intel (x86) or M1 (arm64) and no way to get only Intel(x86)

### ISSUE THREAD

**Issue by medyagh** [actions/runner#3339]
**Describe the bug**

We try to run functional test for minikube (using virtualbox) as seen here, how ever it randomly gives us either Arm64 or Intel CPU architecture and there is NO WAY for us to force it to give us only Intel 
https://github.com/kubernetes/minikube/blob/5eecf3084f2487ceb3cebad33ddfe0006908c941/.github/workflows/pr.yml#L521
we use
```
runs-on: macos-12
```
**To Reproduce**

```
  functional_virtualbox_macos:
    permissions:
      contents: none
    needs: [build_minikube_test_binaries]
    env:
      TIME_ELAPSED: time
      JOB_NAME: "functional_virtualbox_macos"
      GOPOGH_RESULT: ""
      SHELL: "/bin/bash" # To prevent https://github.com/kubernetes/minikube/issues/6643
    runs-on: macos-12
    steps:
      - name: Check architecture
        shell: bash
        run: |
          if [ $(uname -m) != "x86_64" ] 
          then 
              echo "$(uname -m) detected. This test must be run on x86_64"
              exit -1
          fi
          exit 0
```
for the full yaml checkout https://github.com/kubernetes/minikube/blob/5eecf3084f2487ceb3cebad33ddfe0006908c941/.github/workflows/pr.yml#L521

## **Expected behavior**
I expect it to give me the CPU architecture not randomly but through a tag such as Arch: x86

## Runner Version and Platform
I am using whatever latest available public for free macos-12 agents. 

### OS of the machine running the runner? OSX/Windows/Linux/...
macos-12

## What's not working?
We try to run minikube with Virtualbox but it fails because it gives us M1 Machines (arm64) and virtualbox only runs on intel.

Currently we are trying to implement a workaround that if we detect the CPU arch to be arm64 we Exit the test so at least it doenst fail, and we are planning to implement a cron job to keep triggering the test till it Gets the Right architecture, which is just a hack to get us going, and this is affecting anyone who uses macos runners, it is better to be fixed in github action runner for all users.

```
    runs-on: macos-13
    steps:
      - name: Check architecture
        shell: bash
        run: |
          if [ $(uname -m) != "x86_64" ] 
          then 
              echo "$(uname -m) detected. This test must be run on x86_64"
              exit -1
          fi
          exit 0
```
