### ISSUE TITLE
Conditional services

### ISSUE THREAD

**Issue by n1hility** [actions/runner#336]
When using a matrix strategy you may have services that are only relevant to a subset of the combinations. Having the ability to use a condition would prevent resource overrun from starting every possible service that a set of permutations might use.

A workaround to this problem is to use steps with the docker command manually, but then you lose the nice service abstraction.

For example

```yaml
strategy: 
  matrix:
    db: [redis, mysql, db2, etc]
services:
  redis:
    image: redis
    ports:
      - 6379/tcp
    if: matrix.db == 'redis'
```

**Comment by ericsciple** [comment]
another workaround is something like:
```yaml
strategy:
  matrix:
    - db: redis
      services:
        redis:
          image: redis
          ports: [ 6379/tcp ]
    - db: mysql
      services: { }
    - db: db2
      services: { }
    - db: etc
      services: { }
services: ${{ matrix.services }}
```
