### ISSUE TITLE
${{ toJson(github) }} results in error when there is bracket anwhere in the github context. 

### ISSUE THREAD

**Issue by PramodKumarYadav** [actions/runner#3361]
**Describe the bug**
The toJson(github) command to print github context fails if the commit message (or anywhere else - say a repository description) contains brackets ().

**To Reproduce**
1. Update your test repository description with a text that includes brackets. Example: My test repository with brackets (to test failing github context).
 ![image](https://github.com/actions/runner/assets/11694972/a84773ba-29fe-4151-a46f-d6d32f29bcb5)
2. Print the github context using echo statements such as below.

```
name: 🎯 Trigger tests

on:
  workflow_dispatch:

jobs:
  log-requester-details:
    runs-on: ubuntu-latest
    steps:
      - name: Log Requester details
        run: |
          echo "Event details: ${{ toJson(github) }}"
```

**Expected behaviour**
Should print the log.

**Actual behaviour**
Throws error on line that contains brackets. In this example it was in the description of repository but a more common scenario is to get this failure in commit message.

![image](https://github.com/actions/runner/assets/11694972/80165e9a-1c4c-4aa8-8330-7dc8faf695c8)

![image](https://github.com/actions/runner/assets/11694972/8cd99a99-d263-4c8f-bcae-e210e2922526)

NOTE: The line number is also always one ahead of what is printed in the logs.
