### ISSUE TITLE
Intermittent error: Docker Login failed with exit code 1 running jobs in container

### ISSUE THREAD

**Issue by FRABUCHI** [actions/runner#3384]
**Describe the bug**
I'm experiencing intermittent errors when attempting to log in to Docker on GitHub Enterprise using a self-hosted runner. 

The error resembles the one discussed in [this issue](https://github.com/actions/runner/issues/1978). 

I am trying to log in to Harbor, but there are no error traces in the Harbor logs corresponding to these login attempts. 

When login information is incorrect, I expect an unauthorized error, but instead, I receive an error message saying "Docker login for [harbor url] failed with exit code 1". 

I suspect the problem might be related to the runner. Notably, the workflow works correctly if I re-run the failed job.

**To Reproduce**
1. Go to the job configuration.
2. Run the GitHub Actions workflow.
3. Observe the error.
3. Re-run the failed workflow.
4. Observe that it runs successfully the second time.

**Expected behavior**
This docker login should succeed every time without exception

## Runner Version and Platform
Version of your runner? 2.311.0

OS of the machine running the runner? Amazon Linux 2

## What's not working?
The intermittent error occurs during the Docker login command to Harbor. The specific error is:

Docker login for [harbor url] failed with exit code 1
```
jobs:
  publish-events:
    runs-on:
      - gprunner
      - pool=m5a.large
    container:
      image: [harbor url]/devops/actions/devops:latest
      credentials:
        username: temp@example.com
        password: ${{ secrets.HARBOR_PASSWORD }}
```

<img width="1532" alt="스크린샷 2024-07-11 오후 4 57 30" src="https://github.com/actions/runner/assets/37655730/17a5c0a7-a53c-4870-911a-220ed690d4ee">

The workflow works correctly when re-run.
