### ISSUE TITLE
Workflow triggered on `workflow_run` event (triggered from `issue_comment` event) lack issue number

### ISSUE THREAD

**Issue by qkdreyer** [actions/runner#3438]
**Describe the bug**
Workflow triggered on `workflow_run` event (triggered from `issue_comment` event) lack issue number

**To Reproduce**
1. Create a `.github/workflows/comment.yml`
```yml
name: Comment
on:
  issue_comment:
    types: [created]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```
2. Create a `.github/workflows/workflow-run.yml`
```yml
name: Workflow Run
on:
  workflow_run:
    workflows:
      - Comment
    types:
      - completed
jobs:
  dump:
    if: ${{ github.event.workflow_run.event == 'issue_comment' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

**Expected behavior**
Payload from `workflow_run` workflow triggered from `issue_comment` event should include issue number

## Runner Version and Platform
Version of your runner?
2.319.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
Please include error messages and screenshots.
- Triggered from issue : https://github.com/qkdreyer/workflows/actions/runs/10527120006/job/29169553772
- Triggered from pull request : https://github.com/qkdreyer/workflows/actions/runs/10527130272/job/29169587891

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
