### ISSUE TITLE
[skip ci], [ci skip], [skip Actions]

### ISSUE THREAD

**Issue by MSP-Greg** [actions/runner#344]
I assume most users appreciate the support GitHub/MSFT give to public repos.  Likewise, I assume most don't want to waste resources.

Please support '[skip ci]' and '[ci skip]', and adding '[skip Actions]' would be helpful.  Both AppVeyor & Travis supported them.

I've seen many repos where people tag their PR's/commits with 'skip' it if it's just a comment/documentation  change.  Now, people stop the CI with:
```
if: "!contains(github.event.head_commit.message, '[ci skip]')"
```
but that still spins up a CI instance, which is wasteful, and also clogs up the CI table/list.

**Comment by TingluoHuang** [comment]
@MSP-Greg if you use that condition in Job `if`,
ex:
```
  
name: SKIP_CI

on: [push]

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'SKIP_ACTIONS') == true
```
 it wouldn't really waste compute resource since the job condition is evaluate on server side and we won't send the job to your physical actions runner. We do still create a check run for it, but that's really light weight.
