### ISSUE TITLE
hashFiles does not follow docs

### ISSUE THREAD

**Issue by y-nk** [actions/runner#3467]
**Describe the bug**
As per the docs:

<img width="763" alt="image" src="https://github.com/user-attachments/assets/5abeced9-3f79-43e3-b0c8-c4017eb8b73a">

internal code of `@actions/glob` mentions:

https://github.com/actions/toolkit/blob/6dd369c0e648ed58d0ead326cf2426906ea86401/packages/glob/src/glob.ts#L11

**To Reproduce**

```
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: touch file.ts file.tsx
      - run: echo ${{ hashFiles('file.ts\nfile.tsx') }} # empty output
      - run: echo ${{ hashFiles('file.ts', 'file.tsx') }} # correct hash

```

**Expected behavior**
it should be possible to pass a string with `\n` delimiters (or even better an array) so that we can feed a `fromJson()` or a `join(fromJson())` expression
