### ISSUE TITLE
Github Action workflows Hang

### ISSUE THREAD

**Issue by chenele** [actions/runner#3535]
Seems like there is an issue with Github Action Runners.
all our different actions looks 'wierd'.
The job output seems collapsed into a single Text output and seems ilke the job are never ends.

just created a simple dummy action to test it and it got reproduce.

```
name: Tester

on:
  push:

  
jobs:
  test:    
    runs-on: ubuntu-latest   
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo
        run: |
          echo Bla  
```

Output is endless while at the end seems like job cannot complete the cleanup process.
```
Post job cleanup.
/usr/bin/git version
git version 2.47.0
Temporarily overriding HOME='/home/runner/work/_temp/ab3e00c9-67e9-4e9a-83c1-740a432d20c6' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
Cleaning up orphan processes
```

Anyone else encountering such issues?
havent seen anything yet on Github-Status indicating the issue

**Comment by merinmarymathewsbh** [comment]
facing the same issue from some time. its waiting for runner even though the runner is idle.

**Comment by iairu** [comment]
same issue here, tried renaming the workflow, canceling the workflow doesn't work either, seems github never recognizes the output properly and considers the job "queued" forever even though the text in logs shows it as complete and successful

**Comment by junha6316** [comment]
same issue here

**Comment by melon-ruet** [comment]
Facing the same issue with ubuntu-24.04 as runner os

**Comment by Mohammed-Keafeel** [comment]
Facing same issue even though the runners are hosted private. Either it is queues to pick runner or getting stuck at Cleaning up orphan processes.

**Comment by Kavindu-Jayasinghe** [comment]
same issue here

**Comment by iairu** [comment]
> same issue here, tried renaming the workflow, canceling the workflow doesn't work either, seems github never recognizes the output properly and considers the job "queued" forever even though the text in logs shows it as complete and successful

renaming the job doesn't work either, left image is how it looks, right image is how it should look:

![image](https://github.com/user-attachments/assets/99812fea-841e-4b04-b716-6aa780e8becd)
![image](https://github.com/user-attachments/assets/e5d9242a-9dfc-4ca7-860b-723e0214012d)

here is my setup, still broken, haven't tried different OS from `ubuntu-latest`:
```
on:
  push:
    branches:
      - "*"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build-deploy
    steps:
    ...
```
