### ISSUE TITLE
`branches` and `paths` are not inclusive

### ISSUE THREAD

**Issue by georeith** [actions/runner#3570]
**Describe the bug**

[The documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) states:

> If you define both branches/branches-ignore and paths/paths-ignore, the workflow will only run when both filters are satisfied.

However this is not the case in our repository, if you specify `branches: **` and include `paths` then the action runs on any commit to any branch.

**To Reproduce**
I tried to make a simple reproduction but I couldn't reproduce the issue there: https://github.com/georeith/action-filter-bug-repro/pull/1. Which leads me to believe it's something to do with the overall size of our repo, it's a very large repository. Unfortunately it's a private repository but I will show screenshots that show it's misbehaving:

![image](https://github.com/user-attachments/assets/adb27bb5-7aee-42eb-940c-5fcdf0870b3c)
![image](https://github.com/user-attachments/assets/b0e96192-4968-42f0-ae90-fd1d14960fc1)

The contents of the action are:

```yml
name: Sync Translations Push

on:
  push:
    branches:
      - '**'
    paths:
      - 'locale/en.json'
      - '.github/workflows/syncTranslations.yml'
      - '.github/workflows/syncTranslationsPush.yml'
      - 'crowdin.yml'

jobs:
  syncTranslations:
    uses: ./.github/workflows/syncTranslations.yml
    name: Sync Translations
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
 ```

**Expected behavior**

The action should only run when both filters are satisfied.

## Runner Version and Platform
Version of your runner?

Ubuntu

## What's not working?

See above
