### ISSUE TITLE
How to use an action in the same repo when the step is running in a container?

### ISSUE THREAD

**Issue by shink** [actions/runner#3620]
Relevant issues:

- https://github.com/actions/runner/issues/2185
- https://github.com/actions/runner/issues/2058
- https://github.com/actions/checkout/issues/785

**Describe the bug**

As the title stated, how to use an action in the same repo when the step is running in a container?

**To Reproduce**

Here is a minimal repro:

Repository file structure:

```
|-- hello-world (repository)
|   |__ .github
|       └── workflows
|           └── my-workflow.yml
|       └── actions
|           |__ hello-world-action
|               └── action.yml
```

Workflow file:

```yml
jobs:
  test:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello world
        uses: ./.github/actions/hello-world
```

**Expected behavior**

I expect that the `hello-world` action can be used correctly, but actually, It seems that `GITHUB_WORKSPACE` and `github.workspace` are different, and GitHub Actions tries to find my action in `github.workspace`.

The [doc][1] says:

> The path is relative (`./`) to the default working directory (`github.workspace`, `$GITHUB_WORKSPACE`). 

[1]: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow

## Runner Version and Platform

self-hosted runner

## What's not working?

https://github.com/cosdt/pytorch-integration-tests/actions/runs/12295364230

<img width="1530" alt="image" src="https://github.com/user-attachments/assets/ce7e0bcf-fd68-48c6-8a80-c25499cdd92d" />

## Job Log Output

https://github.com/cosdt/pytorch-integration-tests/actions/runs/12295364230
