### ISSUE TITLE
Ubuntu 24.04 Noble Docker Image

### ISSUE THREAD

**Issue by dniasoff** [actions/runner#3623]
### Discussed in https://github.com/actions/runner/discussions/3607

<div type='discussions-op-text'>

<sup>Originally posted by **dniasoff** December  4, 2024</sup>
Hi,

I am using the actions-runner-controller and gha-runner-scale-sets to run action-runners on Kubernetes.

The default docker images used by the runners are hosted in this repo - ghcr.io/actions/actions-runner

They are all based on Ubuntu 22.04.

Are there any plans to upgrade to 24.04? Can I easily build my own 24.04 image? Where is the Dockerfile  used to build the standard image?

Feeling a bit stupid as I should be able to work this all out myself!

Thanks

Daniel
</div>

**Comment by cmckeen** [comment]
I have the same questions. With the [impending update](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/) of the ubuntu-latest label to use Ubuntu 22.04, what is the plan for the next release of the runner? Will this be a new major version upgrade? Is this coming soon?

**Comment by dniasoff** [comment]
It's quite easy to build your own noble image. Here are bits of the workflow I use
```
name: 'Build GitHub Action Runner Image'

on:
  workflow_dispatch:
    inputs:
      github_runner_version:
        description: 'The version of github runner'
        required: true
        default: '2.321.0'
```
...
```
   - name: Build Docker Image
      run: |
        wget https://github.com/actions/runner/archive/refs/tags/v${{ github.event.inputs.github_runner_version }}.tar.gz
        tar -xf v${{ github.event.inputs.github_runner_version }}.tar.gz
        cd runner-${{ github.event.inputs.github_runner_version }}/images
        sed -i 's/8.0-jammy/9.0-noble/g' Dockerfile
        docker build --build-arg RUNNER_VERSION=${{ github.event.inputs.github_runner_version }} -t ${{ env.REPO_ADDRESS }}/qumulus/actions-runner-base:${{ github.event.inputs.github_runner_version }} .
```

Been testing it today and no issues so far
