### ISSUE TITLE
Skipped checks on automerge are falsly considered successful 

### ISSUE THREAD

**Issue by evantahler** [actions/runner#3649]
We've got classic branch protections enabled on our main branch.

<img width="802" alt="Screenshot 2025-01-11 at 11 14 00 AM" src="https://github.com/user-attachments/assets/91e3cf1b-fc5d-4989-b9cc-51e3c0af9320" />

Our test suite is set up such that a number of sub-jobs need all pass which then trigger a final job, `backend-test-complete`, which is the required check in the branch protection.

```yaml
jobs: 

...

  backend-test-complete:
    runs-on: ubuntu-latest
    needs:
      - backend-lint
      - backend-seed
      - backend-tests
      - backend-acceptance-tests
    steps:
      - run: echo "SUCCESS!"
```

If one of the sub jobs fails (in this example, `backend-seed`), the final job, `backend-test-complete` is skipped.  

<img width="872" alt="Screenshot 2025-01-11 at 11 16 14 AM" src="https://github.com/user-attachments/assets/abe7fec6-5a96-45e8-93ba-5e1dcc64797e" />

<img width="966" alt="Screenshot 2025-01-11 at 11 17 05 AM" src="https://github.com/user-attachments/assets/d89ef2cc-c166-489e-8405-6fd63c428d92" />

However, auto-merge proceeded when it should have been prevented. The language about branch protections implies that "skipped" jobs should not pass the branch protection, and only "successful" jobs should pass:

<img width="751" alt="Screenshot 2025-01-11 at 11 10 54 AM" src="https://github.com/user-attachments/assets/58598270-0d36-4c6c-8ea6-8bffe7459d39" />

So... I think it is a bug that automerge happened in this case.  Thanks!

**Comment by cantecim** [comment]
```
A job that is skipped will report its status as "Success". It will not prevent a pull request from merging, even if it is a required check.
```

According to the docs, skipped jobs are considered successful. We are also looking for a way to enforce strict success for some specific jobs to be considered. I think the best approach would be not skipping any of them but manually adjusting the last exit code

**Comment by cantecim** [comment]
Hey @evantahler, good news. We have tried out the solution I've mentioned in my previous commit and it solved the issue.

You might want to utilize something like below

```
  backend-test-complete:
    runs-on: ubuntu-latest
    needs:
      - backend-lint
      - backend-seed
      - backend-tests
      - backend-acceptance-tests
    steps:
      - if: needs.myprevious.step == 'failure'
        run: echo check failed!; exit 1
      - run: echo check successful!
```
