### ISSUE TITLE
Why is my job cancelling when I have 'cancel-in-progress' set to false?

### ISSUE THREAD

**Issue by tking16** [actions/runner#3722]
So I have 3 jobs in a workflow, 2 of which share the name concurrency ID

```
jobs:
############################### BOOT SIMULATORS #########################################
  node1:
    name: Selenium Grid Node 1
    runs-on: [appium-grid-hub]
    timeout-minutes: 250

  node2:
   name: Selenium Grid Node 2
   runs-on: [ios-appium-test-node]
   timeout-minutes: 250
   concurrency:
    group: ios-appium-test-runs
    cancel-in-progress: false


  test:
    needs: [node1, node2]
    #needs: [node1]
    name: Run tests
    runs-on: [appium-grid-hub]
    timeout-minutes: 270
    concurrency:
      group: ios-appium-test-runs
      cancel-in-progress: false
```

This workflow runs as devs create PRs, seems very frequently that if two jobs are waiting around, one of jobs in the `ios-appium-test-runs` groups ends up getting cancelled 

![Image](https://github.com/user-attachments/assets/8c8c45db-9875-488e-b0d3-7aaca0b2d591)

I don't know how to prevent this, seems it won't cancel if it's in progress, but if a job is from another PR is "Waiting" then it will cancel another (these are PRs from two different branches BTW, I would expect a cancellation if someone pushes to the same branch causing a new run on their PR)
