### ISSUE TITLE
`Download action repository` called repeatedly for actions that have to be the same

### ISSUE THREAD

**Issue by jsoref** [actions/runner#3731]
**Describe the bug**
If an action is used multiple times and the owner or repository name varies in case, then the action will be downloaded multiple times.

As GitHub asserts that owners and repository names are case-insensitive, this is wasteful.

(Note: paths within repositories may be case-sensitive, that's outside the scope of this report.)

**To Reproduce**
1. Create a workflow that uses an action multiple times where the owner/repository name differ only by case -- https://github.com/check-spelling-sandbox/animated-umbrella/actions/runs/13579366005/workflow
2. Trigger the workflow
3. Look at the `Set up job` section of the workflow run for `Getting action download info` and `Download action repository`...

**Expected behavior**
* Possibly a warning to the job log (`::notice ::action requested by multiple cases <...>`)
* The action should only be downloaded once

## Runner Version and Platform
Version of your runner? 2.322.0

OS of the machine running the runner? Linux

## What's not working?

The runner is needlessly downloading multiple copies of an action that it can know to be identical.

## Job Log Output

```
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'actIONS/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'actions/CHECKout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'aCTions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'actions/checKOut@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'actIONS/cHECkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Complete job name: checkout
```

## Runner and Worker's Diagnostic Logs

https://github.com/check-spelling-sandbox/animated-umbrella/actions/runs/13579439266/job/37962625594#step:1:25

---

For comparison, here's a workflow run where the same action is used multiple times, each time w/ the same case. Note that it only downloads the action repository once:
https://github.com/check-spelling-sandbox/animated-umbrella/actions/runs/13579366005/job/37962422085

**Comment by jsoref** [comment]
@nebuk89 these bots are insulting.

https://github.com/check-spelling-sandbox/animated-umbrella/actions/runs/22558025492/job/65338971995

**Comment by ChristopherHX** [comment]
I have some doubts if https://github.com/actions/runner/pull/4296, actually fixes this. Looks more like it throttles api calls to launch service, my runner implementations spams this endpoint that just returns jsons no repo data.

That PR appear to always use ORDINAL, never ORDINAL_IGNORE_CASE, which would end up in a cache miss for all examples here like in the old code.

**Comment by jsoref** [comment]
I agree with @ChristopherHX

Per https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinal?view=net-10.0
> Gets a [StringComparer](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparer?view=net-10.0) object that performs a case-sensitive ordinal string comparison.

I'd reopen the issue, but I can't.

@stefanpenner, there was a testcase linked to in the description -- https://github.com/check-spelling-sandbox/animated-umbrella/actions/runs/13579366005/workflow

I'd have expected it or something substantially similar to have been (a) tested and (b) included in the test suite.

<details><summary>workflow with actions references that only vary by case</summary>

```yaml
name: checkout
on:
  push:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actIONS/checkout@v4
      - uses: actions/CHECKout@v4
      - uses: aCTions/checkout@v4
      - uses: actions/checKOut@v4
      - uses: actIONS/cHECkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
```

</details>

I'm sorry I didn't flag this when I glanced over the PR. I'm on vacation and apparently so is my brain.

**Comment by ChristopherHX** [comment]
> workflow with actions references that only vary by case

Looks like you put a wrong example in your spoiler

<Details><summary>workflow with actions references that only vary by case correct example</summary>

```yaml
name: checkout
on:
  push:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actIONS/checkout@v4
      - uses: actions/CHECKout@v4
      - uses: aCTions/checkout@v4
      - uses: actions/checKOut@v4
      - uses: actIONS/cHECkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

```

</details>

You also seem to have put the wrong example into the original issue post link under Reproduce step 1.
