### ISSUE TITLE
A `on.workflow_run.workflows` containing `+` not supported

### ISSUE THREAD

**Issue by EnricoMi** [actions/runner#3763]
**Describe the bug**
A `on.workflow_run.workflows` value containing `+` fails with `Encountered an issue parsing workflow trigger(s) "c++" in a workflow`, even though such a workflow name is allowed.

**To Reproduce**
1. Create the following workflow in `.github/workflows/workflow_run.yml`:
```yaml
name: Workflow Run Issue

on:
  workflow_run:
    workflows: ['C++']
    types:
      - completed

jobs:
  job:
    name: job
    runs-on: ubuntu-latest
    steps:
      - run: true
        shell: bash
```
2. Merge this to your default branch. Make sure you have another workflow that gets triggered on `push` event on your default branch before you push this workflow to the default branch.
3. You will see in the Actions tab an `Unknown event` of an `Unknown workflow`:
![Image](https://github.com/user-attachments/assets/a803ca02-5a1f-47a1-ac16-2dce96af3e5e)
4. Click on that action run and you will see an annotation saying:
```
Encountered an issue parsing workflow trigger(s) "c++" in a workflow ".github/workflows/workflow_run.yml".
```

**Expected behavior**
The `workflow_run` should work with workflow names that contain `+`.

## Runner Version and Platform
2.322.0

## What's not working?
![Image](https://github.com/user-attachments/assets/a803ca02-5a1f-47a1-ac16-2dce96af3e5e)
```
Encountered an issue parsing workflow trigger(s) "c++" in a workflow ".github/workflows/workflow_run.yml".
```
