### ISSUE TITLE
## Fix macos-13 and macos-14

### ISSUE THREAD

**Issue by Firas2515** [actions/runner#3791]
## Fix macos-13 and macos-14

Combining both solutions I found here, this worked for me:

```yml
- name: macos-13 dependencies fix
  if: matrix.os == 'macos-13'
  run: |
    sudo -H pip install setuptools
- name: macos-14 dependencies fix
  if: matrix.os == 'macos-14'
  run: |
    brew install python-setuptools
```

_Originally posted by @FrancescoBorzi in https://github.com/actions/runner/issues/2958#issuecomment-2781511834_
