### ISSUE TITLE
Conditional operator or function for expression syntax

### ISSUE THREAD

**Issue by StephenCleary** [actions/runner#409]
**Describe the enhancement**

I'd like some kind of conditional operation added to expression syntax. This can be an actual ternary operator (`?` `:`) or a built-in function (e.g., `if(<condition>, <true-value>, <false-value>)`).

**Additional information**

There is a workaround: using shell scripts to evaluate the condition, setting step outputs, and having other steps reference those outputs. But it would be much cleaner to have some kind of ternary / if/then/else / conditional branching built in to the expression syntax.

**Comment by ylemkimon** [comment]
Another alternative syntax could be:
```
${{ if(condition) }} evaluateIfTrue ${{ else }} evaluateIfFalse ${{ endif }}
```
like [CircleCI](https://circleci.com/docs/2.0/reusing-config/#boolean).

**Comment by ylemkimon** [comment]
It seems, although not identical, `<condition> && <true-value> || <false-value>` seems to work in most cases.

**Comment by molszanski** [comment]
Syntax: `${{ x && 'ifTrue' || 'ifFalse'  }}`

fake ternary example 
```yml
    steps:
      - name: stuff
        env:
          PR_NUMBER_OR_MASTER: ${{ github.event.number == 0 && 'master' ||  format('pr-{0}', github.event.number)  }}
```
