### ISSUE TITLE
Folded chomping block parse error

### ISSUE THREAD

**Issue by crawford** [actions/runner#418]
**Describe the bug**
When using a folded chomping block (`>-`) to specify the run command, it seems as though only the first line gets executed.

**To Reproduce**
Create a workflow like the following:

```yaml
name: example
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >-
          cargo test
            --verbose
```

**Expected behavior**
`cargo test --verbose` should be invoked.

## Runner Version and Platform
Version of your runner? `2.168.0`

OS of the machine running the runner? `  Ubuntu 18.04.4 LTS`

## What's not working?
It appears as though only `cargo test` is being invoked. The output of the step is not the verbose output of cargo.

## Notes

The using an indent block works as expected, though I don't like needing to use shell escapes inside of YAML:

```yaml
name: example
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cargo test \
            --verbose
```
