### ISSUE TITLE
Create a new env var for the branch name

### ISSUE THREAD

**Issue by dungahk** [actions/runner#463]
**Describe the enhancement**
We already have access to the branch/PR/tag ref name which is good but having an easy way to get the actual branch name is a really important feature.

Gitlab has two very good variables for that: (by the way, they very handy for me)

- `CI_COMMIT_REF_NAME` for the branch/tag name
- `CI_COMMIT_REF_SLUG` a slug for the branch/tag name

Ref: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference

One of my use cases is to tag a Docker image based on the branch name.

**Additional information**
Here is a list of questions on the web about it and how this can lead to different implementations prone to error:

- https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
- https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action?noredirect=1&lq=1
- https://github.community/t5/GitHub-Actions/How-to-get-PR-branch-name-in-GitHub-Actions/td-p/35041#
- https://github.com/igordcsouza/github-action-get-branch-name

**Comment by TingluoHuang** [comment]
@chrispat from the product team for feedback.

**Comment by chrispat** [comment]
An ENV would be one option.  Another option might be to have a SubString function as part of the expression library.  Here is a PR that is adding Replace https://github.com/actions/runner/pull/552.

**Comment by jwarby** [comment]
The commit ref slug would be a really useful feature I think.

I'm kind of stuck with my workflow at the moment - what I would like to do is:

1. build Docker images for the branch that the workflow was triggered for;
2. run the images as services in a later step;
3. delete images for a PR branch after the PR is merged/closed.

I think I can do nearly everything except step 2; I think the closest I can get right now is to define an env var at the start of my jobs which need it, using shell commands (which feels a bit hacky too) to convert `github.ref` into
a valid Docker container tag and making the value available to later steps using the [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)
feature.  This works for creating the images but unfortunately does not work for running them as service containers later on in the workflow.  Having a "slug" context variable as others have suggested would
solve this, and avoid the need for any duplication of the tag/slug name generation.

Here is a drastically simplified version of the setup I'm running with, which shows where I'm having to duplicate the logic for creating the tag/slug as an
environment variable, and shows how I get stuck on the job which needs to use the images I just created as services because I have no way to reference the tag in the
`services.x.image` field:


```yaml
name: Build & test

on:
    push:

jobs:
    build-thing-one:
        name: Build thing one image
        runs-on: ubuntu-latest
        steps:
        # Define variable (this is duplicated in build-thing-two job)
        - run: echo "DOCKER_TAG=$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/__/gi')" >> $GITHUB_ENV
        - uses: actions/checkout@v2
        - run: <build thing one>
        - name: Push to GitHub Packages
          uses: docker/build-push-action@v1.1.0
          with:
              username: ${{ github.actor }}
              password: ${{ secrets.CR_PAT }}
              registry: ghcr.io
              repository: <repository>
              # Using the tag:
              tags: ${{ env.DOCKER_TAG }}

    build-thing-two:
        - run: echo "DOCKER_TAG=$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/__/gi')" >> $GITHUB_ENV
        - uses: actions/checkout@v2
        - run: <build thing two>
        - name: Push to GitHub Packages
          uses: docker/build-push-action@v1.1.0
          with:
              username: ${{ github.actor }}
              password: ${{ secrets.CR_PAT }}
              registry: ghcr.io
              repository: <repository>
              tags: ${{ env.DOCKER_TAG }}

    run_tests:
        name: Run tests
        needs: [build-thing-one, build-thing-two]
        runs-on: ubuntu-latest

        # We get stuck here because there's no way to set/use the Docker tag name in the services.x.image field
        services:
            thing-one:
                image: <thing one image>
                ports:
                    - 8000:8000
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.CR_PAT }}
            thing-two:
                image: <thing two image>
                ports:
                    - 9000:9000
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.CR_PAT }}
        steps:
        # ...snip run tests...
  ```

**Comment by chrispat** [comment]
You should be able to use job outputs and bind those to the image keys https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs.

**Comment by jwarby** [comment]
> You should be able to use job outputs and bind those to the image keys https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs.

Thanks @chrispat, I missed that one in the docs! I take it I will be able to use the `needs` context as part of the `services.x.image` value, eg  something like `image: ghcr.io/<xyx>/${{ matrix.id }}:${{ needs.job1.outpus.dockerTag }}` should work?

**Comment by chrispat** [comment]
@jwarby yes that should work.

**Comment by jwarby** [comment]
Brill, cheers @chrispat - will try it sometime this week!

**Comment by tony** [comment]
@jwarby Do you (or anyone else in this situation) have a working example of using variables in the `image:` name?

**Comment by jwarby** [comment]
@tony been a while since I looked at this but I ended up with something along these lines:

```
jobs:
      define-vars:
          name: Define variables
          runs-on: ubuntu-latest
          outputs:
              docker_tag: ${{ steps.create-docker-tag.outputs.docker_tag }}
          steps:
          - uses: actions/checkout@v2
          - id: create-docker-tag
            run: echo "::set-output name=docker_tag::$(git rev-parse --abbrev-ref ${{ github.head_ref || github.ref || 'HEAD' }} | sed 's/[^a-z0-9_-]/__/gi')"

    build:
        # ..snip...
        steps:
           # Build app steps here
           - name: Push to GitHub Packages
            uses: docker/build-push-action@v1.1.0
            with:
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
                registry: ghcr.io
                repository: <repository-name>/<app-name>
                path: <path/to/app>
                tags: ${{ needs.define-vars.outputs.docker_tag }}
```

Hope that helps!
