### ISSUE TITLE
Add a function to merge objects

### ISSUE THREAD

**Issue by MOZGIII** [actions/runner#466]
**Describe the enhancement**

I need a function to merge two (or more) objects into a single object.

**Code Snippet**

```yaml
jobs:
  strategy:
    matrix:
      platform:
        - name: a
          env:
            VAL1: qwerty_1
        - name: b
          env:
            VAL1: qwerty_2
      toolchain:
        - name: stable
          env:
            VAL2: abc1
        - name: nightly
          env:
            VAL2: abc2
  env: ${{ merge(matrix.platform.env, matrix.toolchain.env) }}
  steps: ...
```

**Additional information**

Some considerations on the design that I think would be a good fit:

- should have a defined behavior for conflicting keys (i.e. which takes priority)
- should accept `null` values and treat them as empty objects
- should be able to take more than two arguments and merge them all

Not sure what the behavior should be non-scalar values (i.e. arrays / objects). Maybe merge them recursively, maybe replace the whole thing. My use case is limited to merging env vars - so I don't have any requirements here.
