### ISSUE TITLE
In action.yml, the ability to pass CLI arguments to nodejs or set environment parameters

### ISSUE THREAD

**Issue by robertbrignull** [actions/runner#479]
When writing a javascript action, it would be useful to be able to pass arguments to nodejs or set environment variables before it starts, or ideally have both options.

The specific use-case I wanted this for was to pass the `--enable-source-maps` command line argument, or alternatively set it using the `NODE_OPTIONS` environment variable.

**Comment by PathogenDavid** [comment]
I was also wanting this and turns out that you can specify `NODE_OPTIONS` in an `env` block and it will be used by the JavaScript action, IE:

```yml
# ...
    steps:
      - uses: user/action-repo@main
        env:
          NODE_OPTIONS: --enable-source-maps
```
