### ISSUE TITLE
Workflow level `env` does not work properly in all fields.

### ISSUE THREAD

**Issue by timharris777** [actions/runner#480]
**Describe the bug**
When using workflow level environment variables they do not work when I use them to substitute for `jobs.build.name` or `jobs.build.runs-on`. See workflow file below for example:
```
name: Testing workflow leve env vars
on:
  push:
    branches:
      - develop

env:
  aws_account: cfaittoolsnp
  environment: dev

jobs:
  build:
    name: Deploy|${{ env.aws_account }}
    runs-on: ${{ env.aws_account }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init
      run: |
        echo ${{ env.aws_account }}
```

**To Reproduce**
1.- Run the workflow file above to receive the following error: 
`The workflow is not valid. .github/workflows/dev.yml (Line: 15, Col: 11): Unrecognized named-value: 'env'. Located at position 1 within expression: env.aws_account,.github/workflows/dev.yml (Line: 16, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.aws_account`

**Expected behavior**
The expected behavior is that using the workflow file above the `build.name` would be `Deploy|cfaittoolsnp` and the `build.runs-on` would be `cfaittoolsnp`.

## Runner Version and Platform
Running latest version of linux self-hosted runner.

OS of the machine running the runner? linux (ubuntu 18.04)

**Comment by dgflexera** [comment]
I'm just wondering if there is any update on this? :)

**Comment by timharris777** [comment]
Unfortunately, no-- env can still not be used. However, I have found that I can use either of the following: 

- `runs-on: ${{ needs.init.outputs.tag }}` -> You would need to export the tag for the runner as an output in a previous step.
- `runs-on: ${{ github.event.inputs.aws }}` -> You would need to provide an input for the runner tag via worfklow_dispatch.

**Comment by leonardchu** [comment]
I'm new to GitHub, hence GitHub workflows. But this is the exactly the first issue I have with workflow. I'd image this is causing troubles for many of us.
Does anyone know the best way to attract attentions from GitHub on this?

**Comment by timharris777** [comment]
@leonardchu, give the first post a thumbs up. Github says that they monitor that. Other than that I'm not sure.

**Comment by pdecat** [comment]
Same [issue](https://github.com/fbradyirl/openwrt-luci-rpc/actions/runs/648723692) with `env` in job `strategy`:

```yaml
name: Python package

on: [push, pull_request]

env:
  target_python_version: 3.8

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7, "${{env.target_python_version}}"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
```

```
.github/workflows/main.yml#L14The workflow is not valid. .github/workflows/main.yml (Line: 14, Col: 31): Unrecognized named-value: 'env'. Located at position 1 within expression: env.target_python_version
```

**Comment by adrienbernede** [comment]
I'm having the same issue in the following context:
```
step:
  - uses: ${{ env.org }}/repo/my_action@master
```

**Comment by roycdiscovery** [comment]
Same problem for me with `if: ${{ github.ref != env.version }}`

**Comment by rvernica** [comment]
It looks like instead of `env` a `strategy.matrix` variable with one value can be used in some cases.

**Comment by fabasoad** [comment]
Any workarounds on this? I can't use `env` on workflow level as well :(

**Comment by restjohn** [comment]
Maybe `env` is not the right mechanism for some these use cases.  What I'd like to see at least is for the Actions YAML parser to support aliases and anchors.

**Comment by paulhutchings** [comment]
Am also running into this issue trying to use env variables in matrix:

```yaml
env:
  MIN_PYTHON_VER: 3.6.7
  LATEST_PYTHON_VER: 3.10.0

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - ${{ env.MIN_PYTHON_VER }}
          - ${{ env.LATEST_PYTHON_VER }}
```

The fact that I have to hard-code values for things like language and os versions is really disappointing to say the least. Also disappointing that this is the 7th most liked issue yet has not received a single response from Github in over a year...
![image](https://user-images.githubusercontent.com/36493057/141704612-b4097224-fe69-4f05-bd98-055e28b05ff1.png)

**Comment by umarcor** [comment]
@paulhutchings, in [pyTooling/Actions](https://github.com/pyTooling/Actions) we use a `Params` job to generate an object of "global parameters" which we can then use in any job. See:

[![](https://github.com/pyTooling/Actions/raw/main/ExamplePipeline.png)](https://github.com/pyTooling/Actions)

- [Params.yml](https://github.com/pyTooling/Actions/blob/d8c384ffcbd9e4adcd2071b87f1ce482c04354df/.github/workflows/Params.yml#L42-L52)
- [ExamplePipeline.yml](https://github.com/pyTooling/Actions/blob/main/ExamplePipeline.yml)

```yml
    needs:
      - Params
    with:
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
```

`fromJson(needs.Params.outputs.params)` is certainly ugly, but it is usable in places where `env.params` fails. Moreover, since we generate the `params` dynamically, we can declare them imperatively (say Python) and not just declaratively; we can also filter them and/or produce warnings.

That is not a solution to this issue, but at least a usable workaround.

Find a more complex variant of this approach in https://github.com/actions/runner/issues/1182#issuecomment-982696462, where a YAML file with anchors is used for generating the job matrix dynamically.

**Comment by umarcor** [comment]
> Maybe `env` is not the right mechanism for some of these use cases. What I'd like to see at least is for the Actions YAML parser to support aliases and anchors in order to create reusable elements in the workflow file.

@restjohn, did you see #1182 and actions/starter-workflows#245 ?

**Comment by vitalykarasik** [comment]
Very upsetting, I wasted two hours on that. And it's not just custom env variables, I couldn't use GITHUB_REF_NAME into zip-release action...

**Comment by tjcorr** [comment]
This is also an issue with reusable workflow. For example:

```
env:
  DOTNET_VERSION: 5.0.x    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow-passing-data:
      uses: ....reusable.yml@main
      with:
          dotnetversion: ${{ env.DOTNET_VERSION }}`
```


Does not work.

**Comment by AndreAlves3** [comment]
Any news on this? Really annoying on reusable workflows :(

**Comment by mrfelton** [comment]
Also hitting this trying to use env vars to make a workflow job name dynamic.

Can't do this:

```
jobs:
  build:
    name: Deploy to ${{ env.GITHUB_REF_NAME }}
```

But can do this:

```
jobs:
  build:
    name: Deploy to ${{ github.ref_name }}`
```

**Comment by restjohn** [comment]
The concept to realize, I think, is that the intent of environment variables is for them to be available in the context that a job step is executing, not in the context of DEFINING a job, which is basically the context of the GitHub Actions platform itself.  If you need dynamically computed values for job definition elements, you need to compute them in a step as outputs, as some have commented above, then reference them from subsequent steps.  Now, there might be potential for a less cumbersome solution than having to use outputs and `needs` references, such as user-defined variables and functions that can augment the job definition context, but `env` is certainly not the correct place for that.

**Comment by matthew-gill** [comment]
I took what @umarcor suggested, and I think I've got a nice workaround which allows env vars to be shared in the way we're all looking for:

```
env:
   FOO: foo
   BAR: bar
jobs:
    params:
        name: Make environment variables available to the rest of the workflow
        runs-on: ubuntu-latest
        outputs:
            params: ${{ steps.env-vars.outputs.params }}
        steps:
            -   name: install jq
                run: pip install jq
            -   id: env-vars
                name: Output environment variables
                run: echo "::set-output name=params::$(echo $(jq -n 'env'))"

    setup:
        needs: [ params ]
        name: Setup
        runs-on: ubuntu-latest
        steps:

            -   name: Use Foo
                run: echo ${{ fromJson(needs.params.outputs.params).FOO }}
            
            -   name: Use Bar
                run: echo ${{ fromJson(needs.params.outputs.params).BAR }}
```

Essentially we use `jq` to parse out the env vars from the `params` step, which inherit the initial `env` values, and saves this as an output you can use in other jobs. FYI it includes all the other env var junk, I'm sure you can filter it out if needs be.

This solution seems to work for our usecase.

**Comment by neekey** [comment]
My use case is to call a reusable workflow, which requires some secrets as input and you can only use `secrets` in the job level, so I had to move the `uses` to the job level, but my reusable workflow itself also requires some inputs, which is definited in my workflow env.... so now I can not pass those envs to my reusable workflow because of this limitation...

**Comment by xor-freenet** [comment]
@restjohn wrote:
> The concept to realize, I think, is that the intent of environment variables is for them to be available in the context that a job step is executing, not in the context of DEFINING a job, which is basically the context of the GitHub Actions platform itself.
> [...]
>  Now, there might be potential for a less cumbersome solution than having to use outputs and needs references, such as user-defined variables and functions that can augment the job definition context, but env is certainly not the correct place for that.

Thanks for your input :)

It may be true that that is how the implementation is implemented and intended currently (or not true, who knows?)

*But:* The sole purpose of an implementation of software is to serve the users needs, it has no purpose of its own.

Therefore, if it cannot serve the needs of the users, it has to change.

It should not be the other way around, the users should not be asked to change their needs to follow the needs of the implementation :)

**Comment by Devofure** [comment]
I don't get it, is the documentation wrong or it does not explains much that we can't use env in reusables workflow actions?
Please update the github actions documentation regarding envs limitations.

**Comment by adamjseitz** [comment]
I am having the same issue with using `env` in `jobs.<job_id>.container`, which the [Context Availability documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) states should be available.

**Comment by paige-wdc** [comment]
This is also causing problems for my team's workflows.  Do you know when it will be prioritized?

**Comment by timharris777** [comment]
> We are also running in this issue. What is the latest whereabout on this?

Still the same. It doesn't work in different places where you would expect it to, and it's still not well documented exactly where it does and doesn't work.

**Comment by nathanchapman** [comment]
For anyone wondering, the documentation for this is here:
https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

**Comment by ServiceDog** [comment]
Confirm, we'd like to be able to define an environment variable that can be used in `runs-on`

**Comment by mihma** [comment]
Yes please also need to be able to use conditional runs-on

**Comment by goneneren** [comment]
Here is context-availability for **env**:
https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

**Comment by dsdavis4** [comment]
Also looking for an update on this. Are there plans to fix?

**Comment by obinnaeye** [comment]
We're having this same issue now.

**Comment by mihaa1** [comment]
same

**Comment by mrjoboto** [comment]
+1, conditional runs-on is necessary for my workflow

**Comment by mihma** [comment]
Much needed feature

**Comment by kierans** [comment]
For some of the use cases outlined in this issue (eg: using a variable in a job name), it looks like [Variables](https://docs.github.com/en/actions/learn-github-actions/variables) is what you're after.

**Comment by mcblair** [comment]
Honestly it is pretty unacceptable that the `env` context is only available when the entirety of a workflows logic is in the same file. 

Our use case is far from uncommon: use the `env` context within inputs for a re-usable workflow.

**Comment by AllanOricil** [comment]
#2565  might be a different issue that is related to this one. Are expressions used in Jobs evaluated after the ones declared in Workflows ? I want to use the result of a workflow expression in a Job using env variables. Why? Because there are many Jobs using the same expression in multiple places and I want to remove the duplications

**Comment by mxmnci** [comment]
> Honestly it is pretty unacceptable that the `env` context is only available when the entirety of a workflows logic is in the same file.
> 
> Our use case is far from uncommon: use the `env` context within inputs for a re-usable workflow.

Agreed, I'm facing the same issue. Why are we able to pass `secrets` into a reusable workflow but not `env`?

**Comment by Kaloszer** [comment]
How is this even an issue? Tagging resources is a perfect use case for this. It's been 3 years now, any news?

**Comment by xor-freenet** [comment]
@TingluoHuang : @github-actions wrote:
> Thank you for your interest in the runner application and taking the time to provide your valuable feedback. We kindly ask you to redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute). 😃

1. This isn't a "feature request". This is a bug, and it was filed in the bugtracker as such. Thus please re-open it.

2. Human lifetime is a finite resource. We will all die, and we will **never** get back time which was taken from us.  
~43 people have spent their lifetime to comment on this annoying issue, 259 have spent their time to search the bugtracker for this issue in order to push the "like" button.  
So you are wasting the lifetime of around 200-300 people by asking them to re-file this issue in the "Community Support forum".  
This is not a nice thing to do, please stop doing it by re-opening the issue.  
Still: Thanks for your time as well :) Let's keep things civil and thus keep this issue open.

3. Given this issue has annoyed hundreds of people for over 3 years now, and probably many more who didn't spend the effort to comment here, how about you just fix it?  There are plenty of suggestions on how to fix it in the discussion.

4. Please don't hide behind the "github-actions" bot when commenting here, it is super annoying to have to dig through dozens and dozens of comments to figure out who is reponsible in order to highlight them. I just highlighted the first person to tag this issue now, @TingluoHuang, but I cannot know if this is the person who closed it, which is suboptimal.

**Comment by Faltenreich** [comment]
+1 I expected this to work

```
env:
  RUNNER: ubuntu-latest

jobs:
  assemble:
    runs-on: ${{ env.RUNNER }}
```

but am receiving

```
The workflow is not valid. [...] Unrecognized named-value: 'env'. Located at position 1 within expression: env.RUNNER [...] (Line: 43, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.RUNNER
```

**Comment by hannes-mk** [comment]
+1 

Workflow:

```
env:
  CONTAINER_REGISTRY: "ghr.io"
  
[...]

jobs:
  frontend-build-image-and-scan:
      uses: ./.github/workflows/frontend-build-image-and-scan.yml
      with:
        container-registry: ${{ env.CONTAINER_REGISTRY }}
```

Error:
`The workflow is not valid. .github/workflows/pipeline.yml (Line: 45, Col: 15): Unrecognized named-value: 'env'. Located at position 1 within expression: env.GITHUB_RUN_ID .github/workflows/pipeline.yml (Line: 46, Col: 27): Unrecognized named-value: 'env'. Located at position 1 within expression: env.CONTAINER_REGISTRY`
