### ISSUE TITLE
A line ending adaptive variant of hashFiles

### ISSUE THREAD

**Issue by mzabaluev** [actions/runner#498]
**Describe the enhancement**
Sometimes cached data is sufficiently cross-platform to be reused across runners on Windows and the Unix OSes. A problem arises if the cache key needs to be computed by hash-summing text files, which produces differing hash sums on the same file if it was e.g. checked out by git in text mode applying auto-conversion to the line endings.

[This workflow run][workflow] failed to hit the cache in the Windows `test` job, even though the preceding `update-deps` job on Linux had stored it.

[workflow]: https://github.com/mzabaluev/github-actions-playground/runs/697380089

**Code Snippet**
It would be nice if a `hashTextFiles` function was available that would canonicalize line endings for the hash input:

```yaml
  test:
    needs: update-deps
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: cargo-registry
        name: Restore cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashTextFiles('**/Cargo.lock') }}
```
