### ISSUE TITLE
action.yml input param validation handling of special `args` parameter 

### ISSUE THREAD

**Issue by mumfy** [actions/runner#499]
**Background:**

The [`inputs` construct](https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) is used to specify the parameters which may be passed into an Action. Recently, validation code was added which emits a _warning_ message if the calling action supplies parameters which the called action does not include as one of the valid `inputs`.

The [`jobs.<job_id>.steps.with.args` documentation](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswithargs) mentions that the `args` parameter has a special meaning for docker jobs. Compounding this, the example code provided actually doesn't use docker, and actually shows `jobs.<job_id>.steps.uses.with.args`. (Note the extra `uses`.)

**Describe the bug**

When an action uses `uses.with.args` to call another action that uses docker, then

1. The argument validation will warn if `args` is not specified as one of the `inputs`
2. The `args` parameter is passed and used by docker regardless.

**To Reproduce**

Steps to reproduce the behaviour:

1. In a repo (`owner/foo`), create an action that uses docker, but which does not specify `args` in the `inputs`.
    1. Add an `action.yml` file which contains something such as:
        ```
        name: foo
        description: Do foo
        runs:
            using: docker
            image: Dockerfile
        ```
    2. Add `Dockerfile`. For example:
        ```
        FROM <something somewhere>
        ADD entrypoint.sh /entrypoint.sh
        ENTRYPOINT ["/entrypoint.sh"]
        ```
    3. Add `entrypoint.sh` etc etc
2. Create an action (eg. `test.yml`) which calls the above Docker action:
    ```
    name: testFoo
    on: push
    jobs:
        myjob:
            name: Do My Jobs
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@master
                - name: Call docker foo with the special 'args' input parameter
                   uses: owner/foo@master
                   with:
                       args: . ./env ; docker build -t $IMAGE .
    ```
3. Trigger the action by pushing to the repo.
4. Look in the Actions tab to see the warning message `Unexpected input 'args', valid inputs are ['']`. Also note that the full output will show that the docker command that was run did include the expanded version of the `args` parameter.

**Expected behavior**

Unclear - I leave it to your expertise.

1. If `args` is _magic_ and does not actually need to be specified amongst the `inputs`, then the warning message should not be emitted.

2. Consider tweaking the warning message. If you understand that it is a "usage" message about bad parameters, then it is meaningful. If you aren't aware of this and you just read it, then it can be confusing. Perhaps mention specifically about the `inputs` construct, and/or add a link to documentation (`https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs`)?

3. The documentation should be improved. 
    1. The example within the section should match the structure being described.
    2. Both docker and non-docker examples should be provided, as they seem to have non-trivial differences.
    3. If _args_ is somehow magic, call this out more clearly.

## Runner Version and Platform

Ubuntu-latest (??)

## What's not working?

Please include error messages and screenshots.

## Job Log Output

```
Unexpected input 'args', valid inputs are ['']
```

Thanks for your consideration. Andy

/cc @tingluohuang
