### ISSUE TITLE
Matrix strategy randomly uses different shell for matrix mode

### ISSUE THREAD

**Issue by Kaspik** [actions/runner#527]
**Describe the bug**
- self-hosted runners on MacStadium (MacMini) with MacOS Catalina (default shell is `zsh` on MacOS)
- 4 github actions runners on every MacMini
- when running matrix strategy on these runners - **randomly some of the modes use different bash**

It seems like this happens only if we try to run more CI checks than we have runners available - if they start queueing, then this starts happening. Could be concurrency issue?

**To Reproduce**
- create more CI checks than number of available runners so they start queueing
- run CI check on commit in open PR
- expect failure due to wrong environment

**Expected behavior**

## Runner Version and Platform
MacOS Catalina, latest Github Actions Runner (2.263.0 - but happening on older too)

## What's not working?
Here is our `yml` file with matrix (ignore please that the modes are there twice, it's just to constantly repro the issue):
```
name: PR Tests

on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        mode: [tests_ci, networking_tests_ci, cduikit_tests_ci, cdfoundation_tests_ci, messaging_tests_ci]
        include:
          - mode: tests_ci
            name: ClassDojo tests
          - mode: networking_tests_ci
            name: Networking tests
          - mode: cduikit_tests_ci
            name: CDUIKit tests
          - mode: cdfoundation_tests_ci
            name: CDFoundation tests
          - mode: messaging_tests_ci
            name: Messaging tests
    name: Run ${{ matrix.name }}
    runs-on: self-hosted
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Run build script
      if: github.head_ref != 'appstore' && github.head_ref != 'changelog'
      run: |
         echo $SHELL
         ./build.sh ${{ matrix.mode }}
```
When running this matrix, some of the modes use different shell than others.

build.sh file:
```
#!/bin/zsh

set -e
function trap_handler {
   echo -e "\n\nOh no! You walked directly into the slavering fangs of a lurking grue!"
   echo "**** You have died ****"
   exit 255
}
trap trap_handler INT TERM EXIT

MODE="$1"
echo MODE
```

Error messages and failure on CI:
![Screen Shot 2020-06-09 at 11 03 26](https://user-images.githubusercontent.com/7204168/84128435-e122bb00-aa40-11ea-9427-2902edfd4cf4.png)
![Screen Shot 2020-06-09 at 11 03 33](https://user-images.githubusercontent.com/7204168/84128440-e41dab80-aa40-11ea-9195-1e40535cd7aa.png)

As you can see, every mode prints different shell with no reason. 8 out of 9 tries it uses zsh (correctly) and then one uses bash.

Changing the step to use specific shell does not work either.

Any hints? I'm already out of ideas... Let me know if you need more info or logs to try to debug this.

Thanks!

**Comment by Kaspik** [comment]
Tried to dig deeper and found some other strange things.

- run script always uses /bin/bash - even if `echo $SHELL` shows `/bin/zsh`
- it doesn't matter if it's bash or zsh, but fails for both in the moment **when there is more PR checks than runners available* - if queued runner starts after ^^ it doesn't have settings applied from `.profile` / `.bash_profile` / `.bashrc` so the PATH is missing what's added in these files

I solved this for now by adding more runners to the repo but I believe this is not what should happen...

**Comment by Kaspik** [comment]
I tried custom shell too however I wasn’t able to get zsh working - would be nice to consider this one as well as it’s default on one OS.

**Comment by TingluoHuang** [comment]
I did
```yaml
    - name: Setup environment and set output
      run: |
        echo "::set-env name=TRAINING_START_TIMESTAMP::2020-05-06T14:05:44.000Z"
      shell: zsh -e {0}
```
and i am getting
```
Run echo "::set-env name=TRAINING_START_TIMESTAMP::2020-05-06T14:05:44.000Z"
  echo "::set-env name=TRAINING_START_TIMESTAMP::2020-05-06T14:05:44.000Z"
  shell: /bin/zsh -e {0}
  env:
    env1: 100
    env2: 200
    enV1: 1000
##[debug]/bin/zsh -e /Users/runner/runners/2.263.0/work/_temp/ae2a6bcd-0cd1-4e51-98bd-c1e35a0a9612
::set-env name=TRAINING_START_TIMESTAMP::2020-05-06T14:05:44.000Z
##[debug]TRAINING_START_TIMESTAMP='2020-05-06T14:05:44.000Z'
##[debug]Finishing: Setup environment and set output
```
