### ISSUE TITLE
The timestamp in job output variable changes format from "2020-05-06T14:05:44.000Z" to "05/06/2020 14:05:44" automatically

### ISSUE THREAD

**Issue by zhu5201314** [actions/runner#528]
Here is the ticket in Community Forum which reported this issue. 
https://github.community/t/iso-8601-string-in-job-output-is-automatically-parsed/117195
There is the workflow to reproduce this issue. 
```
name: What's up with the timestamp??

on:
  push:
    branches:
      - whats_up_ts

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment and set output
        run: |
          echo "::set-env name=TRAINING_START_TIMESTAMP::2020-05-06T14:05:44.000Z"
      - name: set output
        id: report
        run: |
          echo "::set-output name=TRAINING_START_TIMESTAMP::$TRAINING_START_TIMESTAMP"
    outputs:
      TRAINING_START_TIMESTAMP: ${{steps.report.outputs.TRAINING_START_TIMESTAMP}}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Setup environment and print timestamp
        run: |
          echo "::set-env name=TRAINING_START_TIMESTAMP::${{needs.job1.outputs.TRAINING_START_TIMESTAMP}}"
      - name: Show me the ts!
        run: echo $TRAINING_START_TIMESTAMP
```
The output variable value in job2 changes to 05/06/2020 14:05:44 automatically. 
![job output format](https://user-images.githubusercontent.com/46183853/84130715-2f05e600-aa76-11ea-8f04-0f8a4fd26fbe.png)

How to disable this default behavior?
