### ISSUE TITLE
Add REF_SLUG with special characters being replaced to "-"

### ISSUE THREAD

**Issue by Evilweed** [actions/runner#553]
**Describe the enhancement**
It is common practice to build and then run Docker Images using branch name in Docker Tag. 
The problem is that branch name can contain characters (for example: "/") that are not allowed in Docker Tags. 

Branch name that is not accepted in docker tags:
`GITHUB_REF=feat/ch-1234/some-feature`

Branch accepted in docker tags:
`GITHUB_REF_SLUG=feat-ch-1234-some-feature`

**Code Snippet**
Probably best solution (as other CI providers do this) would be to create new `env.GITHUB_REF_SLUG` that would replace all special characters in `env.GITHUB_REF` with "-" (which is supported).
```
job:
  container: docker-registry.com/rails:${{ env.GITHUB_REF_SLUG }}-${{ github.sha }}
  steps:
    - ...
```
Where change should be made:
`src/Runner.Worker/GitHubContext.cs:32`

-------
Or, for example, add new function `replace(github.ref, "/", "-")`:
```
job:
  container: docker-registry.com/rails:${{ replace(github.ref, "/", "-") }}-${{ github.sha }}
  steps:
    - ...
```
PR:
https://github.com/actions/runner/pull/552

**Additional information**
In current implementation of the Runner it is not possible to use ${{ env.SOME_ENV }} in `container: ...` field. That is why I'm proposing adding replace function.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md
