### ISSUE TITLE
self-hosted: unable to evaluate symlinks in Dockerfile path

### ISSUE THREAD

**Issue by elgohr** [actions/runner#560]
As described in https://github.com/elgohr/Publish-Docker-Github-Action/issues/79 the action https://github.com/elgohr/Publish-Docker-Github-Action does not work on self-hosted workers, but on GitHub workers.

**To Reproduce**
1. Create a repository including a Dockerfile
2. Add the following workflows

Self-Hosted

```
name: Self-Hosted
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Plain Docker Build
      run: |
        docker build .
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

GitHub-Hosted

```
name: Runs On GitHub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Plain Docker Build
      run: |
        docker build .
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

The Self-Hosted will run `docker build .` without a problem, but will fail on the same command in the action with
```
Login Succeeded
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
```
As you can see in the other issue the file is present and correct.

The GitHub-Hosted will run both builds without errors.

**Expected behavior**
1. Have a better way to debug actions on workers (maybe `ACTIONS_STEP_DEBUG` could enable verbose logging)
2. Run self-hosted workers the same as GitHub workers

## Runner Version and Platform
v2.263.0

OS of the machine running the runner?
Maybe @synixebrett could add some details

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
@synixebrett maybe also these
