### ISSUE TITLE
Unable to add new combinations to matrix 

### ISSUE THREAD

**Issue by PazerOP** [actions/runner#644]
**Describe the bug**
I want to compile x86 and x64 on windows, and whatever the native platform is (I assume x64) on linux. 

My current matrix specification is as follows:

```yml
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04]
        unrelated_parameter: [true, false]
        include:
          - os: windows-latest
            triplet: x86-windows           
          - os: windows-latest
            triplet: x64-windows            
```

However, this results in the following behavior (ignore the failures, they are an unrelated issue with my code): 
![image](https://user-images.githubusercontent.com/6569500/89383731-d9366e80-d6b1-11ea-9056-8a6149b29638.png)

**To Reproduce**
* See the above workflow example.

**Expected behavior**

I would expect to see the following jobs created:
* (windows-latest, x86-windows, true)
* (windows-latest, x86-windows, false)
* (windows-latest, x64-windows, true)
* (windows-latest, x64-windows, false)
* (ubuntu-20.04, true)
* (ubuntu-20.04, false)

I'm fairly certain I'm just doing something wrong, but the documentation is very vague about matrix functionality with few examples (and is significantly more difficult to navigate after the migration to the new documentation site...) so I finally decided to give up and ask for help. Is there any way I can spawn the above set of jobs on github actions without having to add the triplets to the matrix, then exclude them for all other OSes? https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations seems to indicate this should be possible, but I can't seem to get it working.

**Comment by ericsciple** [comment]
the following will produce the desired set:

```
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - [windows-latest, x86-windows]
          - [windows-latest, x64-windows]
          - ubuntu-20.04
        unrelated_parameter: [true, false]
```

**Comment by PazerOP** [comment]
Thanks for the reply, I haven't seen this syntax in any of the documentation, but I might have just missed it.

How does your example know that `x86-windows` and `x64-windows` are supposed to be in the `${{ matrix.triplet }}` variable? Asking since I don't see "triplet" in your example anywhere.

**Comment by ericsciple** [comment]
Sorry I missed something. I was thinking you needed `x86-windows` and `x64-windows` labels to choose a runner.

It sounds like something like this might work instead:

```yaml
jobs:
  ci:
    runs-on: ${{ matrix.config.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - runs-on: windows-latest
            arch: x86-windows
          - runs-on: windows-latest
            arch: x64-windows
          - runs-on: ubuntu-20.04
        unrelated_parameter:
          - true
          - false
```

Or you can specify explicit sets if that makes it easier rather than cross-multiplying.

```yaml
jobs:
  ci:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: windows-latest
            arch: x86-windows
            unrelated_parameter: true
          - runs-on: windows-latest
            arch: x86-windows
            unrelated_parameter: false
          - runs-on: windows-latest
            arch: x64-windows
            unrelated_parameter: true
          - runs-on: windows-latest
            arch: x64-windows
            unrelated_parameter: false
          - runs-on: ubuntu-20.04
            unrelated_parameter: true
          - runs-on: ubuntu-20.04
            unrelated_parameter: false
```
