### ISSUE TITLE
Load `env` from files

### ISSUE THREAD

**Issue by timharris777** [actions/runner#655]
It would be awesome if `env` could be loaded from a file. Example:
```
name: Loading env vars from file
on:
  push:
    branches:
      - develop

env-file: dev.env
env:
  other-env-var: env-var-value

jobs:
  build:
    ...
```

**Comment by ylemkimon** [comment]
A workaround would be to use `fromJson`:
```yaml
jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.import-env.outputs.result }}

    steps:
    - uses: actions/checkout@v2

    - name: Import environment variables from a file
      id: import-env
      uses: actions/github-script@v2
      with:
        script: return parseEnvToJSON(`${process.env.GITHUB_WORKSPACE}/dev.env`)

    - name: Print environment variable
      run: echo $ABC
      env: ${{ fromJson(steps.import-env.outputs.result) }} # step-level env

  build:
    runs-on: ubuntu-latest
    needs: [env]
    env: ${{ fromJson(needs.env.outputs.env) }} # job-level env

    steps:
    - name: Print environment variable
      run: echo $ABC
```

Note I've used `actions/github-script` to parse the `.env` to JSON. If the file is JSON, it's possible to [directly read the file into the output](https://github.community/t/set-output-truncates-multiline-strings/16852).

**Comment by timharris777** [comment]
We wrote an action that loads yaml, json, or env files into the current jobs `env`. However there is no good way to load into the workflows env. Seems like that should be a feature.

**Comment by rgstephens** [comment]
parseEnv is not defined:

```
Run actions/github-script@v2
ReferenceError: parseEnv is not defined
Error: Unhandled error: ReferenceError: parseEnv is not defined
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:7985:56), <anonymous>:3:13)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:7986:12)
    at main (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:8011:26)
    at Module.833 (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:7995:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:37:19)
    at /home/runner/work/_actions/actions/github-script/v2/dist/index.js:43:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:46:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by rgstephens** [comment]
Ended up doing it with the shell:

```yml
      - name: Import environment variables from a file
        id: import-env
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ${{ env.ENV_FILE }}
```

**Comment by typebrook** [comment]
> Ended up doing it with the shell:
> 
> ```yaml
>       - name: Import environment variables from a file
>         id: import-env
>         shell: bash
>         run: |
>           while read line; do
>             echo "$line" >> $GITHUB_ENV
>           done < ${{ env.ENV_FILE }}
> ```

Why not just use `cat`?
```yaml
run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV
```
or
```yaml
run: < ${{ env.ENV_FILE }} >> $GITHUB_ENV
```

**Comment by AnnamSai** [comment]
> Ended up doing it with the shell:
> 
> ```yaml
>       - name: Import environment variables from a file
>         id: import-env
>         shell: bash
>         run: |
>           while read line; do
>             echo "$line" >> $GITHUB_ENV
>           done < ${{ env.ENV_FILE }}
> ```


@rgstephens

Im completely new to powershell scripts. 

Can you post a windows runner script? Please

**Comment by cardinalby** [comment]
I faced with the same question and made a [export-env-action](https://github.com/cardinalby/export-env-action) that you can use as one of your steps:

**constants.env file:**
```env
PROTOCOL=https
HOST=example.com
PORT=8080
URI=${PROTOCOL}://${HOST}:${PORT}
```

**a step in your workflow:**
```yaml
- uses: cardinalby/export-env-action@v1
  with:
    envFile: 'constants.env'    
    expand: 'true'

# env.PROTOCOL == 'https'
# env.HOST == 'example.com'
# env.PORT == '8080'
# env.URI == 'https://example.com:8080'
```

**Comment by cardinalby** [comment]
> Is there anyway to load from an `.env` file and use it when defining the credentials of a MySQL service? (e.g. `DB_PORT=3307`)
> 
> ```yaml
> services:
>   mysql:
>     image: mysql:5.7
>     ports:
>       - $DB_PORT:3306
> ```

First, I would warn you that if you store your creds in `.env` file in the repo then you probably doing something wrong and you should use GitHub Secrets instead.

You case can make sense if you download env file from outside for example. Then, yes, you can use mentioned `cardinalby/export-env-action` action to read the creds (use `mask` parameter to mark values as secrets in the workflow) and use `${{ env.MY_PSW }}` expression in the workflow. But be aware that other untrasted steps in your workflow can also have access to env variables

**Comment by raimille1** [comment]
Jumping in here with another solution since some of these didn't exactly do what I needed, which was to load a regular env file like this:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/6089617/228840618-25948782-111b-41eb-8dd1-1fe98cc8028b.png">

Into the env vars of the job itself so I can do other env replacement in subsequent steps without having to enumerate all the vars in the env file.

This did the trick:
```
      - name: Inject env vars
        run: |
          export $(grep -Ev ^'(#|$)' .env)
          envsubst < ./apps/api/.ebextensions/03_inject_env_vars.config | tee ./apps/api/.ebextensions/03_inject_env_vars.config
```

`export` takes in the output from grep which removes empty lines and comments from the file 
`envsubst` does env substitution on the targeted file, finds all vars that are wrapped in brackets ${VAR} and replaces it with the actual value from the env file... all without having to enumerate them one by one.

**Comment by cardinalby** [comment]
@moleary-gsa 
I would comment on your approach:
1. You can remove env file after `cardinalby/export-env-action@v2` step because of the security concerns
2. Even though secrets are masked in the log, I still don't recommend exporting all secrets in this way for the entire job making them available for all untrusted steps. Instead, you should pass secrets only for the steps where they are actually needed.

You can achieve it by using `export: false` input for export action:

```
- uses: cardinalby/export-env-action@v2
  id: readEnvFile 
  with:
    mask: true
    export: false
    envFile: '.env'
```

And pass the secrets to the steps where they are needed by accessing them as `steps.readEnvFile.outputs.YOUR_SECRET_NAME`
