### ISSUE TITLE
Support relative paths in problemMatchers to support monorepos

### ISSUE THREAD

**Issue by jnewland** [actions/runner#659]
**Background**

I'm working on CI/CD automation for a repository that includes multiple components, each in a subdirectory. Each component directory contains a Dockerfile, and in the course of building images errors are emitted with paths relative to the subdirectory of each component.

Example repository tree:

```
components/project1/Dockerfile
components/project1/src/example.fake
components/project2/Dockerfile
components/project2/src/example2.fake
```

Example error emitted during project1 build:

```
src/example.fake: syntax error
```

**Describe the enhancement**

To support monorepos, problem matchers should provide some mechanism for setting a static prefix to be applied to all errors emitted in a region of job output. I was not able to determine how to use the `fromPath` in Actions' problem matchers for my use case, as the build process being executed has no awareness of its fully qualified path and thus can't include it in error output.

**Possible implementations**

One approach might be to ask integrators to embed this information in the problem matcher configuration itself, possibly via a field similar to VS Code Tasks `fileLocation` property. This would require problem matchers to be imported into each repository and include a `fileLocation` field.

```
components/project1/.github/tsc.json
```

```json
{
    "problemMatcher": [
        {
            "owner": "tsc",
            "fileLocation": ["relative", "components/project1"],
            "pattern": [
                {
                    "regexp": "^(?:\\s+\\d+\\>)?([^\\s].*)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\)\\s*:\\s+(error|warning|info)\\s+(\\w{1,2}\\d+)\\s*:\\s*(.*)$",
                    "file": 1,
                    "location": 2,
                    "severity": 3,
                    "code": 4,
                    "message": 5
                }
            ]
        }
    ]
}
```

Another approach that used an action command could retain the use of shared matchers, like the one from `setup-node` above, and be integrated with existing matrix builds like so:

```yaml
strategy:
  matrix:
    component:
    - project1
    - project2
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
- run: |
    # Tell the tsc matcher configured by setup-node to assume errors are relative to each component
    echo "::set-matcher-prefix owner=tsc:components/${{ matrix.component }}:"
- name: Build and push Docker image
  uses: docker/build-push-action@v1
  with:
    path: components/${{ matrix.component }}
    ...
- run: |
    # Clear prefix for subsequent steps
    echo "::set-matcher-prefix owner=tsc::"
```

If there's an alternative approach or workaround I'm possibly missing here, please let me know! Thanks for your time. 😄
