### ISSUE TITLE
INPUT_* environment variables are missing in composite actions

### ISSUE THREAD

**Issue by airtower-luna** [actions/runner#665]
[According to the documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) actions should receive their input values as environment variables prefixed with `INPUT_` in addition to the `inputs` context. These environment variables are missing for composite actions.

**To Reproduce**
1. Create a composite action with one or more inputs, and a step that outputs the associated `INPUT` variables:
```yaml
inputs:
  foo:
    description: 'Test input'
    required: yes
runs:
  using: composite
  steps:
    - run: |
        echo "FOO: ${INPUT_FOO}"
      shell: bash
```
2. Use the action in a workflow:
```yaml
steps:
  - uses: ./example-action
    with:
      foo: 'bar'
```
3. Observe the lack of value after the `FOO:` prefix.

I have an [example action](https://github.com/airtower-luna/hello-github-actions/blob/master/composite-action/action.yaml) and [workflow](https://github.com/airtower-luna/hello-github-actions/blob/master/.github/workflows/main.yml) (the `uses: ./composite-action` step) that demonstrate the issue and the obvious workaround. There's a [workflow run](https://github.com/airtower-luna/hello-github-actions/runs/995382506) as well (check the "Run /./composite-action" step).

**Expected behavior**
Steps should be able to read inputs via environment variables, `INPUT_FOO` in the example above, `INPUT_NUM1` (to 4) in my reproducer.

## Runner Version and Platform
Version of your runner?
* 2.272.0

OS of the machine running the runner? OSX/Windows/Linux/...
* Ubuntu 20.04.1 LTS (Github hosted runner VM)

## Job Log Output
From the workflow run linked above:
```
Run ./composite-action
  with:
    num1: 1
    num2: 4
    num3: 0
    num4: 0
Show INPUT vars
  INPUT_NUM1 = 
  INPUT_NUM2 = 
  INPUT_NUM3 = 
  INPUT_NUM4 = 
Add numbers
```

## Credit
I became aware of the issue thanks to a [post on the Github community forum](https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611) and tried to reproduce the issue out of curiosity.

**Comment by ericsciple** [comment]
When authoring a composite action, inputs must be mapped into inner steps using GitHub Actions [expressions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions).

For example, map into the script directly:

```yaml
inputs:
  foo:
    description: 'Test input'
    required: yes
runs:
  using: composite
  steps:
    - run: |
        echo "FOO: ${{inputs.foo}}"
      shell: bash
```

Or for example, map into the script indirectly via env var:

```yaml
inputs:
  foo:
    description: 'Test input'
    required: yes
runs:
  using: composite
  steps:
    - run: |
        echo "FOO: $MY_VAR"
      shell: bash
      env:
        MY_VAR: ${{ inputs.foo }}
```

**Comment by ericsciple** [comment]
We need to update the referenced doc

**Comment by airtower-luna** [comment]
Fair enough, but wouldn't it be simpler to have the same behavior across all kinds of actions? Or is there a technical action not to provide the `INPUT_` environment variables?

**Comment by amis92** [comment]
I've hit that as well.

After some thought I imagine it's because if, in future, they enable composite steps to contain other `uses` actions (not just shell runs), this would cause confusion in those sub-actions which inputs are theirs, and which are the parent composite action's.

Better documentation definitely will help there. :)

**Comment by thepwagner** [comment]
👋  I've been using a workaround like _ericsciple's:
```
inputs:
  branches:
    description: 'Branches to update'
    required: false
runs:
  using: "composite"
  steps:
    - run: my-awesome-action.sh
      shell: bash
      env:
        INPUT_BRANCHES: ${{ inputs.branches }}
 ```

I want to map the variable as `INPUT_BRANCHES` so I can reuse `getInput()` from the Actions SDK in my implementation.
Using `${{input.branches}}` directly in the command doesn't work (Actions SDK can't find it).

I'd dig a way to say "please forward ALL my `action.yml:inputs` to this step" without mapping every key. `env: actionInputs()`, `actionInputs: true`?
Forwarding them without special configuration is 👍  too, but changing the exposure of existing composite actions is, as noted, bad.

(I wound up here after adding an input and forgetting about needing this hack to forward it. ~10% of my current action.yaml is input forwarding boilerplate)

**Comment by burner1024** [comment]
What the...
A year, and not only it's not recognized as a bug, even the doc is not updated to help people in the meatime.

**Comment by jsoref** [comment]
@burner1024: The doc now mentions this. I'm not sure if that's any actual comfort.

**Comment by burner1024** [comment]
It is, thank you.

**Comment by thboop** [comment]
The docs have been updated for this, you need to explicitly map inputs into sub steps. This is intentional behavior/design per our [adr](https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#inputs)

I'm relabeled this as an enhancement for the meantime.

If mapping inputs into the steps does not work for your workflow  let me know and we can reopen this to evaluate other options here.

**Comment by jsoref** [comment]
Speaking as someone with a fairly large number of them, this is moderately annoying:
https://github.com/check-spelling/check-spelling/blob/5c726fe37eed6f0ed3aba58fc418ca2c0edfbbf9/action.yml#L168-L189

**Comment by AllanOricil** [comment]
That is really weird. It is basically enforcing developers to write more and it does not seem that hard to fix it.

**Comment by nathanblair** [comment]
The documentation [here](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepswith) should also reflect the special behavior mentioned at the top of the page. Probably more importantly in the section more explicitly dedicated to `with`.

**Comment by maxsxu** [comment]
The issue still exists but thanks to the above workaround, which works.

Wondering any updates or plans on this?

**Comment by diepes** [comment]
I seem to have stumbled on another corner case in an action.

The inputs.xyz seem to disappear after a step that uses a `with:`, they (inputs.) are no longer available for other steps.

ci.yaml. (steps: uses action1 passing inputs in with:)
action1.yaml ( halfway through uses action2 passing inputs in with:)
after this step in action1.yaml all the input.xyz seem to be empty.

**Comment by perj** [comment]
Note that Github recommends to not use `${{ inputs.x }}` directly in shell scripts, due to quoting issues.
It's better to always first set them to input variabls. Why not one called `INPUT_x` such that if this is ever fixed that is the same variable name.

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack

**Comment by y-nk** [comment]
there's an issue with this, is that we can't use @actions/core's getInput because it relies on `process.env.INPUT_xxx` to function.

**Comment by ericsciple** [comment]
**Partial workaround**

There's a way to pass inputs as environment variables, though it doesn't fully replicate `INPUT_*` behavior:

```yaml
inputs:
  foo:
    description: Example input
runs:
  using: composite
  steps:
    - run: echo "foo is $foo"
      shell: bash
      env: ${{ inputs }}
```

**Caveat:** The env var names are determined by the caller's casing, not the action.yml definition. This makes it unpredictable for action authors since you can't control how consumers will spell the input names.

---

**Potential Enhancement**

I'm considering a declarative option:

```yaml
inputs:
  foo:
    description: Example input
runs:
  using: composite
  set-input-env-vars: true  # Automatically sets INPUT_* for all inputs
  steps:
    - run: echo "foo is $INPUT_FOO"
      shell: bash
```

Would this fully address the issue? Any feedback on the naming or behavior is welcome.
