### ISSUE TITLE
Support Signed Commits by actions@github.com

### ISSUE THREAD

**Issue by timharris777** [actions/runner#667]
Currently if "signed commits" are required in branch protection there is no good way to have actions update code using the token provided for used with github actions and the current repository. Seems like github actions should provide a way for changes made by `actions@github.com` to be signed and show as verified through the interface.

**Comment by lanecm** [comment]
Yes, agreed. This is needed.

**Comment by lceni** [comment]
+1

**Comment by deepakjotwani** [comment]
+1

**Comment by nathanbirrell** [comment]
Does anyone have a workaround for this?

**Comment by timharris777** [comment]
I have been using the following action. Once the action runs any git commands in following steps will use the signature. It does require storing secrets with GPG info though.

```
- name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GITHUB_ACTIONS_GPG_KEY }}
          PASSPHRASE: ${{ secrets.GITHUB_ACTIONS_GPG_PASS }}
```
