### ISSUE TITLE
Workflow doesn't get triggered on repository creation

### ISSUE THREAD

**Issue by alexlemaire** [actions/runner#673]
**Describe the bug**
I have a workflow set on some of my template repositories that should get triggered on `push`. I'm seeing an inconsistency in terms of behavior when creating a new repository from my templates: this workflow is sometimes not triggered on the initial commit (`First commit`)

**To Reproduce**
1. Create a template repository
2. Add a new workflow that should get triggered on push (except on the template repository) such as:
```
name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    if: github.repository != 'user/your-template-repository'
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo "Hello World!"
```
3. Create a new repository based on this template
4. Sometimes the workflow `init` will run inside of the new repository, but sometimes it doesn't

**Expected behavior**
The `push` trigger should always start the workflow on repository creation from template

## Runner Version and Platform
`2.272.0`

OS of the machine running the runner? `ubuntu-latest`
