### ISSUE TITLE
Self-hosted running exceeding maximum execution times

### ISSUE THREAD

**Issue by rakheshster** [actions/runner#685]
Hi,

I have a self-hosted runner which I've setup for GitHub Actions. From what I understand the maximum execution time limits don't apply to self-hosted runners, but mine seems to be getting cancelled after 360 mins. This is the error message I get:

> The job running on runner ghrunner-yza3xr has exceeded the maximum execution time of 360. 

Just to be explicit about it I even added an entry to specify the time limit:
```
jobs:
  buildx-selfhosted:
   # this job runs on Ubuntu
    runs-on: [self-hosted, linux, x64]
    # set timeout to 10 days
    timeout-minutes: 14400
```

I know it's picking up my correct runner as the name in the error is correct. 

Am I missing something here? 

Thanks,
Rakhesh
