### ISSUE TITLE
Run the job.container as the same user of the host VM by default

### ISSUE THREAD

**Issue by felipecrs** [actions/runner#691]
## Description

Run the containers as the same user running on the host (the VM) by default, or at least provide an option. The related docker option would be `docker run --user "$(id -u):$(id -g)"`.

Containers `job.container` runs as the container's default user by default, which often is root. This causes some weird behaviors because the `workspace` on the GitHub runner is mounted to the container, and no other user (other than the Runner user) has permission to write on it. [This is what makes @actions/checkout fail when running on containers](https://github.com/actions/checkout/issues/211).

As Jenkins does, this should be made by default. Users who might want to run as a different user can still use the `--user` docker option.

## Workaround

[As suggested by](https://github.com/actions/checkout/issues/211#issuecomment-680125896) @xanantis:

```YAML
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  clone-and-install:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - uses: actions/checkout@v2
```

It's even funny to have to do such a thing.

**Comment by BlueskyFR** [comment]
Can reproduce, I know it's been 2 years now but is there any update?

**Comment by sulfasTor** [comment]
> ## Description
> 
> Run the containers as the same user running on the host (the VM) by default, or at least provide an option. The related docker option would be `docker run --user "$(id -u):$(id -g)"`.
> 
> Containers `job.container` runs as the container's default user by default, which often is root. This causes some weird behaviors because the `workspace` on the GitHub runner is mounted to the container, and no other user (other than the Runner user) has permission to write on it. [This is what makes @actions/checkout fail when running on containers](https://github.com/actions/checkout/issues/211).
> 
> As Jenkins does, this should be made by default. Users who might want to run as a different user can still use the `--user` docker option.
> ## Workaround
> 
> [As suggested by](https://github.com/actions/checkout/issues/211#issuecomment-680125896) @xanantis:
> 
> ```yaml
> jobs:
>   configure:
>     runs-on: ubuntu-latest
>     outputs:
>       uid_gid: ${{ steps.get-user.outputs.uid_gid }}
>     steps:
>       - id: get-user
>         run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
> 
>   clone-and-install:
>     needs: configure
>     runs-on: ubuntu-latest
>     container:
>       image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
>       options: --user ${{ needs.configure.outputs.uid_gid }}
>     steps:
>       - uses: actions/checkout@v2
> ```
> 
> It's even funny to have to do such a thing.

This won't work if you have a big pool of runners and jobs are dispatched by different runners. ID's may mismatch.

**Comment by felipecrs** [comment]
That's true.

**Comment by russellsch** [comment]
Does anyone have any suggestions for dealing with this on self-hosted runners?

**Comment by xanantis** [comment]
@russellsch There are two options for you:
Rootless Docker
Podman, with podman.socket enabled. You may have to create a symlink for /usr/bin/docker to /usr/bin/podman.

Before rootless docker was available and podman supported interaction over a socket, I used parameter injection to inject --user for create, exec, and run commands.

**Comment by jcelerier** [comment]
any hope of seeing this little change one day ?

**Comment by dcfsc** [comment]
> This won't work if you have a pool of self-hosted runners and jobs are dispatched by different runners. ID's may mismatch.

@sulfasTor that is correct if you have arbitrary user ids. 

We create our 10 self-hosted runners using Ansible, so the `builder` userid is consistent across all runners. 

Just being able to inject something into the command line would be helpful. Doesn't have to be pretty.

**Comment by gfrankliu** [comment]
We use github hosted runners, the "runner" user uid/gid is different between "ubuntu-22.04" and "ubuntu-24.04". Today we find even "ubuntu-22.04" runners itself have "runner" uid 1000 for a short time, then back to 1001.

It would be nice if we can add "pre-steps" prior to job.container steps, so we can do below in "pre-steps", to ensure it is running on the same runner:

```
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
```

**Comment by felipecrs** [comment]
The image templates could have been done to always ensure UID is 1000. I see no good reason for it not to be the default always.

**Comment by gfrankliu** [comment]
For us using github runners, unfortunately we don't have control over how github created their runner image across different runner types or ubuntu versions. If they can guarantee runner uid/gid across all runners, eg: 1000/128, we can just hardcode it:

```
    container:
      options: --user 1000:128
      volumes:
        - /etc/passwd:/etc/passwd
        - /etc/group:/etc/group

```
