### ISSUE TITLE
Strategy matrix order is broken

### ISSUE THREAD

**Issue by denzhel** [actions/runner#703]
**Describe the bug**
When using Strategy matrix function in order to "loop" through an array, the order is not respected as mentioned in the documentation. Instead, it loops through the array randomly.

**To Reproduce**
1. Create a new repo
2. Add a single self hosted runner
3. Create a new workflow using this code:
```
on: [push]

jobs:
  test_job:
    runs-on: self-hosted
    strategy:
      matrix:
        node: [1, 2, 3]
    steps:
    - run: echo ${{ matrix.node }}
    - run: date
    - run: sleep 30000
```

**Expected behavior**
I expect that the jobs will start in this order:
1. test_job (1)
2. test_job (2)
3. test_job (3)

## Runner Version and Platform
* Runner version: 2.273.1
* Platforms: Ubuntu 18.04/ MacOS Catalina 10.15.6

## What's not working?
![](https://i.ibb.co/ZTBmxBG/Screen-Shot-2020-09-14-at-18-11-42.png)

Instead of respecting the order of the matrix(the documentation says the order matters) it chooses the index randomly.
As you can see in the picture, ```test_job (2) ``` is running first instead of ```test_job (1)```

![](https://i.ibb.co/TRLRDHy/Screen-Shot-2020-09-14-at-18-25-49.png)

**Comment by denzhel** [comment]
![](https://media.giphy.com/media/fdLR6LGwAiVNhGQNvf/giphy.gif)

**Comment by denzhel** [comment]
Found a workaround/Fix/Hack.

It's not clear but I guess using this method with self hosted runners is buggy.

To fix this behaviour, add ```max-parallel: 1``` to your strategy definiton:
```
strategy:
      max-parallel: 1
      matrix:
        node: [1, 2, 3]
```

**Comment by EvanK** [comment]
This bug bit me as well, and (with the default GH hosted runners at least) the `max-parallel: 1` workaround above causes the workflow to _error out entirely_ rather than run the matrix jobs in the expected order:

![max-parallel of 1 breaks entire workflow](https://user-images.githubusercontent.com/84145/151269549-30d89503-0c52-4dfe-bbd1-8bec2f750303.png)

**Comment by denzhel** [comment]
> This bug bit me as well, and (with the default GH hosted runners at least) the `max-parallel: 1` workaround above causes the workflow to _error out entirely_ rather than run the matrix jobs in the expected order:
> 
> ![max-parallel of 1 breaks entire workflow](https://user-images.githubusercontent.com/84145/151269549-30d89503-0c52-4dfe-bbd1-8bec2f750303.png)

Hi @EvanK,
Can you share your workflow file ? at least only the job's config

**Comment by EvanK** [comment]
Sure, [this stripped down copy of the workflow](https://gist.github.com/EvanK/cbdca4afbb798797baaea3be49f4da9b) was intended to run when opening or updating a pull request against the listed branches.

**Comment by denzhel** [comment]
Hi @EvanK, 

Maybe try this:
```
strategy:
        max-parallel: 1
        matrix:
            modules:
                - first-module-dirname
                - second-module-dirname
```
