### ISSUE TITLE
Can't get git tag annotation

### ISSUE THREAD

**Issue by gris-martin** [actions/runner#712]
**Describe the bug**
`git tag -l --format='%(contents)' <tag name>` displays the commit message instead of the tag annotation.

**To Reproduce**
1. Create a new local and GitHub repository, and set the local origin remote to the GitHub repository.
2. Create a workflow file `.github/workflows/main.yml` with the following content:
```yaml
on:
  push

jobs:
  git-tag-test:
    name: Test a git command
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v1.2.0
    - name: Run the command
      run: |
        echo $GITHUB_REF_NAME
        echo $(git tag -l --format='%(contents)' ${GITHUB_REF_NAME})
```
3. Stage and commit the file with a commit message: `git add .` && `git commit -m "Add GitHub workflow"`
4. Create a new tag: `git tag -a 1.0.0 -m "My first tag"`
5. Push the tag

See this repository where I have done these steps: https://github.com/hassanbot/issue-actions-tag-annotation/runs/1130066935

**Expected behavior**
A GitHub workflow is run with the following output:
```
1.0.0
My first tag
```

## Runner Version and Platform
The GitHub default runner (not using a local runner)

## What's not working?
The workflow output displays the commit message instead of the tag message:
```
1.0.0
Add GitHub workflow
```

## Other information
I have checked the git version of the runner with `echo $(git --version)`, and it is 2.28.0. I have the same version on my computer, where the command is working as expected.

I found out about the command from [this](https://stackoverflow.com/a/48693527/6685703) StackOverflow answer.

The reason I want to use the command is to automatically add the tag annotation to a Release description.

**Comment by classabbyamp** [comment]
I am also having this issue in exact same context/fashion

**Comment by classabbyamp** [comment]
I solved this by using:

```yaml
uses: actions/checkout@v2
with:
  ref: ${{ github.ref }}
```
