### ISSUE TITLE
Workflow run is stuck on GitHub-hosted macOS runner

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#725]
Associated GitHub Community ticket: https://github.community/t/macos-latest-get-stuck-on-starting-your-workflow-run/134783

The customer setup a matrix in his workflow like as below:
```yaml
name: Test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.7, 3.8]
```
The workflow run is stuck with the message "**`Starting your workflow run…`**".
I also tested with **`macos-latest`** on my side, and found that the jobs would be stuck for 3 to 5 minutes before they started to run.
