### ISSUE TITLE
Containerized action workspace directories seems to be rewritten on-the-fly

### ISSUE THREAD

**Issue by nervo** [actions/runner#728]
In a containerized action, where docker volumes are automatically mounted, the default `github.workspace` property (something like `/home/runner/work/my-repo-name/my-repo-name`) is automatically converted to the volume destination path (`/github/workspace`).
Btw, this conversion seems to be applied on-the-fly on all action parameters, stopping ability to use the original workspace path (`/home/runner/work/my-repo-name/my-repo-name`) in custom behaviors (such as - for instance - mounting workspace volumes in a docker-in-docker context)

1. Define some environment variables in a containerized action
```
      - name: Test
        uses: gofrolist/molecule-action@v2
        env:
          DEST_WORKSPACE: ${{ github.workspace }}
          SRC_WORKSPACE: ${{ runner.workspace }}/${{ github.event.repository.name }}
          SRC_WORKSPACE_FOO: ${{ runner.workspace }}/foo/${{ github.event.repository.name }}
```
3. See error

* `DEST_WORKSPACE` is `/github/workspace` and not `/home/runner/work/my-repo-name/my-repo-name`, that's fine :)
* `SRC_WORKSPACE` *should* be the original `/home/runner/work/my-repo-name/my-repo-name` as it's exactly how checkout action compose it but is `/github/workspace`
* `SRC_WORKSPACE_FOO` where the original workspace is poorman's obfuscated by injected a "foo" string is `/home/runner/work/my-repo-name/foo/my-repo-name`

**Expected behavior**
I expected to be able to use the original workspace `/home/runner/work/my-repo-name/my-repo-name` directory string in custom situations.

## Runner Version and Platform
The last available one on linux
