### ISSUE TITLE
Service is not visible on test step

### ISSUE THREAD

**Issue by thiaguerd** [actions/runner#738]
```yml
name: Rspec
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: running tests
        run: |
          sleep 60
          curl -X GET http://elasticsearch:9200/
```

Before 60 sec, I access a container of redis, install a curl and run curl -X GET http://elasticsearch:9200/ and i see a response ok.

On step running tests I got error message "Could not resolve host: elasticsearch"

Inside service/container redis I see a host elasticsearch but on step running tests no. What I can do?

using v2.273.4
