### ISSUE TITLE
Run multiarch docker image on self-hosted machine.

### ISSUE THREAD

**Issue by acburigo** [actions/runner#749]
**Describe the bug**
I'm trying to run an `armv7l` build on a `x86_64` self-hosted machine using a [multiplatform docker image](https://hub.docker.com/r/perimeterinc/homebase/tags).

Although I am able to correctly execute the docker container locally (docker image running `armv7l` while host is `x86_64`), the docker container does not execute the proper architecture image when using GitHub Actions. It always runs as `x86_64`, which is clearly shown by the output of the execution of the step "Show Architecture" (see workflow below).

My GitHub Action workflow looks something like the following:

```
name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build ARM Executable
    runs-on: [self-hosted, linux, ARM]
    container:
      image: perimeterinc/homebase
      options: --platform linux/arm/v7

    steps:
      - name: Show Architecture
        run: uname -m

      - name: Setup git credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
```

**Expected behavior**
Image runs in ARM architecture (at least in my self-hosted machine, which is already able to do so when done manually).

## Runner Version and Platform
Version of your runner?
`actions-runner-linux-x64-2.263.0.tar.gz`

```
$ uname -a
Linux monster 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

## What's not working?
Image runs as `x86_64`.
