### ISSUE TITLE
Step if condition starting with ! fails parsing

### ISSUE THREAD

**Issue by EnricoMi** [actions/runner#753]
**Describe the bug**
My workflow has a step if condition that starts with a `!` to negate the expression. The yaml file cannot be parsed: `While parsing a tag, did not find expected tag URI.`

**To Reproduce**
1. Add this yaml to your repo under `.github/workflow/`:

```
name: "Issue"
on: [push]

jobs:
  condition:
    name: "Condition Issue"
    runs-on: ubuntu-latest

    steps:
    - name: Not false condition
      if: ! false
      run: echo "works"
```

2. Commit and push to github, see the "Actions" tab, it will show you a failed action:

![grafik](https://user-images.githubusercontent.com/44700269/95779010-88eb1680-0cc9-11eb-96c1-c4e21aad10cb.png)

**Expected behavior**
The expression `! false` should be resolved to `true`. This workflow file works when the expression is enclosed in round brackets: `if: ( ! false )`. Those brackets should not be required.

## Runner Version and Platform
Version of your runner? Current

OS of the machine running the runner? Ubuntu
