### ISSUE TITLE
Support --privileged or --cap-add for docker containers

### ISSUE THREAD

**Issue by rwalker-apple** [actions/runner#754]
Thank you 🙇‍♀ for wanting to create a feature in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.  

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions or issues with the service, writing workflows or actions, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#contacting-support)

If you have a feature request that is relevant to this repository, the runner, then please include the information below:

**Describe the enhancement**
Facilities for controlling how a runner's container are constrained to volumes, ports, and environment.  This restricts the kinds of things that can be accomplished inside the container.  In my specific case, I run my jobs as root in the container, and I'd like access to iptables.

**Code Snippet**
Proposed sample:
```
         container:
             image: connectedhomeip/chip-build-cirque:0.4.10
             volumes:
                 - "/tmp:/tmp"
                 - "/dev/pts:/dev/pts"
             env:
                 LOG_DIR: /tmp/cirque_test_output/
                 CLEANUP_DOCKER_FOR_CI: 1
             options: "--privileged"
```
