### ISSUE TITLE
Cron job is running twice on schedule, expect to be running once

### ISSUE THREAD

**Issue by fartbagxp** [actions/runner#764]
**Describe the bug**
I have setup a daily cron job via https://github.com/fartbagxp/aas-cidr-ranges/actions/runs/322881434/workflow, and I notice it running the action twice. The scheduled cron is `*/50 20 * * *` for 20:50 UTC.

**To Reproduce**
1. Go to https://github.com/fartbagxp/aas-cidr-ranges/actions.
2. Notice that it's being run twice every day.

**Expected behavior**
I expect it to only run once.

## Runner Version and Platform
Version of your runner?
Github latest

OS of the machine running the runner? OSX/Windows/Linux/...
ubuntu:latest

## What's not working?
I expect the cron job to run once a day, and it is running twice a day.
For example, today it ran https://github.com/fartbagxp/aas-cidr-ranges/actions/runs/322828228/workflow and https://github.com/fartbagxp/aas-cidr-ranges/actions/runs/322828228/workflow back to back, and I'm not sure why.

**Comment by Kuboczoch** [comment]
Same issue here

My action that is executing twice a day:
```
name: Build and Deploy
on:
  push:
    branches:
      - production
  schedule:
    - cron: "* 1 * * *"

jobs:
  buildAndDeploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: production
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PRODUCTION }}
```
