### ISSUE TITLE
How to downgrade a homebrew package

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#770]
Associated GitHub Community topic: https://github.community/t/how-to-downgrade-a-homebrew-package/139578

Recently, the library **`libcerf`** has been downgraded from **`2.0`** to **`1.14`**, and Homebrew has followed this.
On a stand-alone Mac, when the customer runs the command "**`brew install libcerf`**", it can correctly installs **`libcerf 1.14`**.
But when try the same command in the workflow, it still installs **`libcerf 2.0`** on the macOS runners.

I have tried the following methods to install **`libcerf 1.14`** on the macOS runner, but none of them can work.
```yaml
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install libcerf
        run: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/fcbd11bbe961816867b4bae386153970a4315eee/Formula/libcerf.rb
```
```yaml
. . .
    steps:
      - name: Install libcerf
        run: brew install libcerf@1.14
```
```yaml
. . .
    steps:
      - name: Install libcerf
        run: |
          brew unlink libcerf
          brew install libcerf@1.14
          brew link libcerf@1.14 --force
```
