### ISSUE TITLE
Supporting Node.js 14 and 16 LTS as the runtime of JavaScript action

### ISSUE THREAD

**Issue by peaceiris** [actions/runner#772]
**Describe the enhancement**

Node.js v14.15.0 has been released and the 14.x release line now moves into Active LTS. Can the GitHub Actions runner support it as the runtime of a JavaScript (TypeScript) action? Is there a roadmap for this?

**Code Snippet**

Today, we can set `node12` to `runs.using`.

```yaml
runs:
  using: 'node12'
  main: 'main.js'
```

Can we set `node14` (or `node16`) as follows?

```yaml
runs:
  using: 'node14'
  main: 'main.js'
```

**Additional information**

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

We also need to update the documentation when `node14` is available.
