### ISSUE TITLE
OPENSSH: command not found

### ISSUE THREAD

**Issue by packyzbq** [actions/runner#776]
**Describe the bug**
I'm using github action to deploy github pages. The blog is generated by Hexo. My workflow is as follows:
```yaml
on: 
  push:
    branches:
      - master

jobs:
  ci:
    name: deploy hexo blog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        submodules: true
    - name: setup node env
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
    - name: deploy to gitee 
      env:
        GITEE_RSA_PRIVATE_KEY : ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      run: |
        npm ci
        npm install hexo -g
        hexo clean
        hexo g
        GITEE_RSA_PRIVATE_KEY=${{ secrets.GITEE_RSA_PRIVATE_KEY }} hexo d
```
When it runs to step `hexo d`, the runner throws an error:
```
/home/runner/work/_temp/2797e823-3ff2-40c9-b451-9c6adbc8cedd.sh: line 5: OPENSSH: command not found
```
Is it a bug or there's something I need to do?
