### ISSUE TITLE
Job-level "if" condition does not see outputs from needed jobs

### ISSUE THREAD

**Issue by martinpitt** [actions/runner#777]
**Describe the bug**
I'm trying to run a job with a condition that depends on the output of a previous job. It seems the first job's outputs are not available in the job-level `if` condition?

**To Reproduce**

This workflow file:
```yaml
name: job-condition
on:
  workflow_dispatch:

jobs:
  determine-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo hello
    outputs:
      proceed: 'yes'

  debug:
    needs: determine-condition
    runs-on: ubuntu-latest
    steps:
      - name: Debug output
        run: |
          echo "${{ toJson(needs.determine-condition) }}"

  maybe:
    needs: determine-condition
    if: needs.determine-condition.proceed == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Do the work
        run: |
          echo "🔨"
```

You can see it in action [at this run](https://github.com/martinpitt/anaconda/actions/runs/337268852).

**Expected behavior**
I expect the "maybe" job to run, not skipped, as the condition is true. Changing it to a boolean, like

    if: needs.determine-condition.proceed

also does not work.

## Runner Version and Platform
Official current GitHub runner as of 2020-10-30, no own deployment.

## What's not working?
The "maybe" job gets skipped. But the "debug" job proves that the output is available within a step, and has the expected value:

![image](https://user-images.githubusercontent.com/200109/97672429-55123e00-1a8a-11eb-8dfe-d6a8dfd935e5.png)

## Job Log Output
Unfortunately skipped jobs don't produce any logs about *why* it was skipped.
