### ISSUE TITLE
Self Hosted Runner: Unable to resolve action `actions/setup-node@v1.4.4`, unable to find version `v1.4.4`

### ISSUE THREAD

**Issue by ZacharyBenamram** [actions/runner#792]
**Describe the bug**
Trying to consume https://github.com/actions/setup-node but returning error below:

![Screen Shot 2020-11-05 at 11 22 14 AM](https://user-images.githubusercontent.com/5185400/98286665-2ea44500-1f59-11eb-9182-1aa292584d5f.png)

**To Reproduce**
1. Write workflow file 
```
jobs:
  build:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ matrix.node-version }}
```
2. Run workflow
3. See error

**Expected behavior**
Expecting the runner to be able to download public action

## Runner Version and Platform
Runner Version: 2.273.5
GHE Version: v2.22.3

OS of the machine running the runner?
ubuntu:18.04

## What's not working?
finding public action

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
