### ISSUE TITLE
"Custom shell" (kotlin) should allow custom file name extension (main.kts)

### ISSUE THREAD

**Issue by fwilhe2** [actions/runner#813]
**Describe the enhancement**
Actions allows to define a [custom shell](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#custom-shell) in worflow runs.
Kotlin has support for [scripting](https://github.com/Kotlin/kotlin-script-examples/blob/master/jvm/main-kts/MainKts.md).
I've tried to make use of Kotlin for runninng a script in Actions.
The issue is that kotlin expects a file name ending in `.main.kts`, but the runner creates a file without extensions for "shells" that are not hardcoded in https://github.com/actions/runner/blob/a2e32170fd83851569804fa7b27d2cae235a5225/src/Runner.Worker/Handlers/ScriptHandlerHelpers.cs#L38

File name construction: https://github.com/actions/runner/blob/a2e32170fd83851569804fa7b27d2cae235a5225/src/Runner.Worker/Handlers/ScriptHandler.cs#L233

**Code Snippet**

Consider this example workflow: 

```
name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: |
            #!/usr/bin/env kotlin
            println("hello")
        shell: kotlin {0}
```

I would expect to be able to run the given script in kotlin (the cli compiler is installed on the runner via `fwilhe2/setup-kotlin`).

**Additional information**

Result of the given workflow script:

![image](https://user-images.githubusercontent.com/52838694/99722987-d2d9d000-2ab1-11eb-8c34-b5bb657f7536.png)

This is because kotlin requires the `main.kts` suffix to know this should be run as a script.

I would need some way to provide a map of `kotlin` to `.main.kts` to `ScriptHandlerHelpers.GetScriptFileExtension()`

Compare to running the script locally with the right or the wrong filename

```
~$ cat foo.main.kts 
#!/usr/bin/env kotlin
println("hello")
~$ kotlin foo.main.kts 
hello
~$ mv foo.main.kts foo
~$ kotlin foo
error: could not find or load main class foo
```

Did I overlook something? Is this already possible? If not, I'd be glad if some option to make this would be provided, as it would make the "custom shell" feature much more interesting.

Thanks!

**Comment by fwilhe2** [comment]
So I've tried the most naive way of fixing this by adding the values to the map as shown in https://github.com/fwilhe2/runner/commit/66b90716c5ea992afcb0ed6995523a89d3f6d18d and used that version of the runner self hosed which shows that it works in principle:

![image](https://user-images.githubusercontent.com/52838694/99843958-aafe7100-2b72-11eb-8ffb-1e0121da005a.png)

I doubt this would be an acceptable solution, but I'm not sure what could be an acceptable solution. I think there would need to be another optional field something like `shell_script_pattern` or something.

Any comments or suggestions/ guidance on the way to a PR would be welcome.

**Comment by fwilhe2** [comment]
For reference: I've also created an issue for Kotlin https://youtrack.jetbrains.com/issue/KT-43534

**Comment by fwilhe2** [comment]
Update: Kotlin `1.4.30-RC` allows to "force" running as a script, so this is a workaround:

```
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.4.30-RC
      - run: |
            #!/usr/bin/env kotlin
            java.io.File(".").listFiles().forEach {it -> println(it.getName().toString())}
        shell: kotlin -howtorun .main.kts {0}
```

Still, it might be more elegant if this was possible:

```
      - run: |
            #!/usr/bin/env kotlin
            java.io.File(".").listFiles().forEach {it -> println(it.getName().toString())}
        shell: kotlin {0}
        scriptFileExtension: .main.kts
```
