### ISSUE TITLE
Do not build container actions ahead of time

### ISSUE THREAD

**Issue by umarcor** [actions/runner#814]
```yml
jobs:

  asciidoc:
    runs-on: ubuntu-latest
    steps:
    - name: Build hdlc/doc
      run: |
        docker build -t image_name - <<-EOF
        FROM asciidoctor/docker-asciidoctor
        RUN apk add -U --no-cache graphviz
        EOF
    - uses: actions/checkout@v2

    - name: Build site
      run: docker run -v /$(pwd)://documents/ image_name ./doc/make.sh

      # BUG: the following 'uses' should be equivalent to the 'run' command above.
      #      Unfortunately, GitHub tries to build a custom image before running the
      #      first step. At that point, image 'hdlc/doc' does not exist, so it fails.
      #
      #  uses: docker://image_name
      #  with:
      #    args: doc/make.sh
```

As explained in the comment, the runner tries to build the container for the last step, before starting the first one. Using local docker images in container steps should be supported too.
