### ISSUE TITLE
using if conditional with matrix.os to detect 'windows-latest' always fails

### ISSUE THREAD

**Issue by PixlRainbow** [actions/runner#819]
**Describe the bug**
Setting an "if" condition to check if the runner platform is 'windows-latest' always fails

**To Reproduce**
1. Create a workflow yml file with a job
2. Create a step with the conditional `if: matrix.os == 'windows-latest'` **OR alternatively** `if: startsWith(matrix.os, 'windows')`
3. Observe that the task is always skipped regardless of whether the runner is 'windows-latest' or another platform like 'ubuntu-latest'

**Expected behavior**
Step is run if the platform is 'windows-latest' and skipped otherwise

## Runner Version and Platform
GitHub free hosted runner

OS of the machine running the runner? 'windows-latest'

## What's not working?
YML file snippet
```yml
    - name: Test on Windows
      if: startsWith(matrix.os, 'windows')
      working-directory: ${{runner.workspace}}/build
      run: chatbot_test.exe

    - name: Test on POSIX
      if: startsWith(matrix.os, 'windows') != true
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./chatbot_test
```
***OR***
```yml
    - name: Test on Windows
      if: matrix.os == 'windows-latest'
      working-directory: ${{runner.workspace}}/build
      run: chatbot_test.exe

    - name: Test on POSIX
      if: matrix.os != 'windows-latest'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./chatbot_test
```

### 'windows-latest' does not trigger condition
![image](https://user-images.githubusercontent.com/44422178/100135513-b5976e00-2ec4-11eb-8be2-22c1d25295cc.png)
### 'ubuntu-latest' skipped normally
![image](https://user-images.githubusercontent.com/44422178/100135889-39e9f100-2ec5-11eb-9a3d-495bc3a27530.png)

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
