### ISSUE TITLE
Support for starting job service on condition is met

### ISSUE THREAD

**Issue by igagis** [actions/runner#822]
**Describe the enhancement**
Add support of `if:` property to `jobs.<job-id>.services.<service-id>` to start services only in case a condition is met.

**Code Snippet**
````
jobs:
  my_job:
    services:
      my_service:
        if: ${{ some expression }}
        ....
````

**Comment by tanguyantoine** [comment]
That would be very helpful if you have a shared workflow. We could turn on/off services based on workflow inputs

**Comment by imclem** [comment]
Couldn't agree more, we add steps to run `docker run` manually because we don't have conditions on services.

**Comment by bvtk** [comment]
Yes this would be a cool feature, we have the same problem on a shared workflow

**Comment by vyacheslav-korneev** [comment]
Got here searching for the solution of our problem with shared workflows :)
Hope this feature will be implemented, because it would increase the utility of shared workflows dramatically.

**Comment by flozano** [comment]
thanks a lot, I was trying something similar. not nice aesthetically but if it works it's great.

**Comment by cezar-tech** [comment]
That would be very helpful for my organization as well

**Comment by Cyberboss** [comment]
Workaround works perfectly for me

**Comment by Cyberboss** [comment]
Best GH can do is update the docs with this workaround.

**Comment by knu** [comment]
The workaround is not ideal as the image names specified in expressions will fall off from automated updates via Renovate.

**Comment by punkpeye** [comment]
I think the suggested workaround falls apart if there are liveness checks?

```yaml
      postgres:
        image: glama-postgres:${{ github.sha }}
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 10
        ports:
          - 7430:5432
```
