### ISSUE TITLE
Add github.repository_name property to github context

### ISSUE THREAD

**Issue by igagis** [actions/runner#826]
**Describe the enhancement**
There is already `github.repository` ('owner/name') and `github.repository_owner` (owner from 'owner/name') in the `github` context.

Add `github.repository_name` to the `github` context which would represent the name part of the 'owner/name'.

**Comment by nikola-jokic** [comment]
Hey @igagis,

Thank you for providing the feedback and suggesting this enhancement! We kindly ask you to redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions.

This enhancement affects multiple components within the platform, and it is a better starting point to increase its visibility.

For more information on this policy, please [read our contribution guidelines](https://github.com/actions/runner#contribute).

Since this enhancement impacts the platform more generally, I will close this issue now. But please, post your feedback to the Forum. It will help us to prioritize it and routing it to the correct team.

**Comment by sixcorners** [comment]
```
      - id: eval
        run: echo "repository_name=${GITHUB_REPOSITORY#*/}" >>"$GITHUB_OUTPUT"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
```
`${{ steps.eval.outputs.repository_name }}`
