### ISSUE TITLE
Token '>' is dropped when parsing shell code out of the yaml file, so a command cannot redirect output to a file

### ISSUE THREAD

**Issue by dougpagani** [actions/runner#828]
**Describe the bug**
I came across this when trying to create a commit for a pull request. Of course, an error is thrown if you try and add-commit changes with a clean working tree. So it became immediately obvious.

**To Reproduce**
1. Create a workflow file (shown below)
2. Start it
3. See that `>` is not preserved; `set -x` shows this clearly.

**Expected behavior**
tokens such as `>` to be maintained (so a file can be written to)

## Runner Version and Platform
Version: github's public, not enterprise

OS: ubuntu

## What's not working?
shell code is not properly parsing `>`, is what the problem seems to be

## Job Log Output
![image](https://user-images.githubusercontent.com/18250753/100317844-007bb900-2f8b-11eb-9e75-f138a403f09e.png)

## Workflow file:
```yaml
on: 
  schedule:
    - cron:  '*/2 * * * *' # should disable when not in use
    # - cron:  '30 6 * * *'


jobs:
  openpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create commits
        run: |
          set -x
          git config user.name 'Doug Pagani' # this should be the maintainer
          git config user.email 'doug@gmail.com'
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > uncommitted.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3

```
