### ISSUE TITLE
add conditional execution of action steps

### ISSUE THREAD

**Issue by igagis** [actions/runner#834]
**Describe the enhancement**
Add possibility to use `if:` option for action steps of composite actions.

**Code Snippet**
````
inputs:
  echo-bla:
    description: 'echo bla-bla-bla if not empty'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "start"
      shell: bash
    - run: echo "bla bla bla"
      shell: bash
      if: ${{ inputs.echo-bla }}
    - run: echo "stop"
      shell: bash
````

**Comment by louisgv** [comment]
Can't this be done with just shell script? Something like `[[ -n ${{ inputs.echo-bla }} ]] && echo "bla"`

**Comment by igagis** [comment]
@louisgv Well, ok, actually, I want the `if:` in composite actions to avoid running in shell which are not present in the system. So that I could make universal actions which would run in linux images, as well as windows ones (i.e. bash/powershell).
So, implementing check in `bash` is not an option for me since `bash` can be absent.

**Comment by dcharles-godaddy** [comment]
I'd like to have an action that does different things depending upon `cancelled()`, `failure()`, or `success()`, and these functions do not appear to be available inside of a `run`:
```
The workflow is not valid. .github/workflows/success.yaml (Line: 8, Col: 14): Unrecognized function: 'success'. Located at position 1 within expression: success()
```

**Comment by tahirmt** [comment]
Is there any plan to add if conditionals to composite actions now that they support `uses`

**Comment by potatoqualitee** [comment]
lol, didn't even realize i needed an if conditional as well. I'm basically building a wrapper for `actions/cache@v2` which requires `if: steps.cacher.outputs.cache-hit != 'true'` within my composite action. looking forward to this implementation!

**Comment by dkirrane** [comment]
@igagis Does this issue include support for `continue-on-error` & `timeout-minutes` for steps in a composite action? Or is there a separate ticket?

**Comment by zmughal** [comment]
A more robust workaround is to use the construction:

```shell
if ${{ toJSON(
         fromJSON( «input that is either 'true' or 'false'» )
         ... «rest of boolean expression»
       ) }}; then
  « commands... »;
fi
```

as the value of the `run:` key. This works because the output of `fromJSON()` in that case is either `true` or `false` which are the same as the shell script built-ins.

If you want to have a fallback value in case the input is left empty, then use  `|| 'false'` is to make sure that `fromJSON()` gets a value that can be parsed as a boolean when the argument is an empty string:

```
fromJSON(inputs.test-enable-coverage || 'false')
```


---

A couple full example steps would be:

```yaml
inputs:
  target-all:
    required: true
    default: false
  target-test:
    required: true
    default: false
  test-enable-coverage:
    required: true
    default: false
  target-notifications:
    required: true
    default: false
runs:
  using: "composite"
  steps:
    # Target: target-test
    - name: target-test (no coverage)
      shell: bash
      env:
        HARNESS_OPTIONS: ${{ inputs.test-harness-options }}
      run: |
          if ${{ toJSON(
                (  fromJSON(inputs.target-all)
                || fromJSON(inputs.target-test)
                )
                && ! fromJSON(inputs.test-enable-coverage || 'false')
              ) }}; then
            echo "::group::test (no coverage)"
            if [ -f Makefile.PL ]; then
              $MYPERL Makefile.PL && make test
            else
              echo "No file Makefile.PL" > /dev/stderr
            fi
            echo "::endgroup::"
          fi
    # Target: target-notifications
    - name: irc push (build messages)
      shell: bash
      run: |
          if ${{ toJSON(
                      fromJSON(inputs.target-notifications)
                   && github.event_name == 'push'
                   && github.repository == inputs.repository
                 ) }}; then
            echo "commitmsg="$( git show -s --oneline ${{ join(github.event.commits.*.id, ' ') }} ) >> $GITHUB_ENV
          fi
```

**Comment by dkirrane** [comment]
Does this issue include support for `continue-on-error` & `timeout-minutes` support for steps in a composite action?

**Comment by ccolella-mdc** [comment]
I also need this functionality. I am trying to run another action based on an `if: `. Using bash/powershell will not work in this case.

**Comment by finolacahill** [comment]
Big +1 on this functionality. I have a number of composite actions that are stored centrally and checked in and used by a variety of different repos for CI checks. This is to avoid massive amounts of repeated code. Currently each composite action has a final step whereby it uploads essential logs/reports as an artifact. Given that in composite actions one can neither _if: always_ nor _continue-on-error_ (and continue on error still frustratingly results in the job appearing as a success overall), all actions that error out have no error logs uploaded as an artifact. 
Composite actions are so close to being the solution to enforcing DRY principles on CI checks here, but it's failing at the last hurdle. All my artifact-upload steps have to be copy and pasted over and over into the individual workflows in the individual repos in order to be able to use an if conditional. **Why?**

**Comment by keepler-ivanmarques** [comment]
+1

**Comment by zmughal** [comment]
@ccolella-mdc , in the meantime, you can call another non-composite action manually by setting the inputs as environment variables and using the bash + `toJSON()` approach I outlined above.

I have some examples of this here where I use an action for sending IRC notifications: <https://github.com/PDLPorters/devops/blob/master/github-actions/irc-notifications/action.yml>. I had to do this as I could not wait for this issue to be resolved --- I would have too much code churn copying/updating this to all my repositories.

**Comment by sureshg** [comment]
@zmughal I think your method will work only for `run` script, not for step that uses third-party action (say `cache`).

**Comment by zmughal** [comment]
> @zmughal I think your method will work only for `run` script, not for step that uses third-party action (say `cache`).

@sureshg, yes, that's what I mean by non-composite action (i.e., Docker and JavaScript). You have to clone the action yourself in the workflow and then look at the `action.yml` of the third-party action and extract out what it would run at each stage like here <https://github.com/actions/cache/blob/v2.1.6/action.yml#L21-L24>. It's a hack-y solution, but if you really need it now, there is a way.

**Comment by tahirmt** [comment]
I don’t think you can do that for any action with post steps or even inputs because most actions take the inputs from the context using Core

**Comment by ChristopherHX** [comment]
I just had an idea how you can easy use `actions/cache@2` with cache-hit conditionally, so here my workaround:
You can use this composite action as a replacement to if, will work if your github actions instance has uses support.

You can copy this `action.yml` to your own repo if you wish or use [ChristopherHX/conditional](https://github.com/ChristopherHX/conditional):
```yaml
inputs:
  if:
    description: Your condition
    default: true
  step:
    description: Your step to run if the condition is met
runs:
  using: composite
  steps:
  - uses: actions/github-script@v4
    with:
      github-token: none
      script: |
        var fs = require('fs');
        try {
          fs.mkdirSync('./.github/conditional/tmp', {recursive: true});
        } catch {
        }
        if(${{fromJSON(inputs.if)}}) {
          fs.writeFileSync('./.github/conditional/tmp/action.yml', 'runs:\n  using: composite\n  steps:\n  - ' + process.env['STEP'].replace(/\n/g, '\n    '));
        } else {
          fs.writeFileSync('./.github/conditional/tmp/action.yml', 'runs: {using: composite, steps: []}');
        }
    env:
      STEP: ${{inputs.step}}
  - uses: ./.github/conditional/tmp
```

## Usage:

- You have to surround the if condition with `${{.,,}}` otherwise it won't work.
- The pipe symbol ( `|` ) after `step:` is required, because inputs have to be strings.
- Expression syntax will even work on places github wouldn't allow (step property)
- Pre steps aren't executed, because they won't work with local actions.
```yaml
- uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
  with:
    if: ${{steps.cacheaction.outputs.cache-hit != 'true'}}
    step: |
      uses: actions/setup-node@v2
      with:
        node-version: ${{inputs.nodever}}
```

[Full example on github](https://github.com/ChristopherHX/conditional/blob/main/.github/tests/test1/action.yml)

## How does it work?

This small composite action create a temporary child composite action in `./.github/conditional/tmp/`, based on the evaluated condition and your provided step, therefore you can skip a uses directive. If the condition evaluates to false, it executes an empty action instead.
The usage of `- uses: actions/github-script@v4` allows this action to work on linux / windows / mac without the need for `bash` or downloading any other shell.


This will continue to work after this feature is finally implemented inside the runner.

**Comment by pommevilla** [comment]
+1

**Comment by floryut** [comment]
@ChristopherHX Wow, good job man, your action is a perfect workaround for this missing important feature.

**Comment by lethalbrains** [comment]
+1

**Comment by gmambro** [comment]
+1

**Comment by ChristopherHX** [comment]
GitHub has finally implemented it in release v2.284.0, it might take some time until all runners are forced updated to that version: https://github.com/actions/runner/releases/tag/v2.284.0

> Does this issue include support for continue-on-error & timeout-minutes on steps in a composite action?

@dkirrane It seems the answer is no, consider open a new issue. These keywords are still unavailable after that runner update.

**Comment by AlexDHoffer** [comment]
For what it is worth, I have filed a new issue for ``continue-on-error`` here, as I would like to see this feature added as well https://github.com/actions/runner/issues/1457

**Comment by webknjaz** [comment]
@asvetlov ☝️

**Comment by AuHau** [comment]
Any ideas when the new version might be deployed? 😅

**Comment by nbrugger-tgm** [comment]
https://github.com/actions/runner/issues/834#issuecomment-956779479

What is time scope of "it might take some time"

**Comment by ChristopherHX** [comment]
> What is time scope of "it might take some time"

I don't know, for self-hosted runners you can dowload the new release, since Monday.
I'm not affiliated with GitHub and honestly don't know how long github tests this specfic release.
- it sometimes take hours if it is a critical patch
  Some folks hate the force update see this issues: https://github.com/actions/runner/issues?q=is%3Aopen+is%3Aissue+label%3A%22Runner+Auto-update+%3Adisappointed%3A%22
- it sometimes take weeks

I heard some github actions free users are randomly selected to test new releases, without opt out. For example my workflow runs had a newer actions/virtual-environment than other workflow runs of the same time, yesterday.

_I doubt you will get the update faster for hosted runners, if you write more comments in this issue_

**Comment by fhammerl** [comment]
Runner v2.284.0 and with it, conditional execution of composite actions is available across all hosted and self-hosted runners on github.com. 

I'm going to leave this issue open for a while for immediate feedback that doesn't warrant its own issue.

**Comment by solarmosaic-kflorence** [comment]
Am I misunderstanding how this works? Current runner version: '2.284.0'

```yaml
name: "..."
description: "..."
inputs:
  ...
  target-environment:
    description: "..."
    required: true
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        ...
    - run: aws sts get-caller-identity
      shell: bash
    - name: "Destroy management resources"
      uses: ./.github/actions/terraform-destroy
      with:
        ...
      if: ${{ inputs.target-environment != management }}
    - name: "Destroy ${{ inputs.target-environment }} resources"
      uses: ./.github/actions/terraform-destroy
      with:
        ...
```

Gives me the error:
```text
Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11):
Error: /home/runner/work/...action.yaml (Line: 45, Col: 11):
Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '"management"'. Located at position 30 within expression: inputs.target-environment != "management"
Error: /home/runner/work/...action.yaml (Line: 45, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ inputs.target-environment != "management" }}
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '"management"'. Located at position 30 within expression: inputs.target-environment != "management",/home/runner/work/...action.yaml (Line: 45, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ inputs.target-environment != "management" }}
```

I have tried various syntax: 
- `if: inputs.target-environment != management`
- `if: inputs.target-environment != "management"`
- `if: ${{ inputs.target-environment != management }}`
- `if: ${{ inputs.target-environment != "management" }}`
- `if: "${{ inputs.target-environment != management }}"`

All result in the same error.

**Comment by ChristopherHX** [comment]
@solarmosaic-kflorence You need single quotes, everything else is not supported in this expression language
```yaml
if: inputs.target-environment != 'management'
```
- management is not a valid expression context
- unquoted double quotes are a syntax error

**Comment by nbrugger-tgm** [comment]
> Am I misunderstanding how this works? Current runner version: '2.284.0'
> 
> ```yaml
> name: "..."
> description: "..."
> inputs:
>   ...
>   target-environment:
>     description: "..."
>     required: true
> runs:
>   using: "composite"
>   steps:
>     - uses: aws-actions/configure-aws-credentials@v1
>       with:
>         ...
>     - run: aws sts get-caller-identity
>       shell: bash
>     - name: "Destroy management resources"
>       uses: ./.github/actions/terraform-destroy
>       with:
>         ...
>       if: ${{ inputs.target-environment != management }}
>     - name: "Destroy ${{ inputs.target-environment }} resources"
>       uses: ./.github/actions/terraform-destroy
>       with:
>         ...
> ```
> 
> Gives me the error:
> ```text
> Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11):
> Error: /home/runner/work/...action.yaml (Line: 45, Col: 11):
> Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '"management"'. Located at position 30 within expression: inputs.target-environment != "management"
> Error: /home/runner/work/...action.yaml (Line: 45, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ inputs.target-environment != "management" }}
> Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '"management"'. Located at position 30 within expression: inputs.target-environment != "management",/home/runner/work/...action.yaml (Line: 45, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ inputs.target-environment != "management" }}
> ```
> 
> I have tried various syntax: 
> - `if: inputs.target-environment != management`
> - `if: inputs.target-environment != "management"`
> - `if: ${{ inputs.target-environment != management }}`
> - `if: ${{ inputs.target-environment != "management" }}`
> - `if: "${{ inputs.target-environment != management }}"`
> 
> All result in the same error.

The correct way is 'management' as started in the github Action documentation about "expression" you find a listing about types and how they work

**Comment by solarmosaic-kflorence** [comment]
I don't think that's true. I use double quotes everywhere and they work fine. FWIW I also tried this with single quotes (`if: inputs.target-environment != 'management'`) and got the same error:

```
Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11):
Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11):
Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '"management"'. Located at position 30 within expression: inputs.target-environment != "management"
Error: /home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ inputs.target-environment != "management" }}
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/...action.yaml (Line: 45, Col: 11): Unexpected symbol: '"management"'. Located at position 30 within expression: inputs.target-environment != "management",/home/runner/work/.../action.yaml (Line: 45, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ inputs.target-environment != "management" }}
```

**Comment by fhammerl** [comment]
Release announcements: https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/

**Comment by solarmosaic-kflorence** [comment]
@fhammerl will https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions be updated to denote `runs.steps[*].if`?

**Comment by foolioo** [comment]
why do one need to find this thread and not read it in the original documentation?! :(

**Comment by solarmosaic-kflorence** [comment]
@foolioo it is being tracked here now https://github.com/github/docs/pull/12378

**Comment by AlexDHoffer** [comment]
Does the if conditional not work for outputs of previous steps?

For example:

````
    - name: Apply Tag of Commit Hash to Master
      id: tag_master_with_commit
      if: ${{ steps.tag_check.outputs.tag_exists }} != true
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ inputs.github_token }}
        custom_tag: ${{ steps.short_sha.outputs.short_sha }}
        tag_prefix: 'master-'
````

This doesn't appear to actually run a conditional statement against the previous step's output and thus always runs.
