### ISSUE TITLE
add possibility to use defaults inside of composite actions

### ISSUE THREAD

**Issue by igagis** [actions/runner#836]
**Describe the enhancement**
Add the `defaults:` option to the composite actions

**Code Snippet**
````
runs:
  using: "composite"
  defaults:
    run:
      shell: bash
  steps:
    - run: echo "bla bla 1"
    - run: echo "bla bla 2"
    - run: echo "bla bla 3"
````
