### ISSUE TITLE
Add `if` to `container`

### ISSUE THREAD

**Issue by Cyberbeni** [actions/runner#842]
**Describe the enhancement**
If you want to test with different Swift versions on Linux then the best way to do this is via a container but since the latest Swift version is preinstalled, it would be faster to skip the container step in that case. Of course you can duplicate the action but it would be cleaner to just be able to skip the container step.

**Code Snippet**
```yaml
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 5.1
        - 5.2
        - 5.3
    container:
      if: matrix.swift != 5.3
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery
```

**Comment by igagis** [comment]
See my recent feature request #855 . Possibly, it may help achieving this as:
````yml
 linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 5.1
        - 5.2
        - 5.3
    container: ${{ if(matrix.swift != 5.3, join(['swift:', matrix.swift],''), '') }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery
````
Though, I'm not sure about `join()` function usage, GHA documentation on that is poor.
