### ISSUE TITLE
Float 3.0 is misparsed as integer 3 in workflow YAML

### ISSUE THREAD

**Issue by eregon** [actions/runner#849]
**Describe the bug**

`3.0` in a workflow is misparsed as integer `3`.
Or at the very least, when it's parsed and then later converted to a string (with `${{ matrix.ruby }}`), it's `3` and not the expected `3.0`.

**To Reproduce**
```yaml
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ 2.7, 3.0 ]
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
```

**Expected behavior**
The input log and the job name should indicate `3.0`, but we see `3` instead:
https://github.com/eregon/setup-ruby/runs/1503368422?check_suite_focus=true#step:3:3
```
Run ./
  with:
    ruby-version: 3
    bundler-cache: true
    bundler: default
    working-directory: .
```

This is important because `ruby-version: 3.0` should pick version 3.0 but not version 3.1.
Due to this bug it would pick version 3.1.

I think in the YAML specification it's clear that floats and integers are different, so they should be kept that way too in workflow YAMLS, including when passing through `${{ matrix.ruby }}`.

Using quotes `[ 2.7, '3.0' ]` is a workaround, but it should be unnecessary and it's much more verbose with many versions.

## Runner Version and Platform
Version of your runner? 2.274.2
OS of the machine running the runner? Applies to all

**Comment by maxim-lobanov** [comment]
@eregon  I have faced with the same issue in my own action https://github.com/maxim-lobanov/setup-xcode and decided that the best solution is updating my action's readme to recommend customers to use quotes in inputs.

I agree that the behavior that you have described looks a bit strange and it could be a bug. But I have found another problem if inputs are not quoted:
```
with:
    python-version: 3.10
```
This input will be parsed as `3.1` and it is definitely not that you expect to see. But based on YAML specification it is expected behavior because `3.10` is float value and trailing `0` can be removed. 

A few words from https://symfony.com/doc/current/components/yaml/yaml_format.html
> Strings in YAML can be wrapped both in single and double quotes. **In some cases, they can also be unquoted**
> ...
> Finally, there are other cases when the strings **must be quoted**, no matter if you’re using single or double quotes:
> ...
> - When the string looks like a number, such as integers (e.g. 2, 14, etc.), floats (e.g. 2.6, 14.9) and exponential numbers (e.g. 12e7, etc.) (otherwise, it would be treated as a numeric value);

So looks like that quoting is the best approach to save input as it is since strings can't be transformed somehow.
Also, All first-party actions recommend to wrap version input to quotes: https://github.com/actions/setup-node#usage

(Please do not take my answer as official position of actions/runner owners 😃  . I don't have context how YAML parsing works under hood in GitHub Actions and just say from position of third-party action's owner who faced with the same issue)

**Comment by eregon** [comment]
I agree for `3.10` it's a problem and there is no other way to fix that than to use quotes (`'3.10'`).
I am taking advantage here that CRuby versions never had and most likely never will have a minor > 9 (i.e., it was 1.9 then 2.0).

When I started the action I considered both options, and I chose the unquoted variant because it worked as far as I could see just as good, and it's a lot more concise.
Compare:
```yaml
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7, head, debug, jruby, jruby-head, truffleruby, truffleruby-head]
```
and
```yaml
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: ['2.5', '2.6', '2.7', 'head', 'debug', 'jruby', 'jruby-head', 'truffleruby', 'truffleruby-head']
```
I find the second one much harder to read.
A practical consequence is the quoted variant actually doesn't fit on one line in the [README](https://github.com/ruby/setup-ruby/tree/07b100f2a15431fc70a2ae673cfda32190cf24ca#matrix).

An example in another project: https://github.com/jeremyevans/sequel/pull/1742/files

Also, as we can still see today, the unquoted versions were also used in TravisCI, which a lot of Ruby users come from:
https://docs.travis-ci.com/user/languages/ruby/
```yml
language: ruby
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby
```
