### ISSUE TITLE
add 'if' function to expression syntax

### ISSUE THREAD

**Issue by igagis** [actions/runner#855]
**Describe the enhancement**
Add `if` function to expression syntax. The function will take 3 arguments:
````
if(expr, then, else)
````
and in case `expr` evaluates to `true` it will replace itself with `then` value, otherwise with `else` value.

**Code Snippet**
See `runs-on` job property in the below snippet
````yaml
name: build
on: push
jobs:
  job1:
    strategy:
       fail-fast: false
       matrix:
         include:
           - { arch: amd64, image: debian:buster }
           - { arch: amd64, image: ubuntu:eoan }
           - { arch: arm,   image: igagis/raspbian:buster } # ARM arch image
    runs-on: ${{ if(matrix.arch == 'amd64', 'ubuntu-latest', '[self-hosted, arm]') }}
    container: ${{ matrix.image }}
    steps:
    - name: build
      run: make
````
