### ISSUE TITLE
Let use lists in matrix include and exclude properties

### ISSUE THREAD

**Issue by jneira** [actions/runner#857]
If you have a feature request that is relevant to this repository, the runner, then please include the information below:

**Describe the enhancement**

* You must use lists in the matrix variables
* But you cant use lists in the include and exclude properties so they come too much annoying too quickly.
* I would suggest let use lists in the include and exclude variables and unroll them as individual values like actual ones

**Code Snippet**
If applicable, add a code snippet.
This new configuration:
```yaml
matrix:
  x: [1,2,3,4]
  y: [a, b, c]
  exclude:
    - x: [1,3]
      y: [a, c]
  include: 
    - x: [2,4]
       y: [a,d]
```
would behave like this actual one:

```yaml
matrix:
  x: [1, 2, 3, 4]
  y: [a, b, c]
  exclude:
    - x: 1
      y: a
    - x: 1
      y: c
    - x: 3
      y: a
    - x: 3
      y: c
  include: 
    - x: 2
      y: a
    - x: 2
      y: d
    - x: 4
      y: a
    - x: 4
      y: d
```
