### ISSUE TITLE
Organization private repo is not accessible from another private repo with Organization secret - Go dependency downloads

### ISSUE THREAD

**Issue by shivarammysore** [actions/runner#858]
I have an Organization setting for my repos. The token supplied has organization setting  with "All Repositories" access
https://github.com/MyOrg/RepoA
https://github.com/MyOrg/RepoB

I have the below workflow action in https://github.com/MyOrg/RepoA/.github/workflows/go.yaml

```yaml
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      env:
        GOPATH: ${{ github.workspace }}
        GOOS: linux
        GOARCH: amd64
        
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
        stable: 'true'
      id: go

    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.MYORG_REPO_ACCESS_TOKEN }}
      run: |
        git config --global url."https://$username:${TOKEN}@github.com".insteadOf "https://github.com"
        cat ~/.gitconfig

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: src/github.com/MyOrg/RepoA
        submodules: true

    - name: Get dependencies
      if: success()
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep status
          dep ensure
        fi
```

`Get Dependencies` step fails

```
Run export PATH=$PATH:$(go env GOPATH)/bin
/home/runner/work/RepoA/RepoA/bin:/opt/hostedtoolcache/go/1.15.5/x64/bin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/go/bin
/home/runner/work/RepoA/RepoA
github.com/ghodss/yaml (download)
created GOPATH=/home/runner/go; see 'go help gopath'
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/MyOrg/RepoB (download)
# cd .; git clone -- https://github.com/MyOrg/RepoB /home/runner/go/src/github.com/MyOrg/RepoB
Cloning into '/home/runner/go/src/github.com/MyOrg/RepoB'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/MyOrg/RepoB/'
package github.com/MyOrg/RepoB: exit status 128
Error: Process completed with exit code 1.

```

**Expected behavior**
I want the dependent private repo to be `git cloned` appropriately just like any public repo.
