### ISSUE TITLE
Extend "on" with possibility to ignore forks (run only for the original repo)

### ISSUE THREAD

**Issue by famod** [actions/runner#859]
**Describe the enhancement**
Enhancement of the [`on` directive](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on) to tigger a workflow only for the original repo, not a fork of it.

**Code Snippet**
One idea:
```yaml
on:
  push:
    repositories:
      - 'quarkusio/quarkus'
```
or more specifically (but less flexible):
```yaml
on:
  push:
    ignore-forks: true
```
or similar.

**Additional information**

There are a couple of workflows over at https://github.com/quarkusio/quarkus which just don't make sense to run for forks.

Right now those workflows are using _per job_:
```yaml
  linux-jvm-tests:
    name: JVM Tests - JDK ${{matrix.java.name}}
    runs-on: ubuntu-latest
    # Skip master in forks
    if: "github.repository == 'quarkusio/quarkus'
```
This is rather verbose and easy to forget for workflows consisting of multiple jobs.
Furthermore, it results in many skipped actions entries in forks, e.g. "Cleanup Duplicate CI Runs" here: https://github.com/famod/quarkus/actions

Disabling actions in forks is not an option for Quarkus, since Quarkus contributors are asked to wait for CI in their forks before creating PRs.

PS: Not sure this is the right report for syntax enhancements. 🤔 If not, please point me in the right direction. Thanks!
