### ISSUE TITLE
github context is not accessible from step.uses

### ISSUE THREAD

**Issue by igagis** [actions/runner#895]
**Describe the bug**
It is not possible to use `github` context in `jobs.<job_id>.steps[*].uses`.

**To Reproduce**
create workflow which uses `github` context within `uses`:

````
name: ci
on: [push, pull_request]
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: this repo action
        uses: ${{ github.repository }}@${{ github.sha }}        
````

**Expected behavior**
`github.repository` and `github.sha` are substituted with correspoonding values.

## Runner Version and Platform
public runner

## What's not working?
`github` context variable substitution

## Job Log Output
````
The workflow is not valid. .github/workflows/ci.yml (Line: 17, Col: 15): Unrecognized named-value: 'github'. Located at position 1 within expression: github.repository 
````

## Runner and Worker's Diagnostic Logs
https://github.com/myci-actions/add-deb-repo/actions/runs/469160309

**Comment by michalinacienciala** [comment]
Same issue occurs also for `steps` context.

**Comment by TingluoHuang** [comment]
We don't support expression in those place, you need to checkout the repo to use local action.

```
- uses: actions/checkout@v2
- uses: ./
```

**Comment by TingluoHuang** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow

**Comment by igagis** [comment]
Is there a reason why it is not supported?

**Comment by TingluoHuang** [comment]
We want the YAML file readable at some level, so we don't open expressions for every part of the YAML file.

You can make a feature request at https://github.community/c/code-to-cloud/github-actions/41

The runner repo might not be a good place for this kind of question, it doesn't understand YAML at all, the service parses the YAML and validates against a defined schema.  😄

**Comment by igagis** [comment]
> We want the YAML file readable at some level, so we don't open expressions for every part of the YAML file.

This looks to me as a pretty weak argumentation.

> You can make a feature request at https://github.community/c/code-to-cloud/github-actions/41

I find forums pretty bad place for feature requests, as the post on forums quickly gets lost and nobody follows up on those. There should be a bug tracker for that! This is why I opened it here. I have no idea which part of the software is responsible for yaml parsing, could you forward this to the right team/software component?

**Comment by TingluoHuang** [comment]
@chrispat from product

**Comment by chrispat** [comment]
The original reason we didn't support it was so we could enforce the policies of the org when they limited which actions you could use.   We have changed how the runner resolves actions so it we could support it now. However, you would get a runtime failure if you violated a policy rather than a queue time failure.  

For this particular scenario I don't see how it is different than referencing a repository local action via ./<path>

**Comment by igagis** [comment]
Ok, for my particular use case using local action is enough, so if you want, you can close the issue.

**Comment by groensch24** [comment]
We want to have a security check of you containers implemented for every PR that is created.

For that it is crucial to build the container in one job, push it into the registry and then pull and run some command in it.

```yml
jobs:
  security-check:
    runs-on: ubuntu-latest
    needs: build-main-test
    steps:
      #....
      - uses: docker://eu.gcr.io/security-check:${{ env.GITHUB_SHA }}
        with:
          entrypoint: security-check
```
How can we achieve this when we cannot use the variables in this context?

**Comment by spangaer** [comment]
If you try access a sibling action that you want to have at the same ref as the action being executed you need that expansion too.

😞

**Comment by cyechow** [comment]
If we have a checkout action that sets a path relative to `GITHUB_WORKSPACE` and then want to call a custom action, is there a way to do this?

I've tried various things and haven't found a method that works.

``` yml
env:
  GIT_CLONE_PATH: "${{ github.workspace }}\\${{ github.ref_name }}"

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          clean: false
          path: "${{ env.GIT_CLONE_PATH }}"
# The following doesn't work because it's looking for actions.yml in ${{ github.workspace }}/.github/actions/CustomAction.
# We also can't set the working directory for uses.
      - uses: ./.github/actions/CustomAction 
# Ideally I can do something like this:
      - uses: "${{ env.GIT_CLONE_PATH }}/.github/actions/CustomAction"
# Or something like this:
      - uses: ./.github/actions/CustomAction 
        working-directory: "${{ env.GIT_CLONE_PATH }}"
```

**Comment by spangaer** [comment]
Try `./${{ github.ref_name }}/.github/actions/CustomAction`

When using local actions the local action is indicated by the `.`, but the `.` equates to ${{ github.workspace }}

I do fear that the uses will not accept any `${{...}}` so you you'll have to check out to `my-code` and then call `./my-code/.github/actions/CustomAction`

I'd avoid using that ref name in check-paths. I guess there some dodging there of the self-hosted runner not cleaning up.

**Comment by wheelerlaw** [comment]
Lets say I have two repos. Repo A has a workflow that calls Composite Action 1 in Repo B. Composite Action 1 calls Composite Action 2 in Repo B.  

The lack of availability of the `github` context object means that a composite action cannot use another composite action unless the branch is hard coded. 

In Composite Action 1, I want to have the following:

```
uses: ./composite-action-2
```

However, I can't because the `.` resolves to the workspace of the calling workflow (which defaults to the root of the repo, Repo A), not the root of the repo where the composite actions are located, Repo B. 

My first instinct is to do this:

```
uses: ${{ github.action_path }}/../composite-action-2
```

However, the `github` object is not available. I also can't do this:

```
uses: Org/repo-b/composite-action-2@${{ github.action_ref }}
```

Instead, I have to hard code the reference to the nested composite action, which greatly complicates the development workflow for working on these shared actions.

**Comment by jenseng** [comment]
I've figured out a workaround using a composite action that generates and runs another composite action to call the desired action dynamically 😅 ... Give [`jenseng/dynamic-uses@v1`](https://github.com/marketplace/actions/dynamic-uses) a spin (or feel free to borrow/fork/adapt its [action.yml](https://github.com/jenseng/dynamic-uses/blob/main/action.yml))

Given a step like so:

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 18
```

If you want your uses to be dynamic you can do:

```yaml
- uses: jenseng/dymamic-uses@v1
  with:
    # now you can use expressions 🥳
    uses: actions/setup-node@${{ inputs.version }}
    # the `with` needs to be converted to a valid json string
    with: '{ "node-version": 18 }'
```
