### ISSUE TITLE
Make ${GITHUB_REF} available in the job.services section of the workflow

### ISSUE THREAD

**Issue by chrisBrookes93** [actions/runner#901]
**Describe the enhancement**
I am using GH Actions to test a network-based library which comes in the form of two scripts: an agent that listens for requests, and an executor that makes the request. I am trying to write a 'split box' test, where each script is on a 'different machine'. I am trying to achieve this by running the agent script within a service as part of a workflow job.

To do this I have created a docker image that does a git clone, installs the python package and then runs a command line to run the actual script. The Git URL for the project, the commit hash/branch for the current push, and the script command line are all passed into the service as environment variables. (see workflow file below):

```
name: CI
on: [push, pull_request]
jobs:
  split-box-test:
    runs-on: ubuntu-latest
    services:
      rfagent:
        image: chrisbrookes93/appservicecontainer:3.8-slim-buster-v0.0.1
        env:
          GIT_URL: git://github.com/chrisBrookes93/robotframework-remoterunner.git
          # THIS GETS PASSED THROUGH AS "${GITHUB_REF}" RATHER THAN "refs/heads/<branch name>"
          GIT_COMMIT_HASH: ${GITHUB_REF}
          APP_LAUNCH_CMDLINE: rfagent -p 1471
        ports:
          - 1471:1471

    steps:
      - name: Print github ref
        # THIS GETS PASSED THROUGH AS "refs/heads/<branch name>"
        run: echo ${GITHUB_REF}
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the package
        run: |
          pip install .
      - name: Execute a remote run script
        run: |
          rfremoterun 127.0.0.1 tests/unit_tests/rf_client_test_resources
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

```

What I'm finding that the "${GITHUB_REF}" variable is getting translated into "refs/heads/\<branchname\>" within the `job.steps`  section, but it is not getting translated in the `job.services.env` section. 

Translation of the variable works in the `job.steps` section:
![image](https://user-images.githubusercontent.com/1598192/104108561-8d6d9e00-52bd-11eb-9b84-ab6b0ee799d6.png)

But not in the `job.services.env` section:

![image](https://user-images.githubusercontent.com/1598192/104108569-bdb53c80-52bd-11eb-8faf-7b3523f5443f.png)

I would like to request that ${GITHUB_*} variables are translated in the `job.services.env` section (and probably globally within the workflow file).

**Comment by chrisBrookes93** [comment]
${GITHUB_REF} is an environment variable so I'm not sure what I'm asking for is possible. Also I have realised that I can obtain the information I need from the ```github``` context:

```
services:
      rfagent:
        image: chrisbrookes93/appservicecontainer:3.8-slim-buster-v0.0.1
        env:
          GIT_URL: git://github.com/chrisBrookes93/robotframework-remoterunner.git
          GIT_COMMIT_HASH: ${{ github.sha }}
          APP_LAUNCH_CMDLINE: rfagent -p 1471
        ports:
          - 1471:1471
```

Closing off this issue!
