### ISSUE TITLE
RUNNER_OS is missing in pwsh

### ISSUE THREAD

**Issue by henryiii** [actions/runner#913]
**Describe the bug**
The environment variable $RUNNER_OS is missing in `pwsh`. This made it harder to write a pwsh action in composite actions, mostly because I didn't realize it was missing.

**To Reproduce**

```yaml
- run: echo $RUNNER_OS
  shell: pwsh
# shell: bash
```

**Expected behavior**
Should be set like the default or bash.

## Runner Version and Platform
Standard host, on OSX/Windows/Linux (though explicitly checked Windows).

(Apologies if this is the wrong repo, feel free to transfer the issue).
