### ISSUE TITLE
Add automatic stdout, stderr and exitcode outputs per step

### ISSUE THREAD

**Issue by halberom** [actions/runner#919]
**Describe the enhancement**
Add automatic stdout, stderr and exitcode outputs per run step.

This would make it very useful for things like generating changes in one step/job, and then adding them to a PR comment or sending them in a Slack notify in another.

**Code Snippet**
```
steps:
  - uses: actions/checkout@v2
  - name: get python version
    id: python_version
    run: python -V
  - name: output python version
    run: echo ${{ steps.python_version.outputs.stdout }}
```

**Additional information**
See also this community post for another example - https://github.community/t/suggest-automatic-output-id-for-stdout-stderr/17419
