### ISSUE TITLE
Runner v2.276.0  fails to open some stderr/stdout streams

### ISSUE THREAD

**Issue by thboop** [actions/runner#927]
**Describe the bug**
The newest runner version may fail to open some stderr/stdout streams. You can't typically open() a socket, and it looks like the stderr stream may be getting kept as a socket now.

**To Reproduce**
Run a ubuntu runner with the following yaml
```
name: CI test

on: push

jobs:
  build:
    name: test
    runs-on: self-hosted
    steps:
    - name: test tee /dev/stderr
      run : |
        set -x
        set -euo pipefail
        seq 0 10 | tee /dev/stderr | xargs echo
```
It will fail with `tee: /dev/stderr: No such device or address`
**Expected behavior**
The stderr stream should open and this should not fail.

## Runner Version and Platform
v2.276.0 on Ubuntu.

## Other information
Looks like it may be related to the .net upgrade
https://github.com/dotnet/runtime/issues/46469
