### ISSUE TITLE
Add a function for testing if a secret exists

### ISSUE THREAD

**Issue by steve-todorov** [actions/runner#953]
**Describe the enhancement**

I would like to propose adding a function which receives a secret name and returns either `true` or `false`.
The use case for this function is pretty simple - sometimes you need to skip non-important steps if a secret is missing.
A perfect example would be a missing SonarQube token in a fork - it would be "good to have", but the next build jobs shouldn't fail if this doesn't pass (I am aware of `strategy.fail-fast: false` but that wouldn't work for my case, since we actually need it to fail-fast)

**Code Snippet**

```yaml
jobs:
  my-jobname:
    steps:
      - name: Submit sonar qube report
        if: ${{ hasSecret("SONAR_TOKEN") == 'true' or containsSecret('SONAR_TOKEN') == 'true' or secretExists('SONAR_TOKEN') == 'true' }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pjacoco-code-coverage -DskipTests
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

**Additional information**

Before opening this feature request I spotted #520 which has been closed. I understand using `secrets.VAR` directly in `if` statements might pose a security issue. However, I believe using a function (i.e. `hasSecret`) that only returns `true/false` should be easier to implement and workaround in the debugging output, don't you think?

**Comment by hross** [comment]
Since we don't maintain the secrets everywhere (ie we don't have secrets at every level of the workflow for security reasons) we wouldn't be able to support this expression function at every level. This would make it pretty confusing because it would only work at the step level. I don't think we would implement this due to that limitation.

Otherwise, we agree this would be an interesting idea. Unfortunately due to security implementation details it is not feasible to make this usable in all cases.

**Comment by ChristopherHX** [comment]
@steve-todorov 
What about rewritting your workflow to something like
```
on: push
jobs:
  my-jobname:
    runs-on: ubuntu-latest
    env:
       HAVE_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN != '' }}
    steps:
      - name: Submit sonar qube report
        if: ${{ env.HAVE_SONAR_TOKEN == 'true' }}
        run: echo "I have the token!"
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
?
It might be unexpected, but does exactly what you want. This only works on step level, but thats enough for your usecase.
Proof on github:
Missing secret:
https://github.com/ChristopherHX/Buildbot/runs/2365595261?check_suite_focus=true
With secret:
https://github.com/ChristopherHX/Buildbot/runs/2365607492?check_suite_focus=true
