### ISSUE TITLE
Support default shell config

### ISSUE THREAD

**Issue by sd185233** [actions/runner#959]
We cannot use the default Powershell shell on Windows, so end up having multiple duplicated jobs or steps with IF statements with steps using different shells on Windows and Linux.  

Could the runner have some config where the default shell for that runner could be set - for example we could set the shell to cmd for all our Windows runners.

**Comment by jbrownsw** [comment]
I'd love to be able to do this at the global level, but at the job level you can do something like:
```
jobs:
  job1:
    defaults:
      run:
        shell: ${{ matrix.os == 'Windows' && 'cmd' || 'bash' }}
```

So unfortunately I have to copy this for all steps that run on both Windows and Linux, but it's better than nothing. For my case I'm calling a bash script on both platforms anyway, but setting the shell to bash on both doesn't work because the runner tries to call the temp script it generates with windows paths which ends up failing.
