### ISSUE TITLE
Question: Run CI conditionally based on `[ci]`, `[ci_mac]`, etc. magic strings presence in commit message

### ISSUE THREAD

**Issue by MartyIX** [actions/runner#982]
Hi,

I have this simple working YAML definition which allows me to start CI for all OSs when `[CI]` string is in the commit message of the last commit of a git branch:

```yaml
name: .NET Core
on: [push, pull_request]

jobs:
  build:
    # If you want to do a CI check for your commit, include `[ci]` (or `[CI]`) anywhere in the git commit message.
    if: "contains(github.event.head_commit.message, '[ci]')" # Second parameter is not case sensitive.
    strategy:
      matrix:
        operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]

    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
```

I would love to add `[ci_mac]` and `[ci_win]` magic strings so that only the specified OS is used in the CI run.

I thought that something like this `if: "matrix.os == 'macos-latest' && contains(github.event.head_commit.message, '[ci_mac]')"` would help me but keep hitting the wall. It seems this is actually hard-ish problem.

Thank you!

**Comment by ChristopherHX** [comment]
Hi,
The [documentation](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) describes a way to populate the matrix dynamically. I know this creates another ubuntu-latest job, it might be even possible to do it directly with more complex [expression binding](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions) of the matrix property.

Here a modified sample of you workflow, do what ever you want with it.
```yaml
name: .NET Core
on: [push, pull_request]

jobs:
  factory:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-result.outputs.result}}
    steps:
    - uses: actions/github-script@v3
      id: set-result
      with:
        script: |
          var includes = []
          var ci = ${{contains(github.event.head_commit.message, '[ci]')}}
          var linux = ${{contains(github.event.head_commit.message, '[ci_linux]')}}
          var windows = ${{contains(github.event.head_commit.message, '[ci_windows]')}}
          var macOS = ${{contains(github.event.head_commit.message, '[ci_macos]')}}
          if(ci || linux) {
            includes.push({ operatingSystem:"ubuntu-latest" })
          }
          if(ci || windows) {
            includes.push({ operatingSystem:"windows-latest" })
          }
          if(ci || macOS) {
            includes.push({ operatingSystem:"macos-latest" })
          }
          return { include:includes }
  build:
    needs: factory
    runs-on: ${{ matrix.operatingSystem }}
    strategy:
      matrix: ${{fromJSON(needs.factory.outputs.matrix)}}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
```

I hope my answer helps you a bit :), I'm not affiliated with github or this repo.

**Comment by ChristopherHX** [comment]
Another method to exclude matrix targets, without an extra job. I used an extra matrix property `skip`, if the exclude tag evaluates to `true` it is excluded, if it evaluates to `false` it removes nothing. Choose what you think to fit best :).

```yaml
name: .NET Core
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        skip: [ true ]
        exclude:
        - operatingSystem: 'ubuntu-latest'
          skip: ${{fromJSON(!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_linux]'))}}
        - operatingSystem: 'windows-latest'
          skip: ${{fromJSON(!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_windows]'))}}
        - operatingSystem: 'macos-latest'
          skip: ${{fromJSON(!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_mac]'))}}
    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
```
