### ISSUE TITLE
Proposal: Add "jobs.<job-id>.output" context

### ISSUE THREAD

**Issue by pepoluan** [actions/runner#986]
**Describe the enhancement**

Based on the discussion in https://github.com/actions/runner/issues/774, plus a need of mine, I propose adding a new "context" called `jobs.<job_id>.output`. To set this context, one use the command `"::set-output::"`

One can use this context to skip execution of heavy jobs if not needed. See example in Code Snippet.

**Code Snippet**

```yaml
jobs:
  static_check:
    steps:
      # ... many steps here ...
      - name: "Set output"
        shell: bash
        run: |
          output=()
          if $if_we_need_building; then
            output+=("yes-building")
          fi
          # other tests to append to the output array
          # finally, emit the ::set-output:: command
          echo "::set-output::${output[*]}"
  build_product:
    # Without this context, GA will spin up 20 (TWENTY!) runners in this job.
    if: contains(jobs.static_check.output, "yes-building")
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-18.04", "ubuntu-20.04", "macos-10.15", "windows-latest" ]
        python-version: [ "3.6", "3.7", "3.8", "3.9", "pypy3" ]
    steps:
      # ... heavyweight building steps here ...
  publish_product:
    if: contains(jobs.static_check.output, "yes-publish")
    # steps, matrix, etc. follow

  # other jobs may depend on different "flags" within the jobs.static_check.output context
```

**Additional information**

This will _greatly_ benefits user _and_ GitHub:
* User will get result faster
* GitHub will save resource especially if the skipped jobs need to spin up a lot of runner

Do note that this is _different_ from the **`[skip ci]`** feature; this proposed feature enables skipping of just some jobs, not the whole workflow.

**Comment by muzimuzhi** [comment]
Does the `actions/toolkit` function `set-output` meets your requirement? It can be used as
```
echo '::set-output name={name}::{value}'
```
See [Using workflow commands to access toolkit functions](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions).

**Comment by pepoluan** [comment]
> 
> 
> Does the `actions/toolkit` function `set-output` meets your requirement? It can be used as
> 
> ```
> echo '::set-output name={name}::{value}'
> ```
> 
> See [Using workflow commands to access toolkit functions](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions).

Does that carry **between jobs** ?

**Comment by muzimuzhi** [comment]
> I think that one carries only between **steps in the same job**, but does not carry between jobs.

You're right. For sharing info between jobs, currently one has to use artifacts. Related info I found
 - [Sharing a variable between jobs](https://github.community/t/sharing-a-variable-between-jobs/16967), a GitHub Community post
 - [Persist Data Between Jobs](https://github.com/marketplace/actions/persist-data-between-jobs) - a GitHub Action

**Comment by pepoluan** [comment]
> > I think that one carries only between **steps in the same job**, but does not carry between jobs.
> 
> You're right. For sharing info between jobs, currently one has to use artifacts. Related info I found
> 
>     * [Sharing a variable between jobs](https://github.community/t/sharing-a-variable-between-jobs/16967), a GitHub Community post
> 
>     * [Persist Data Between Jobs](https://github.com/marketplace/actions/persist-data-between-jobs) - a GitHub Action

The problem with those two options is that the job already gets started. If I use a job matrix, that means a LOT of runners being started just to be cancelled almost immediately.

With my proposal, jobs (and its whole matrix) can be prevented from starting _selectively_, without needing to fail a previous job.

**Comment by muzimuzhi** [comment]
got it

**Comment by TingluoHuang** [comment]
You can pass outputs across jobs with job outputs.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs
Ex:
```
jobs:
  build:
    outputs:
      build_out: ${{steps.one.outputs.foo}}
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        id: one
        run: |
          echo ::set-output name=foo::something1
    test: 
    needs: [build]
    if: needs.build.outputs.build_out == 'something1'
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo hello
```
