### ISSUE TITLE
Running pre-built docker action does not provide required default values

### ISSUE THREAD

**Issue by EnricoMi** [actions/runner#989]
**Describe the bug**
Running an action without providing required inputs that have a default will use the default values. Running the same action pre-built as a docker image does not show this behaviour.

**To Reproduce**
1. Use an action that has required inputs, e.g. [EnricoMi/download-buildkite-artifact-action](https://github.com/EnricoMi/download-buildkite-artifact-action):
```yaml
      uses: EnricoMi/download-buildkite-artifact-action@v1
      with:
        buildkite_token: ${{ secrets.BUILDKITE_TOKEN }}
```
2. The `github_token` input is defined `required` in the [action.yml](https://github.com/EnricoMi/download-buildkite-artifact-action/blob/c97d9e79b0c469b040a7c1367d00475aeb0906ab/action.yml#L5-L8) but not given here.

https://github.com/EnricoMi/download-buildkite-artifact-action/blob/c97d9e79b0c469b040a7c1367d00475aeb0906ab/action.yml#L5-L8

3. This makes the runner execute the action with the default value: https://github.com/horovod/horovod/pull/2666/checks?check_run_id=1912170696#step:4:2

```
Run EnricoMi/download-buildkite-artifact-action@v1
  with:
    buildkite_token: ***
    github_token: ***
    log_level: INFO
```

4. When I now switch over to the identical but pre-built action, the default values for missing inputs are not provided (e.g. `github_token` or `log_level`):

```yaml
      docker://ghcr.io/enricomi/download-buildkite-artifact-action:v1
      with:
        buildkite_token: ${{ secrets.BUILDKITE_TOKEN }}
```

https://github.com/horovod/horovod/pull/2666/checks?check_run_id=1912156006#step:4:2
```
Run docker://ghcr.io/enricomi/download-buildkite-artifact-action:v1
  with:
    buildkite_token: ***
```

**Expected behavior**

Running the action should behave identical, no matter if run as [pre-build docker image](https://github.com/horovod/horovod/blob/d294f40ab9aae13908926a8d34ea6fbfc0c56853/.github/workflows/buildkite_unit_tests.yml#L36-L43) (`docker://ghcr.io/enricomi/download-buildkite-artifact-action:v1`) or from [sources](https://github.com/horovod/horovod/blob/40266507b1282fa3eedad7ee6ba7fffa6043c3c6/.github/workflows/buildkite_unit_tests.yml#L36-L43) (`EnricoMi/download-buildkite-artifact-action@v1`). 

## Runner Version and Platform
Current version running at GitHub. Above example runs on `ubuntu-latest`.

## What's not working?
Please include error messages and screenshots.

## Job Log Output
https://github.com/horovod/horovod/pull/2666/checks?check_run_id=1912156006#step:4:2
https://github.com/horovod/horovod/pull/2666/checks?check_run_id=1912170696#step:4:2
