### ISSUE TITLE
Setting job environment dynamically doesn't work when using key-value format

### ISSUE THREAD

**Issue by deepakgc** [actions/runner#998]
**Describe the bug**
I was trying to set the job environment dynamically so I can use my GitHub production & staging environment secrets in a single workflow. 

**To Reproduce**

```yaml
name: Set Job Enviroment Dynamically 
on:
  workflow_dispatch:
jobs:
  set_environment:
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - id: setenv
      run: echo "::set-output name=my_env::production"

  use_outputs_environemnt_directly:    
    needs: set_environment
    environment: ${{ needs.set_environment.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Testing job environment
      run: echo "Hello From Production Envrionment." 
```
See failing workflow: [failure.yaml](https://github.com/D-GC/workflow-test/blob/main/.github/workflows/failure.yaml)

**Expected behavior**
 The environment should be set to production.

## What's not working?
I get the below error:
`The workflow is not valid. .github/workflows/job-environment-test-ko.yml (Line: 15, Col: 18): Unrecognized named-value: 'needs'. Located at position 1 within expression: needs.set_environment.outputs.en`

## Workaround found 
Using object format for jobs environment fixes the issue
```yaml
 environment: 
      name: ${{ needs.set_environment.outputs.my_env }}
```
See successful workflow: [success.yaml](https://github.com/D-GC/workflow-test/blob/main/.github/workflows/success.yaml)

**Comment by sqljim** [comment]
There are a couple of outstanding SO questions that relate to this too:

https://stackoverflow.com/questions/66830251/dynamically-setting-the-environment-context-in-github-actions?noredirect=1#comment118150164_66830251

https://stackoverflow.com/questions/65826284/use-dynamic-input-value-for-environment-in-github-actions-workflow-job

At the moment I'm working around it by using an IF statement:

```
jobs:

  deploy-develop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    if: ${{ github.ref == 'refs/heads/develop' }}

    environment: develop

    - steps ........


    deploy-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    if: ${{ github.ref == 'refs/heads/main' }}

    environment: main

    - steps ........

```

But this of course means duplicating most of the code in the workflow.

**Comment by cornwe19** [comment]
Will being able to dynamically specify environment name be added at any point? This makes selecting an environment from a `workflow_dispatch` event a lot more complicated.

**Comment by RevoluPowered** [comment]
This issue is causing me to have to duplicate workflow files pointlessly.

**Comment by KodDobra** [comment]
Namaste
Sorry
Sho ne tak
To da

GOLOVA
Ne hvataet sil
Grustno<<<●nashu●>>> planetu
Cheloveki zasrali vse veka ECOLOG I YA I mi I oni ii vi ta ni po mne voina
***@***.***°o°Bra



нд, 26 бер. 2023 р., 18:17 користувач Gordon MacPherson <
***@***.***> пише:

**Comment by philomory** [comment]
> Will being able to dynamically specify environment name be added at any point? This makes selecting an environment from a `workflow_dispatch` event a lot more complicated.

You already can, you just have to explicitly write it as
```yaml
environment:
  name: ${{ some.dynamic.expression }}
```
... rather than `environment: ${{ some.dynamic.expression }}`, but, the results are exactly the behavior you're asking for.

**Comment by jdschleicher** [comment]
i have also had some luck without leveraging the name property using the "format" expression:

```
    environment: "${{ format('{0}{1}{2}', needs.get-parent-by-tag.outputs.parent_name, '_', 'child_one_environment') }}"

```

will finish as "dynamicValue_child_one_environment"

**Comment by Zambonilli** [comment]
> > ```yaml
> > environment:
> >   name: ${{ some.dynamic.expression }}
> > ```
> 
> do you have some example ?

This worked for me.

```yaml
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
jobs:
  deploy:
name: Deploy
    environment:
      name: ${{ inputs.environment }}          
```

**Comment by zentavr** [comment]
Added:
```
    needs:
      - check-branch
```
For the second job and it worked :)

**Comment by sam3k** [comment]
> Hm... Have
> 
> name: "CI/CD - CI Pipeline"
> 
> on:
>   push:
>     branches:
>       - main
>       - develop
>     paths-ignore:
>       - "**.md"
>   workflow_dispatch:
> 
> # Remove all permissions by default.
> permissions: {}
> 
> env:
>   # The version of "bitnami/python" image we are starting from
>   NODE_VERSION: "18.12.1-alpine3.16"
>   # We are building multiarch image. "bitnami/python" has only arm64+amd64
>   DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
>   # Container name
>   ECS_CONTAINER_NAME: "website-app"
>   ENV_STAGING_NAME: "staging"
>   ENV_PRODUCTION_NAME: "production"
> 
> jobs:
>   check-branch:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Dump VARS context
>         env:
>           VARS_CONTEXT: ${{ toJson(vars) }}
>         run: echo "$VARS_CONTEXT"
> 
>       - name: "Check the branch"
>         id: check-env
>         run: |
>           if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
>             echo "Have ${{ env.ENV_PRODUCTION_NAME }}"
>             echo "environment=${{ env.ENV_PRODUCTION_NAME }}" >> $GITHUB_OUTPUT
>           elif [[ "${{ github.ref_name }}" == "develop" || "${{ github.ref }}" == "refs/heads/develop" ]]; then
>             echo "Have ${{ env.ENV_STAGING_NAME }}"
>             echo "environment=${{ env.ENV_STAGING_NAME }}" >> $GITHUB_OUTPUT
>           else 
>             echo "Unknown branch name: ${{ github.ref_name }}, REF: ${{ github.ref }}"
>             exit 1
>           fi
>     outputs:
>       environment: ${{ steps.check-env.outputs.environment }}
> 
>   build-image:
>     runs-on: ubuntu-latest
>     name: 'Builds the docker image and uploads it into the registry'
>     environment:
>       # TODO: Here is being said that the name could be an expression
>       #       Does not work with our case
>       #       ref.: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-expression-as-environment-name
>       # name: ${{ needs.check-branch.outputs.environment }}
>       name: staging
>     permissions:
>       contents: read                 # This is required for actions/checkout
>       id-token: write                # This is required for requesting the JWT
>       packages: write
>     steps:
>       - name: Check out repository code
>         uses: actions/checkout@v4
>         with:
>           fetch-depth: 1
> 
>       # ref.: https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#examples-of-usage
>       - name: Configure AWS credentials
>         uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
>         with:
>           role-to-assume: ${{ vars.WM_AWS_ASSUME_ROLE_ARN }}
>           role-session-name: GitHub_to_AWS_via_FederatedOIDC
>           aws-region: ${{ vars.WM_AWS_REGION }}
>           mask-aws-account-id: 'true'
> 
> ....
> ...And seems like `name: ${{ needs.check-branch.outputs.environment }}` does not work. What might be the issue?

This worked for me perfectly. I needed it to find out the base branch and based on that determine the environment which is then used to determine which environment's `PUBLIC_APP_API_BASE_URL` env var to use. Came up with this in case it helps someone:

```yaml
name: End-to-End Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - staging
      - test
      - squad-3
    paths:
      - 'src/**'
      - 'cypress/**'
      - 'public/**'
      - 'package.json'

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Dump VARS context
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: echo "$VARS_CONTEXT"

      # When Cypress runs on a PR that has been opened, it does not have access to "environment variables" simply
      # because the PR is not merged yet. We need to tell it what environment to run the tests in. Moving forward,
      # we will need to add every new environment to this if/else block.
      # Ref: https://github.com/actions/runner/issues/998#issuecomment-2216493323

      - name: "Check the branch"
        id: check-env
        run: |
          if [[ "${{ github.base_ref }}" == "dev" || "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "Set env to dev"
            echo "environment=develop" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "test" || "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "Set env to test"
            echo "environment=testing" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "staging" || "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "Set env to staging"
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "squad-3" || "${{ github.ref }}" == "refs/heads/squad-3" ]]; then
            echo "Set env to squad-3"
            echo "environment=squad-3" >> $GITHUB_OUTPUT
          else
            echo "Unknown branch name: ${{ github.ref_name }}, REF: ${{ github.ref }}. base_ref: ${{ github.base_ref }}"
            exit 1
          fi
    outputs:
      environment: ${{ steps.check-env.outputs.environment }}
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1] # [1, 2] Uses 2 parallel instances
    env:
      PUBLIC_APP_API_BASE_URL: ${{ vars.PUBLIC_APP_API_BASE_URL }}
    environment:
      name: ${{ needs.check-branch.outputs.environment }}
    needs:
      - check-branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          build: npm run build
          start: npm run preview
          wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: false # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
